### ISSUE TITLE
Migration of Snowflake Provider Broke Configuration

### ISSUE THREAD

**Issue by Kyle-Hughes-Imprivata** [Snowflake-Labs/terraform-provider-snowflake#1025]
**Provider Version**

0.25.36

**Terraform Version**

0.14.7

**Describe the bug**

The snowflake terraform provider has migrated to Snowflake-labs from chanzuckerberg, and suddenly 0.25.36 is not available:

The literal output from this bug is the following:
```
Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/chanzuckerberg/snowflake:
- For users on Terraform 0.13 or greater, this provider has moved to
Snowflake-Labs/snowflake. Please update your source in required_providers.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Missing required argument

The argument "region" is required, but was not set.
```

Providing the "region" input to the provider config did not get rid of the error.  It is a deprecated field anyhow, and the provider gets the region from the account field (i.e. blahblah.us-east-1)

Moving to the snowflake-labs/snowflake provider resulted in the following:

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
snowflake-labs/snowflake: no available releases match the given constraints
0.25.36
```

**Expected behavior**

A successful terraform plan for the snowflake provider formerly know as chanzuckerberg/snowflake

**Code samples and commands**
```
terraform {
  required_providers {
    snowflake = {
      source = "chanzuckerberg/snowflake"
      version =  "0.25.36"
    }
...
}
```

**Additional context**

**Comment by robbruce** [comment]
@Kyle-Hughes-Imprivata - you can use the `terraform state replace-provider` command to migrate

https://www.terraform.io/cli/commands/state/replace-provider

Personally, I had to clone this repo, switch to the tag I wanted, 0.34.0 in my instance, and the compile a version for my OS/Arch, effectively forcing terraform to use a local mirror for the old reference to chanzuckerberg.

If you already have a local copy/mirror then this wouldn't be needed.

```bash
# in clone of provider code
git checkout v0.34.0
CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ~/.terraform.d/plugins/registry.terraform.io/chanzuckerberg/snowflake/0.34.0/darwin_arm64/terraform-provider-snowflake
```

```bash
# in terraform code
terraform replace-provider chanzuckerberg/snowflake Snowflake-Labs/snowflake
```

**Comment by sfc-gh-swinkler** [comment]
Hello @Kyle-Hughes-Imprivata 

```
Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/chanzuckerberg/snowflake:
- For users on Terraform 0.13 or greater, this provider has moved to
Snowflake-Labs/snowflake. Please update your source in required_providers.
```

This is not an error but a desired warning message. We want people to know that the provider has moved from chanzuckerberg organization to Snowflake-Labs. If you want to use 0.25.36 then you can continue to do so using the chanzuckerberg provider.

I am not sure why not all of the older versions transferred over when we registered the new provider location. Only versions 0.28.6 and newer transferred over. This is more of a HashiCorp question. 

Agreed with @robbruce on the procedure for upgrading. The chanzuckerberg provider has been archived and if you want any newer version then you will want to use the Snowflake-Labs provider source.

Regards,
Scott

**Comment by Kyle-Hughes-Imprivata** [comment]
Hello @robbruce and @sfc-gh-swinkler your feedback has been helpful.  There did seem to be a network interruption or something where I couldn't download the older provider version, but it's passed now.  I haven't had to migrate yet, but I'll follow these instructions when I do.  Thank you!
