### ISSUE TITLE
The automated release is not working

### ISSUE THREAD

**Issue by emancu** [Snowflake-Labs/terraform-provider-snowflake#1044]
This bug doesn't apply to the template because is about the automatic release rather than the provider itself.

The documentation says
> Releases will be performed once a week on Monday around 11 am PST. If your change is more urgent and you need to use it sooner, use the commit hash.

However, for the last two Mondays, there were no releases even when changes have been merged.

I'm not sure if the automation is broken or if there is a manual step required to trigger the release.

**Comment by sfc-gh-asawicki** [comment]
Hey @emancu. Thanks for reporting the issue.

Currently, we are releasing on demand: `Releases will be performed as needed, typically once every 1-2 weeks. If your change is more urgent and you need to use it sooner, use the commit hash.`

This is outdated, so I am closing it.
