### ISSUE TITLE
snowflake_function does reject Snowscript/SQL User Defined Functions

### ISSUE THREAD

**Issue by christophkreutzer** [Snowflake-Labs/terraform-provider-snowflake#1048]
**Provider Version**

Snowflake-Labs/snowflake 0.35.0

**Terraform Version**

Terraform v1.1.7
on windows_amd64

**Describe the bug**

When creating a resource of type `snowflake_function` with `language = "SQL"`, the following error is thrown:

> Error: expected language to be one of [javascript java], got SQL
> with ...
> on ... in resource "snowflake_function" "validate_ip_address"

According to the following comment, SQL should be supported as well:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/snowflake/function.go#L83

However, it seems to be validated somewhere (wasn't able to chase it down, i'm not that fluent in Go).

**Expected behavior**

A Snowflake Function with SQL (Snowscript) body should be created.

**Code samples and commands**

```terraform
resource "snowflake_function" "network_policies_validate_ip_address" {
  database  = snowflake_schema.network_policies.database
  schema    = snowflake_schema.network_policies.name
  name      = "validate_ip_address"

  comment   = "Validates the given IP address, returns a string containing a valid IP/subnet, returns an empty string on empty input or NULL on validation failure"

  arguments {
    name = "ip_address"
    type = "VARCHAR(100)"
  }
  arguments {
    name = "netmask_allowed"
    type = "BOOLEAN"
  }
  return_type = "VARCHAR"
  language    = "SQL"
  statement   = <<-EOT
    SELECT CASE
        WHEN ip:error IS NOT NULL -- parse_ip failed, invalid IP given
            THEN null
        WHEN ip:host::varchar IS NULL -- input was empty/null
            THEN ''
        WHEN (ip:family = 4 AND (ip:netmask_prefix_length::integer IS NULL OR ip:netmask_prefix_length::integer = 32) AND bitand(ip:ipv4,255) = 0) -- only a prefix was given (last octet is 0), but no netmask
            THEN null
        WHEN (ip:family = 4 AND (ip:netmask_prefix_length::integer IS NULL OR ip:netmask_prefix_length::integer = 32)) -- valid single IPv4
            THEN (concat(bitand(bitshiftright(ip:ipv4,24),255), '.', bitand(bitshiftright(ip:ipv4,16),255), '.', bitand(bitshiftright(ip:ipv4,8),255), '.', bitand(ip:ipv4,255)))::varchar -- recreate ip from integer representation
        WHEN netmask_allowed AND (ip:family = 4 AND ip:netmask_prefix_length::integer > 0) -- valid IPv4 subnet, if allowed
            THEN (concat(bitand(bitshiftright(ip:ipv4,24),255), '.', bitand(bitshiftright(ip:ipv4,16),255), '.', bitand(bitshiftright(ip:ipv4,8),255), '.', bitand(ip:ipv4,255)))::varchar || '/' || ip:netmask_prefix_length::integer  -- recreate ip from integer representation
        ELSE null -- when not matched, fail
        END validated_ip
    FROM (SELECT parse_ip(ip_address, 'inet', 1) ip)
EOT
}
```

**Additional context**

-

**Comment by adamantike** [comment]
@christophkreutzer, can you check if it works if you remove the `language` variable? From what I can see in the code, the variable is optional, and [`CREATE FUNCTION`](https://docs.snowflake.com/en/sql-reference/sql/create-function.html#syntax) only adds `LANGUAGE` to the statement when it's set to Java/Javascript.

**Comment by christophkreutzer** [comment]
Hi @adamantike, thanks, that actually seems to work :) I'm gonna open a PR regardless, as it seems to be a trivial fix.
