### ISSUE TITLE
MANAGE FIREWALL_CONFIGURATION

### ISSUE THREAD

**Issue by johnjelinek** [Snowflake-Labs/terraform-provider-snowflake#1058]
**Is your feature request related to a problem? Please describe.**

```terraform
resource "snowflake_account_grant" "grant" {
  roles                  = "MY_ROLE"
  privilege              = "MANAGE FIREWALL_CONFIGURATION"
  with_grant_option      = false
  enable_multiple_grants = true
}
```
[Docs](https://other-docs.snowflake.com/en/LIMITEDACCESS/data-applications.html#manage-firewall-configuration)

Error:
```
Error: expected privilege to be one of [CREATE ACCOUNT CREATE INTEGRATION CREATE USER MANAGE GRANTS MONITOR USAGE ATTACH POLICY CREATE DATABASE CREATE NETWORK POLICY CREATE ROLE EXECUTE TASK MONITOR EXECUTION APPLY MASKING POLICY CREATE DATA EXCHANGE LISTING CREATE SHARE CREATE WAREHOUSE MANAGE ORGANIZATION SUPPORT CASES MANAGE USER SUPPORT CASES APPLY ROW ACCESS POLICY APPLY TAG IMPORT SHARE OVERRIDE SHARE RESTRICTIONS EXECUTE MANAGED TASK MANAGE ACCOUNT SUPPORT CASES], got MANAGE FIREWALL_CONFIGURATION
```

**Describe the solution you'd like**

I wanted to implement the setting in the docs.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
