### ISSUE TITLE
CREATE ORGANIZATION ACCOUNT

### ISSUE THREAD

**Issue by kvillar** [Snowflake-Labs/terraform-provider-snowflake#1062]
**Is your feature request related to a problem? Please describe.**

We would like to create new Snowflake accounts in our organization using this provider. 

**Describe the solution you'd like**
 org_account resource

```
resource snowflake_organization_account account {
  name                     = "newaccount"
  admin_name         = "accountadmin"
  admin_password  = var.snowflakeadmin_password
  edition                  = "enterprise"
  email                    = "SnowflakeAdmin@XXX.com"
  region                   = "aws_us_east_1"
}
```

**Describe alternatives you've considered**

Manually creating accounts :(

**Comment by Spince** [comment]
We would like this as well, not sure how you would access the new account without also setting up a user in the account.

**Comment by sfc-gh-dszmolka** [comment]
capability looks to be already available with [snowflake_managed_account](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/managed_account)
