### ISSUE TITLE
Existing Task in plan & apply change & error

### ISSUE THREAD

**Issue by depowell** [Snowflake-Labs/terraform-provider-snowflake#1071]
**Provider Version**
snowflake-labs/snowflake v0.36.0

**Terraform Version**
image: hashicorp/terraform

**Describe the bug**
we have existing tasks in state and snowflake that have no predecessor or after parameter in terraform
we just recently changed from chanzuckerberg/terraform to snowflake-labs but error occured before change

in snowflake UI predecessor of effected tasks shows '[]'
in the **terraform plan** we get the message that tasks are updating as such:
delete marker - after = jsonencode([]) -> null

in **terraform apply**:
Error: error retrieving root task TASK_NAME: failed to locate the root node of: []: sql: no rows in result set

we tried a couple of work arounds but didnt do anything good:
terraform tasks:
change from nothing -> after = null
change from nothing -> after = jsonencode([])

**Expected behavior**
no change or error for these tasks

**Comment by depowell** [comment]
just tried a workaround but no luck at the moment

step1::

look at statefile for tasks with no preceding task
task
after = ""

step 2::
changed to 0.35.0
run terraform plan with -refresh-only option:
$ terraform plan -refresh-only

step 3::
look at statefile for tasks with no preceding task
task
after = "[]"

... it changed to square brackets in the state file

step4:: 
look at terraform apply:
│ Error: error retrieving root task TASK_NAME: failed to locate the root node of: []: sql: no rows in result set

**Comment by linussjo** [comment]
We are having the same issue, and we haven't figured out any solution to it either.

**Comment by Fraask** [comment]
We have exactly the same issue and did not managed to find any reasonable workaround.

**Comment by grantcooksey** [comment]
Same issue here. We're pretty blocked by this. We ran into the same issue using the old chanzuckerberg/terraform provider on 0.25.6 but still have the same issue after upgrading to Snowflake-Labs/snowflake 0.32.0.

**Comment by Anatoli-deBRADKE** [comment]
I think this is related to snowflake bundle 2022_03 which has been activated by default in version 6.21 (June 22-23).
[https://community.snowflake.com/s/article/Pending-Behavior-Change-Log](https://community.snowflake.com/s/article/Pending-Behavior-Change-Log)

**Comment by Anatoli-deBRADKE** [comment]
I think this is related to snowflake bundle 2022_03 which has been activated by default in version 6.21 (June 22-23).
[https://community.snowflake.com/s/article/Pending-Behavior-Change-Log](https://community.snowflake.com/s/article/Pending-Behavior-Change-Log)

**Comment by Anatoli-deBRADKE** [comment]
I think that one temporary workaround would be to disabble for the moment the bundle 2022_03 in your account.

[https://docs.snowflake.com/en/sql-reference/functions/system_disable_behavior_change_bundle.html](https://docs.snowflake.com/en/sql-reference/functions/system_disable_behavior_change_bundle.html)

select system$disable_behavior_change_bundle('2022_03');

**Comment by truepill-fiona-tang** [comment]
We are having the same issue. We're still on a older version of the provider: 
```
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.36"
    }
```

**Comment by yiannissakk** [comment]
Has this been fixed? We are encountering the same issue still

**Comment by zlisde** [comment]
Explicitly set default `after` value should help  `after = jsonencode([])`

**Comment by yiannissakk** [comment]
@zlisde We are using the `schedule` attribute in the snowflake_task resource which conflicts with `after`

**Comment by zlisde** [comment]
@yiannissakk 
Hmmmm,  it is interesting,  it worked for us when explicitly set it to the json encoded null value along with schedule.

**Comment by larssnek** [comment]
Same error for us. Not able to set `after` because we are using `schedule`. Still on an older version of the provider:
```
snowflake = {
    source  = "chanzuckerberg/snowflake"
    version = "0.25.25"
}
```

**Comment by Hyurt** [comment]
@gouline 
I gave a try

For storage integration resources:
`Could not show storage integration: 390201 (08004): The requested warehouse does not exist or not authorized.`

For other resources: (snowflake_user/snowflake_table/snowflake_role ...
`390201 (08004): The requested warehouse does not exist or not authorized.`

Reverting to 0.36.0 doesn't trigger this issue

**Comment by fcraposo** [comment]
We had the same issue and upgrading to 0.37.0 solved it. 🎉

**Comment by sfc-gh-swinkler** [comment]
i am going to mark this as complete. thanks everyone 👏

**Comment by Hamza442** [comment]
> We had the same issue and upgrading to 0.37.0 solved it. 🎉

How did you to the upgrade its giving me error 
Error: Failed to install provider

Error while installing chanzuckerberg/snowflake v0.41.0: provider
registry.terraform.io/chanzuckerberg/snowflake 0.41.0 is not available for
linux_amd64

don't know why its installing this now I am using 
    snowflake = {
        source  = "snowflake-labs/snowflake"
        version = "0.37.0"
    }

**Comment by gouline** [comment]
@Hamza442 Your problem is solved in #1089

**Comment by javabudd** [comment]
I'm seeing this issue again with [0.42.1](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.42.1).

Could this have regressed?

**Comment by fermezz** [comment]
I described the problem here as well https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1194 not sure how it worked for everyone else.
