### ISSUE TITLE
SNOW-1348103: Allow importing user defined functions (UDF)

### ISSUE THREAD

**Issue by rubemz** [Snowflake-Labs/terraform-provider-snowflake#1079]
**Is your feature request related to a problem? Please describe.**

There is already support for snowflake user defined functions, but there isn't a way to properly import them. See that the import section is not even available on the [documentation page](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/function)

**Additional context**

Even though it is not documented, there is a way to import UDFs running (very similar how the external function import works)

```
terraform import snowflake_function.example 'dbName|schemaName|functionName|varchar-varchar-varchar'
```

However, after importing the function snowflake is forcing me to recreate the function, because it does not properly recognize the db name, comment field, etc so my guess is that the import is not fully implemented and that's why it is not documented yet.

Importing UDF would be very helpful to manage existing functions.

**Comment by sfc-gh-asawicki** [comment]
Hey @rubemz.

In v0.100.0, we have introduced new function resources. They allow importing. Please consult the docs (e.g. https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/function_sql#import).

**Comment by sfc-gh-dszmolka** [comment]
closing this out as it has been implemented already. Do let us know if you still see issues even after using v0.100.0 / v1
