### ISSUE TITLE
AWS_STAGE_CREDENTIALS information available as output from snowflake_stage resource

### ISSUE THREAD

**Issue by ndavies-om1** [Snowflake-Labs/terraform-provider-snowflake#1087]
**Is your feature request related to a problem? Please describe.**

When writing Terraform code to integrate Snowflake and AWS S3 buckets, I need to create both IAM policies and Snowflake stages. However, I cannot get the `SNOWFLAKE_IAM_USER` and `AWS_EXTERNAL_ID` from the Snowflake Stage when I create it using this Terraform provider, which I need to ensure the role used by Snowflake can be assumed by Snowflake as I create a statement in the policy like
```
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["SNOWFLAKE_IAM_USER"]
    }

    condition {
      test     = "StringLike"
      values   = ["AWS_EXTERNAL_ID"]
      variable = "sts:ExternalId"
    }
  }
```
with the `SNOWFLAKE_IAM_USER` and `AWS_EXTERNAL_ID` values above taken from running the following query
```
DESCRIBE STAGE MY_NEW_STAGE;
SELECT "property_value", "property" from table(result_scan(last_query_id())) where "property" = 'AWS_EXTERNAL_ID' OR "property" = 'SNOWFLAKE_IAM_USER';
```

**Describe the solution you'd like**

The ability to have the above parameters `SNOWFLAKE_IAM_USER` and `AWS_EXTERNAL_ID` as outputs from the `snowflake_stage` resource. Maybe an object such as 
```
aws_stage_credentials {
  role = AWS_ROLE
  external_id = AWS_EXTERNAL_ID
  iam_user = SNOWFLAKE_IAM_USER
}
```

**Describe alternatives you've considered**

I create two code changes, one to create the resources and the second to hard code the values in the AWS Assume role policy. Then I try not to throw up.

**Additional context**

**Comment by ndavies-om1** [comment]
This feature request can be ignored because it has already been implemented!! 🥳 

However, it has not been documented and I only discovered this by inspecting the source code 😭 😡 

Any change we can get Outputs to automatically document correctly? It seems like none of them do

**Comment by sfc-gh-jcieslak** [comment]
Hey @ndavies-om1
The documentation fix was published some time ago, could you take a look ([here](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/stage#optional)) and close the ticket if you're ok with the current description?

**Comment by sfc-gh-dszmolka** [comment]
closing it out per above comment. Do let us know if you see something not working per the documentation.
