### ISSUE TITLE
Incompatible provider version

### ISSUE THREAD

**Issue by Bryan-Meier** [Snowflake-Labs/terraform-provider-snowflake#1089]
**Provider Version**

0.37.0

**Terraform Version**

1.1.1

**Describe the bug**

I upgraded from the chanzuckerberg/snowflake 0.29.0 provider to the snowflake-labs/snowflake 0.37.0 provider. I made this change everywhere in my project. I deleted the .terraform directory and the .hcl file so that it would build a new one fresh on the first terraform init. I am now getting this error:

Initializing provider plugins...
- Finding aidanmelen/snowsql versions matching ">= 0.2.0, >= 0.3.0"...
- Finding snowflake-labs/snowflake versions matching ">= 0.37.0"...
- Finding latest version of chanzuckerberg/snowflake...
- Installing aidanmelen/snowsql v0.4.3...
- Installed aidanmelen/snowsql v0.4.3 (self-signed, key ID A4DA8FCBF0FE9BC0)
- Installing snowflake-labs/snowflake v0.37.0...
- Installed snowflake-labs/snowflake v0.37.0 (signed by a HashiCorp partner, key ID 5166D7352E69A585)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for registry.terraform.io/chanzuckerberg/snowflake:
│ - For users on Terraform 0.13 or greater, this provider has moved to Snowflake-Labs/snowflake. Please update your source in required_providers.
╵

╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/chanzuckerberg/snowflake v0.37.0 does not have a package available for your current platform, windows_386.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

My question is, since I swapped out the old provider with the new Snowflake-Labs provider why is it still trying to use the old chanzuckerberg provider?

**Expected behavior**

A successful Terraform init

**Code samples and commands**

N/A

**Additional context**

Nothing more to add.

**Comment by gouline** [comment]
You need to replace the provider in your Terraform state as well https://www.terraform.io/cli/commands/state/replace-provider
