### ISSUE TITLE
In snowflake_stage_grant with on_future=on it is required to provide schema_name

### ISSUE THREAD

**Issue by owlleg6** [Snowflake-Labs/terraform-provider-snowflake#1100]
**Provider Version**

0.37.1

**Terraform Version**

1.2.3

**Describe the bug**

in snowflake_stage_grants when you chose **_"on_future= true"_** it is required to provide schema_name, but in parameter description you said that it is optional

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/stage_grant#schema_name

![image](https://user-images.githubusercontent.com/3865349/177559052-466aa994-ed44-4021-8be5-f1d9ec2978e4.png)

**Expected behavior**

in snowflake_stage_grant if you choose on_future=true, it could be created without providing schema_name

**Code samples and commands**

![image](https://user-images.githubusercontent.com/3865349/177560502-01aea6fe-efba-4ae7-aedd-f7fbfe6e4f98.png)

**Comment by philippeboyd** [comment]
+1 on this... the [documentation](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/stage_grant#on_future) even says:

> When this is true and no schema_name is provided apply this grant on all future stages in the given database.
