### ISSUE TITLE
Unable to create file formats due to obsolete VALIDATE_UTF8 parameter

### ISSUE THREAD

**Issue by zyzil** [Snowflake-Labs/terraform-provider-snowflake#1147]
**Provider Version**

0.40.0

**Terraform Version**

1.0.4

**Describe the bug**

File formats are not able to be created due to SQL compilation errors around the validate_utf8 parameter:

`Error: error creating file format EXAMPLE_FILE_FORMAT: 001008 (22023): SQL compilation error: invalid value [false] for parameter 'VALIDATE_UTF8'`

**Expected behavior**

File formats should be able to be created.

**Code samples and commands**

```
resource "snowflake_file_format" "example" {
  name = "EXAMPLE_FILE_FORMAT"
  database = "sandbox"
  schema = "public"
  format_type = "CSV"
}
```

**Additional context**

[Snowflake info on obsolete VALIDATE_UTF8](https://community.snowflake.com/s/article/VALIDATE-UTF8-File-Format-Option-Obsoleted)

**Comment by sfc-gh-asawicki** [comment]
Closing because done in #1166.
