### ISSUE TITLE
after import a role_grant it does not show any `users` associated with said role_grant

### ISSUE THREAD

**Issue by umarh-ccy** [Snowflake-Labs/terraform-provider-snowflake#1149]
**Provider Version**
~> 0.40

**Terraform Version**
Terraform v1.2.3

The version of Terraform you were using when the bug was encountered.
Terraform v1.2.3

**Describe the bug**

After import a specific role_grant via the import syntax the state file does not show the associated users with said role_grant

if I try to add a user to the grant, it lists this is a change.

when I run `SHOW GRANTS OF ROLE TEST`

I can see a view users which I've granted access to the this role_grant.

am I misunderstanding something? 

**Expected behavior**

A list of associated users with the role_grant

**Code samples and commands**

```
terraform import module.c_role_grant.snowflake_role_grants.TEST_GRANT TEST

terraform state show module.c_role_grant.snowflake_role_grants.TEST_GRANT

resource "snowflake_role_grants" "TEST_GRANT" {
    id        = "TEST"
    role_name = "TEST"
    roles     = []
    users     = [] # <- should contain user1, user2 etc. 
}
```

**Comment by umarh-ccy** [comment]
so, after new role_grant, adding a few users to it it works only after adding them in Terraform and running apply which lists adding users as a change. I'm unsure why the state is not updating with the users?

**Comment by nikoshet** [comment]
Take a look at this issue https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1082 and at this discussion https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/740 which mention the same problem, yet no solution is provided.

**Comment by umarh-ccy** [comment]
> Take a look at this issue #1082 and at this discussion #740 which mention the same problem, yet no solution is provided.

Thanks @nikoshet would you suggest I close this or should I leave it to maintainers to merge with yours & #740 ?

**Comment by nikoshet** [comment]
We can let the maintainers decide :)

**Comment by hugh-oa** [comment]
In addition, if you change a role via the UI that is already maintained by terraform and then run `terraform apply` it will not report the drift. It thinks the infra is unchanged.

**Comment by sfc-gh-swinkler** [comment]
Hello, i just wanted to let you know that this has been fixed in the latest release. Example:

```
$ terraform import snowflake_role_grants.prd_dl_epmd_db_ro "OPERATIONS_USER|TST_SNOWSQL_ROLE,PRD_DL_EPMD_DB_RO|user2,user1"
snowflake_role_grants.prd_dl_epmd_db_ro: Importing from ID "OPERATIONS_USER|TST_SNOWSQL_ROLE,PRD_DL_EPMD_DB_RO|user2,user1"...
snowflake_role_grants.prd_dl_epmd_db_ro: Import prepared!
  Prepared snowflake_role_grants for import
```

...

```
$ terraform state show snowflake_role_grants.prd_dl_epmd_db_ro
# snowflake_role_grants.prd_dl_epmd_db_ro:
resource "snowflake_role_grants" "prd_dl_epmd_db_ro" {
    id        = "OPERATIONS_USER|TST_SNOWSQL_ROLE,PRD_DL_EPMD_DB_RO|user2,user1"
    role_name = "OPERATIONS_USER"
    roles     = [
        "PRD_DL_EPMD_DB_RO",
        "TST_SNOWSQL_ROLE",
    ]
    users     = [
        "user1",
        "user2",
    ]
}
```
