### ISSUE TITLE
"snowflake_external_oauth_integration" is missing the "external_oauth_scope_mapping_attribute" attribute

### ISSUE THREAD

**Issue by ElectroTiger** [Snowflake-Labs/terraform-provider-snowflake#1153]
The "[snowflake_external_oauth_integration](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/external_oauth_integration)" is missing the "external_oauth_scope_mapping_attribute" attribute.

Strangely enough, Snowflake themselves have forgtten to document the "external_oauth_scope_mapping_attribute" in their [official SQL docs](https://docs.snowflake.com/en/sql-reference/sql/create-security-integration-oauth-external.html) - but they did remember to document it in their [tutorial ](https://docs.snowflake.com/en/user-guide/oauth-ext-custom.html#step-1-obtain-key-environment-values-to-use-external-oauth) for setting up custom external oauth integration. I have raised this issue with Snowflake support - hopefully the correct the official SQL documentation in a few days.

**Comment by aherve** [comment]
Any update on this ? For some reason this value is shown in snowlake with a default value of `scp`, but nothing works until we manually set the value to `scp`. This makes this resource virtually useless until we can set this missing parameter !
