### ISSUE TITLE
Support "days_to_expiry" for a given user

### ISSUE THREAD

**Issue by thisiscab** [Snowflake-Labs/terraform-provider-snowflake#1155]
**Is your feature request related to a problem? Please describe.**

We're trying to set an expiration date for some of the users we're creating. You can achieve this in the Admin of Snowflake but this provider doesn't support that option.

**Describe the solution you'd like**

To add the property "days_to_expiry" at the user level.

**Describe alternatives you've considered**

None

**Additional context**

It seems like you're accounting for that property in the  "[user_ownership_grant](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/snowflake/user_ownership_grant.go#L52)" but it's not being surfaced at the user level.

**Comment by sfc-gh-asawicki** [comment]
Hey @thisiscab. We released v0.95 of the provider yesterday. It adds the `days_to_expiry` attribute: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/user#days_to_expiry.
