### ISSUE TITLE
resource `snowflake_schema_grant`'s shares default value has been changed to `null` on Snowflake

### ISSUE THREAD

**Issue by Tideorz** [Snowflake-Labs/terraform-provider-snowflake#1164]
**Provider Version**

0.40.0

**Terraform Version**

1.0.11

**Describe the bug**

For resource `snowflake_schema_grant`, I set the `shares` after applying the terraform and found that the `shares` default value will be set as `null` in the state file. And in my CI job, when running the `terraform plan` command again. There will have a change in output. 

**Expected behavior**

`plan` shouldn't show any output.

**Code samples and commands**

I didn't set the `shares` in terraform `main.tf`. 

```
resource "snowflake_schema_grant" "schema_grant_create_materialized_view" {
  provider      = snowflake.security
  database_name = var.database
  schema_name   = var.name
  privilege     = "CREATE MATERIALIZED VIEW"
  roles         = [module.owner_role.name]
}
```
But in the CI job,  run the`terraform plan` again to double-check the created resources, there is an update. ` + shares                 = []`

```
  ~ resource "snowflake_schema_grant" "schema_grant_create_materialized_view" {
        id                     = "PROD_LOAD_INCREMENTAL|FORMATTED_ZYTE_META||CREATE MATERIALIZED VIEW|PROD_LOAD_INCREMENTAL_FORMATTED_ZYTE_META_OWNER|false"
      + shares                 = []
        # (7 unchanged attributes hidden)
```

If the optional argument could be `null`, I think this output will disappear.

**Additional context**

Other resources like `snowflake_role_grants`'s `users` maybe also have the same problem.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
