### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by gary-beautypie** [Snowflake-Labs/terraform-provider-snowflake#1169]
Hi, just wondering how frequently this gets released anymore/ if it's still on a schedule? The README suggests weekly but that doesn't seem to be the case anymore

**Comment by sfc-gh-asawicki** [comment]
Hey @gary-beautypie.

Currently, we are releasing weekly, usually on Wednesdays or Thursdays. There are exceptions to this rule.

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity, the answer was already provided. We try to stick to weekly releases, as mentioned, usually on Wednesdays or Thursdays.
