### ISSUE TITLE
UNIQUE key for CREATE TABLE

### ISSUE THREAD

**Issue by yohei1126** [Snowflake-Labs/terraform-provider-snowflake#1177]
**Is your feature request related to a problem? Please describe.**

We want to use UNIQUE key for columns in CREATE TABLE statements 
https://docs.snowflake.com/en/sql-reference/constraints-overview.html

but can not find in current implementation 

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/table.go
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table

**Describe the solution you'd like**

* add new boolean value `unique` to column in snowflake_table

```
resource "snowflake_table" "table" {
  database            = snowflake_schema.schema.database
  schema              = snowflake_schema.schema.name
  name                = "table"
  comment             = "A table."

  column {
    name     = "id"
    type     = "int"
    nullable = true
    unique = true
  }
```

**Additional context**

**Comment by sfc-gh-asawicki** [comment]
Closing because of https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table_constraint existence.
