### ISSUE TITLE
Stored procedure argument name not getting updated on snowflake

### ISSUE THREAD

**Issue by akshazsingh** [Snowflake-Labs/terraform-provider-snowflake#1189]
**Provider Version**

provider registry.terraform.io/snowflake-labs/snowflake v0.41.0

**Terraform Version**

Terraform v1.1.4

**Describe the bug**

The arguments for snowflake_procedure not updating the name of the argument.
I tried changing the name of an argument for a snowflake_procedure and during the apply step it states that the resource will be replaced in place but when I check the argument signature on snowflake the signature does not update.

**Expected behavior**

The argument signature should be updated in snowflake when the name of the argument in snowflake_procedure is updated.

**Code samples and commands**

>> terraform plan

![Capture1](https://user-images.githubusercontent.com/89646904/186383425-0e4e6008-b4a5-4798-9de1-3a67e9d88666.PNG)

>> terraform apply

![Capture3](https://user-images.githubusercontent.com/89646904/186383863-16dbf9f1-b25c-49d1-85fc-5eb32daf9fad.PNG)

On Snowflake when I check the arguments

![Capture2](https://user-images.githubusercontent.com/89646904/186383948-71c612f5-242c-496f-a64d-d22a256d0dba.PNG)

Still no change!

**Comment by sfc-gh-asawicki** [comment]
Hey @akshazsingh.

In v0.100.0 we have introduced new procedure resources. Renaming attribute should be handled correctly now. Please check it out and let us know.

**Comment by sfc-gh-dszmolka** [comment]
closing this out per above comment. If you still see the issue happening with v0.100.0 / v1, do let us know please.
