### ISSUE TITLE
snowflake_tag_association does not support column-level tagging

### ISSUE THREAD

**Issue by ogr003** [Snowflake-Labs/terraform-provider-snowflake#1201]
**Provider Version**

0.43.0

**Terraform Version**

1.2.1

**Describe the bug**

It is not possible to create a column tag association, even though it is a supported `object_type`. This should execute a `ALTER TABLE ... ALTER COLUMN` statement, but currently executes a `ALTER COLUMN`-statement, which is not valid.

**Expected behavior**

The resource should support passing database, schema, table (only supported for column) and name as separate attributes, or parse the attributes similarly to what is done for the `tag_id` attribute. When the `object_type` is "COLUMN", an `ALTER TABLE ... ALTER COLUMN` statement should be executed.

**Code samples and commands**

```
# COLUMN
resource "snowflake_tag_association" "tag_associations" {
    object_name     = "DB.SCHEMA.TABLE_NAME.TEST_COLUMN"
    object_type     = "COLUMN"
    tag_id          = "TAG_DB.TAG_SCHEMA.TAG_NAME"
    tag_value       = "TEST"
}
```

**Additional context**

The statement above executes `ALTER COLUMN "DB.SCHEMA.TABLE_NAME.TEST_COLUMN" SET TAG "TAG_DB"."TAG_SCHEMA"."TAG_NAME" = "TEST"` which gives a syntax error as `ALTER COLUMN ...` is not supported on Snowflake.

**Comment by liamjamesfoley** [comment]
➕1 this is preventing us from implementing tag based masking polices in Terraform.

**Comment by mhmcdonald** [comment]
this is also preventing us from implementing tag-based masking with Terraform. Is anyone able to help with this?
