### ISSUE TITLE
snoflake_table resource is not renaming the column

### ISSUE THREAD

**Issue by pranavkulkarni1012** [Snowflake-Labs/terraform-provider-snowflake#1210]
Provider Version:0.43.0

The provider version you are using.

**Describe the bug**

When we rename the column in snowflake_table resource file, its not renaming the column in table (i.e. alter table rename column...)
but its dropping existing column and creating new column with new name. Existing data of old column is lost
**Expected behavior**

it should run alter table rename column. Data should not be lost from the column.

resource "snowflake_table" "tf_test" {
  database = "TF_DEMO_DB"
  schema   = "TF_DEMO"
  name     = "TF_TEST"

  column {
    name     = "id"
    type     = "NUMBER(38,0)"
    nullable = true
    comment  = "id column comment"
  }

  column {
    name     = "newdata"
    type     = "VARCHAR(16777216)"
    nullable = false
    comment  = "data column comment"
  }

  column {
    name     = "create_ts"
    type     = "timestamp"
    nullable = false
    comment  = "ts column comment"
  }

  comment = "table comment"
}

Snowflake DDL:

ALTER TABLE "TF_DEMO_DB"."TF_DEMO"."TF_TEST" DROP COLUMN "data"

ALTER TABLE "TF_DEMO_DB"."TF_DEMO"."TF_TEST" ADD COLUMN "newdata" VARCHAR(16777216) NOT NULL COMMENT 'data column comment'

 
This use case failed, as there are rows in the table. The first alter table dropped the column, the second alter failed as it could not create column as not null with rows

**Comment by sfc-gh-ngaberel** [comment]
Duplicates of https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/753
