### ISSUE TITLE
Suspend the task on snowflake_task_grant

### ISSUE THREAD

**Issue by alex-user-go** [Snowflake-Labs/terraform-provider-snowflake#1212]
**Is your feature request related to a problem? Please describe.**
When creating a task with enabled = true:
```
resource "snowflake_task" "task_cleaning {
  name          = "task_cleaning"
  enabled       = true
...
}
```
It's impossible to change the OWNERSHIP privilege:
```
resource "snowflake_task_grant" "grant_task_cleaning" {
  task_name = "task_cleaning"
  enable_multiple_grants = true
  with_grant_option = true    
  privilege = "OWNERSHIP"
  roles     = ["new_role"] 
}
```

> Error: 091421 (22000): Unable to update graph with root task "..."task_cleaning" since that root task is not suspended.

**Describe the solution you'd like**

In my opinion snowflake_task_grant must suspend the task, make changes and then resume it.

**Describe alternatives you've considered**

Maybe there is another way to do it?

**Additional context**
-

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
