### ISSUE TITLE
Allow configuration of SYNC_PASSWORD setting for SCIM integration

### ISSUE THREAD

**Issue by ehluke** [Snowflake-Labs/terraform-provider-snowflake#1224]
We are seeing passwords being synchronized via the Terraform configured SCIM integration via Okta; which presents a security concern.

The Snowflake SCIM Integration supports a `SYNC_PASSWORD` property to disable this functionality, but it cannot currently be set via the Terraform provider.

We would like the Terraform provider to be able to optionally configure the `SYNC_PASSWORD` property as part of the "snowflake_scim_integration" (especially if using Okta).

Currently, the only option to set this property is outside of Terraform.

**Comment by bschwedler** [comment]
This is an important setting for our setup.
We want to completely disable the user of password basic auth for any user that is managed with Okta.

We currently have to manually go in after the fact and alter this setting via SQL.

**Comment by sfc-gh-jmichalak** [comment]
Hey @ehluke @bschwedler   👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) is adjusted and contains `sync_password`. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#snowflake_scim_integration-resource-changes).
