### ISSUE TITLE
0.44.0 regression for snowflake_schema_grant resources

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1226]
**Provider Version**

Upgrading from 0.43.1 to 0.44.0.

**Terraform Version**

1.2.0

**Describe the bug**

We're currently on provider 0.43.1, and dependabot proposed an upgrade to 0.44.0. On 0.43.1, we're using a bunch of `snowflake_schema_grant` resources, and we can run a `terraform plan` on 0.43.1 cleanly with no proposed diffs.

When we change the provider to 0.44.0, `terraform plan` proposes a bunch of diffs to create `snowflake_schema_grant` resources, even though those resources already exist.

**Expected behavior**

If I'm on 0.43.1 and `terraform plan` proposes no diffs, then I should be able to upgrade to 0.44.0, also with no difffs.

**Code samples and commands**

Here's the Snowflake console showing that this grant already exists as expected:

<img width="888" alt="Screen Shot 2022-09-21 at 9 43 50 AM" src="https://user-images.githubusercontent.com/39737211/191520987-e726c0b3-3ec8-421b-a8ed-ba308fa344c9.png">

Here's the behavior of 0.43.1:

```
$ terraform version | grep snowflake
+ provider registry.terraform.io/snowflake-labs/snowflake v0.43.1

$ terraform state show module.production_application.snowflake_schema_grant.staging_schema[\"MONITOR\"]
# module.production_application.snowflake_schema_grant.staging_schema["MONITOR"]:
resource "snowflake_schema_grant" "staging_schema" {
    database_name     = "PRODUCTION"
    id                = "PRODUCTION|STAGING||MONITOR|false"
    on_future         = false
    privilege         = "MONITOR"
    roles             = [
        "PRODUCTION_STAFF_READ_WRITE",
        "production_role",
    ]
    schema_name       = "STAGING"
    shares            = []
    with_grant_option = false
}

$ terraform plan -target=module.production_application.snowflake_schema_grant.staging_schema[\"MONITOR\"]

No changes. Your infrastructure matches the configuration.
```

Here's the behavior of 0.44.0:

```
$ git checkout dependabot/terraform/environments/production/Snowflake-Labs/snowflake-0.44.0
$ rm -rf .terraform && terraform init

$ terraform version | grep snowflake
+ provider registry.terraform.io/snowflake-labs/snowflake v0.44.0

$ terraform plan -target=module.production_application.snowflake_schema_grant.staging_schema[\"MONITOR\"]
Terraform will perform the following actions:

  # module.production_application.snowflake_schema_grant.staging_schema["MONITOR"] will be created
  + resource "snowflake_schema_grant" "staging_schema" {
      + database_name          = "PRODUCTION"
      + enable_multiple_grants = false
      + id                     = (known after apply)
      + on_future              = false
      + privilege              = "MONITOR"
      + roles                  = [
          + "PRODUCTION_STAFF_READ_WRITE",
          + "production_role",
        ]
      + schema_name            = "STAGING"
      + with_grant_option      = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by pecigonzalo** [comment]
This is also causing the following error for us on apply

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ snowflake_warehouse_grant.element_warehouses_operate["security_s"],
│ provider "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by astanfel** [comment]
I am seeing a similar issue when jumping from 0.51.0 and the latest version 0.56.3. Zero diff on 0.51.0 and Terraform is wanting to issue all of our schema grants again. It will successfully apply, but display the same grants being issued again when we run a plan again.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
