### ISSUE TITLE
This is a bug in the provider, which should be reported in the provider's own issue tracker.

### ISSUE THREAD

**Issue by systematics78** [Snowflake-Labs/terraform-provider-snowflake#1230]
**Provider Version**
0.44.0
The provider version you are using.
0.44.0
**Terraform Version**
latest
The version of Terraform you were using when the bug was encountered.
latest
**Describe the bug**
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["2"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
**Expected behavior**
All grants which looks good for version 0.43.1 now encounters an error
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
**Code samples and commands**
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
Please add code examples and commands that were run to cause the problem.
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
**Additional context**
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_database_grant.ownerchange_to_pla_admins_for_idq_dbs["3"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.
23:56:51  
23:56:51  
23:56:51  Error: Provider produced inconsistent result after apply
23:56:51  
23:56:51  When applying changes to
23:56:51  snowflake_schema_grant.idq_ownership_grant_to_idq_admin["26"], provider
23:56:51  "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new
23:56:51  value: Root resource was present, but now absent.
23:56:51  
23:56:51  This is a bug in the provider, which should be reported in the provider's own
23:56:51  issue tracker.

**Comment by sfc-gh-ckite** [comment]
Also experiencing this error on a fresh install of 0.44.0

**Comment by amonkhouse** [comment]
Also getting this when trying to create a table on v0.46.0.

**Comment by systematics78** [comment]
It is already addresed and fixed in provider version 0.45.0
