### ISSUE TITLE
new feature: Explicitly Enable Change Tracking on Views

### ISSUE THREAD

**Issue by yohei1126** [Snowflake-Labs/terraform-provider-snowflake#1253]
**Is your feature request related to a problem? Please describe.**

* Table has a property `change_tracking`, which is a requirement to create a stream on a table https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table
* but View does not have the same property. It should support `change_tracking` https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/view

* https://docs.snowflake.com/en/user-guide/streams-manage.html#explicitly-enable-change-tracking-on-views

```
create secure view v change_tracking = true as select col1, col2 from t;
alter view v2 set change_tracking = true;
```

**Describe the solution you'd like**

* Add new property `change_tracking` just like table

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by sfc-gh-jmichalak** [comment]
Closing the issue due to inactivity.
