### ISSUE TITLE
Warehouse grant fails due to recently created warehouse not being available yet

### ISSUE THREAD

**Issue by froblesmartin** [Snowflake-Labs/terraform-provider-snowflake#1255]
**Provider Version**

0.45.0

**Terraform Version**

Terraform v1.3.1

**Describe the bug**

While configuring a warehouse and a warehouse grant, I have faced:

> module.snowflake.module.warehouses["warehouse_sample"].snowflake_warehouse.warehouse: Creation complete after 1s [id=some-sample-warehouse]
> 
> Error: 002003 (02000): SQL compilation error:
> Warehouse '"some-sample-warehouse"' does not exist or not authorized.

After a second execution, it worked just fine.

**Expected behavior**

The provider should wait properly for a resource that depends on another to be created and then available to be configured.

**Comment by bennylu2** [comment]
Could you provide sample code of the issue?

**Comment by froblesmartin** [comment]
Sorry, it was my bad, not referencing the warehouse by the resource itself, I was initially referencing it just by the warehouse name variable.
