### ISSUE TITLE
Creation of non reader Snowflake account via Terraform

### ISSUE THREAD

**Issue by sfc-gh-msingh** [Snowflake-Labs/terraform-provider-snowflake#1260]
We would like to automate the creation of our Snowflake account with Terraform, Currently, as per the documentation[1] we can create only   "READER" type accounts in Snowflake-managed accounts.

Within the managed account terraform resource it looks like "type" is set to "reader". We would like to have a feature to create sub-accounts, which are not only reader type, We would also need the ability to set these as "enterprise" accounts but we do not see "EDITION" in the Terraform schema as well.

[1]
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/managed_account

**Comment by sfc-gh-swinkler** [comment]
Hello, @sfc-gh-msingh I am not sure this is a Terraform provider issue. The Terraform provider can only manage resources that the API supports. See https://docs.snowflake.com/en/sql-reference/sql/create-managed-account.html#create-managed-account which states:

> Creates a new managed account. Currently used by data providers to create reader accounts for their consumers.

Managing other kinds of accounts could be done using a different resource, for example a `snowflake_account` resource. The API that allows for this is different than the one for managed accounts: https://docs.snowflake.com/en/sql-reference/sql/create-account.html. I intend to be working on this feature soon. Can you please confirm if this would fix your problem?

**Comment by sfc-gh-swinkler** [comment]
@sfc-gh-msingh there is now a snowflake_account resource.  https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account
