### ISSUE TITLE
snowflake_roles (Data Source)

### ISSUE THREAD

**Issue by systematics78** [Snowflake-Labs/terraform-provider-snowflake#1269]
**Is your feature request related to a problem? Please describe.**

Data source snowflake_roles as snowflake_users (Data Source) - which will help to pool all roles from snowflake. Also very useful data source can be snowflake_roles_hierarchy - which will give as output role hierarchy info - https://community.snowflake.com/s/article/Quickly-Visualize-Snowflake-s-Roles-Grants-and-Privileges

By the way it is already in new web ui. 

But any case - snowflake_roles data source will be very usefull

**Comment by bennylu2** [comment]
This was resolved with https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1309 so it should be marked as resolved/closed

**Comment by sfc-gh-asawicki** [comment]
Closing because done in #1309
