### ISSUE TITLE
Updating the credit_quota in snowflake_resource_monitor breaks the resource monitor

### ISSUE THREAD

**Issue by bdumford-OM1** [Snowflake-Labs/terraform-provider-snowflake#1310]
**Provider Version**

0.40.0

**Terraform Version**

0.13.4

**Describe the bug**

Updating the credit quota in "snowflake_resource_monitor" causes the resource monitor to be replaced such that it is no longer attached to the warehouse it is monitoring.  Additionally, any monitoring grants on the resource monitor provider to roles are lost.

```
# module.sample_warehouse.snowflake_resource_monitor.warehouse_monitor must be replaced
-/+ resource "snowflake_resource_monitor" "warehouse_monitor" {
!       credit_quota               = 1500 -> 1000 # forces replacement
        frequency                  = "MONTHLY"
!       id                         = “SAMPLE_MONITOR" -> (known after apply)
        name                       = “SAMPLE_MONITOR"
        notify_triggers            = []
        set_for_account            = false
!       start_timestamp            = "2022-10-01T00:00:00Z" -> "2022-11-01T00:00:00Z"
-       suspend_immediate_triggers = [] -> null
-       suspend_triggers           = [] -> null
    }
```
Workaround: A subsequent plan and apply will fix both of these issues
```
# module.sample_warehouse.snowflake_resource_monitor_grant.warehouse_monitor_grants must be replaced
-/+ resource "snowflake_resource_monitor_grant" "warehouse_monitor_grants" {
        enable_multiple_grants = false
!       id                     = “SAMPLE_MONITOR" -> (known after apply)
        monitor_name           = "SAMPLE_MONITOR"
        privilege              = "MONITOR"
!       roles                  = [ # forces replacement
+           “ROLE1”,
+           "ROLE2”,
        ]
        with_grant_option      = false
    }

  # module.sample_warehouse.snowflake_warehouse.warehouse will be updated in-place
! resource "snowflake_warehouse" "warehouse" {
        auto_resume                         = true
        auto_suspend                        = 300
        id                                  = “SAMPLE”
        initially_suspended                 = true
        max_cluster_count                   = 1
        max_concurrency_level               = 1
        min_cluster_count                   = 1
        name                                = “SAMPLE”
!       resource_monitor                    = "null" -> “SAMPLE_MONITOR"
        scaling_policy                      = "STANDARD"
        statement_queued_timeout_in_seconds = 0
        statement_timeout_in_seconds        = 14400
        warehouse_size                      = "X-Large"
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```

**Expected behavior**

The resource monitor would be recreated such that it is still attached to the warehouse and monitoring grants are not lost.  Ideally, the resource monitor would be updated in place rather than destroyed and recreated.

**Comment by JonMerlevede** [comment]
A change in credit quota should not force the re-creation of the monitor; altering it is possible...

**Comment by sfc-gh-swinkler** [comment]
@JonMerlevede agreed, looking at the source code for this resource it looks like some lazy implementation, since no Update function was done at all for this resource. We can definitely get this fixed so it is no longer force new.

**Comment by bennylu2** [comment]
> @JonMerlevede agreed, looking at the source code for this resource it looks like some lazy implementation, since no Update function was done at all for this resource. We can definitely get this fixed so it is no longer force new.

@sfc-gh-swinkler I would love to contribute/pair on this feature. This has bothered me for a while now but I am relatively new to go
