### ISSUE TITLE
The option `enable_multiple_grants` for grants is not respected for shares

### ISSUE THREAD

**Issue by fernandobrito** [Snowflake-Labs/terraform-provider-snowflake#1339]
**Provider Version**

`0.49.0`

**Terraform Version**

`1.3.0`

**Describe the bug**

On grants (such as [snowflake_database_grant](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/database_grant)), there is an argument called `enable_multiple_grants` to "cause Terraform to not revoke grants applied to roles and objects outside Terraform."

It works for `roles`, but not for `shares`. 

**Expected behavior**

The `enable_multiple_grants` is respected for shares, just like it is for roles.

**Code samples and commands**

Given the following resources (one database, 2 shares and one grant):

```
  resource "snowflake_database" "database" {
    provider = snowflake.ACCOUNTADMIN
    name     = "TEST"
  }
  
  resource "snowflake_share" "share_one" {
    provider = snowflake.ACCOUNTADMIN
    name     = "SHARE_ONE"
  }
  
  resource "snowflake_share" "share_two" {
    provider = snowflake.ACCOUNTADMIN
    name     = "SHARE_TWO"
  }
  
  resource "snowflake_database_grant" "database_share_one_usage" {
    provider      = snowflake.ACCOUNTADMIN
    database_name = snowflake_database.database.name
  
    privilege = "USAGE"
    shares = [
      snowflake_share.share_one.name
    ]
  
    enable_multiple_grants = true
  }
```

When applying, I end up with the following, as expected:

![image](https://user-images.githubusercontent.com/196840/199804721-46157730-b6c8-4228-a8fb-f1ba09790628.png)

Then I run an extra grant on Snowflake with `grant usage on database test to share share_two;`.

On the next execution, Terraform will delete this extra grant.

![image](https://user-images.githubusercontent.com/196840/199805594-e1fbece5-3ab6-44aa-a05c-85c6ceb41744.png)

**Reproducing only with Terraform**

Another way to reproduce the issue without any manual steps (only within Terraform), is to add the second grant at the end of the file above.

```
resource "snowflake_database_grant" "database_share_two_usage" {
  provider      = snowflake.ACCOUNTADMIN
  database_name = snowflake_database.database.name

  privilege = "USAGE"
  shares = [
    snowflake_share.share_two.name
  ]

  enable_multiple_grants = true
}
```

Running apply multiple times in a row will cause Terraform to keep dropping and giving the grants, as the first `snowflake_database_grant` tries to delete the grant created by the second one, and vice-versa.

**Additional information**

I have no experience writing Terraform providers or using Golang, but trying to trace down how and where exactly `enable_multiple_grants` is applied led me to https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/grant_helpers.go#L280. The `multipleGrantFeatureFlag` is used when populating the `roles` variable, but not for the `shares`.

I'm happy to take this as my first contribution if all that is needed is to replicate the same logic that is applied for the `roles` array.

**Comment by systematics78** [comment]
this issue i have observed starting from version 0.46.0

**Comment by fernandobrito** [comment]
@systematics78 for shares? Interesting. I can reproduce the issue by running the code above on version 0.45.0. Also, the source code for this version looks fairly similar to what it looks like today: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/v0.45.0/pkg/resources/grant_helpers.go#L290.

**Comment by arik103** [comment]
@fernandobrito I am stuck on this bug as well. Did you find any workarounds for this issue?

**Comment by cpmub1** [comment]
I am facing the same issue. can this issue be fixed ? or any workarounds ?

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)

Important to note is that the new resources don't have such a flag as enable_multiple_grants. Right now, the new resources have enable_multiple_grants "enabled by default". Also, there's no option (yet at least) to turn it off, so `enable_multiple_grants = false` is not available in the new grant resources.
