### ISSUE TITLE
The option `enable_multiple_grants` for grants does not respect empty argument for roles

### ISSUE THREAD

**Issue by fernandobrito** [Snowflake-Labs/terraform-provider-snowflake#1341]
**Provider Version**

`0.49.0`

**Terraform Version**

`1.3.0`

**Describe the bug**

On grants (such as [snowflake_database_grant](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/database_grant)), there is an argument called `enable_multiple_grants` to "cause Terraform to not revoke grants applied to roles and objects outside Terraform."

If you use grant resources with `enable_multiple_grants = true` to grant privileges to shares but do not specify any roles, the provider will remove the existing grants given to roles on the target object.

**Expected behavior**

All existing grants (including the ones granted to roles) are kept.

**Code samples and commands**

Given the following resources (one database, one shares, one role and one grant):

```
resource "snowflake_database" "database_grants" {
  provider = snowflake.ACCOUNTADMIN
  name     = "TEST_GRANTS"
}

resource "snowflake_share" "share_a" {
  provider = snowflake.ACCOUNTADMIN
  name     = "SHARE_A"
}

resource "snowflake_role" "role_one" {
  provider = snowflake.SECURITYADMIN
  name     = "ROLE_ONE"
}

resource "snowflake_database_grant" "database_share_a_usage" {
  provider      = snowflake.ACCOUNTADMIN
  database_name = snowflake_database.database_grants.name

  privilege = "USAGE"
  shares = [
    snowflake_share.share_a.name
  ]

  enable_multiple_grants = true
}
```

If I run an extra grant on Snowflake (outside Terraform) with `grant usage on database test_grants to role role_one`, on the next execution, Terraform will delete this extra grant.

![image](https://user-images.githubusercontent.com/196840/199918848-eb13452d-1687-4ea3-b478-c9e3b294e787.png)

If I add `roles = []` as argument to the resource, the same happens (all grants to roles are deleted).

However, if I add a valid argument (such as `roles = ["SYSADMIN"]`), the behavior changes. On the first run, Terraform will delete the existing grant given outside Terraform, but if I grant them again (outside Terraform), Terraform will then keep them.

**Additional context**

I have no experience writing Terraform providers or using Golang, but trying to trace down how and where exactly `enable_multiple_grants` is applied led me tohttps://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/grant_helpers.go#L285. I haven't had time yet to go deeper on where the issue is.

**Comment by sfc-gh-swinkler** [comment]
fixed in pr #1510 . Will be released as part of 0.56.3
