### ISSUE TITLE
Data retention time should be nullable

### ISSUE THREAD

**Issue by jnoynaert** [Snowflake-Labs/terraform-provider-snowflake#1367]
Data retention time for databases, schemas, and tables should support passing a true null value (to allow these objects to inherit settings)

**Comment by sfc-gh-jcieslak** [comment]
Hey @jnoynaert 👋
I'm currently working on databases as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1. In the next release we will provide new database resources with parameters (like data_retention_time_in_days) as Optional and Computed values. Meaning, if you would like to set this parameter you can, but if you don't set it it will be populated with the value from Snowflake (inherited value for data_retention_time_in_days from the Account in this case). Is that something you are referring to or something else?

**Comment by sfc-gh-jcieslak** [comment]
Hey @jnoynaert  👋
The new version ([v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0)) refactored `snowflake_database` with the new convention on parameters. When (e.g. `data_retention_time_in_days`) is not set, the value from Snowflake will be put there (from the parameters hierarchy), but when you set it in the configuration, the value will be set on the Database parameter level. Please, try to use the latest version and resolve the issue if that's what you requested for.

**Comment by sfc-gh-jcieslak** [comment]
Closing, due to long inactivity.
