### ISSUE TITLE
data sources seem to ignore variables.tfvars

### ISSUE THREAD

**Issue by short-hi** [Snowflake-Labs/terraform-provider-snowflake#1371]
**Provider Version**
0.47

**Terraform Version**
1.3.4

**Describe the bug**
It appears that snowflake data sources ignore the supplied "variables.tfvars" file.

When data sources are not part of our code, the following command ```terraform plan -var-file="environments/shared/variables.tfvars"``` works without fail. We can create resources and assing privileges without problems.
But when we introduced 'data sources' to the Terraform code, the same command (```terraform plan -var-file="environments/shared/variables.tfvars"```) resulted in errors of missing variable values:

![image](https://user-images.githubusercontent.com/103753960/201673638-448983cd-98c9-4148-bb06-d5baa847ac29.png)

The supposedly  missing values are part of the "variables.tfvars":
![image](https://user-images.githubusercontent.com/103753960/201675847-b54445b7-cdfe-41b7-82cb-92c72c48a046.png)
And the code worked without the data sources. Also the errors dissappear again as soon as we remove the data sources from the Terraform code.

**Expected behavior**

We expected no errors about missing values for variables as without the data sources code, everything works fine.

**Code samples and commands**

We haven't been able to link the behaviour to a single data source, it seems to be a problem for all data sources.

Example of 2 of our datasources:

**Databases Data Source**
```
data "snowflake_databases" "current" {}
```
**Tables Data Source **
```
data "snowflake_tables" "current" {
  for_each = { for obj in  local.managed_schemas : "${obj.database}-${obj.schema}" => obj}
  database = each.value.database
  schema   = each.value.schema
}
```

Commands that fail:
```terraform plan -var-file="environments/shared/variables.tfvars"```
```terraform apply -var-file="environments/shared/variables.tfvars"```

**Additional context**

We have currently found a work-around, which is setting all required variables as environment variables, then everything works. But it requires script rework to fully replace the "variables.tfvars" and it just seems like a bug.

**Comment by sfc-gh-jcieslak** [comment]
Hey @short-hi 👋 
It seems like an issue with the provider rather than data source. As the issue is pretty old, please try the latest version and let me know If you still need some help with that.

**Comment by sfc-gh-jcieslak** [comment]
Hey @short-hi 👋 
Closing due to long inactivity. If the issue still persists, please try to use the newer versions of the provider. If any issue appears there, please create another gh issue. Thank You.
