### ISSUE TITLE
snowflake_databases does not return any databases

### ISSUE THREAD

**Issue by jifeous** [Snowflake-Labs/terraform-provider-snowflake#1383]
**Provider Version**

Terraform v1.3.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.40.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.52.0

**Describe the bug**

Using the snowflake_databases and snowflake_database data provider returns only nulls  and does not return the expected db. If I check the snowflake query history I can see that it has run the correct sql "SHOW DATABASES LIKE "MYDB"".

**Expected behavior**

Returns the db so that I can use it to create a schema

**Code samples and commands**

data "snowflake_database" "domain" {
  name = "MYDB"
}

output "snowflake_database" {
  description = "Where is my db?"
  value = data.snowflake_database.domain
}

**Comment by bennylu2** [comment]
This sounds like a permission issue. Have you confirmed the role you're using has access to list the db?

**Comment by jifeous** [comment]
yes, it's the same role that created everything including databases so I
would expect it to return some in a list. Hmm, but let me turn logging on
and double check it's empty.

**Comment by bennylu2** [comment]
```
data "snowflake_database" "domain" {
  name = "TEST"
}

output "snowflake_database" {
  value = data.snowflake_database.domain
}
```

```
Changes to Outputs:
  + snowflake_database = {
      + comment        = "Snowflake database for TEST"
      + created_on     = "2021-10-21T13:35:25.113-07:00"
      + id             = "TEST"
      + is_current     = false
      + is_default     = false
      + name           = "TEST"
      + options        = ""
      + origin         = ""
      + owner          = "SYSADMIN"
      + retention_time = 30
    }
```

I'm unable to reproduce this bug. I would confirm that the role is able to list the database

One thing to note is the provider puts double-quotes to qualify everything so it is case sensitive. For example if you created your database as "test" you need to pass "test" and not "TEST"  to the data source

**Comment by jifeous** [comment]
The more general case is that no databases are returned from the snowflake_databases data provider

`data "snowflake_databases" "this" {}

output "databases" {
  description = "Current Databases"
  value = data.snowflake_databases.this
}

Outputs:

databases = {
  "databases" = tolist(null) /* of object */
  "id" = tostring(null)
}
`
I can see the query in Snowflake and it returns the correct list of databases. It doesn't show in the terraform state.

I don't know what the difference could be

**Comment by brettwatkins-Built** [comment]
@jifeous @jag-super @bennylu2 did you ever figure out what the issue here was? I'm running into the same thing

**Comment by jifeous** [comment]
no, didn't figure it out and just did something else in the end
