### ISSUE TITLE
Snowflake Alerts Feature Request

### ISSUE THREAD

**Issue by amonkhouse** [Snowflake-Labs/terraform-provider-snowflake#1388]
**Is your feature request related to a problem? Please describe.**

Snowflake have recently added alerts and it would be great to get these added to the terraform provider so we can be alerted when we are e.g. missing expected data. [Source](https://www.snowflake.com/blog/new-ways-obseriving-snowflake-workloads/).

**Describe the solution you'd like**

snowflake_alert resource added.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by philippeboyd** [comment]
Would also love to see this!

**Comment by culpgrant** [comment]
This did get added: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/alert
But you cannot define the necessary grants in terraform to use it

**Comment by sfc-gh-asawicki** [comment]
Closing, because snowflake_alert was already added.
