### ISSUE TITLE
[Snowflake provider] no authentication method provided when explicitly configured

### ISSUE THREAD

**Issue by phuongvu** [Snowflake-Labs/terraform-provider-snowflake#1389]
**Provider Version**

`0.52.0`

**Terraform Version**

`Terraform v1.3.4`

**Describe the bug**

Related to this https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/725

With snowflake provider configured like below (i.e. with username, account, private key in line):

```
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.52.0"
    }
  }
}

provider "snowflake" {
  username = ...
  account  = ...
  region   = ...
  private_key = ...

  alias    = "security_admin"
  role     = "SECURITYADMIN"
}
``` 
when running `terraform plan`, it will prompt:
```
provider.snowflake.account
  The name of the Snowflake account. Can also come from the `SNOWFLAKE_ACCOUNT` environment variable.

  Enter a value: ...

provider.snowflake.username
  Username for username+password authentication. Can come from the `SNOWFLAKE_USER` environment variable.

  Enter a value: ...
```
Once inputing the required username and account, which already have been configured within the provider, it will throw:
```
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/snowflake-labs/snowflake" requires explicit configuration. Add a provider block to the root module and
│ configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: could not build dsn for snowflake connection: no authentication method provided
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on <input-prompt> line 1:
│   (source code not available)
```

**Expected behavior**

It shouldn't prompt for `account` and `username` and it should run `terraform plan` as the required args have been explicitly configured within the provider.

Note: when using env vars, everything works as expected. However, my setup requires fetching these configs from HashiCorp's Vault and input them to the provider, hence I'm going with aforementioned approach.

**Comment by TimoVink** [comment]
Hey, I was just banging my head against the wall with the same issue and managed to resolve it. My issue had to do with the `alias` so maybe this will help you too:

Similar to you my provider specified an `alias`, but my resources did not specify the [`provider` meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/resource-provider). So even though I had a correctly configured provider, Terraform was not using that provider to try to create the resources. Instead, it tries using the "implicit" unaliased/unconfigured provider.

If your problem happens to be the same you have two options:
  1. Remove the `alias = "security_admin"` from your `provider` configuration (if you don't intend to have multiple snowflake providers)

  2. Add `provider = snowflake.security_admin` to the resources you are trying to create with this provider (if you _do_ intend to have multiple snowflake providers).

**Comment by phuongvu** [comment]
Thank you so much @TimoVink. `alias = "security_admin"` totally solves the issue. 🙏🏼
