### ISSUE TITLE
Plugin did not respond:(*GRPCProvider).ReadResource call in `snowflake_role_grants`

### ISSUE THREAD

**Issue by charlesdong1991** [Snowflake-Labs/terraform-provider-snowflake#1391]
**Provider Version**

0.43.1

**Terraform Version**

1.3.5

**Describe the bug**

It is quite similar to the issue 1076: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1076

But in our case, the newer version of provider didn't help

**Expected behavior**

should run without errors

**Code samples and commands**

```
terraform {
  required_version = "1.3.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.43.1" # https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1226
    }
}

```

**Additional context**

this is the error we see, but not sure why it will trigger this during `apply` stage because there is no change impacting the role grant.

```
Error: Plugin did not respond
│ 
│   with module.teams_db.module.schema["xxxx"].module.writer.snowflake_role_grants.this,
│   on modules/snowflake-db/snowflake-schema/write/main.tf line 81, in resource "snowflake_role_grants" "this":
│   81: resource "snowflake_role_grants" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
```

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
