### ISSUE TITLE
No maintainer this project?

### ISSUE THREAD

**Issue by mnagaa** [Snowflake-Labs/terraform-provider-snowflake#1396]
Who maintains this open-source project?

**Comment by sfc-gh-dschonberg** [comment]
As detailed in this [Medium](https://medium.com/snowflake/snowflake-terraform-provider-9c26dffa8bf3) post, we at Snowflake maintain this project.

**Comment by mnagaa** [comment]
@sfc-gh-dschonberg
Thank you for sharing the post!!

The README states that new versions will be released every Monday, but it doesn't seem to be released any longer than that. Many pull requests also seem to be ignored.

> Releases will be performed once a week on Monday around 11am PST. If your change is more urgent and you need to use it sooner, use the commit hash.

I was worried that Snowflake ended maintenance due to some kind of development policy change.

Some OSS contributors want to fix bugs that pile up in Issues as soon as possible. In order for OSS contributors to be active in this project and for Snowflake to grow, I believe that the key is to fast merge the pull requests by maintainers.

**Comment by mnagaa** [comment]
@sfc-gh-dschonberg 
@sfc-gh-swinkler , the reviewer of all of my previous PRs been back from his vacation. Everything is clear now, so I will close this issue after a while.
