### ISSUE TITLE
Usage of snowflake_failover_group leads to plugin error

### ISSUE THREAD

**Issue by Christopher-Schick** [Snowflake-Labs/terraform-provider-snowflake#1417]
**Provider Version**

0.53.0

**Terraform Version**
v1,3,6

**Describe the bug**

We are using the resource snowflake_failover_group to create a failover group on the primary account and the corresponding failover group on the secondary account.
The deploy command results in the following error message:

panic: runtime error: index out of range [0] with length 0

**Expected behavior**

We would expect the failover group to be created without an error, as specified in the resource.

**Code samples and commands**

resource "snowflake_failover_group" "source_accounting_failover_group" {
  name = snowflake_database.accounting.name
  object_types = ["DATABASES"]
  allowed_accounts = ["${var.snowflake_account_parameters.secondary.org}.${var.snowflake_account_parameters.secondary.account}"]
  allowed_databases = [snowflake_database.accounting.name]
  replication_schedule {
    interval = 10
   }
}

**Additional context**

[deploy_053.log](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/10206402/deploy_053.log)

**Comment by sfc-gh-swinkler** [comment]
Hello @Christopher-Schick i fixed this in pr #1448 . It will be released in next patch, within a few days.
