### ISSUE TITLE
v0.53.1 binary is not released and breaks download.sh

### ISSUE THREAD

**Issue by dtsai-czi** [Snowflake-Labs/terraform-provider-snowflake#1420]
**Provider Version**

0.53.1

**Terraform Version**

0.13.5

**Describe the bug**

`download.sh` calls a `curl` on `https://github.com/chanzuckerberg/terraform-provider-snowflake/releases/download/v0.53.1/terraform-provider-snowflake_0.53.1_linux_amd64.zip` and 404s

**Additional context**

Latest version in [Terraform registry](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest) is 0.53.0, checking the 0.53.1 release on [Github](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.53.1) shows that there are no binaries released

**Comment by sfc-gh-asawicki** [comment]
Hey @dtsai-czi. `download.sh` was removed. Closing this for being out-dated.
