### ISSUE TITLE
Snowflake security integration for custom oauth

### ISSUE THREAD

**Issue by akkigpt** [Snowflake-Labs/terraform-provider-snowflake#1421]
**Problem statement**
Currently terraform snowflake oauth security integration ( resource : snowflake_oauth_integration) only support snowflake security integration for partner application like tableau etc.

**Feature Request**
We wanted to use snowflake security integration oauth for  **custom client** and for that there should be a required parameter **oauth_client_type**. This parameter is not available currently in latest snowflake terraform provided i.e version 0.53.0.

**Solution**
To implement this we need a required parameter to be added to snowflake provided ( in resource **snowflake_oauth_integration** ) **oauth_client_type**. This parameter should be of type string and accept values  'CONFIDENTIAL' | 'PUBLIC'.

Thanks in Advance !!

**Comment by robotpistol** [comment]
Following  as this is relevant to my interests.

**Comment by astanfel** [comment]
Running into this issue with the latest version of the provider (0.63) where Terraform is trying to remove the `oauth_client_type` from the integration. This is causing issues since the resource has already been declared in our state previously. 

```terraform 
  # snowflake_oauth_integration.oauth_custom_int will be updated in-place
  ~ resource "snowflake_oauth_integration" "oauth_custom_int" {
        id                           = "OAUTH_CUSTOM_INT"
        name                         = "OAUTH_CUSTOM_INT"
      - oauth_client_type            = "PUBLIC" -> null
        # (8 unchanged attributes hidden)
    }
```

**Comment by sfc-gh-jmichalak** [comment]
Hey @akkigpt @robotpistol @astanfel  👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides a new resource for oauth: `oauth_integration_for_custom_clients`. This new resource has `oauth_client_type` field. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-snowflake_oauth_integration_for_custom_clients-and-snowflake_oauth_integration_for_partner_applications-resources).
