### ISSUE TITLE
Error: '@' is not valid identifier character in resource "snowflake_role_grants"

### ISSUE THREAD

**Issue by denzhel** [Snowflake-Labs/terraform-provider-snowflake#1425]
**Provider Version**
```
snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.47.0"
    }
```
**Terraform Version**
```
Terraform v1.1.2
on darwin_amd64
```
**Describe the bug**
When trying to grant a role that contains `@` to an other role I get the following error:
```
╷
│ Error: '@' is not valid identifier character.
│ 
│   with module.snowflake.snowflake_role_grants.custom_role_to_admins["NAME@EMAIL.COM"],
│   on modules/aws/snowflake/main.tf line 218, in resource "snowflake_role_grants" "custom_role_to_admins":
│  218:   role_name = "NAME@EMAIL.COM"
│ 
╵
```
**Expected behavior**
I expect the role to be granted to the role I requested as the other roles that does not contain `@` in their names.

**Code samples and commands**
```
# grant the roles that were created by Okta to DATA-PLATFORM-ADMINS
resource "snowflake_role_grants" "custom_role_to_admins" {
  # parameters
  role_name = "NAME@EMAIL.COM"
  roles = [
    local.admins_role_name
  ]
  enable_multiple_grants = true
}
```

**Additional context**
Other resources had the same exact issue and were fixed:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1184
https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1240
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1242

**Comment by bennylu2** [comment]
I don't believe `@` is an allowed character https://docs.snowflake.com/en/sql-reference/sql/create-role.html#required-parameters

https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html

**Comment by bennylu2** [comment]
Oh it is possible with double quote identifier https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#double-quoted-identifiers
