### ISSUE TITLE
Task resources failing after initial deployment

### ISSUE THREAD

**Issue by ruimffl** [Snowflake-Labs/terraform-provider-snowflake#1427]
**Provider Version**

provider registry.terraform.io/snowflake-labs/snowflake v0.36.0

**Terraform Version**

Terraform v1.2.6 on darwin_amd64

**Describe the bug**

After creating a task through the task resource, deployments fail because Terraform is not able to fetch the status of the task. Even if there's no changes to the task, terraform plan gives the error below:

`Error: error retrieving root task MY_TEST_TASK: failed to locate the root node of: []: sql: no rows in result set`

Looking at the query history in Snowflake, this is the query passed to Snowflake: `SHOW TASKS LIKE '[]' IN SCHEMA "MY_DATABASE"."MY_SCHEMA"`. 

This is the query passed to retrieve information from stages: `SHOW STAGES LIKE 'MY_STAGE' IN SCHEMA "MY_DATABASE"."MY_SCHEMA"`.

It looks like for Tasks the resource does not pass the task name and therefore the SQL statement returns an empty set.

**Expected behavior**

Terraform plan should retrieve information about the task, the same way as it does from other resources.

**Code samples and commands**

```
resource "snowflake_task" "task" {
  name                 = "MY_TEST_TASK"
  database             = "MY_DATABASE"
  schema               = "MY_SCHEMA"
  warehouse          = snowflake_warehouse.warehouse["warehouse_ingestion"].name
  schedule             = "USING CRON 0 20 * * * UTC"
  sql_statement        = "CALL ${snowflake_procedure.delete_expired_events.name}(CURRENT_TIMESTAMP())"
  user_task_timeout_ms = 300000
  enabled              = false
}
```

**Additional context**

Task gets created correctly.

**Comment by sfc-gh-asawicki** [comment]
Hey @ruimffl. Thanks for creating the issue.

The task resource has been greatly reworked since v.0.36.0. Can you confirm if the problem persists after upgrading to the newest provider version?

**Comment by ruimffl** [comment]
Hey @sfc-gh-asawicki I did noticed changes in recent versions of the provider and tried again last month. It all works as expected 👍 Thanks
