### ISSUE TITLE
Successive apply of the same plan makes changes and then reverts them

### ISSUE THREAD

**Issue by alexchouraki** [Snowflake-Labs/terraform-provider-snowflake#1428]
Using  provider registry.terraform.io/hashicorp/tls v4.0.4 and provider registry.terraform.io/snowflake-labs/snowflake v0.53.0

**Describe the bug**
While running an apply with a plan involving warehouse grants, two successive applys lead to warehouses being granted, and then ungranted, even though the plan doesn't change. 

**Expected behavior**

Terraform's behavior should be consistent : granting the resources, as specified in the .tf files, rather than ungranting them.

**Code samples and commands**
terraform apply 
`resource "snowflake_warehouse_grant" "grant_model_wh" {
  warehouse_name = snowflake_warehouse.model_wh.name
  privilege      = "USAGE"

  roles = [snowflake_role.model_role.name]

  with_grant_option = false
}`

Full video available [here](https://drive.google.com/file/d/1xbbSatbxuHNngVxZV7Ri-PgcS3C-EFeZ/view?usp=sharing)

**Comment by cpmub1** [comment]
did you try using [enable_multiple_grants] flag ?

**Comment by alexchouraki** [comment]
No, because I shouldn't need to use it. I'm trying to grant my warehouse to the list of roles specified, and this list of roles only - I do want any other grant manually set up on Snowflake to be revoked here...
The issue is that asking twice for the same thing yields different behaviors ; after the first apply, I shouldn't get any modification...

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
