### ISSUE TITLE
In `snowflake_schema_grant` can not grant privilege `CREATE SESSION POLICY`.

### ISSUE THREAD

**Issue by vicsteiner** [Snowflake-Labs/terraform-provider-snowflake#1438]
**Provider Version**

provider registry.terraform.io/snowflake-labs/snowflake v0.52.0

**Terraform Version**

Terraform v1.3.6 on darwin_amd64

**Describe the bug**

In `snowflake_schema_grant` can not grant privilege `CREATE SESSION POLICY`.

**Expected behavior**

The privilege should be granted when specified.

**Code samples and commands**

When running `terraform plan`  using `snowflake_schema_grant` as specified in https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/schema_grant got the following error:

```
Error: expected privilege to be one of [OWNERSHIP CREATE TAG CREATE STREAM CREATE SEQUENCE CREATE ROW ACCESS POLICY MONITOR CREATE EXTERNAL TABLE CREATE MASKING POLICY ADD SEARCH OPTIMIZATION CREATE VIEW CREATE FUNCTION CREATE MATERIALIZED VIEW MODIFY USAGE CREATE TABLE CREATE FILE FORMAT CREATE STAGE CREATE PIPE CREATE TASK CREATE PROCEDURE CREATE TEMPORARY TABLE], got CREATE SESSION POLICY
```

However, privilege `CREATE SESSION POLICY` does exist in Snowflake documentation: https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html under `schemaPrivileges`.

**Comment by vicsteiner** [comment]
It seems it is missing in the list here https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/schema_grant.go#L11 and here https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/7358fdd94a3b106a13dd7000b3c6a8f1272cf233/pkg/resources/privileges.go#L9

**Comment by bennylu2** [comment]
I'll pick this up
