### ISSUE TITLE
support for database roles

### ISSUE THREAD

**Issue by cpmub1** [Snowflake-Labs/terraform-provider-snowflake#1442]
snowflake has introduced DATABASE ROLES. 
https://docs.snowflake.com/en/sql-reference/sql/create-database-role.html

can support for DATABASE ROLE be introduced ?

**Comment by bennylu2** [comment]
I'm not sure what the policy is for the provider to support features that are in preview

**Comment by MLdavion** [comment]
wholeheartedly wanted this feature, this feature makes data share sooooo much easier to configure and control

**Comment by bennylu2** [comment]
I can put up a PR for this but I'm unsure what policy is for provider to support features in preview. I'm also unsure of the status of the provider and if there's going to a be a major version release in the near future.

I'd be happy to pick this up if given the go ahead by the maintainers

**Comment by cpmub1** [comment]
Thanks @bennylu2 
who should give ahead to move on ? Let me try to tag them here or get their attention

**Comment by cpmub1** [comment]
Though this feature is said to be in "preview", Snowflake has implemented it on the SNOWFLAKE database & enabled it for all accounts, with no restrictions. More over, almost everyone has their own version of database role, thru custom roles - which does not provide a defined scope boundary across databases.
hence, i strongly believe, Snowflake has it as "preview" for paper-document reasons, rather than for functionality.

**Comment by cpmub1** [comment]
@sfc-gh-swinkler I see that you have recently committed some changes to this repo. 
Can you please suggest on who can give a go ahead for making this change ?

@bennylu2 was willing to do a PR , but there was no ahead & the effort stopped.

**Comment by bgabrhelik-com** [comment]
Now there is the `snowflake_database_role` resource, however it seems there is not support for granting of database role. Granting model seems to be quit difficult and duplication of all the resources doesn't make sense. There is small difference in the syntax.
* FQN for role
* TO DATABASE ROLE abcd;

E.g. 
GRANT USAGE ON SCHEMA DB1.PUBLIC TO DATABASE ROLE DB_READ;

**Comment by sfc-gh-asawicki** [comment]
Closing because done in #1654.

Database role grants are currently being developed (#2034).
