### ISSUE TITLE
Ignore edition check does not work as expected

### ISSUE THREAD

**Issue by brandocomando** [Snowflake-Labs/terraform-provider-snowflake#1453]
**Provider Version**

0.54.0

**Terraform Version**

1.3.6

**Describe the bug**

Unable to add replication from A business critical account to a non business critical account even with ignore_edition_check = true

**Expected behavior**

Able to create database that can be replicated if ignore_edition_check = true

**Code samples and commands**

error:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.platform.snowflake_database.mytestdb will be updated in-place
  ~ resource "snowflake_database" "mytestdb" {
        id                          = "MY_TEST_DB"
        name                        = "MY_TEST_DB"
        # (2 unchanged attributes hidden)

      + replication_configuration {
          + accounts             = [
              + "MY_ORG_ID.MY_SECONDARY_ACCOUNT",
            ]
          + ignore_edition_check = true
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
module.platform.snowflake_database.mytestdb: Modifying... [id=MY_TEST_DB]
╷
│ Error: error enabling replication configuration with statement ALTER DATABASE "MY_TEST_DB" ENABLE REPLICATION TO ACCOUNTS MY_ORG_ID.MY_SECONDARY_ACCOUNT err = 003537 (23001): SQL execution error: Replication is not allowed from an account on BUSINESS CRITICAL edition to an account on a lower edition. 
│ The following account(s) are on editions lower than BUSINESS CRITICAL: [PUBLIC.AWS_EU_WEST_1.MY_SECONDARY_ACCOUNT]
│ You can override this check for this database.
│ Before overriding this check, confirm that the target account has appropriate security controls and is compliant for the data being replicated.
│ 
│ To override this check for this database, run
│ alter database <database_name> enable replication to <accounts> ignore edition check
│ 
│   with module.platform.snowflake_database.mytestdb,
│   on ../modules/platform/databases.tf line 102, in resource "snowflake_database" "mytestdb":
│  102: resource "snowflake_database" "mytestdb" {
│ 
```

**Comment by brandocomando** [comment]
I'm no golang expert, but the error seems to indicate that it is not passing the ignore edition check in the statement. and the function:
```
func (db *DatabaseBuilder) EnableReplicationAccounts(dbName string, accounts string) string {
	return fmt.Sprintf(`ALTER DATABASE "%v" ENABLE REPLICATION TO ACCOUNTS %v`, dbName, accounts)
}
```

also has no reference to the ignore edition check. havent been able to track down how it should make it to this function tho.

**Comment by brandocomando** [comment]
@sfc-gh-jalin Looks like you were the one who last updated the db replication pieces. Are you able to take a look at this?

**Comment by sfc-gh-jcieslak** [comment]
Hey @brandocomando 👋
I'm currently working on databases as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1. I reproduced your configuration and this issue shouldn't happen in later versions of the provider. If you can, please try the latest one (or one of the latest) and let me know if that works for you. In case of any issues with upgrading, check our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) (it may be lacking in information for early versions).

**Comment by brandocomando** [comment]
thank you!
