### ISSUE TITLE
[snowflake_stage_grant] schema_name is not required

### ISSUE THREAD

**Issue by eaguilera23** [Snowflake-Labs/terraform-provider-snowflake#1477]
**Provider Version**

0.54.0

**Terraform Version**

1.2.6

**Describe the bug**

When using snowflake_stage_grant with the `on_future` falg as `true` the `schema_name` is being required

**Expected behavior**

As per the documentation:

>  When this is true and no schema_name is provided apply this grant on all future stages in the given database. 

**Code samples and commands**

```
module "snowflake_on_future_read_only_stages" {
  source = "resource_module"

  database_name     = "DATABASE"
  privilege         = "USAGE"
  roles             = ["ROLE"]
  on_future         = true
  with_grant_option = false
}

```

Error:

> The argument "schema_name" is required, but no definition was found.

**Additional context**

**Comment by bennylu2** [comment]
Have open MR for this https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1466
