### ISSUE TITLE
Add support for `GCP_PUBSUB_TOPIC_NAME` for notification integration

### ISSUE THREAD

**Issue by novikovaTanya** [Snowflake-Labs/terraform-provider-snowflake#1480]
**Is your feature request related to a problem? Please describe.**

Currently, `NotificationIntegration` doesn't allow passing `gcp_pubsub_topic_name` parameter.
Adding this parameter allows people to create push notification integration meant for snowpipe errors.

**Describe the solution you'd like**

`gcp_pubsub_topic_name` parameter is added to the schema for notificationIntegration

**Describe alternatives you've considered**

I set up Pub/Sub related resources in terraform/pulumi and then manually create notification integration in Snowflake. 

**Additional context**

- [Creating a Notification Integration in Snowflake](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-errors-gcs.html#step-3-creating-a-notification-integration-in-snowflake)
- [cloudProviderParamsPush](https://docs.snowflake.com/en/sql-reference/sql/create-notification-integration.html#:~:text=NOTIFICATION_PROVIDER%20%3D%20GCP_PUBSUB-,GCP_PUBSUB_TOPIC_NAME,-%3D%20%27%3Ctopic_id)

**Comment by sfc-gh-asawicki** [comment]
Closing because done in #1687.
