### ISSUE TITLE
No support for IMPORTED privileges for shared TABLES & VIEWS

### ISSUE THREAD

**Issue by amit0904** [Snowflake-Labs/terraform-provider-snowflake#1481]
Provider Version

0.53.0

Terraform Version

1.3.6

Describe the bug

For resource "snowflake_table_grant", provider does have privilege IMPORTED. In snowflake we can run 

`GRANT IMPORTED PRIVILEGES ON ALL views IN DATABASE INBOUND TO ROLE INBOUND_DB_READ_ONLY;`

error message

`expected privilege to be one of [TRUNCATE REFERENCES REBUILD OWNERSHIP SELECT INSERT UPDATE DELETE], got IMPORTED`

Expected behavior

Privilege should have following accepted values

`TRUNCATE REFERENCES REBUILD OWNERSHIP SELECT INSERT UPDATE DELETE IMPORTED`

Code samples and commands

resource "snowflake_table_grant" "grant" {
  database_name = "database"
  schema_name   = "schema"
  table_name    = "table"

  privilege = "IMPORTED"
  roles     = ["role1"]
  shares    = ["share1"]

  on_future         = false
  with_grant_option = false
}

**Comment by amit0904** [comment]
Any updates to this one ?

**Comment by smith-m** [comment]
Error: expected privilege to be one of [INSERT REFERENCES OWNERSHIP ALL PRIVILEGES REBUILD SELECT UPDATE DELETE TRUNCATE], got IMPORTED PRIVILEGES
│ 
│   with snowflake_table_grant.read,
│   on main.tf line 61, in resource "snowflake_table_grant" "read":
│   61:   privilege     = "IMPORTED PRIVILEGES"

resource "snowflake_table_grant" "read" {
  database_name = data.snowflake_database.example.name
  on_future     = true
  privilege     = "IMPORTED PRIVILEGES"
  roles         = [snowflake_role.example.name]
}

"IMPORTED PRIVILEGES" doesn't work for tables or views
