### ISSUE TITLE
Importing RoleGrants results in an empty list of users and roles

### ISSUE THREAD

**Issue by AaronFriel** [Snowflake-Labs/terraform-provider-snowflake#1499]
Hey folks, a user of the bridged Pulumi provider (based on this provider) reported:
- https://github.com/pulumi/pulumi-snowflake/issues/177

I believe this change might be the cause: 
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/520

## What happened?

User ran `import ...` and received an empty set of role grants.

## Expected behavior

That infra-as-code tools would be able to adopt existing grants to bring them under management, generating code like so in Pulumi Python:

```python
  accountadmin = snowflake.RoleGrants(
    "ACCOUNTADMIN", 
    role_name="ACCOUNTADMIN",
    roles = [ list of roles ],
    users = [ list of users ],
    opts=pulumi.ResourceOptions(protect=True))
```

**Comment by sfc-gh-swinkler** [comment]
Hello @AaronFriel , this was fixed as part of 0.56.4. I would suggest rereading the documentation however, since the format of the import has changed slightly: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/role_grants#import.

**Comment by AaronFriel** [comment]
Hey @sfc-gh-swinkler, would it be possible for a different delimiter than ❄️ to be supported here?

While many terminals now support emoji input, inputting the emoji could be a problem for some users.

**Comment by sfc-gh-swinkler** [comment]
Hello @AaronFriel the ❄️  emoji is only necessary for internal use and is not required for import ID. For example, take a look at the account_grant resource:
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account_grant#import
. If you like, I can implement something like this for role_grants to make it easier to import resources.

Also, I am planning to deprecate a lot of these resources in the future and replace them with new ones. So I will keep your suggestion in mind when designing these new resources.
