### ISSUE TITLE
Change table column and clustering dependencies 

### ISSUE THREAD

**Issue by uristernik** [Snowflake-Labs/terraform-provider-snowflake#1507]
**Provider Version**

0.35.0

**Terraform Version**

1.3.7

**Describe the bug**

When changing an changing an existing table columns and cluster_by column, it fails because it tries to change the clustering before it changes the columns.

**Expected behavior**

Successful run. If a successful run can't be completed because of dependencies, then force recreate and notify about it in the plan

**Additional context**

Had a table with one variant column with json content.
I want to parse the json content into different columns and define the indexing according to the new column

**Comment by michael-robbins** [comment]
Not sure! We just encountered this ourselves yesterday and I saw it was a quick fix (no idea about tests/etc, but we'll see how we go!)
