### ISSUE TITLE
Altering Resource Monitor Notification Settings

### ISSUE THREAD

**Issue by astanfel** [Snowflake-Labs/terraform-provider-snowflake#1513]
**Provider Version**

latest (56.3)

**Terraform Version**

1.3.4

**Describe the bug**

Terraform is not issuing the correct statement when only modifying the notification settings for a given resource monitor. Below is the statement that was issued to Snowflake looking at the query logs: 

ALTER RESOURCE MONITOR "LOOKER" SET TRIGGERS ON 75 PERCENT DO NOTIFY ON 100 PERCENT DO NOTIFY

And the error statement that was produced: 

SQL compilation error: syntax error line 1 at position 45 unexpected 'ON'. syntax error line 1 at position 59 unexpected 'DO'. syntax error line 1 at position 69 unexpected 'ON'. syntax error line 1 at position 84 unexpected 'DO'. syntax error line 1 at position 93 unexpected '<EOF>'.

**Expected behavior**

Terraform should generate the following statement: ALTER RESOURCE MONITOR LOOKER TRIGGER ON 75 PERCENT DO NOTIFY ON 100 PERCENT DO NOTIFY;

(With no set)

**Comment by sfc-gh-asawicki** [comment]
Hey @astanfel. Thanks for reporting the issue.

You are using a pretty old version of the provider. Resource monitors were migrated to a different SQL-generating method. Would you give it a try?

@jbonatakis, which version of the provider do you use?

**Comment by astanfel** [comment]
@sfc-gh-asawicki I think we should be able to close this issue out. I don't believe that we are experiencing this on version 0.67.0 (which is the current version we are using for the provider).
