### ISSUE TITLE
Existing snowflake_procedure_grant fail to plan in >= 0.56.1

### ISSUE THREAD

**Issue by rjoelnorgren** [Snowflake-Labs/terraform-provider-snowflake#1517]
**Provider Version**

Tested in 0.56.1, 0.56.3, and 0.56.4

**Terraform Version**

1.3.7

**Describe the bug**

snowflake_procedure_grant created with versions prior to 0.56.1 fail to plan when performing a provider upgrade to version >=0.56.1.

**Expected behavior**

I am able to upgrade the snowflake provider versions > 0.56 with existing snowflake_grant_procedure resources.

**Code samples and commands**

Create a snowflake_procedure_grant with snowflake provider < 0.56.1 and upgrade to 0.56.1 or later.

```terraform
resource "snowflake_database" "foo" {
  name = "FOO__DEV"
}

resource "snowflake_role" "foo" {
  name = "FOO"
}

resource "snowflake_procedure" "foo" {
  name     = "FOO"
  database = snowflake_database.foo.name
  schema   = "PUBLIC"
  language = "JAVASCRIPT"
  arguments {
    name = "VARIABLE_NAME"
    type = "VARCHAR"
  }
  return_type = "VARCHAR"
  execute_as  = "OWNER"
  statement   = <<-JS
    return VARIABLE_NAME
  JS
}

resource "snowflake_procedure_grant" "foo" {
  database_name       = snowflake_database.foo.name
  schema_name         = "PUBLIC"
  procedure_name      = snowflake_procedure.foo.name
  privilege           = "USAGE"
  roles               = [snowflake_role.foo.name]
  argument_data_types = ["VARCHAR"]
}
```

After upgrading to a later snowflake provider version, plans will throw the following error (even if you remove deprecated arguments and us argument_data_types):

```
# using deprecated arguments
snowflake_role.foo: Refreshing state... [id=FOO]
snowflake_database.foo: Refreshing state... [id=FOO__DEV]
snowflake_procedure.foo: Refreshing state... [id=FOO__DEV|PUBLIC|FOO|VARCHAR]
snowflake_procedure_grant.foo: Refreshing state... [id=FOO__DEV|PUBLIC|FOO(VARIABLE_NAME VARCHAR):VARCHAR|USAGE|FOO|false]
╷
│ Warning: Argument is deprecated
│
│   with snowflake_procedure_grant.foo,
│   on main.tf line 61, in resource "snowflake_procedure_grant" "foo":
│   61: resource "snowflake_procedure_grant" "foo" {
│
│ use argument_data_types instead.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 65 unexpected 'VARCHAR'.
│
│   with snowflake_procedure_grant.foo,
│   on main.tf line 61, in resource "snowflake_procedure_grant" "foo":
│   61: resource "snowflake_procedure_grant" "foo" {
│
╵

----
# using non-deprecated arguments
snowflake_role.foo: Refreshing state... [id=FOO]
snowflake_database.foo: Refreshing state... [id=FOO__DEV]
snowflake_procedure.foo: Refreshing state... [id=FOO__DEV|PUBLIC|FOO|VARCHAR]
snowflake_procedure_grant.foo: Refreshing state... [id=FOO__DEV|PUBLIC|FOO(VARIABLE_NAME VARCHAR):VARCHAR|USAGE|FOO|false]
╷
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 65 unexpected 'VARCHAR'.
│
│   with snowflake_procedure_grant.foo,
│   on main.tf line 61, in resource "snowflake_procedure_grant" "foo":
│   61: resource "snowflake_procedure_grant" "foo" {
│
╵
```

**Additional context**
With provider version <0.56.1, refreshing the grant resource generates the following SQL:

```sql
SHOW GRANTS ON PROCEDURE "FOO"."PUBLIC"."BAR"(VARCHAR)
```

After the upgrade to >=0.56.1, the procedure grant generates this sql
```sql
SHOW GRANTS ON PROCEDURE "FOO"."PUBLIC"."BAR"(VARIABLE_NAME VARCHAR)
```

Terraform show output:
```
# snowflake_database.foo:
resource "snowflake_database" "foo" {
    data_retention_time_in_days = 1
    id                          = "FOO__DEV"
    is_transient                = false
    name                        = "FOO__DEV"
}

# snowflake_procedure.foo:
resource "snowflake_procedure" "foo" {
    comment             = "user-defined procedure"
    database            = "FOO__DEV"
    execute_as          = "OWNER"
    id                  = "FOO__DEV|PUBLIC|FOO|VARCHAR"
    language            = "JAVASCRIPT"
    name                = "FOO"
    null_input_behavior = "CALLED ON NULL INPUT"
    return_behavior     = "VOLATILE"
    return_type         = "VARCHAR(16777216)"
    schema              = "PUBLIC"
    statement           = <<-EOT
        return VARIABLE_NAME
    EOT

    arguments {
        name = "VARIABLE_NAME"
        type = "VARCHAR"
    }
}

# snowflake_procedure_grant.foo:
resource "snowflake_procedure_grant" "foo" {
    database_name          = "FOO__DEV"
    enable_multiple_grants = false
    id                     = "FOO__DEV|PUBLIC|FOO(VARIABLE_NAME VARCHAR):VARCHAR|USAGE|FOO|false"
    on_future              = false
    privilege              = "USAGE"
    procedure_name         = "FOO"
    return_type            = "VARCHAR"
    roles                  = [
        "FOO",
    ]
    schema_name            = "PUBLIC"
    with_grant_option      = false

    arguments {
        name = "VARIABLE_NAME"
        type = "VARCHAR"
    }
}

# snowflake_role.foo:
resource "snowflake_role" "foo" {
    id   = "FOO"
    name = "FOO"
}

```

**Comment by bennylu2** [comment]
Seems related to #1502 and possibly #1508

**Comment by sfc-gh-swinkler** [comment]
Hello @bennylu2. This was fixed in 0.56.2. Please upgrade and let me know how it goes.

**Comment by rjoelnorgren** [comment]
> Hello @bennylu2. This was fixed in 0.56.2. Please upgrade and let me know how it goes.

@sfc-gh-swinkler, just want to clarify that I tested this in 0.56.1 and 0.56.3. I am assuming it's also present in 0.56.2.

**Comment by mlorek** [comment]
also broken in 0.56.3, param names are included in show grants statement

**Comment by Relativity74205** [comment]
Using `argument_data_types` attribute instead of the `arguments` attribute works for me. The `arguments` attribute is also deprecated according to the docs.

**Comment by rjoelnorgren** [comment]
@Relativity74205, I was unable to get this to work for procedures created with provider < 0.56.1.

**Comment by ruimffl** [comment]
This was also broken to me after upgrading to 0.56.3., the new arguments didn't fix it.
My workaround to be able to upgrade the provider was to use a future grant on the schema and apply the usage grant retrospectively (via console) to existing stored procedures. I had to downgrade first just to be able to remove the `snowflake_procedure_grant` resources.

```terraform
resource "snowflake_procedure_grant" "procedure_usage_grant" {
  database_name     = "MY_DB"
  schema_name       = "MY_SCHEMA"
  privilege         = "USAGE"
  roles             = "MY_ROLE"
  with_grant_option = false
  on_future         = true
}
```

**Comment by sfc-gh-swinkler** [comment]
Have you tried in 0.56.4? Also yes, I would recommend switching to using the `argument_data_types` attribute instead of arguments. If you are still having trouble, then please provide some additional information including:
1. TF Provider version you are using
2. Result of `terraform show` command on the resource
3. Sample of configuration code

**Comment by rjoelnorgren** [comment]
> Have you tried in 0.56.4? Also yes, I would recommend switching to using the `argument_data_types` attribute instead of arguments. If you are still having trouble, then please provide some additional information including:
> 
> 1. TF Provider version you are using
> 2. Result of `terraform show` command on the resource
> 3. Sample of configuration code

@sfc-gh-swinkler I have updated the original issue post. 0.56.4 did not fix the issue. Switching the arguments style does not change the error.

**Comment by mlorek** [comment]
0.56.5 still includes column names as part of show grants command

**Comment by mlorek** [comment]
0.57.0 is also broken
#1571 should fix the issue

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
