### ISSUE TITLE
Parameter ressource doesn't take the parameter hierarchy into account

### ISSUE THREAD

**Issue by tuhren** [Snowflake-Labs/terraform-provider-snowflake#1523]
**Provider Version**

0.55.0

**Describe the bug**

The ressource for account parameters should allow any parameter (account, object, session) to be set since there is a parameter hierarchy. 

As stated in the doc (https://docs.snowflake.com/en/sql-reference/parameters.html#object-types) a object / session parameter can also be set at the account level.

Example:

resource "snowflake_account_parameter" "enable_stream_task_replication" {
  key   = "ENABLE_STREAM_TASK_REPLICATION"
  value = "true"
}

│ Error: expected key to be one of [INITIAL_REPLICATION_SIZE_LIMIT_IN_TB ENABLE_INTERNAL_STAGES_PRIVATELINK REQUIRE_STORAGE_INTEGRATION_FOR_STAGE_CREATION SSO_LOGIN_PAGE PREVENT_UNLOAD_TO_INLINE_URL NETWORK_POLICY MIN_DATA_RETENTION_TIME_IN_DAYS PERIODIC_DATA_REKEYING ALLOW_CLIENT_MFA_CACHING ALLOW_ID_TOKEN EXTERNAL_OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST CLIENT_ENCRYPTION_KEY_SIZE ENFORCE_SESSION_POLICY], got ENABLE_STREAM_TASK_REPLICATION
│ 
│   with snowflake_account_parameter.enable_stream_task_replication,
│   on main-account-parameter.tf line 9, in resource "snowflake_account_parameter" "enable_stream_task_replication":
│    9:   key   = "ENABLE_STREAM_TASK_REPLICATION"
│ 

**Expected behavior**

This should work as stated in the docs and generate the SQL:

alter account set enable_stream_task_replication = true;

**Comment by Relativity74205** [comment]
If I understood it correctly, you can do this at least for session parameters with the [snowflake_session_parameter](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/session_parameter) resource.

Works at least for this example:
```
resource "snowflake_session_parameter" "week_start" {
  provider = snowflake.account
  key      = "WEEK_START"
  value    = 2
}
```

However, I am not sure if there is something similar for object parameters . There is the snowflake_object_parameter ressource, however, this seems only to work for objects.

**Comment by tuhren** [comment]
@sfc-gh-swinkler: Internal JIRA raised for that: SNOW-739988

**Comment by anthonyrussano** [comment]
> If I understood it correctly, you can do this at least for session parameters with the [snowflake_session_parameter](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/session_parameter) resource.
> 
> Works at least for this example:
> 
> ```
> resource "snowflake_session_parameter" "week_start" {
>   provider = snowflake.account
>   key      = "WEEK_START"
>   value    = 2
> }
> ```
> 
> However, I am not sure if there is something similar for object parameters . There is the snowflake_object_parameter ressource, however, this seems only to work for objects.


Setting the following session parameter at the account level throws an error

resource "snowflake_session_parameter" "week_start_sunday" {
  provider   = snowflake.ACCOUNTADMIN
  key        = "WEEK_START"
  value      = "7"
  on_account = true
}


│ Error: WEEK_START must be either 0 or 1
│ 
│   with snowflake_session_parameter.week_start_sunday,
│   on main.tf line 17, in resource "snowflake_session_parameter" "week_start_sunday":
│   17: resource "snowflake_session_parameter" "week_start_sunday" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
