### ISSUE TITLE
Failover group Update not detecting existing Integration types

### ISSUE THREAD

**Issue by venkad-intc** [Snowflake-Labs/terraform-provider-snowflake#1532]
Local Environment:

Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.56.3

**Describe the bug**

When failover group is updated, the existing integration types are not detected. 
2023-02-13T12:07:25.975Z [INFO]  provider.terraform-provider-snowflake_v0.56.3: 2023/02/13 12:07:25 [DEBUG] sql-conn-exec [query ALTER FAILOVER GROUP FOG_ALL_EXCEPT_DB SET OBJECT_TYPES = INTEGRATIONS,USERS,WAREHOUSES,ROLES,NETWORK POLICIES,ACCOUNT PARAMETERS,RESOURCE MONITORS err 500043 (42601): ALLOWED_INTEGRATION_TYPES should be specified when INTEGRATIONS is part of OBJECT_TYPES. duration 54.572167ms args {}]: timestamp=2023-02-13T12:07:25.975Z

│ Error: error updating object types for failover group FOG_ALL_EXCEPT_DB err = 500043 (42601): ALLOWED_INTEGRATION_TYPES should be specified when INTEGRATIONS is part of OBJECT_TYPES.
│ 
│   with snowflake_failover_group.source[0],
│   on main.tf line 563, in resource "snowflake_failover_group" "source":
│  563: resource "snowflake_failover_group" "source" {

**Expected behavior**

Alter statement should include the allowed integrations.

**Code samples and commands**

Version 1:
```
resource "snowflake_failover_group" "source_failover_group" {
  name                      = "FG1"
  object_types              = ["WAREHOUSES", "DATABASES", "INTEGRATIONS", "ROLES"]
  allowed_accounts          = ["<org_name>.<target_account_name1>", "<org_name>.<target_account_name2>"]
  allowed_databases         = [snowflake_database.db.name]
  allowed_integration_types = ["SECURITY INTEGRATIONS"]
  replication_schedule {
    cron {
      expression = "0 0 10-20 * TUE,THU"
      time_zone  = "UTC"
    }

    // replication_schedule could also be specified with interval instead of cron
    // interval = 10
  }
}
```

Version 2: (Removing warehouse now)
```
resource "snowflake_failover_group" "source_failover_group" {
  name                      = "FG1"
  object_types              = ["DATABASES", "INTEGRATIONS", "ROLES"]
  allowed_accounts          = ["<org_name>.<target_account_name1>", "<org_name>.<target_account_name2>"]
  allowed_databases         = [snowflake_database.db.name]
  allowed_integration_types = ["SECURITY INTEGRATIONS"]
  replication_schedule {
    cron {
      expression = "0 0 10-20 * TUE,THU"
      time_zone  = "UTC"
    }

    // replication_schedule could also be specified with interval instead of cron
    // interval = 10
  }
}

```

**Comment by sfc-gh-swinkler** [comment]
@venkad-intc the failover group resource was completely refactored in the 0.65 release of the provider and a specific test was added to verify that removing a warehouse (like the example you have included) works in the update step: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/failover_group_acceptance_test.go#L70. So this should no longer be an issue. Please let me know if there is any other trouble.
