### ISSUE TITLE
Resource Snowflake User setting password to null doesnt remove their password (Unset Password)

### ISSUE THREAD

**Issue by culpgrant** [Snowflake-Labs/terraform-provider-snowflake#1535]
**Provider Version**

0.53.0

**Terraform Version**

1.3.6

**Describe the bug**

We previously had users created with a password and are switching them to a different auth method. So I want to set the password to null so they can't login using basic authentication. When I set the password parameter to null it doesn't recognize this as a change.

**Expected behavior**

I would expect TF to run this SQL statement `alter user <username> unset password;`

But it is not recognizing that this user needs tobe adjusted as I am not getting back any changes in the terraform plan.

This unsets the password for that user. 

**Code samples and commands**
```
resource "snowflake_user" "USER" {
  name              = "USER"
  login_name        = "USER"
  display_name      = "USER"
  first_name        = "FIRST"
  last_name         = "LAST"
  email             = "email"
  comment           = "comment"
  disabled          = false
  password        = null
}
```

**Additional context**

**Comment by git-benjamin** [comment]
The password requires a string and doesn't accept boolean values as per the [docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/user).  

I'd try removing the password line which might remove the password from the user. 

If that doesn't work I'd suggest destroying the user and create them again without a password.

**Comment by culpgrant** [comment]
Gotcha that is a good point this might be a feature enhancement.

**Comment by sfc-gh-asawicki** [comment]
Hey @culpgrant, the change https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3013 confirms that this problem is not reproducible in the newest provider version. Please migrate and confirm that it works.

**Comment by culpgrant** [comment]
> Hey @culpgrant, the change https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3013 confirms that this problem is not reproducible in the newest provider version. Please migrate and confirm that it works.

You can close - I am no longer using this provider
