### ISSUE TITLE
Resource id constructed with ❄️ symbols

### ISSUE THREAD

**Issue by kallangerard** [Snowflake-Labs/terraform-provider-snowflake#1541]
**Provider Version**

v0.56.4
**Terraform Version**

v1.3.5

**Describe the bug**

Resource id constructed with `❄️` symbols

**Expected behavior**

Enterprise providers that don't use `❄️` for resource id's

**Code samples and commands**

https://github.com/Snowflake-Labs/terraform-provider-snowflake/commit/0502c61e7211253d029a0bec6a8104738624f243

```go
func (v *MaterializedViewGrantID) String() string {
	roles := strings.Join(v.Roles, ",")
	shares := strings.Join(v.Shares, ",")
	return fmt.Sprintf("%v❄️%v❄️%v❄️%v❄️%v❄️%v❄️%v", v.DatabaseName, v.SchemaName, v.ObjectName, v.Privilege, v.WithGrantOption, roles, shares)
}
```

**Additional context**

Why?

**Comment by sfc-gh-swinkler** [comment]
How exactly is this a bug? Its just a delimiter for IDs. And I needed some way to distinguish between old ID delimiters "|" and new ones.

**Comment by philippeboyd** [comment]
@sfc-gh-swinkler As a Senior Software Engineer, you should know to **never** use non-ascii characters in an identifier.

**Comment by frsann** [comment]
Remember, escalating through your account manager is the recommended way of getting things prioritised with these Snowflake OSS projects
