### ISSUE TITLE
Support session parameters at user or account level

### ISSUE THREAD

**Issue by alejobs** [Snowflake-Labs/terraform-provider-snowflake#1546]
**Is your feature request related to a problem? Please describe.**

Based on Snowflake documentation (see: https://docs.snowflake.com/en/sql-reference/parameters, under "Session Parameters"), session parameters can be applied at account, session or user level. 

With the current terraform implementation (see: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/session_parameter) one can't define the level (it's always at a session level).

**Describe the solution you'd like**

There should be one extra attribute to define level: ACCOUNT, USER, SESSION

**Comment by gokhanatil** [comment]
Let me correct one thing. As the readme file says, "If you are an enterprise customer, please contact your Snowflake account representative". You shouldn't submit a "Support ticket". You need to directly contact your account team.

**Comment by sfc-gh-gatil** [comment]
Let me correct one thing. As the readme file says, "If you are an enterprise customer, please contact your Snowflake account representative". You shouldn't submit a "Support ticket". You need to directly contact your account team.

**Comment by sfc-gh-asawicki** [comment]
Closing as completed in #1685
