### ISSUE TITLE
Pipeline on Gitlab fails with many 'Request cancelled' 

### ISSUE THREAD

**Issue by olivierdewit** [Snowflake-Labs/terraform-provider-snowflake#1548]
**Provider Version**

v0.56.4

**Terraform Version**

Terraform v1.3.9 on linux_amd64

**Describe the bug**

Pipeline on Gitlab fails with many 'Request cancelled' errors e.g.

Error: Request cancelled
│ 
│   with snowflake_role_grants.prd_dl_epmd_db_ro,
│   on access_roles.tf line 71, in resource "snowflake_role_grants" "prd_dl_xxxx":
│   71: resource "snowflake_role_grants" "prd_dl_xxxx" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

**Expected behavior**

Terraform plan should be completed successfully.

**Comment by sfc-gh-swinkler** [comment]
Hello @olivierdewit can you please provide some additional information for me? Specifically: 
1. the result of `terraform state show` on this resource
2. the configuration code you are using?
Also if you can enable debug logs and share with me the result of the error message, that would be useful.

**Comment by bennylu2** [comment]
Seems all grant resources are having issues #1547

**Comment by olivierdewit** [comment]
Hello @sfc-gh-swinkler ,

Here is the result of terraform state show on that resource:

# snowflake_role_grants.prd_dl_epmd_db_ro:
resource "snowflake_role_grants" "prd_dl_epmd_db_ro" {
    enable_multiple_grants = false
    id                     = "PRD_DL_EPMD_DB_RO||||TST_SNOWSQL_ROLE,OPERATIONS_USER|false"
    role_name              = "PRD_DL_EPMD_DB_RO"
    roles                  = [
        "OPERATIONS_USER",
        "TST_SNOWSQL_ROLE",
    ]
    users                  = []
}

An here is the code used for that grant:

resource "snowflake_role_grants" "prd_dl_epmd_db_ro" {
  role_name = snowflake_role.prd_dl_epmd_db_ro.name
  roles = [
    snowflake_role.operations_user.name,
    snowflake_role.tst_snowsql.name
  ]
}

Do you still need the logs?

**Comment by sfc-gh-swinkler** [comment]
this has been fixed.
