### ISSUE TITLE
In grants on_future=false should behave as null

### ISSUE THREAD

**Issue by froblesmartin** [Snowflake-Labs/terraform-provider-snowflake#1562]
**Provider Version**

[v0.56.3](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.56.3)

**Terraform Version**

1.3.0

**Describe the bug**

In a grant, when setting `on_future` to `false` instead of just `null` collides with other parameters, as for example `schema_name` in a schema grant.

**Expected behavior**

`False` should just behave as `null` does.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). This also may be Terraform specific issue and not the provider one. Please use the latest resources and see if the issue persists, If yes, create another GitHub issue.

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
