### ISSUE TITLE
Why so many grant resources? Why not a single generic one?

### ISSUE THREAD

**Issue by froblesmartin** [Snowflake-Labs/terraform-provider-snowflake#1563]
**Describe the solution you'd like**

I do not know the reasons behind the decision of creating a `grant` resource for each of the "normal" resources, instead of just creating a single `grant`resource which would have the kind of resource to be applied to as one input, but it would simplify a lot the usage.

**Describe alternatives you've considered**

I have checked if I could create a module using a variable on the resource type, but that does not seem to be possible (kind of `resource "snowflake_${var.resource_type}_grant" "grant" {`).

**Comment by Tsanton** [comment]
I second this, but maybe split it into a `grant` and `future_grant` resource to reduce complexity?
Further it might make sense to further split into`role`, `user` and `database_role` grants?
Might be a bit less DRY, but it would significantly reduce complexity and enhance the possibility for automation in terms of the usage of `for_each`.

**Comment by froblesmartin** [comment]
> I second this, but maybe split it into a `grant` and `future_grant` resource to reduce complexity? Further it might make sense to further split into`role`, `user` and `database_role` grants? Might be a bit less DRY, but it would significantly reduce complexity and enhance the possibility for automation in terms of the usage of `for_each`.
> 
> I would also love to see the usage of a grants array so that you don't have to `for_each` over your locals array to grant `select`, `references`, `update` etc.. over multiple resources. This would reduce API-calls and improve performance, offloading the logic of delta-detection to the terraform provider.

Hi @Tsanton ! For the last part of your comment, I have also raised the issue here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1593, so that multiple privileges can be defined in the same `grant` resource, as the command line of Snowflake allows.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)

They're more generic than the previous grant resources which were create per object.
