### ISSUE TITLE
Support object parameters at account level

### ISSUE THREAD

**Issue by adamhealy** [Snowflake-Labs/terraform-provider-snowflake#1565]
**Is your feature request related to a problem? Please describe.**

Based on Snowflake documentation (see: https://docs.snowflake.com/en/sql-reference/parameters, under "Object Parameters"), object parameters can be applied at account, or object level.

With the current terraform implementation (see: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/object_parameter) one can't define the level (it's always at an object level).

**Describe the solution you'd like**

The `object_type` and `object_identifier` should be optional in favour of a parameter to declare it an account level parameter.

**Additional context**

This relates to the issue #1546 which handles the session parameters, but object parameters are also impacted

**Comment by sfc-gh-asawicki** [comment]
Closing as completed in #1685
