### ISSUE TITLE
Password Policy Object

### ISSUE THREAD

**Issue by culpgrant** [Snowflake-Labs/terraform-provider-snowflake#1581]
**Is your feature request related to a problem? Please describe.**

Not related to a problem just an object in Snowflake that isn't available to be created through Terraform.

**Describe the solution you'd like**

I would like to be able to create the Snowflake object [Password Policy](https://docs.snowflake.com/en/sql-reference/sql/create-password-policy) through Terraform. We manage objects like this through Terraform so being able to create and manage this through TF would be helpful.

**Describe alternatives you've considered**

It just isn't available so I don't know of any alternatives

**Additional context**

I created a [discussion ](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1446 )on this as well.

**Comment by sfc-gh-swinkler** [comment]
Hello @culpgrant this is an excellent suggestion, and definitely something that should be implemented. Can you please bring this request up with your Snowflake account representative so I can allocate time to getting this done?

**Comment by culpgrant** [comment]
Hey @sfc-gh-swinkler thanks for your comment! And yes I did on Monday :) I sent over a couple of bug fixes and this item that we are hoping to leverage for our account.

**Comment by csp33** [comment]
hi there, any news about this issue? 
My team would be glad to have this feature available :D

**Comment by culpgrant** [comment]
Not that I know of I have mentioned it a couple times to my account team to try and get it prioritized. I haven't built a terraform resource on my own but I am thinking about trying to contribute this.

**Comment by sfc-gh-swinkler** [comment]
I am not seeing any internal requests from account rep coming through. Who is your account rep? I can ping them directly if that helps

**Comment by culpgrant** [comment]
Darrin Gardiner and Nick Akincilar

**Comment by sfc-gh-swinkler** [comment]
@culpgrant i have reached out to those two individuals and confirmed your request. So I will start working on it as soon as I have availability.

**Comment by culpgrant** [comment]
Thank you for working on this! I greatly appreciate it
