### ISSUE TITLE
snowflake_table_grant not working as expected

### ISSUE THREAD

**Issue by ethanj20** [Snowflake-Labs/terraform-provider-snowflake#1592]
**Provider Version**

v0.57.0

**Terraform Version**

v1.3.9

**Describe the bug**

After applying the following code, the user `EJ_R` is still not able to view and query objects in the `AB_DB` database:

```terraform
resource "snowflake_database_grant" "EJ_DB_grant" {
  database_name = snowflake_database.AB_DB.name
  privilege = "USAGE"
  roles     = [snowflake_role.EJ_R.name]
}

resource "snowflake_schema_grant" "AB_S_grant_to_EJ_R_u" {
  database_name = snowflake_database.AB_DB.name
  schema_name   = snowflake_schema.AB_S.name
  privilege = "USAGE"
  roles     = [snowflake_role.EJ_R.name]
}

resource "snowflake_table_grant" "EJ_table_grant" {
  database_name = snowflake_database.AB_DB.name
  roles     = [snowflake_role.EJ_R.name]
  privilege = "SELECT"
  on_future = true
}
```
I believe the final block (the `snowflake_table_grant` is the issue, as when I ran `GRANT SELECT ON ALL TABLES IN DATABASE AB_DB TO ROLE EJ_R;` in Snowflake directly, the role `EJ_R` was able to see the objects in the database and schema. 

**Expected behavior**

It would be expected that `GRANT SELECT ON ALL TABLES IN DATABASE AB_DB TO ROLE EJ_R;` and 

```
resource "snowflake_table_grant" "EJ_table_grant" {
  database_name = snowflake_database.AB_DB.name
  roles     = [snowflake_role.EJ_R.name]
  privilege = "SELECT"
  on_future = true
}
```

Perform the same function, but they appear to not.

**Comment by Relativity74205** [comment]
The snowflake query `GRANT SELECT ON ALL TABLES IN DATABASE AB_DB TO ROLE EJ_R` is not implemented yet in the terraform provider.
The `on_future = true` part translates to `GRANT SELECT ON FUTURE TABLES IN DATABASE AB_DB TO ROLE EJ_R`.

**Comment by ethanj20** [comment]
Got it. Is there a `terraform` resource definition that would give permissions to a role that would give it select/modify access to any schema or table in a database (both present and future), or is this required manually at the moment?

Or will the configuration that I provided only work on _new_ tables in the db, not current tables?

**Comment by ethanj20** [comment]
Just tested, looks like that configuration works for future tables, just not existing ones. That is fine for now - going to close this issue. Thanks for the response!
