### ISSUE TITLE
snowflake_stage_grant READ and WRITE dependency, change privilege argument to be an array?

### ISSUE THREAD

**Issue by froblesmartin** [Snowflake-Labs/terraform-provider-snowflake#1593]
**Provider Version**

[v0.56.5](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.56.5)

**Terraform Version**

v1.3.1

**Describe the bug**

When configuring snowflake_stage_grant resources, if you want to grant the WRITE privilege, it is mandatory to first grant READ. As of the error returned:

> Error: 003511 (23001): SQL compilation error: Privilege order violation for the future grants on stage. READ should be granted before/simultaneously with WRITE.

This could be solved by making one resource dependent on the other one, but in my case, I use a Terraform module which can not check which privileges are being set to generate the dependencies between resources.

**Expected behaviour**

As with the regular command (check examples at https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#examples), I understand that multiple privileges could be assigned with a single grant resource so that it is an array of strings, or just accepts multiple privileges separated by commas.

**Comment by Bryan-Meier** [comment]
I have the same issue. I don't see a work around for this in the Snowflake provider. Stages are very finicky from a privilege perspective anyway. It's sort of not surprising there is issues in the provider around stages. I noticed other issues that are open related to stages like #1544.

I agree with the expected behavior as well.

**Comment by Oracen** [comment]
+1 for expected behaviour. For anyone else who ends up here, I have an ugly but workable solution for my use-case, hope it helps yours.

```hcl
locals {
  stage_product = {
    for pair in setproduct(
      local.database_schema_pairs,
      var.grants_stage
    ) :
    "${pair[0].database}-${pair[0].schema}-${pair[1]}" => {
      database  = pair[0].database,
      schema    = pair[0].schema,
      privilege = pair[1]
    }
  }
}

resource "snowflake_stage_grant" "read_grant" {
  for_each      = { for key, value in local.stage_product : key => value if lower(value.privilege) == "read" }
  database_name = each.value.database
  schema_name   = each.value.schema

  privilege              = each.value.privilege
  roles                  = [data.snowflake_role.role.name]
  enable_multiple_grants = var.allow_external_grants
  on_future              = true
  with_grant_option      = false
}


resource "snowflake_stage_grant" "grant" {
  depends_on = [
    snowflake_stage_grant.read_grant
  ]
  for_each      = { for key, value in local.stage_product : key => value if lower(value.privilege) != "read" }
  database_name = each.value.database
  schema_name   = each.value.schema

  privilege              = each.value.privilege
  roles                  = [data.snowflake_role.role.name]
  enable_multiple_grants = var.allow_external_grants
  on_future              = true
  with_grant_option      = false
}
```

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
