### ISSUE TITLE
snowflake_file_format_grant outputs error when only the role variable changed

### ISSUE THREAD

**Issue by BenoitLF** [Snowflake-Labs/terraform-provider-snowflake#1594]
**Provider Version**

0.50
**Terraform Version**
1.3.7

**Describe the bug**
```
When applying file_format_grand_read on a number of roles, the error does not make much sense to me
module.sandbox_db.module.db.module.privileges["test"].snowflake_file_format_grant.read["USAGE"]: Modifying... [id=SANDBOX_DEV|test||USAGE|SANDBOX_ADMIN_DEV,SANDBOX_READER_DEV,SANDBOX_DEVELOPER_DEV|false]
snowflake_stage.raw_stage: Modifying... [id=SANDBOX_DEV|test|sandbox_stage]
snowflake_stage.raw_stage: Modifications complete after 0s [id=SANDBOX_DEV|test|sandbox_stage]
╷
│ Error: 4 fields allowed
│
│   with module.sandbox_db.module.db.module.privileges["test"].snowflake_file_format_grant.read["USAGE"],
│   on modules/application_database/privileges/privileges.tf line 191, in resource "snowflake_file_format_grant" "read":
│  191: resource "snowflake_file_format_grant" "read" {
```

**Expected behavior**

**Code samples and commands**

```
resource "snowflake_file_format_grant" "read" {
  for_each = toset(local.reader_privileges["file_format"])

  database_name = var.db
  schema_name   = var.schema
  privilege     = each.key
  roles         = var.all_read_roles
  on_future     = true
}
```

**Comment by BenoitLF** [comment]
I believe it is likely a bug of the snowflake provider, because destroying and recreating the resource works...

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
