### ISSUE TITLE
snowflake_schema_grant does not work as expected when multiple privileges are granted by for_each

### ISSUE THREAD

**Issue by nakazono1011** [Snowflake-Labs/terraform-provider-snowflake#1610]
**Provider Version**

0.56.5

**Terraform Version**

1.3.6

**Describe the bug**

`snowflake_schema_grant` does not work as expected when multiple permissions are linked.
Specifically, some roles, including USAGE, are not granted.

```
locals {
  schema_all_privileges = [
      "MODIFY",
      "MONITOR",
      "USAGE",
      "CREATE TABLE",
      "CREATE EXTERNAL TABLE",
      "CREATE VIEW",
      "CREATE MATERIALIZED VIEW",
      "CREATE MASKING POLICY",
      "CREATE SESSION POLICY",
      "CREATE STAGE",
      "CREATE FILE FORMAT",
      "CREATE SEQUENCE",
      "CREATE FUNCTION",
      "CREATE PIPE",
      "CREATE STREAM",
      "CREATE TASK",
      "CREATE PROCEDURE",
      "ADD SEARCH OPTIMIZATION"
    ]
}

resource "snowflake_schema" "prod_int" {
  database = snowflake_database.prod.name
  name     = upper("int")
  comment  = "This is an int schema."

  is_transient        = false
  is_managed          = false
  data_retention_days = 1
}

resource "snowflake_schema_grant" "prod_int_grant_all" {
  for_each = toset(local.schema_all_privileges)

  database_name = snowflake_database.prod.name
  schema_name   = snowflake_schema.prod_int.name

  privilege = each.value
  roles = [
    snowflake_role.db_prod_rw.name,
  ]
}
```

![image](https://user-images.githubusercontent.com/66734196/223917523-6493b37b-ce36-4c49-b8f0-9b6bf336bdc9.png)

**Expected behavior**

I want all the permissions held in the list to be granted.

**Additional context**

I looked at `QUERY_HISTORY` on Snowinsight and could not find the relevant GRANT syntax.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
