### ISSUE TITLE
Implement Share Grant

### ISSUE THREAD

**Issue by frctnlss** [Snowflake-Labs/terraform-provider-snowflake#1632]
**Is your feature request related to a problem? Please describe.**

When creating a share, there isn't a resource for granting permissions to manage the share.

**Describe the solution you'd like**

A resource for creating share grants similar to all the other object-specific resource grants. 

**Describe alternatives you've considered**

A generic resource for running queries when a given feature hasn't been implemented.

**Additional context**

My specific use case, if needed:
I create a managed reader account. I create a share. I build secure views within DBT. DBT runs without the ACOUNTADMIN role. I need to grant the role used by DBT access to the schema so that as the views are created and refreshed, it can grant view access to the share. I also need to be able to grant the reader account access to the share. I am not going to grant the ACOUNTADMIN role to anyone, so I have become a manual cron for when the views change.

**Comment by frctnlss** [comment]
To expand, I do understand that I may grant share access to snowflake objects created in terraform. I need a machine service to do the same. This requires the role granted to the service to have the ability.

**Comment by kramer1007** [comment]
+1 on this. Exactly what @brettwatkins-Built mentioned.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
