### ISSUE TITLE
terraform plugin crashes during  oauth_integration update

### ISSUE THREAD

**Issue by mlorek** [Snowflake-Labs/terraform-provider-snowflake#1637]
**Provider Version**

0.58.2, 0.59.0

**Terraform Version**

1.3.9

**Describe the bug**

terraform plugin crashes during the oauth_integration resource update.

**Expected behavior**

clean plan

**Code samples and commands**

resource "snowflake_oauth_integration" "tableau_desktop" {
  name                         = "TABLEAU_DESKTOP"
  oauth_client                 = "TABLEAU_DESKTOP"
  enabled                      = true
  oauth_issue_refresh_tokens   = true
  oauth_refresh_token_validity = 3600
  blocked_roles_list           = ["SYSADMIN"]
}

**Additional context**

14:59:52  Stack trace from the terraform-provider-snowflake_v0.58.2 plugin:
14:59:52  
14:59:52  panic: interface conversion: interface {} is *schema.Set, not []interface {}
14:59:52  
14:59:52  goroutine 114 [running]:
14:59:52  github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateOAuthIntegration(0xc0005c7300, {0x130ce60?, 0xc0005f85b0})
14:59:52  	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/oauth_integration.go:292 +0x9a6
14:59:52  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1580ae0?, {0x1580ae0?, 0xc00086c8d0?}, 0xd?, {0x130ce60?, 0xc0005f85b0?})
14:59:52  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:729 +0x178
14:59:52  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003a7b20, {0x1580ae0, 0xc00086c8d0}, 0xc00098fee0, 0xc0005c6780, {0x130ce60, 0xc0005f85b0})
14:59:52  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:847 +0x83a
14:59:52  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00038c2d0, {0x1580ae0?, 0xc00043a840?}, 0xc0009a0000)
14:59:52  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
14:59:52  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003a0640, {0x1580ae0?, 0xc00043a000?}, 0xc000438070)
14:59:52  	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
14:59:52  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x12d8d00?, 0xc0003a0640}, {0x1580ae0, 0xc00043a000}, 0xc000438000, 0x0)
14:59:52  	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
14:59:52  google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f6000, {0x15868a0, 0xc000602820}, 0xc00092f560, 0xc00039c9f0, 0x1d365a0, 0x0)
14:59:52  	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
14:59:52  google.golang.org/grpc.(*Server).handleStream(0xc0003f6000, {0x15868a0, 0xc000602820}, 0xc00092f560, 0x0)
14:59:52  	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
14:59:52  google.golang.org/grpc.(*Server).serveStreams.func1.2()
14:59:52  	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
14:59:52  created by google.golang.org/grpc.(*Server).serveStreams.func1
14:59:52  	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
14:59:52  
14:59:52  Error: The terraform-provider-snowflake_v0.58.2 plugin crashed!

**Comment by HeliosLHC** [comment]
I also encountered this error/crash on versions 0.63 and 0.64 as well with mostly the same error stacktrace.

**Comment by mlorek** [comment]
interesting, 0.64.0 fixed the issue for me

**Comment by don-code** [comment]
I also hit this issue on 0.64.0. I just tried the latest, 0.68.2, and get the same crash.

**Comment by sfc-gh-jmichalak** [comment]
Hey @mlorek @HeliosLHC @don-code @don-code   👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides new resources for oauth: `oauth_integration_for_custom_clients` and `oauth_integration_for_partner_applications`. These resources handle `blocked_list` correctly, so please migrate from `oauth_integration` to one of them. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-snowflake_oauth_integration_for_custom_clients-and-snowflake_oauth_integration_for_partner_applications-resources).
