### ISSUE TITLE
Error creating Tag

### ISSUE THREAD

**Issue by dan-siddall** [Snowflake-Labs/terraform-provider-snowflake#1657]
**Provider Version**

Installed snowflake-labs/snowflake v0.59.0 (signed by a HashiCorp partner, key ID 5166D7352E69A585)

**Terraform Version**

Terraform v1.4.0
on windows_amd64

**Describe the bug**

running "terraform apply" on this configuration
terraform {
    required_providers {
        snowflake = {
            source = "Snowflake-Labs/snowflake"
                version = "~> 0.35"
        }
    }
}

provider "snowflake" {
	alias = "sys_admin"
    role = "SYSADMIN"
}

provider "snowflake" {
    alias = "security_admin"
    role = "SECURITYADMIN"
}

resource "snowflake_database" "db" {
	provider = snowflake.sys_admin
    name = "TEST_DATABASE"
}
resource "snowflake_schema" "schema" {
	provider = snowflake.sys_admin
    database = snowflake_database.db.name
    name = "TEST_SCHEMA"
    is_managed = false
}

resource "snowflake_warehouse" "warehouse" {
	provider = snowflake.sys_admin
    name = "TEST_WAREHOUSE"
    warehouse_size = "small"
    query_acceleration_max_scale_factor = 0

    auto_suspend = 60
}

resource "snowflake_tag" "area_tag" {
  name           = "area"
  database       = snowflake_database.db.name
  schema         = snowflake_schema.schema.name
}

Results in this output
snowflake_database.db: Creating...
snowflake_warehouse.warehouse: Creating...
snowflake_database.db: Creation complete after 1s [id=TEST_DATABASE]
snowflake_schema.schema: Creating...
snowflake_schema.schema: Creation complete after 0s [id=TEST_DATABASE|TEST_SCHEMA]
snowflake_tag.area_tag: Creating...
snowflake_warehouse.warehouse: Creation complete after 1s [id=TEST_WAREHOUSE]
╷
│ Error: error creating tag area
│
│   with snowflake_tag.area_tag,
│   on main.tf line 40, in resource "snowflake_tag" "area_tag":
│   40: resource "snowflake_tag" "area_tag" {
│

**Expected behavior**

No error when running the configuration

**Code samples and commands**

See above

**Additional context**

None

**Comment by sfc-gh-jmichalak** [comment]
Hi @dan-siddall 👋 
Sorry for the late response. Does this occur on newer versions of the provider? If yes, please include logs with `TF_LOG=DEBUG` because this error is very generic.

**Comment by sfc-gh-jmichalak** [comment]
Hi @cpmub1  👋 

Closing the issue because of inactivity. FYI, we've just released v0.99.0 ([release](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.99.0), [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v0980--v0990)) in which we reworked tags. This issue should be fixed. Please upgrade to this version and let us know if you have any issues.
