### ISSUE TITLE
0.60.0 resource_monitor suspend_triggers and suspend_immediate_triggers

### ISSUE THREAD

**Issue by bennylu2** [Snowflake-Labs/terraform-provider-snowflake#1672]
**Provider Version**

`0.60.0`

**Terraform Version**

`1.3.4`

**Describe the bug**

The `suspend_triggers` and `suspend_immediate_triggers` were deprecated but appear to have a bug

```
  # module.tdm_atwork.module.tdm_resource_monitor.snowflake_resource_monitor.this will be updated in-place
  ~ resource "snowflake_resource_monitor" "this" {
        id                         = "TDM_ATWORK"
        name                       = "TDM_ATWORK"
      - suspend_immediate_trigger  = 100 -> null
        # (8 unchanged attributes hidden)
    }
```

The functions called appear to be swapped so it's not setting the attribute properly i.e. `suspend_immediate_triggers` is calling `cb.SuspendAt` but should be calling `cb.SuspendImmediatelyAt`

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/c61ed6379895f83cebdc8e1c2a82ec0bf97f42d6/pkg/resources/resource_monitor.go#L159-L162

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/c61ed6379895f83cebdc8e1c2a82ec0bf97f42d6/pkg/resources/resource_monitor.go#L168-L172

**Expected behavior**

No changes, deprecated attributes should still be supported while we migrate

**Additional context**

Was removed in #1545
Added back in #1643 but looks like copy-pasta

**Comment by bennylu2** [comment]
I linked the Create but there appears to be issues with Read as well, it no longer sets the plural attributes

**Comment by mlorek** [comment]
also getting the following err on resource monitor options change
11:37:20
11:37:20 Stack trace from the terraform-provider-snowflake_v0.60.0 plugin:
11:37:20
11:37:20 panic: interface conversion: interface {} is *schema.Set, not int
