### ISSUE TITLE
Provider upgrade forces needless replacement of grants

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1677]
**Provider Version**

0.60.0

**Terraform Version**

Terraform v1.4.2

**Describe the bug**

The bug presents itself when Dependabot proposes upgrading from provider version from 0.56.0 to 0.60.0. When I run a plan using 0.56.0, no diffs are proposed.

But when I run a plan in 0.60.0, I get these diffs for a resource which I've been using for many months:

```
  # module.production_application.snowflake_schema_grant.app_config_and_reference_tables["MODIFY"] must be replaced
-/+ resource "snowflake_schema_grant" "app_config_and_reference_tables" {
      + enable_multiple_grants = false
      ~ id                     = "PRODUCTION|APP_CONFIG_AND_REFERENCE_TABLES||\"MODIFY\"|true" -> (known after apply)
      ~ privilege              = "\"MODIFY\"" -> "MODIFY" # forces replacement
      ~ roles                  = [
          + "PRODUCTION_STAFF_READ_WRITE",
          + "production_role",
        ]
      - shares                 = [] -> null
        # (4 unchanged attributes hidden)
    }
```

**Expected behavior**

No diffs.

**Code samples and commands**

```
resource "snowflake_schema_grant" "app_config_and_reference_tables" {
  for_each = toset([
    "ADD SEARCH OPTIMIZATION",
    "CREATE EXTERNAL TABLE",
    "CREATE FILE FORMAT",
    "CREATE FUNCTION",
    "CREATE MASKING POLICY",
    "CREATE MATERIALIZED VIEW",
    "CREATE PIPE",
    "CREATE PROCEDURE",
    "CREATE SEQUENCE",
    "CREATE STAGE",
    "CREATE STREAM",
    "CREATE TABLE",
    "CREATE TASK",
    "CREATE TEMPORARY TABLE",
    "CREATE VIEW",
    "MODIFY",
    "MONITOR",
    "USAGE",
  ]) : []
  database_name = snowflake_schema.app_config_and_reference_tables[0].database
  schema_name   = snowflake_schema.app_config_and_reference_tables[0].name

  privilege = each.key
  roles = compact([
    snowflake_role.role[0].name,
    snowflake_role.staff_read_write[0].name,
    each.key == "USAGE" ? snowflake_role.staff_read_only[0].name : ""
  ])
  with_grant_option = true
}
```

Notice I don't have any weird escaping in the strings which specify `"MODIFY"`.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
