### ISSUE TITLE
Email notification integration support

### ISSUE THREAD

**Issue by adrian-damaschin** [Snowflake-Labs/terraform-provider-snowflake#1693]
**Is your feature request related to a problem? Please describe.**

We are trying to implement notification integration within Terraform on snowflake. Although snowflake allows EMAIL type notifications we cannot implement it here.

**Describe the solution you'd like**

Implementation to support EMAIL type notification integration

**Describe alternatives you've considered**

Creating the notification manually when deploying new environments.

**Additional context**

**Comment by culpgrant** [comment]
If people find this in the future here is the resource: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/email_notification_integration

**Comment by sfc-gh-asawicki** [comment]
Closing because #1720 was merged.
