### ISSUE TITLE
SQL compilation error: An active warehouse is required for creating Python stored procedures.

### ISSUE THREAD

**Issue by KPGR** [Snowflake-Labs/terraform-provider-snowflake#1695]
**Provider Version**

0.61.0

**Terraform Version**

1.0.6

**Describe the bug**

Whilst creating a new Python Stored procedure, I get this error error: creating procedure <name> err = 391531 (42601): SQL compilation error: An active warehouse is required for creating Python stored procedures.

**Expected behavior**

The stored procedure is created without throwing this error. 

**Code samples and commands**

resource "snowflake_procedure" "test_proc" {
  name              = "stored_proc"
  database        = "TEST"
  schema          = "TEST"
  language        = "PYTHON"
  comment         = "whatever"
  return_type     = "STRING"
  execute_as      = "OWNER"
  runtime_version = "3.8"
  handler         = "main"
  packages        = ["snowflake-snowpark-python", "pandas"]
  statement       = "my python code"
}

**Additional context**

In order to create a Python stored procedure, the warehouse is required to be defined as well. Therefore, an extra argument "warehouse" needs to be added in the resource and the warehouse needs to be used before creating the procedure. @sfc-gh-jhollan was going in the right direction here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1533/files, but the PR was closed in favour of https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1516

**Comment by pei0804** [comment]
I detected a similar problem.

Provider Version
0.86.0

Terraform Version
1.7.3

**Comment by pei0804** [comment]
This problem has been resolved.
It was possible to use Warehouse with properties.

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs#warehouse

steps:

```sql
GRANT OPERATE ON WAREHOUSE dev_xs_wh TO ROLE terraform;
```

```console
$ export SNOWFLAKE_WAREHOUSE:=DEV_XS_WH
```

```
terraform apply
```

**Comment by javabudd** [comment]
> This problem has been resolved. It was possible to use Warehouse with properties.
> 
> https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs#warehouse
> 
> steps:
> 
> ```sql
> grant operate, usage on warehouse xxx_wh to role terraform
> ```
> 
> ```
> $ export SNOWFLAKE_WAREHOUSE:=xxx_wh
> ```
> 
> ```
> $ terraform apply
> ```

We use multiple warehouses, this approach is not feasible. I believe there is still a need for `warehouse` to be added to the resource creation options.

**Comment by sfc-gh-asawicki** [comment]
Hey @javabudd. Please check my comment here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2977#issuecomment-2329785915.

For now, you can declare multiple providers, with different `warehouse` attribute values and use them to create procedures using the [provider meta attribute](https://developer.hashicorp.com/terraform/language/meta-arguments/resource-provider).

In the end, it's still setting one field on the resource level, the only additional burden is to duplicate the provider definition. Still, this does not scale well with the number of warehouses growing.

**Comment by sfc-gh-asawicki** [comment]
In v0.100.0, we introduced new procedure resources. The registry docs now emphasize that a warehouse may be required.

I will close this issue.
