### ISSUE TITLE
Error: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by tamathew** [Snowflake-Labs/terraform-provider-snowflake#1704]
**Provider Version**

      version = "~> 0.60"

**Terraform Version**

Terraform 1.4.2 - TF Cloud

**Describe the bug**

Whenever I run a plan or try to destroy everything, i get this error... I have checked every single syntax and nothing wrong in there..

Error: strconv.ParseInt: parsing "": invalid syntax

**Expected behavior**

Expected is no error

**Code samples and commands**

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.60"
    }
  }
}

provider "snowflake" {

  alias = "user_admin"
  account = var.GQ_SNOWFLAKE_ACCOUNT
  username = var.GQ_SNOWFLAKE_USER
  password = var.GQ_SNOWFLAKE_PASSWORD
  role  = "USERADMIN"

}

provider "snowflake" {
  alias = "sys_admin"
  account = var.GQ_SNOWFLAKE_ACCOUNT
  username = var.GQ_SNOWFLAKE_USER
  password = var.GQ_SNOWFLAKE_PASSWORD
  role  = "SYSADMIN"
}

provider "snowflake" {
  alias = "account_admin"
  account = var.GQ_SNOWFLAKE_ACCOUNT
  username = var.GQ_SNOWFLAKE_USER
  password = var.GQ_SNOWFLAKE_PASSWORD
  role  = "ACCOUNTADMIN"
}
provider "snowflake" {
  alias = "security_admin"
  account = var.GQ_SNOWFLAKE_ACCOUNT
  username = var.GQ_SNOWFLAKE_USER
  password = var.GQ_SNOWFLAKE_PASSWORD
  role  = "SECURITYADMIN"
}

variable "GQ_SNOWFLAKE_USER" {
    type = string
} 
variable "GQ_SNOWFLAKE_PASSWORD" {
    type = string
} 
variable "GQ_SNOWFLAKE_ACCOUNT" {
    type = string
}

resource "snowflake_warehouse" "sqms_nrt_dw" {
  provider = snowflake.sys_admin
  name           = "SQMS_NRT_DW"
  comment        = "Near Real Time Warehouse."
  warehouse_size = "small"
}

resource "snowflake_warehouse" "sqms_etl_dw" {
  provider = snowflake.sys_admin
  name           = "SQMS_ETL_DW"
  comment        = "ETL Warehouse."
  warehouse_size = "small"
}

**Additional context**

**Comment by Hyurt** [comment]
Hi, 
I just ran into this issue - but this is due to a upgrade that seems to break how is read the terraform state. I suggest you to downgrade your provider back to a prior working version (0.51.0 for me) - apply your changes and then upgrade the provider.

**Comment by tamathew** [comment]
Figured out the issue. The RCA was a manual change(deletion of a resource) did to Snowflake bypassing TF.   This manual change was done by somebody without my knowledge and the error was very generic and took me to a spiral spin.

The resource was manually placed back and then I ran the TF and it went fine.
