### ISSUE TITLE
Snowflake File Format defaults not retained by subsequent Terraform Plans

### ISSUE THREAD

**Issue by gayathriatoodle** [Snowflake-Labs/terraform-provider-snowflake#1706]
**Provider Version**

version = "= 0.61.0"

**Terraform Version**

required_version = "= 1.3.6"

**Describe the bug**

Snowflake File Format resource created successfully. Subsequent plans attempt to unset default values to null causing deployment failures when applied

**Expected behavior**

Terraform plan picks up no changes where none's been made

**Code samples and commands**

Resource created successfully - 

resource "snowflake_file_format" "csv_format" {
  name                           = "CSV_FORMAT"
  database                     = snowflake_database.db.name
  schema                       = snowflake_schema.schema.name
  format_type                = "CSV"
  skip_header                  = 1
  field_optionally_enclosed_by = "0x22"
}

Terraform plan change (attempts to reset the defaults)

# snowflake_file_format.data_raw_dialler_csv_format will be updated in-place
  ~ resource "snowflake_file_format" "csv_format" {
      - binary_format                  = "HEX" -> null
      - compression                    = "AUTO" -> null
      - date_format                    = "AUTO" -> null
      - encoding                       = "UTF8" -> null
      - escape                         = "NONE" -> null
      - escape_unenclosed_field        = "\\" -> null
      - field_delimiter                = "," -> null
      ~ field_optionally_enclosed_by   = "\"" -> "0x22"
        id                             = "DATA_RAW|RAW_DIALLER|CSV_FORMAT"
        name                           = "CSV_FORMAT"
      - record_delimiter               = <<-EOT
            
        EOT -> null
      - time_format                    = "AUTO" -> null
      - timestamp_format               = "AUTO" -> null
        # (21 unchanged attributes hidden)
    }

Error during Terraform Apply

Error: -05T16:35:54.472Z [ERROR] provider.terraform-provider-snowflake_v0.56.3: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/Snowflake-Labs/snowflake tf_req_id=aaed465c-02a2-c7f2-7f41-048ef2480d02 tf_resource_type=snowflake_file_format tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_summary="error updating file format compression on DATA_RAW|RAW_DIALLER|CSV_FORMAT err = 001008 (22023): SQL compilation error:
invalid value [''] for parameter 'COMPRESSION'" timestamp=2023-04-05T16:35:54.472Z
Error: -05T16:35:54.482Z [ERROR] vertex "snowflake_file_format.data_raw_dialler_csv_format" error: error updating file format compression on DATA_RAW|RAW_DIALLER|CSV_FORMAT err = 001008 (22023): SQL compilation error:
invalid value [''] for parameter 'COMPRESSION'

**Additional context**

Appears to be a plugin issue. We tried some earlier versions of the plugin only to observe the same behaviour.

I have removed the actual db and schema names for obvious reasons

**Comment by apelletier-dev** [comment]
Seconding this to be fixed as I and others I work with were also impacted.
