### ISSUE TITLE
Database resources error after upgrade to 0.6.2

### ISSUE THREAD

**Issue by mlavaert** [Snowflake-Labs/terraform-provider-snowflake#1734]
**Provider Version**
0.62.0

**Terraform Version**
1.4.5

**Describe the bug**

After upgrading the Terraform plugin from version 0.56.2, I get the following exception.

```
 Error: unable to scan row for SHOW DATABASES LIKE 'TEST' err = missing destination name resource_group in *[]snowflake.Database
│ 
│   with snowflake_database.databases["TEST"],
│   on databases.tf line 51, in resource "snowflake_database" "databases":
│   51: resource "snowflake_database" "databases" {
│ 
╵
```
Removing the state and re-importing doesn't help.

Terraform used to generate the databases:
```
locals {
  databases = {
    # Environments
    "PRODUCTION" = {
      data_retention_time_in_days = 14
    }

    "TEST" = {
      data_retention_time_in_days = 1
    }
}

resource "snowflake_database" "databases" {
  provider = snowflake.sysadmin

  for_each = local.databases

  name                        = each.key
  comment                     = lookup(each.value, "comment", null)
  data_retention_time_in_days = lookup(each.value, "data_retention_time_in_days", 3)

  lifecycle {
    prevent_destroy = true
  }
}
```

We've been struggling ever since version 0.56.3 to upgrade because of issues with the databases. Versions previous to 0.62.0 remove all databases from the state. When trying to re-import them we get the following:
```
snowflake_database.databases["TEST"]: Refreshing state... [id=TEST]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "snowflake_database.databases[\"TEST\"]", the provider detected that no object exists with the given id.
│ Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or
│ use "terraform apply" to create a new remote object for this resource.
```

**Comment by sfc-gh-swinkler** [comment]
i would like to schedule a call with you so you can show me what you are experiencing because for the life of me I am not able to replicate the error you are seeing. Using the config you provided I had no problem applying, planning, and re-importing the resources.

```
$ terraform apply
snowflake_database.databases["TEST"]: Creating...
snowflake_database.databases["PRODUCTION"]: Creating...
snowflake_database.databases["TEST"]: Creation complete after 1s [id=TEST]
snowflake_database.databases["PRODUCTION"]: Creation complete after 1s [id=PRODUCTION]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
$ terraform state rm snowflake_database.databases[\"TEST\"]
Removed snowflake_database.databases["TEST"]
Successfully removed 1 resource instance(s).
$ terraform import snowflake_database.databases[\"TEST\"] "TEST"
snowflake_database.databases["TEST"]: Importing from ID "TEST"...
snowflake_database.databases["TEST"]: Import prepared!
  Prepared snowflake_database for import
snowflake_database.databases["TEST"]: Refreshing state... [id=TEST]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by sfc-gh-dszmolka** [comment]
@mlavaert (or anyone with the same exact issue) maybe a long shot but ... are you getting this error  `err = missing destination name` only perhaps when running the plugin against replicated databases ?

**Comment by mlorek** [comment]
our db was not replicated and it was removed from state

**Comment by christyvp** [comment]
I'm having a similar issue with replicated databases. We are getting the error `Error: unable to scan row for SHOW DATABASES LIKE '<database_name>' err = missing destination name firewall_configuration in *[]snowflake.Database`, we have not made any changes to our snowflake terraform resources - we are seeing this error on the plan when updating resources with a different provider (AWS).

**Comment by marcincuber** [comment]
I am getting this error as well with provider version 0.63.0.
```
Error: unable to scan row for SHOW DATABASES LIKE 'EUROWIND' err = missing destination name resource_group in *[]snowflake.Database
```

**Comment by dalebradman** [comment]
Also facing the same error as @marcincuber with the same 0.63.0 provider version & Terraform `v1.4.6`

**Comment by mlorek** [comment]
#1758 should fix this issue

**Comment by mlavaert** [comment]
> @mlavaert (or anyone with the same exact issue) maybe a long shot but ... are you getting this error `err = missing destination name` only perhaps when running the plugin against replicated databases ?

We're not using replicated databases.

**Comment by PedroMartinSteenstrup** [comment]
Just testing snowflake-labs/snowflake v0.63.0 from 0.59
```
│ Error: unable to scan row for SHOW DATABASES LIKE 'AIRBYTE' err = missing destination name firewall_configuration in *[]snowflake.Database
│ 
│   with snowflake_database.this_db["AIRBYTE"],
│   on main.tf line 1, in resource "snowflake_database" "this_db":
│    1: resource "snowflake_database" "this_db" {
│ 
```

If I run `show databases like 'AIRBYTE'`, here is my output
```
[
  {
    "created_on": "2022-06-08 07:56:18.819 +00:00",
    "name": "AIRBYTE",
    "is_default": "N",
    "is_current": "N",
    "origin": "",
    "owner": "SYSADMIN",
    "comment": "",
    "options": "",
    "retention_time": "1",
    "firewall_configuration": null,
    "share_events_with_provider": ""
  }
]
```

I do not get the `ResourceGroup` @mlorek is referring to, but I have the `firewall_configuration` from @christyvp 

Is that some kind of feature available only for some customers?

**Comment by mlavaert** [comment]
These issues have been resolved in the 0.64.0 release.

**Comment by philippeboyd** [comment]
@mlavaert I have a simiar issue as @christyvp 

Even on `0.64.0` I get the following error when creating a database from a replica
```
unable to scan row for SHOW DATABASES LIKE 'TEST_DB' err = missing destination name kind in *[]snowflake.Database
```

**Comment by PedroMartinSteenstrup** [comment]
still in 0.65.0 https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1836

**Comment by douglaszickuhr** [comment]
Not sure I am allowed to comment it here but for the sake of other people I will. 
We had the same issue today and I opened a ticket with snowflake support. Although they say that terraform provider is not covered by support they gave me the following feedback.


> Looking at similar issues, it appears that the issue is related to the most recent release and how it affects the SHOW DATABASES output
Could you please attempt to roll back this behavior change?
select system$disable_behavior_change_bundle(‘2023_03’);

Running that made the plan/apply go back to work. I reckon this is something that has to be addressed on provider eventually.

Although that makes it work for us, it also let us out of any sort of improvement that was released on that bundle.

**Comment by sfc-gh-ngaberel** [comment]
Hi everyone, this issue should have been fixed in the v0.66 release from last week. Can you upgrade to v0.66.1 and confirm whether that solves your problem?

**Comment by sfc-gh-ngaberel** [comment]
@douglaszickuhr you'll probably want to re-enable the 2023_03 bundle once you've upgraded, I suggest getting in touch with support to confirm the process.

**Comment by douglaszickuhr** [comment]
Hey @sfc-gh-ngaberel thanks for that - we're actually stuck with 0.63.0 because of some breaking changes introduced to masking policies. Once we've managed to get over that we will plan to upgrade it. For now we'll have to stay on v0.63.0
