### ISSUE TITLE
snowflake_function_grant: from prior state: unsupported attribute "arguments"

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1736]
**Provider Version**

```
+ provider registry.terraform.io/snowflake-labs/snowflake v0.62.0
```

**Terraform Version**

```
Terraform v1.4.5
on darwin_arm64
```

**Describe the bug**

Dependabot proposed that we upgrade from provider version 0.56.0 to 0.62.0, and upon running `terraform plan` with version 0.62.0, terraform crashes with this error:

```
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "module.sandbox4_application.snowflake_function_grant.application_functions_future_grant[0]" from prior state: unsupported
│ attribute "arguments"
```

But I'm not using any such attribute `arguments`:

```
$ terraform state show module.sandbox4_application.snowflake_function_grant.application_functions_future_grant[0]
# module.sandbox4_application.snowflake_function_grant.application_functions_future_grant[0]:
resource "snowflake_function_grant" "application_functions_future_grant" {
    database_name          = "SANDBOX4"
    enable_multiple_grants = false
    id                     = "SANDBOX4|APPLICATION||USAGE|SANDBOX4_STAFF_READ_WRITE,SANDBOX4_STAFF_READ_ONLY|false"
    on_future              = true
    privilege              = "USAGE"
    roles                  = [
        "SANDBOX4_STAFF_READ_ONLY",
        "SANDBOX4_STAFF_READ_WRITE",
    ]
    schema_name            = "APPLICATION"
    with_grant_option      = false
}
```

**Expected behavior**

`terraform plan` should run without crashing.

**Comment by sfc-gh-swinkler** [comment]
Sorry but i am not able to replicate the error you are seeing. I started with 0.56, created the future grant, then upgraded to 0.62 with no issue. I also made sure that the ID i was using was the same as yours. 

Could you please try removing the resource and reimporting it? 

```
terraform state rm snowflake_function_grant.application_functions_future_grant
terraform state import snowflake_function_grant.application_functions_future_grant "SANDBOX4|APPLICATION|||USAGE|false|true|SANDBOX4_STAFF_READ_WRITE,SANDBOX4_STAFF_READ_ONLY|"
```

If this issue persists, I would be happy to jump on a call to assist you.

**Comment by jrobison-sb** [comment]
Hi @sfc-gh-swinkler , thanks for your reply.

I tried `state rm / import` as requested and was able to get it to import successfully. But a subsequent `terraform plan` still crashed on 0.62. The crash log contained several entries like this:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│   with module.sandbox4_application.snowflake_database.default[0],
│   on ../../modules/aws/application/snowflake.tf line 133, in resource "snowflake_database" "default":
│  133: resource "snowflake_database" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
```

Along with other similar crashes which mention snowflake_warehouse, snowflake_storage_integration, snowflake_role, snowflake_saml_integration and snowflake_resource_monitor resources.

Then finally at the bottom of the crash log, this:

```
Stack trace from the terraform-provider-snowflake_v0.62.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 58 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadResourceMonitor(0x14000a66580, {0x10384d960?, 0x14000222b60})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/resource_monitor.go:322 +0x9cc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x103878140?, {0x103878140?, 0x14000c8d380?}, 0xd?, {0x10384d960?, 0x14000222b60?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400067b420, {0x103878140, 0x14000c8d380}, 0x140001add40, {0x10384d960, 0x14000222b60})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400074a378, {0x103878140?, 0x14000c8d260?}, 0x140001cbdc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140000b9360, {0x103878140?, 0x14000c8cab0?}, 0x1400014bb60)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x103814900?, 0x140000b9360}, {0x103878140, 0x14000c8cab0}, 0x140001e0b60, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000750000, {0x10387e580, 0x140005201a0}, 0x14000c85320, 0x14000752930, 0x1040f98d0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x14000750000, {0x10387e580, 0x140005201a0}, 0x14000c85320, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-snowflake_v0.62.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I assume this is the kind of thing which will probably be blocked without a debug log or similar, especially since you can't reproduce it yourself. And I'd be happy to provide such a log, but preferably not publicly on this GitHub Issue. If debug logs or similar would be helpful here, is there a way I can get them to you privately by way of Snowflake support? (We do have an enterprise contract / enterprise support, etc.)

I'm also happy to set up a call and screenshare whatever might be needed. Please let me know how you prefer to set up a call if desired.

Thanks.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
