### ISSUE TITLE
Snowflake External OAuth Integration Error after Upgrade to 0.62.0

### ISSUE THREAD

**Issue by culpgrant** [Snowflake-Labs/terraform-provider-snowflake#1741]
**Provider Version**

0.62.0

**Terraform Version**

1.4.5

**Describe the bug**

The Blocked Roles parameter is causing an issue. It seems to be trying to remove ORGADMIN as a blocked role - I don't explicitly have any roles in the blocked roles parameter.

**Expected behavior**

It shouldn't be adjusting the blocked_roles on snowflake_external_oauth_integration

**Code samples and commands**
I changed some values to XXX for security
```
resource "snowflake_external_oauth_integration" "INTEGRATION_XXX" {
  name                             = "XXX"
  type                             = "AZURE"
  enabled                          = true
  snowflake_user_mapping_attribute = "login_name"
  token_user_mapping_claims        = ["upn", "sub"]
  any_role_mode                    = "ENABLE" # Allows the user to use any role that they are given in Snowflake
  audience_urls = [xxx]
  issuer        = "xxx"
  jws_keys_urls = [xxx]
  comment       = "OAuth Integration for Power BI"
  provider      = snowflake.account_admin
}
```
Commands:
```
terraform plan

# snowflake_external_oauth_integration.INTEGRATION_XXX will be updated in-place
  ~ resource "snowflake_external_oauth_integration" "INTEGRATION_XXX" {
      ~ blocked_roles                    = [
          - "ORGADMIN",
        ]
        id                               = "XXX"
        # (10 unchanged attributes hidden)
    }
```

```
terraform apply

Error: error executing unset statement: 003118 (42601): SQL compilation error:
│ Cannot unset property 'EXTERNAL_OAUTH_BLOCKED_ROLES_LIST' on integration 'XXX'.
```

**Additional context**

It looks like the integration is not having a default value of ORGADMIN for the blocked role so it is trying to remove it.

**Comment by culpgrant** [comment]
The workaround was to add ORGADMIN to the blocked roles parameter

**Comment by akshjain83** [comment]
We ran into the same error and it seems like this particular change removed `ORGADMIN` from the default list: https://github.com/Snowflake-Labs/terraform-provider-snowflake/commit/66d88bd29b6aa78dbc2acd11cf729fa9380b011d#diff-840246f685e775bcf2dee809f30f112848676899dd47e5ef076598dd9e8536b3L286-L288

**Comment by sfc-gh-jmichalak** [comment]
Hey @culpgrant @akshjain83  👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides a reworked `external_oauth_integration`. Now, this list should be handled correctly. Keep in mind there's an account [parameter](https://docs.snowflake.com/en/sql-reference/parameters#external-oauth-add-privileged-roles-to-blocked-list) for adding such privilieged roles. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-snowflake_oauth_integration_for_custom_clients-and-snowflake_oauth_integration_for_partner_applications-resources).
