### ISSUE TITLE
Impossible to set alert_schedule on Alert

### ISSUE THREAD

**Issue by gllsoft** [Snowflake-Labs/terraform-provider-snowflake#1745]
**Provider Version**

0.62

**Terraform Version**

0.7

**Describe the bug**

A try to create Alert by terraform in Snowflake plateform, when I don't set alert_schedule, tu build is ok but when I set alert_schedule, the build is KO.

**Expected behavior**

The build job finish without error

**Code samples and commands**

`
resource "snowflake_alert" "merge" {
  database        = var.database_name
  schema          = var.name
  name            = "MERGE_${var.name}_ALERT"
  warehouse       = "BATCH_WH"
  condition       = "select * from table(snowflake.information_schema.query_history(end_time_range_start=>dateadd( 'MINUTE', -30, current_timestamp()), end_time_range_end=>current_timestamp(), result_limit => 10000)) where query_type in ('MERGE') AND USER_NAME = 'MyUSer' AND execution_status like 'FAILED%' AND database_name = '${var.database_name}' and schema_name = '${var.name}'"
  action          = "CALL SYSTEM$SEND_EMAIL('my_email_int','myemail@email.com','${var.database_name}.${var.name}] - My Text)"
  enabled         = true
  comment         = "Alert on merge"
  alert_schedule  = "10 MINUTE"
}
`

Error :

`
╷
│ Error: Unsupported argument
│ 
│   on modules/application_schema/main.tf line 79, in resource "snowflake_alert" "merge":
│   79:   alert_schedule  = "10 MINUTE"
│ 
│ An argument named "alert_schedule" is not expected here. Did you mean to
│ define a block of type "alert_schedule"?
╵
`

**Comment by danu165** [comment]
Looks like [the example in the docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.62.0/docs/resources/alert) is incorrect. If you refer to the Schema section of the docs, it seems the alert_schedule should look like this:


```
alert_schedule {
  intervel = 10
}
```

**Comment by gllsoft** [comment]
> Looks like [the example in the docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.62.0/docs/resources/alert) is incorrect. If you refer to the Schema section of the docs, it seems the alert_schedule should look like this:
> 
> ```
> alert_schedule {
>   intervel = 10
> }
> ```

Thank you, it's the good syntax.

Just replace intervel by interval.

**Comment by sfc-gh-asawicki** [comment]
Closing because it was fixed with #1747 .
