### ISSUE TITLE
snowflake.Database struct is missing resource_group field

### ISSUE THREAD

**Issue by mlorek** [Snowflake-Labs/terraform-provider-snowflake#1757]
1.3.9

The provider version you are using.

0.63.0

The version of Terraform you were using when the bug was encountered.

**Describe the bug**

Error: unable to scan row for SHOW DATABASES LIKE 'SCRATCH' err = missing destination name resource_group in *[]snowflake.Database

**Expected behavior**

imported exisiting db

**Code samples and commands**

**Additional context**

broken when importing existing dbs in eu-west-1

**Comment by jglapa** [comment]
thx, for reporting and providing a fix, just encountered this after upgrade to `0.63.0` eagerly waiting for next version

**Comment by sfc-gh-asawicki** [comment]
Closing because #1758 was merged.
