### ISSUE TITLE
`snowflake_task` resources applied before v0.50.0 and that define the `after` attribute cannot be upgraded

### ISSUE THREAD

**Issue by jamiekt** [Snowflake-Labs/terraform-provider-snowflake#1761]
**Provider Version**

0.37.0 (although I'm trying to upgrade to 0.51.0)

**Terraform Version**

v1.4.6

**Describe the bug**

I am attempting to upgrade a terraform configuration from using [Snowflake-Labs/snowflake/0.37.0](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.37.0) to [Snowflake-Labs/snowflake/0.51.0](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.51.0). The `after` attribute on `snowflake_task` is managed differently in those two versions:

> In 0.37.0 ([docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.37.0/docs/resources/task#after)):
>
> after (String) Specifies the predecessor task in the same database and schema of the current task. When a run of the predecessor task finishes successfully, it triggers this task (after a brief lag). (Conflict with schedule)
>
> In 0.51.0 ([docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.51.0/docs/resources/task#after)):
>
> after (List of String) Specifies one or more predecessor tasks for the current task. Use this option to create a DAG of tasks or add this task to an existing DAG. A DAG is a series of tasks that starts with a scheduled root task and is linked together by dependencies.

This change was made in 0.50.0.

Hence when I try to upgrade the provider I change all of the values supplied for `after` from 

* `after     = snowflake_task.task1.name`

to

* `after     = [snowflake_task.task1.name]`

When I run `terraform plan` I get warnings:

>  │ Warning: Failed to decode resource from state
>  │ 
>  │ Error decoding "snowflake_task.task2" from
>  │ prior state: missing expected [

and errors:

>  │ Error: missing expected [
>  │ 
>  │   with snowflake_task.task2,
>  │   on shn_task.tf line 551, in resource "snowflake_task" "task2":
>  │  551:   after     = [snowflake_task.task1.name]

Here is the portion of the state file that defines this resource:

```json
{
  "mode": "managed",
  "type": "snowflake_task",
  "name": "task2",
  "provider": "provider[\"registry.terraform.io/snowflake-labs/snowflake\"].sys",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "after": "task1",
        "comment": "Merge data",
        "database": "db",
        "enabled": true,
        "error_integration": "",
        "id": "db|sch|task2",
        "name": "task2",
        "schedule": "",
        "schema": "sch",
        "session_parameters": {
          "ODBC_QUERY_RESULT_FORMAT": "ARROW"
        },
        "sql_statement": "...",
        "user_task_managed_initial_warehouse_size": "",
        "user_task_timeout_ms": null,
        "warehouse": "wrhs",
        "when": ""
      },
      "sensitive_attributes": [],
      "private": ""
    }
  ]
}
```

Notice that the value for `after` is a string, not a list of strings.

**Expected behavior**

The upgrade should be handled smoothly. The provider should recognise the value in the state file as being a string and migrate it to being a list of strings.

**Comment by sfc-gh-asawicki** [comment]
Hey @jamiekt. This is an old version of the provider. As we are still in the pre-stable release, we are not providing backward bug fixes. The easiest way would be to remove the resource from the state and re-import it (you can check how to do it here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md#resource-migration).

**Comment by jamiekt** [comment]
@sfc-gh-asawicki Thanks for the response. By the way, I suggest you update your [guidance to use `terraform state rm`](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md#2-terraform-rm). As of terraform 1.7 [resources can be removed using removed blocks](https://www.hashicorp.com/blog/terraform-1-7-adds-test-mocking-and-config-driven-remove) which is much MUCH easier than using `terraform state rm`.

**Comment by jamiekt** [comment]
You also state in that article:

> Unfortunately, for_each cannot be used when generating with import blocks, so we have to define them one by one.

That has also been solved. terraform 1.7 supports `for_each` for import blocks.

**Comment by sfc-gh-jcieslak** [comment]
Hey @jamiekt afaik, `for_each` is available in import blocks (which is used in one of the ways to import state in the migration guide), but `for_each` cannot be used in import blocks when generating configuration with `-generate-config-out` flag.
