### ISSUE TITLE
snowflake_password_policy max_age_days does not work with 0

### ISSUE THREAD

**Issue by culpgrant** [Snowflake-Labs/terraform-provider-snowflake#1762]
**Provider Version**

0.62.0

**Terraform Version**

1.4.5

**Describe the bug**

The parameter `max_age_days` on `snowflake_password_policy` can be set to 0 but when you run terraform it sets the value to 90 the default.

**Expected behavior**

0 should be set to 0 for `max_age_days` when terraform creates the object and not set it to 90 which is the default

**Code samples and commands**

This can be tested by creating a password policy with `max_age_days` set to 0 and then run `DES PASSWORD POLICY xxx;` It will show the value `PASSWORD_MAX_AGE_DAYS` is set to 90 days.

```
resource "snowflake_password_policy" "SF_ACCOUNT_PASSWORD_POLICY" {
  database             = xxx
  schema               = xx
  name                 = "xxx"
  comment              = "xxx"
  max_age_days         = 0
}
```
Terraform Plan:
```

  # snowflake_password_policy.xxx will be updated in-place
  ~ resource "snowflake_password_policy" "xxx" {
        id                   = "xxx"
      ~ max_age_days         = 90 -> 0
        name                 = "xxx"
        # (11 unchanged attributes hidden)
    }

```

**Additional context**

This can be tested by creating a password policy with `max_age_days` set to 0 and then run `DES PASSWORD POLICY xxx;` It will show the value `PASSWORD_MAX_AGE_DAYS` is set to 90 days. Then when you run Terraform again and it recognizes it as a replace.

**Comment by sfc-gh-ngaberel** [comment]
@culpgrant thanks for reporting this issue, there is a fix in master and it will be available in the next release.

**Comment by culpgrant** [comment]
Thank you for getting to this!
