### ISSUE TITLE
`snowflake_external_table_grant` missing `on_all`

### ISSUE THREAD

**Issue by jgogstad** [Snowflake-Labs/terraform-provider-snowflake#1765]
**Provider Version**

0.63

**Terraform Version**

1.4.6

**Describe the bug**

The resource for [`snowflake_external_table_grant`](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/external_table_grant) is missing the `on_all` argument that we find in for instance [`snowflake_table_grant`](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table_grant).

This makes it impossible to provision

```sql
grant select on all external tables in database foo to role my_role;
```

**Comment by jgogstad** [comment]
related PR for the other resources: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1686

**Comment by jgogstad** [comment]
ah, ok, just found https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1742

**Comment by AnotherAlexForGreatJustice** [comment]
Can confirm bug still present on `v0.68.2`:
```
╷
│ Error: expected on_schema_object.0.all.0.object_type_plural to be one of [ALERTS EVENT TABLES FILE FORMATS FUNCTIONS PROCEDURES SECRETS SEQUENCES PIPES MASKING POLICIES PASSWORD POLICIES ROW ACCESS POLICIES SESSION POLICIES TAGS STAGES STREAMS TABLES TASKS VIEWS MATERIALIZED VIEWS], got EXTERNAL TABLES
│ 
│   with module.databases["KEY1"].module.permissions_prod.snowflake_grant_privileges_to_role.writer_external_table_permissions["KEY2"],
│   on database/permission-unit/function_write.tf line 83, in resource "snowflake_grant_privileges_to_role" "writer_external_table_permissions":
│   83:       object_type_plural = "EXTERNAL TABLES"
│ 
╵
Releasing state lock. This may take a few moments...
```

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
