### ISSUE TITLE
Error importing an inbound share defined using `for_each`

### ISSUE THREAD

**Issue by grahamwetzler** [Snowflake-Labs/terraform-provider-snowflake#1770]
**Provider Version**

0.63.0

**Terraform Version**

v1.4.2

**Describe the bug**

Attempting to import a share defined with `for_each` results in `Error: strconv.ParseInt: parsing "": invalid syntax`

**Expected behavior**

The share to successfully import.

**Code samples and commands**

```
resource "snowflake_database" "shares" {
  name       = each.key
  from_share = {
    provider = each.value.provider
    share    = each.value.share
  }

  for_each = {
    "MY_SHARE" = {
      provider = "ORG\".\"ACCT"
      share    = "MY_SHARE"
    }
  }
}
```

```
terraform import 'snowflake_database.shares["MY_SHARE"]' MY_SHARE
```

**Additional context**

Importing works fine when defined like so:
```
resource "snowflake_database" "MY_SHARE" {
  name = "MY_SHARE"
  from_share = {
    provider = "ORG\".\"ACCT"
    share    = "MY_SHARE"
  }
}
```

**Comment by sfc-gh-jcieslak** [comment]
Hey @grahamwetzler 👋 
I'm currently working on databases as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1. I reproduced your configuration and this issue shouldn't happen in later versions of the provider. Didn't check lower, but at least 0.70.0 should work.

**Comment by sfc-gh-jcieslak** [comment]
Hey @grahamwetzler  👋
The new version ([v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0)) contains the new database resources. The issue with the database from share shouldn't be present there. If you can, please try to migrate to/import the snowflake_shared_database. Closing the ticket as snowflake_database is now representing the standard database and the snowflake_database_old (that was previously snowflake_database) is no longer supported. If you encounter any issues with the new resources, please report a new issue. Thank You.
