### ISSUE TITLE
Updating an snowflake_external_oauth_integration resource throws an error

### ISSUE THREAD

**Issue by kietay** [Snowflake-Labs/terraform-provider-snowflake#1773]
**Provider Version**

v0.59.0

**Terraform Version**

v.1.3.7

**Describe the bug**

When updating the "blocked roles" list, an error is thrown during interface conversion.

We initially included `ACCOUNTADMIN` in the blocked roles list. We saw perpetual drift in the plan as Snowflake includes this role by default, so Terraform thinks it needs to re-add the role to the list on each change. When we try to apply, this throws the below stack trace.

**Expected behavior**

The resource update will succeed.

**Code samples and commands**

1. Include "ACCOUNTADMIN" in blocked roles list
2. Re plan unrelated change in the same stack
3. Snowflake tries to re-add ACCOUNTADMIN
4. Error is thrown

**Additional context**

Stack trace:
```
goroutine 115 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateOAuthIntegration(0xc000a24d80, {0x130dec0?, 0xc0005f6c30})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/oauth_integration.go:309 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1582000?, {0x1582000?, 0xc000a50120?}, 0xd?, {0x130dec0?, 0xc0005f6c30?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004107e0, {0x1582000, 0xc000a50120}, 0xc000a28b60, 0xc000a24c00, {0x130dec0, 0xc0005f6c30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00044def0, {0x1582000?, 0xc000a50000?}, 0xc000a16690)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0007f6dc0, {0x1582000?, 0xc000a115f0?}, 0xc000a200e0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x12d9d40?, 0xc0007f6dc0}, {0x1582000, 0xc000a115f0}, 0xc000a20070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00048e000, {0x1587dc0, 0xc000582ea0}, 0xc000a2cd80, 0xc0004719b0, 0x1d385a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00048e000, {0x1587dc0, 0xc000582ea0}, 0xc000a2cd80, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

**Comment by sfc-gh-jmichalak** [comment]
Hey @kietay  👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides a reworked external_oauth_integration. Now, this list should be handled correctly. Keep in mind there's an account [parameter](https://docs.snowflake.com/en/sql-reference/parameters#external-oauth-add-privileged-roles-to-blocked-list) for adding such privilieged roles. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#snowflake_external_oauth_integration-resource-changes).
