### ISSUE TITLE
Grant `insert` on a table to role requires multiple `Apply` to become effective

### ISSUE THREAD

**Issue by alex-ld** [Snowflake-Labs/terraform-provider-snowflake#1794]
**Provider Version**

```"0.63.0"```

**Terraform Version**

```1.3.7```

**Describe the bug**

In commit 1, I have two `insert` grants on `all` and `future` tables in a schema, to a role.
In commit 2, I removed the two `all` and `future` grants, and instead, added `insert` grant to a certain table to this role.

I ran `plan`, got the first plan:
(You will see 3 resources being added, because it was in fact 3 tables)
![first](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/62313436/84115b91-766a-4005-949c-a456d9f87946)
Applied it, and tested on Snowflake. The role doesn't have the permission to insert.

I ran `plan` again, got the second plan:
(You will see 3 resources being changed, because it was in fact 3 tables)
![second](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/62313436/71c92094-4352-4627-81a4-f9c750f92b01)
Tested on Snowflake, now it worked.

**Expected behavior**
This grant should become effective after the first `apply`, now it requires applying twice to make it effective.

**Code samples and commands**
```
resource "snowflake_table_grant" "xxx" {
  database_name = local.workspace["database_name"]
  schema_name   = snowflake_schema.xxx.name
  table_name    = snowflake_table.xxx.name

  privilege = "INSERT"
  roles     = [var.xxx_role]

  with_grant_option = false
}
```

**Additional context**

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
