### ISSUE TITLE
Include "snowflake_failover_group_grant" resource

### ISSUE THREAD

**Issue by sfc-gh-klim** [Snowflake-Labs/terraform-provider-snowflake#1797]
**Is your feature request related to a problem? Please describe.**

We are looking for the following grants: https://docs.snowflake.com/en/user-guide/security-access-control-privileges#failover-group-privileges

Since we frequently add failover groups, we would need to do the grant manually every time now. This is quite error-prone so we want to do that via Terraform.

**Describe the solution you'd like**

We need a corresponding grant resource for "snowflake_failover_group" resource, which is currently missing.

It would be similar to "snowflake_warehouse" and "snowflake_warehouse_grant".

**Describe alternatives you've considered**

Doing it manually by running the required SQL but it is error prone.

**Additional context**

-

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
