### ISSUE TITLE
snowflake_stage_grant raising error when on_future is false and stage name is provided

### ISSUE THREAD

**Issue by LucasMMota** [Snowflake-Labs/terraform-provider-snowflake#1815]
**Provider Version**

provider registry.terraform.io/snowflake-labs/snowflake v0.63.0

**Terraform Version**

Terraform v1.4.5

**Describe the bug**

The doc is not much clear about the `on_future` usage. It says: _"The stage_name field must be unset in order to use on_future"_.
We can conclude that we could have the stage name when it's `false`. Although, when the `on_future=false` and the stage name are provided, we get the error: 
```
Error: Conflicting configuration arguments

"on_future": conflicts with stage_name
```

**Expected behavior**

It should be able to accept the parameter `on_future` (equal `false`) + stage name. And only raise an error if the `on_future` is `true` and `stage name != null`.

**Code samples and commands**

my stage list
```terraform
resource "snowflake_stage_grant" "grant" {
  for_each          = { for privilege, roles in local.roles_by_privilege : privilege => roles }
  database_name     = var.database
  schema_name       = var.schema
  stage_name        = var.name
  privilege         = each.key
  roles             = each.value
  with_grant_option = false
  on_future         = false
  depends_on        = [snowflake_stage.stage]
}
```

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
