### ISSUE TITLE
Grant a database role to a share

### ISSUE THREAD

**Issue by AnatEzra81** [Snowflake-Labs/terraform-provider-snowflake#1817]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, you can create a database role but you cannot grant it to a share (or any other resource I think)

**Describe the solution you'd like**
A snowflake_database_role_grant resource, or some other way to grant database roles to shares

**Describe alternatives you've considered**

**Additional context**

**Comment by sfc-gh-pbosak** [comment]
I think it's connected to #1830

**Comment by sfc-gh-pbosak** [comment]
I am looking into it

**Comment by danieladams456** [comment]
I am trying to do the same thing, and it does not appear to be possible.

My use case is I want shares to be managed at the `ACCOUNTADMIN` level but delegate management of object assignment to said shares to a lower privilege role.

**Comment by emancu** [comment]
I have the same request, I want to share a DB between accounts using `SHARES` and `DATABASE ROLE` and its not possible =(

**Comment by ayalalo** [comment]
same here.
is it possible?

**Comment by sfc-gh-jcieslak** [comment]
Closing as this is a Snowflake feature request and not a provider one. We can only do things possible on the Snowflake side. During the grants redesign, we introduced database role resources, so please check if they're resolving your issue:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)

If anything you want is supported by Snowflake and it's not supported by the provider, please create another GitHub issue.
