### ISSUE TITLE
Issue with importing the resource "snowflake_database.from_share" into state file

### ISSUE THREAD

**Issue by sirishachaparla** [Snowflake-Labs/terraform-provider-snowflake#1833]
**Provider Version**

0.59.0

**Terraform Version**

1.0.3

**Describe the bug**

Terraform shows difference in plans after successful importing the snowflake database from share. The plans are fine for simple database after import. 
Plans looks like destroying the imported database and recreating it. The below are the changes to  "snowflake_database.from_share "

 # module.test_db.snowflake_database.from_share must be replaced
-/+ resource "snowflake_database" "from_share" {
      + comment                     = "Managed through Terraform. 
      ~ data_retention_time_in_days = 0 
+ from_share                  = {
          + "provider" = "provider.account"
          + "share"    = "share_name"
        } # forces replacement
      ~ id                          = "database_name" -> (known after apply)
        name                        = "database_name"
        # (1 unchanged attribute hidden)
    }

**Expected behavior**
Imported Database should not be changed or force replaced

**Comment by sirishachaparla** [comment]
Hello,
Still I am facing the issue. If anyone has any suggestions on the above issue. Please add here.

**Comment by piotrszwajkowski** [comment]
Same on my end. Could you please take a look into it? 🙏

**Comment by sfc-gh-asawicki** [comment]
Hey. We will look closely at the database resource in the upcoming weeks as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap. We will discuss how the import should work then.

Be aware that it may be not possible to import the database created from a share correctly. We are limited to SQL statements that can be run against Snowflake. If we can't get information on the database that it was created from share, then it may be impossible to set the state correctly in the current import. We will research what options we have.

**Comment by sfc-gh-jcieslak** [comment]
Hey @sirishachaparla 👋 
The new version ([v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0)) contains the new database resources. The issue with importing the database from share shouldn't occur there. If you can, please try to migrate to/import the `snowflake_shared_database`. Closing the ticket as `snowflake_database` is now representing the standard database and the `snowflake_database_old` (that was previously `snowflake_database`) is no longer supported. If you encounter any issues with the new resources, please report a new issue. Thank You.
