### ISSUE TITLE
Valid warehouse sizes not accepted

### ISSUE THREAD

**Issue by ian-r-rose** [Snowflake-Labs/terraform-provider-snowflake#1844]
**Provider Version**

0.65.0

**Terraform Version**

1.x

**Describe the bug**

In the most recent release of the provider (0.65), valid warehouse sizes are no longer accepted (possibly related to #1792). If I choose a warehouse size "X-LARGE", I get an error message:

```
│ Error: expected warehouse_size to be one of [XSMALL SMALL MEDIUM LARGE XLARGE XXLARGE XXXLARGE X4LARGE X5LARGE X6LARGE], got X-LARGE
```

Previous versions of the provider worked, and were able to normalize warehouse sizes like X-SMALL or X-LARGE. Worse, it seems that Snowflake itself stores the warehouse sizes in the hyphenated form, so in my configurations the provider is unable to identify that `XSMALL` and `X-SMALL` are the same, and thinks there are changes to apply.

**Expected behavior**

Both hyphenated and non-hyphenated forms of warehouse sizes should be acceptable.

**Additional context**

This may be a consequence of #1792

**Comment by jreslock** [comment]
We are seeing this behavior after updating our provider to 0.66.1 today.

**Comment by WojtekWaga** [comment]
In our case it misinterprets 3XLARGE read from Snowflake:

  # snowflake_warehouse.warehouses_se["ETL_3XL"] will be updated in-place
  ~ resource "snowflake_warehouse" "warehouses_se" {
        id                                  = "ETL_3XL"
        name                                = "ETL_3XL"
      ~ warehouse_size                      = "3XLARGE" -> "xxxlarge"
        # (12 unchanged attributes hidden)
    }

**Comment by sfc-gh-asawicki** [comment]
Hey @ian-r-rose @jreslock @WojtekWaga.

We are currently reworking the warehouse resource as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1. However, the customized diff suppression was already added in earlier provider versions (#1873 #1946), so this problem should not happen in recent ones.

Can you confirm that?
