### ISSUE TITLE
0.66.1 Un-recognized warehouse size prompts new apply

### ISSUE THREAD

**Issue by PedroMartinSteenstrup** [Snowflake-Labs/terraform-provider-snowflake#1856]
**Provider Version**

+ provider registry.terraform.io/aidanmelen/snowsql v1.3.3
+ provider registry.terraform.io/hashicorp/aws v5.0.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/vault v3.15.2
+ provider registry.terraform.io/snowflake-labs/snowflake v0.66.1

**Terraform Version**

Terraform v1.4.6 on darwin_arm64

**Describe the bug**

If you set the warehouse size to `XXLARGE` and apply, the next Terraform Plan will only see it as `2XLARGE` on the warehouse, and will therefore want to re-apply the changes. This is a perpetual loop. Changing to `2XLARGE` is not accepted by the provider
```
│ Error: expected warehouse_size to be one of [XSMALL SMALL MEDIUM LARGE XLARGE XXLARGE XXXLARGE X4LARGE X5LARGE X6LARGE], got 2XLARGE
```

**Expected behavior**

Provider can read 2X-Large and understand it is XXLARGE and not prompt to apply.

**Code samples and commands**

Terragrunt plan
```
  # snowflake_warehouse.this_warehouse["TRANSFORM"] will be updated in-place
  ~ resource "snowflake_warehouse" "this_warehouse" {
        id                                  = "TRANSFORM"
        name                                = "TRANSFORM"
      ~ warehouse_size                      = "2XLARGE" -> "XXLARGE"
        # (13 unchanged attributes hidden)
    }
```

Terragrunt state
```
# snowflake_warehouse.this_warehouse["TRANSFORM_PRODUCT"]:
resource "snowflake_warehouse" "this_warehouse" {
[...]
    id                                  = "TRANSFORM"
    name                                = "TRANSFORM"
[...]
    warehouse_size                      = "XXLARGE"
    warehouse_type                      = "STANDARD"
}
```

Snowflake SHOW WAREHOUSE
```
+---------+---------+--------+--------+
|name     |state    |type    |size    |
+---------+---------+--------+--------+
|TRANSFORM|SUSPENDED|STANDARD|2X-Large|
+---------+---------+--------+--------+

```

**Comment by fredriv** [comment]
Seems like `SHOW WAREHOUSES` uses the warehouse sizes from https://docs.snowflake.com/en/user-guide/warehouses-overview, i.e. `2X-Large`, `3X-Large`, etc. The `CREATE/ALTER WAREHOUSE` on the other hand expects the sizes defined in the Terraform provider...

**Comment by drn** [comment]
After upgrading to the latest version of this provider and adjusting our `warehouse_size`s to fit the new required list, we ran into this issue as well:

```
# snowflake_warehouse.transforming will be updated in-place
  ~ resource "snowflake_warehouse" "transforming" {
        id                                  = "TRANSFORMING"
        name                                = "TRANSFORMING"
      ~ warehouse_size                      = "2XLARGE" -> "XXLARGE"
        # (12 unchanged attributes hidden)
    }
```

and when attempting to change to `2XLARGE`, we see the following error:

```
│ Error: expected warehouse_size to be one of [XSMALL SMALL MEDIUM LARGE XLARGE XXLARGE XXXLARGE X4LARGE X5LARGE X6LARGE], got 2XLARGE
│ 
│   with snowflake_warehouse.transforming,
│   on snowflake_warehouse.tf line 29, in resource "snowflake_warehouse" "transforming":
│   29:   warehouse_size    = "2XLARGE"
```

**Comment by PedroMartinSteenstrup** [comment]
i believe this is fixed with https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1873
