### ISSUE TITLE
Grant read operation fails when a privilege has been granted to a database role

### ISSUE THREAD

**Issue by ogr003** [Snowflake-Labs/terraform-provider-snowflake#1863]
**Provider Version**

0.65.0

**Terraform Version**

1.3.7

**Describe the bug**

Grant read operation fails when a privilege has been granted to a database role:

```
Error: error reading database grant: unknown grantee type DATABASE_ROLE
```

**Expected behavior**

Provider ignores database role grants, as they are not currently supported.

**Code samples and commands**

```hcl
resource "snowflake_database_grant" "grant" {
  database_name = "DB"

  privilege = "USAGE"
  roles     = ["role1", "role2"]
  shares    = ["share1", "share2"]

  with_grant_option = false
}
```

**Executed outside of Terraform**

```sql
GRANT USAGE ON DATABASE DB TO DATABASE ROLE DB.EXAMPLE_ROLE
```

**Additional context**

I guess support for database role grants is on the roadmap, but this can be fixed temporarily by ignoring `DATABASE_ROLE` grants in read operations. It can be as simple as adding the following to https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/grant_helpers.go#L251:

```go
if currentGrant.GranteeType == "DATABASE_ROLE" {
  // Temporary measure so that Terraform will not fail
  // when a database role has been granted privileges
  continue
}
```

and the equivalent to https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/grant_helpers.go#L287:

```go
if futureGrant.GranteeType == "DATABASE_ROLE" {
  // Temporary measure so that Terraform will not fail
  // when a database role has been granted privileges
  continue
}
```

**Comment by sfc-gh-swinkler** [comment]
#2037 fixed this issue. if you upgrade to 0.70.1 then this error will go away
