### ISSUE TITLE
URGENT : Not able to create Schema, Error says to issue with provider

### ISSUE THREAD

**Issue by ArnabMon14** [Snowflake-Labs/terraform-provider-snowflake#1870]
**Provider Version**

0.41.0

**Terraform Version**

1.2.7

**Describe the bug**

Not able to create Schema in Terraform Cloud. Getting the below error which told to do this :
"This is a bug in the provider, which should be reported in the provider's own issue tracker."

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/136154492/d1348648-e70f-4a43-9304-81319aec93e0)

**Expected behavior**

To create a schema in a Database

**Code samples and commands**

CREATE SCHEMA DEV_LZ.HVR_DWNI

**Additional context**

This is being used in a crucial part and it is important that we resolve this as soon as possible.

**Comment by bogdan-cioata** [comment]
Could you share the resource block you used?
Additionally, make sure that the schema doesn't exist already in the database, as the error suggests so.
