### ISSUE TITLE
Unable to import snowflake procedure grant 

### ISSUE THREAD

**Issue by ashshetty90** [Snowflake-Labs/terraform-provider-snowflake#1875]
**Provider Version**

Sowflake provider version : v0.64.0
AWS Provider Version : v5.1.0

**Terraform Version**

Terraform version : v1.4.6

**Describe the bug**

On trying to import the snowflake procedure grant I am getting the error as
 `Error: incorrect ID format (expecting database_name|schema_name|procedure_name|argument_data_types|privilege|with_grant_option|on_future|roles|shares)`

**Expected behavior**

The grant attached to the snowflake procedure must be successfully imported

**Code samples and commands**

Resource in main.tf file : 

`resource "snowflake_procedure_grant" "DEV_SP_PURGE_EXCLUSION_CHECK_GRANT" {
}`

Import Command : 

`terraform import snowflake_procedure_grant.DEV_SP_PURGE_EXCLUSION_CHECK_GRANT "DEV_DWH|ANALYTICS_SB|SP_PURGE_EXCLUSION_CHECK|[]|OWNERSHIP|true|false|DEV_ANALYTICS_SB_CREATE_ROLE|[]"`
**Additional context**
I have tried with upgrading the Snowflake provider version to the latest one but the issue is the same. 
While debugging this issue, I tried importing the grant as a new resource instead of importing, and even there I faced an error with the attribute  _with_grant_option_. It gave me an error stating `with_grant_option conflicts with procedure name` error

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
Closing, as the issue was about the deprecated resources. Recently, we released [a new grant resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership) which is capable of granting ownership. Please, give it a try. If there will be any issues with it, create another GitHub issue.
