### ISSUE TITLE
Incorrect Snowflake warehouse type switching from STANDARD to SNOWPARK-OPTIMIZED in Terraform Snowflake Provider

### ISSUE THREAD

**Issue by astanfel** [Snowflake-Labs/terraform-provider-snowflake#1884]
**Provider Version**

`0.64.0`

**Terraform Version**

`1.3.4`

**Describe the bug**

Currently, when using the Snowflake Provider for Terraform, we have encountered a bug where the Snowflake warehouse type is being incorrectly switched from "STANDARD" to "SNOWPARK-OPTIMIZED" in the plan, even when the warehouse was originally defined as "SNOWPARK-OPTIMIZED".

**Expected behavior**

The expected behavior is that the Snowflake warehouse type should remain as "SNOWPARK-OPTIMIZED" since it was initially defined as such.

**Code samples and commands**

Below is an example from the Terraform plan where the issue occurs:

```hcl
# module.my_warehouse_snowpark_optimized_wh.snowflake_warehouse.this will be updated in-place
  ~ resource "snowflake_warehouse" "this" {
        id                                  = "MY_WAREHOUSE__SNOWPARK_OPTIMIZED"
        name                                = "MY_WAREHOUSE__SNOWPARK_OPTIMIZED"
      ~ warehouse_type                      = "STANDARD" -> "SNOWPARK-OPTIMIZED"
        # (12 unchanged attributes hidden)
    }
```

**Additional context**

This issue arises when using the Snowflake Provider for Terraform. Despite initially defining the warehouse type as "SNOWPARK-OPTIMIZED," the plan shows that the warehouse type is switching from "STANDARD" to "SNOWPARK-OPTIMIZED." This behavior is unexpected and may cause incorrect configuration or undesired resource modifications.

Please note that this issue occurs with the Snowflake Provider version `0.64.0`. It would be greatly appreciated if this bug could be addressed and fixed in future releases of the provider.

**Comment by astanfel** [comment]
This is only happening in the plan, in Snowflake the warehouse is set correctly as "SNOWPARK-OPTIMIZED."

**Comment by jaymilagroso-globe** [comment]
Hi, I encountered the same behavior.

The SF warehouse itself is properly set to `SNOWPARK-OPTIMIZED` but the terraform plan says otherwise.

Watching this issue. Thanks!

**Comment by jaymilagroso-globe** [comment]
@git-benjamin here's a sample configuration:
```sh
terraform {
  backend "gcs" {
    bucket = "some-bucket"
    prefix = "some-path/state"
  }
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.53"
    }
  }
}
....
resource "snowflake_warehouse" "SOME_WAREHOUSE_L" {
  name                         = "SOME_WAREHOUSE_L"
  comment                      = "SOME_WAREHOUSE_L"
  warehouse_size               = "large"
  auto_suspend                 = 600
  auto_resume                  = true
  max_concurrency_level        = 4
  min_cluster_count            = 1
  max_cluster_count            = 1
  scaling_policy               = "STANDARD"
  statement_timeout_in_seconds = 7200
  warehouse_type               = "SNOWPARK-OPTIMIZED"
}
```

**Comment by sfc-gh-asawicki** [comment]
Hey @astanfel.

There was a change: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1804, and a few subsequent modifications to the warehouse resource. Can you please bump to the newer version of the provider to check if the issue still persists? The first change mentioned was introduced in [v0.65.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.65.0).

**Comment by sfc-gh-asawicki** [comment]
Hey @astanfel, I will close this issue; please open a new one if you are experiencing this problem in the more recent versions of the provider.
