### ISSUE TITLE
0.66.2 Warehouse size endless changes

### ISSUE THREAD

**Issue by askldjd** [Snowflake-Labs/terraform-provider-snowflake#1889]
**Provider Version**
0.66.2

**Terraform Version**
1.3.2

**Describe the bug**

We upgraded to 0.66.2 recently and modified the warehouse sizes according to the enumeration.

Now every time we run Terraform plan, it will always recommend a warehouse size change.
```
  ~ resource "snowflake_warehouse" "runner_warehouses" {
        id                                  = "RUNNER_X4LARGE_PROD"
        name                                = "RUNNER_X4LARGE_PROD"
      ~ warehouse_size                      = "4XLARGE" -> "4X-LARGE"
        # (12 unchanged attributes hidden)
    }
```

And if we try to use `4XLARGE` for warehouse size, terraform will fail with
```
Error: not a valid warehouse size: 4XLARGE
```

**Expected behavior**

Terraform plan should detect no changes.

**Comment by jasonicarter** [comment]
Another issue similar to this was fixed for me with this merge #1873
Based on the snippet, you probably want `X4LARGE` or `4X-LARGE` to get it working
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/59b7ef5d791ecce366063a5cb8e2d68c68fb3e39/pkg/sdk/warehouses.go#L55-L81

**Comment by askldjd** [comment]
I am already using 4X-LARGE in my code.

**Comment by sfc-gh-klim** [comment]
Could repro the issue, using any warehouse size above LARGE.

**Comment by sfc-gh-swinkler** [comment]
It appears like you have an invalid warehouse size saved in your state file, which causes you to be stuck in validation. `4XLARGE` is not a valid size as per: https://docs.snowflake.com/en/sql-reference/sql/create-warehouse#optional-properties-objectproperties.  I am wondering even how you were able to get in this state.

In any case, it is a simple enough fix. We can just add `4XLARGE` to the `ToWarehouseSize(s string)` function

```
	case "X4LARGE", "4X-LARGE", "4XLARGE":
		return WarehouseSizeX4Large, nil
```

and might as well do the same for other potential misspellings. @sfc-gh-pbosak has a PR to fix this, i was able to verify it works by first creating a warehouse with `4X-LARGE`, then editing the state manually to `4XLARGE`, then running terraform plan and it showed no diff, whereas without the change it would return the error you described.
