### ISSUE TITLE
Allow spaces in role names for grants

### ISSUE THREAD

**Issue by jacobRiehl** [Snowflake-Labs/terraform-provider-snowflake#1893]
**Is your feature request related to a problem? Please describe.**

Unable to manage grants on roles with spaces in the name

**Describe the solution you'd like**

I would like to be able to manage all role grants.

**Describe alternatives you've considered**

We are unable to remove spaces from our naming convention. Currently we are manually managing grants.

**Comment by sfc-gh-swinkler** [comment]
Hello @jacobRiehl , i am sorry you are experiencing this problem. Can you please provide an example configuration code, along with the error message you see so that we can look into this further?

**Comment by jacobRiehl** [comment]
Code example:
resource "snowflake_role_grants" "grants" {
  role_name = "SUBJECT DB_DEV_CONFORMED SNOWFLAKE_INFO ALL"
  roles = [
    "SUBJECT DB_DEV_CONFORMED SNOWFLAKE_INFO MS"
  ]
}

Error:
##[error]╷
│ Error: ' ' is not a valid identifier character.
│ 
│   with snowflake_role_grants.grants,
│   on roles.tf line 106, in resource "snowflake_role_grants" "grants":
│  106:   role_name = "SUBJECT DB_DEV_CONFORMED SNOWFLAKE_INFO ALL"
│ 
╵
╷
│ Error: ' ' is not a valid identifier character.
│ 
│   with snowflake_role_grants.grants,
│   on roles.tf line 106, in resource "snowflake_role_grants" "grants":
│  106:   role_name = "SUBJECT DB_DEV_CONFORMED SNOWFLAKE_INFO ALL"
│ 
╵
╷
│ Error: ' ' is not a valid identifier character.
│ 
│   with snowflake_role_grants.grants,
│   on roles.tf line 106, in resource "snowflake_role_grants" "grants":
│  106:   role_name = "SUBJECT DB_DEV_CONFORMED SNOWFLAKE_INFO ALL"
│ 
╵

**Comment by shintaro-amaike** [comment]
Is this a bug or specification?

Code Sample
```
resource "snowflake_grant_privileges_to_role" "schema_grant" {
  provider = snowflake.security_admin
  privileges = ["SELECT TABLE"]
  role_name  = "ANALYST"
  on_schema {
    schema_name = "TF_DB.TF_SCHEMA"
  }
}
```

Error
```
│ Error: error granting privileges to account role: 003007 (42601): SQL compilation error: error line 1 at position 6
│ Invalid privilege SELECTTABLE.
│ 
│   with snowflake_grant_privileges_to_role.schema_grant_select,
│   on role.tf line 97, in resource "snowflake_grant_privileges_to_role" "schema_grant_select":
│   97: resource "snowflake_grant_privileges_to_role" "schema_grant" {
```

Its ok.
```
resource "snowflake_grant_privileges_to_role" "schema_grant" {
  provider = snowflake.security_admin
  privileges = ["CREATE TABLE"]
  role_name  = "ADMIN"
  on_schema {
    schema_name = "TF_DB.TF_SCHEMA"
  }
}
```

Why can't you 'select table' when you can 'create table'?

**Comment by Bryan-Meier** [comment]
@shintaro-amaike for select on tables you need to use something like the below. The difference is creating objects versus using objects:

`resource "snowflake_grant_privileges_to_role" "grant_to_all_tables" {
  privileges = ["SELECT"]
  role_name  = "SOME_ROLE"
  
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_schema          = "\"${var.database_name}\".\"${var.schema_name}\""
    }
  }`

**Comment by shintaro-amaike** [comment]
@Bryan-Meier 
Thank you very much. for the follow up.
I will try to use that.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them (and it seems like it was already fixed, but not confirmed). Please, try to use the latest provider version with the non-deprecated resources. If the issue persists on the non-deprecated resource, please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources.
