### ISSUE TITLE
Database role grant and grant to database role

### ISSUE THREAD

**Issue by alexandrewatercare** [Snowflake-Labs/terraform-provider-snowflake#1896]
**Is your feature request related to a problem? Please describe.**

We have the snowflake_database_role resource but we don't have snowflake_database_role_grant so we cannot grant the database role to a account role. Also, we cannot use a database role in snowflake_table_grant or any type of database object (stream, procedure, etc).

**Describe the solution you'd like**

We should have a snowflake_database_role_grant object to be able to grant a database role to an account role.
We also should have a database_roles in all object.

- snowflake_external_table_grant
- snowflake_file_format_grant
- snowflake_function_grant
- snowflake_materialized_view_grant
- snowflake_pipe_grant
- snowflake_procedure_grant
- snowflake_schema_grant 
- snowflake_sequence_grant
- snowflake_stage_grant 
- snowflake_stream_grant 
- snowflake_table_grant 
- snowflake_task_grant 
- snowflake_view_grant 

**Describe alternatives you've considered**

- I code my grant with null_resource and snowsql command, it works but it take a lot of time.

**Comment by vmatt** [comment]
I just came to open the exact same issue, but you've preceded me :D For me, snowflake_database_role_grants would be the highest priority.

**Comment by sfc-gh-swinkler** [comment]
@alexandrewatercare we absolutely need a `snowflake_grant_privileges_to_database_role` resource, and we intend to work on it alongside `snowflake_grant_privileges_to_application_role`, `snowflake_grant_privileges_to_share` and `snowflake_grant_ownership`. This will eliminate the need for so many new resources while still being easy to use. Refer to https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1890.
 We will be introducing these resources soon.

**Comment by alexandrewatercare** [comment]
Do you have any idea when the snowflake_grant_privileges_to_database_role  will be available, @sfc-gh-swinkler ?

Thanks

**Comment by sfc-gh-asawicki** [comment]
Hey @alexandrewatercare. I'm sorry for not getting back to you sooner!

We plan to add it in October/November.
