### ISSUE TITLE
Error Importing Snowflake Account 

### ISSUE THREAD

**Issue by RoyerRamirez** [Snowflake-Labs/terraform-provider-snowflake#1899]
**Provider Version**
0.66.2 (latest)

**Terraform Version**
1.39.0

**Terragrunt Version**
0.45.3

**Describe the bug**

We believe we’re running into a bug when importing Snowflake Accounts using the resource [snowflake_account](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account). We’re currently using the latest version (0.66.2). 

Whenever, we perform an import,  we are running into a permission issues.  Form our end, we can confirm it’s a TF provider issue for the following reasons:
1. We used the same query the provider is running when doing an import, which is SHOW ORGANIZATION ACCOUNTS LIKE '<ACCOUNT NAME>'. On the Snowflake console, the query runs without any issues. It only fails when we use TF for the import.
2. We are able to create new accounts using the resource [snowflake_account](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account) with the exact same permissions.
3. We are using the same permissions when creating as we are when importing. 

Whenever we perform an import, this is the error message we get:
```
Error reading account: 003001 (42501): SQL access control error: │ Insufficient privileges to operate on 'SYSTEM'
```

It almost seems like the import is needing more elevated permissions compared to creating new accounts, or the import query is incorrect. Your help to resolving this issue would be greatly appreciated.

**Expected behavior**

We expect the import to work correctly when using the `ORGADMIN` role. 

**Code samples and commands**

`terraform import 'snowflake_account.snowflake_account["<ACCOUNT NAME>"]' <ACCOUNT LOCATOR ID>`

**Additional context**

**Comment by amirhessam88** [comment]
+ 1 on the above-mentioed issue

**Comment by RoyerRamirez** [comment]
The bug seems to be resolved when we upgraded to the latest release that just came out 20 hours ago (version 0.67.0)
