### ISSUE TITLE
PR 1678 makes role grants done via Terraform utterly useless

### ISSUE THREAD

**Issue by ndavies-om1** [Snowflake-Labs/terraform-provider-snowflake#1907]
**Provider Version**

0.67.0

**Terraform Version**

1.3.4

**Describe the bug**

This PR https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1678 now ensures any applies are yolo applies when you are changing grants. You can no longer see who will have access to the role once the apply has been made. The claim that this is to be valid with European PII laws is simply wrong. If this were the case then you would have to:
- block this as the DDL level. I can still run DDL to see who has the grants
- block this in the UI

European PII laws have a carve out for administration of systems. To administer a system (which we are doing with Terraform) you need to know what users are being affected when a change is being made.

**Expected behavior**

Remove the users from sensitive output

**Code samples and commands**

```
! resource "snowflake_role_grants" "my_grant_to_a_role" {
        id                     = "MY_ROLE||"
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change.
!       users                  = (sensitive)
        # (3 unchanged attributes hidden)
    }
```

What is happening with my code changer? I have no idea. I do not want to YOLO this apply, especially with all the grants issues that have been occurring recently.

**Additional context**

**Comment by sfc-gh-ngaberel** [comment]
Hi @ndavies-om1, thank you for reporting this issue. The point of #1678 was to remove any PII from run logs generated by automated systems (eg. Terraform Enterprise), which is a feature that was requested by some of our European customers. Apologies for the lacking description of the PR, it should have been clearer.

It sounds like your current requirements are at odds with this feature. In our view, the ideal solution to this issue would be to earn enough of your trust that you can automate your entire RBAC setup with the Snowflake provider and not feel like you have to manually check its proposed changes every time. While we're working hard on stabilizing the provider to earn this trust we understand that we're just not there yet. We'll be sharing a roadmap with our plans to get to a stable v1.0, and later v2.0, in the next couple of weeks.

Discussing with the team, one idea we had to provide a workaround for your use case would be to introduce a new environment variable (eg. `SNOWFLAKE_DISABLE_INSECURE_PII_FIELDS`) that would control whether those fields are marked as sensitive. For this to work we'd recommend making sure this variable is always set when starting runs (plan or apply) to avoid unexpected side effects, for example forcing the state to frequently change between sensitive and insensitive version of the fields.
Would that be an acceptable solution to this issue?

**Comment by ndavies-om1** [comment]
To me this feature request is because of a poor implementation of Snowflake and this feature is a bandaid over this. You should always understand the impact of a Terraform change before applying it. It might not always be clear as to what your change is going to do, hence why you should see your changes before you apply them. This is a Terraform best practice and this feature goes against that.

Your European customers who are using Terraform Enterprise have their Terraform setup poorly and they are asking you to implement a bad feature rather than fix their setup. If they do not want their human user informations to show up in plans, then these human users and their grants should be *not* managed using Terraform, and the `enable_multiple_grants flag` should be used for all grants. This will prevent these users from ever showing up. If their users and/or grants are defined in source code, it is easy to see what the user would have access to, and who the user is (based on their username), so hiding this information from the output of Terraform does not achieve anything from a compliance perspective. I would advise them to move their human users information and grants out of Terraform, *or* into a different Terraform state file and Terraform Enterprise project that has tighter permissions to avoid this information being commonly available to all users of their Terraform Enterprise. 

I would like to point out that AWS provider does not have these same concerns or have I run into any other Terraform provider that is marking such data as sensitive.

Once the grants model uses the model as suggested for v1, this problem should go away as the grant resource ID will be the based off principal and not the target resource of the grant.

Please revert this change and work on addressing their concerns with the v1 of the grants rather than forcing the rest of us to be YOLO-ing changes when we are making grant changes.

**Comment by qbatten** [comment]
I see that this PR is closed, and that login_name appears to have been marked as non-sensitive in response to this issue. However, I'm on v0.79.1 and am seeing that every single snowflake_role_grant has the "users" field marked as sensitive. I'd consider this issue to very much still be open as I am currently unable to properly administer role grants via TF... every grant change is a "yolo apply".
