### ISSUE TITLE
Add Support for Dynamic Tables

### ISSUE THREAD

**Issue by heyhughes** [Snowflake-Labs/terraform-provider-snowflake#1922]
Description:
I would like to request the addition of the Dynamic Table to the Snowflake provider in Terraform. Currently, as of version 0.67.0, this object type is not supported by the provider. Dynamic tables in Snowflake are a new table type that lets you define the result of your data pipelines declaratively. This means that you can define the transformation steps in SQL, and Snowflake will automatically refresh the dynamic table as the data changes. Dynamic Table Snowflake documentation: [Dynamic Table](https://docs.snowflake.com/en/sql-reference/commands-table#dynamic-table).

Solution:
I would suggest the following:
- Add "CREATE DYNAMIC TABLE" to `snowflake_schema_grant` - This will allow the provider to add this privilege on schemas.
- Create `snowflake_dynamic_table` - This will be similar to `snowflake_view` which will allow the user to input the SQL for the table as well as the LAG. 
- Create `snowflake_dynamic_table_grant` - For grants, just like all of your other "snowflake_<obj type>_grant" resources.  

Alternatives Considered:
As an alternative, users can manually grant and create these objects. However, as Dynamic Tables usage grows, Terraform Provider users would like to see this added. At a minimum adjust the `snowflake_schema_grant` to allow existing Terraform add this privilege to existing deployments.

Additional Context:
Please note that the dynamic tables are still in public preview.

**Comment by sfc-gh-swinkler** [comment]
@heyhughes I agree, this is a great suggestion. We intend to support all resources that the Snowflake API support. The current goal is to have this implemented within the next 3 months, although hopefully, it will be even sooner.

**Comment by sfc-gh-asawicki** [comment]
Hey @heyhughes.

Dynamic tables were introduced in #2104 (released in [v0.74.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.74.0)). Please feel free to start using them and provide feedback if you happen to encounter any bugs/missing features.

**Comment by LukasSandm** [comment]
@sfc-gh-asawicki thank for adding dynamic tables. When can we expect to have support for dynamic table grants added to the provider?

**Comment by heyhughes** [comment]
@LukasSandm I was able to use the "snowflake_grant_privileges_to_role" resource to grant access to Dynamic tables. 
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role

**Comment by LukasSandm** [comment]
@heyhughes thanks for sharing! Unfortunately though I need to grant privileges on dynamic tables to shares, and not to roles. So this does not work IIUC, but still good to know.

**Comment by sfc-gh-jcieslak** [comment]
Hey @LukasSandm 
Afaik, what you are referring to is not possible on Snowflake (see the docs https://docs.snowflake.com/en/sql-reference/sql/grant-privilege-share#syntax). Closing the issue as the main goal was achieved. If you're missing anything else, please create another GitHub issue. Lately, we did a grants redesign which introduced new grant resources to cover all grant capabilities of Snowflake:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)
