### ISSUE TITLE
snowflake_grants data source returns incomplete important information

### ISSUE THREAD

**Issue by inotopsdata** [Snowflake-Labs/terraform-provider-snowflake#1925]
**Provider Version**

0.55.1, 0.67.0

**Terraform Version**

1.3.1,  1.5.2

**Describe the bug**

When using snowflake_grants data source -> https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants used with "grants_to { user = <username> }"
which triggers in the back towards snowflake "SHOW GRANTS TO USER <username>" does not return the ROLE names granted. "name", "privilege" and "granted_on" attributes are always returned empty <"">

**Expected behavior**

I would expect the "name" attribute to always be filled in OR return the ROLE column visible when running the respective command in snowflake

**Code samples and commands**

variable "checked_user" {
    type=string
}

data "snowflake_grants" "grants_to" {
  grants_to {
    user = var.checked_user
  }
}

output "user_current_grants" {
    value = data.snowflake_grants.grants_to.grants[*] 
}

###### output
+ user_current_grants = [
              + {
                  + created_on   = "2022-12-16T12:00:33.878Z"
                  + grant_option = false
                  + granted_by   = "USERADMINXX"
                  + granted_on   = ""
                  + granted_to   = "USER"
                  + grantee_name = "TEST_USER"
                  + name         = ""
                  + privilege    = ""
                },
              + {
                  + created_on   = "2021-09-13T16:26:47.56Z"
                  + grant_option = false
                  + granted_by   = "USERADMINXX"
                  + granted_on   = ""
                  + granted_to   = "USER"
                  + grantee_name = "TEST_USER"
                  + name         = ""
                  + privilege    = ""
                },
              + {
                  + created_on   = "2023-03-13T08:57:40.733Z"
                  + grant_option = false
                  + granted_by   = "USERADMINXX"
                  + granted_on   = ""
                  + granted_to   = "USER"
                  + grantee_name = "TEST_USER"
                  + name         = ""
                  + privilege    = ""
                },

**Additional context**

NO

**Comment by sfc-gh-swinkler** [comment]
@inotopsdata, we need to investigate the issue further and report back to you. Thank you for your patience.

**Comment by sfc-gh-asawicki** [comment]
Hey @inotopsdata. `snowflake_grants` was redesigned and reimplemented. We have released it as part of v0.88.0 release yesterday. Please check if the error is still present in the newest version.

**Comment by sfc-gh-asawicki** [comment]
Closing as fixed. Please open a new issue if the problem persists in the newest provider version.
