### ISSUE TITLE
Streamlit

### ISSUE THREAD

**Issue by JohnCalhoun** [Snowflake-Labs/terraform-provider-snowflake#1933]
**Is your feature request related to a problem? Please describe.**
Support for Streamlit in snowflake

I want to create streamlit app in snowflake

**Describe the solution you'd like**
A streamlit resource

**Describe alternatives you've considered**

**Additional context**

**Comment by sfc-gh-swinkler** [comment]
I agree this is a good feature request and one that we plan to implement in the coming quarter.

**Comment by danielhstahl** [comment]
Is there any updated ETA on this feature?

**Comment by sfc-gh-asawicki** [comment]
Hey @danielhstahl.

We will share our roadmap soon. Despite what was written above, we will start work on it no earlier than February/March.

**Comment by ric-sylvera** [comment]
Correct me if I'm wrong but I think it would be as simple as this?
```diff
diff --git a/pkg/resources/grant_helpers.go b/pkg/resources/grant_helpers.go
index df015d0f..27677faf 100644
--- a/pkg/resources/grant_helpers.go
+++ b/pkg/resources/grant_helpers.go
@@ -425,6 +425,7 @@ func ValidGrantedObjectType() schema.SchemaValidateDiagFunc {
 		sdk.ObjectTypeTag.String(),
 		sdk.ObjectTypeStage.String(),
 		sdk.ObjectTypeStream.String(),
+		sdk.ObjectTypeStreamlit.String(),
 		sdk.ObjectTypeTable.String(),
 		sdk.ObjectTypeExternalTable.String(),
 		sdk.ObjectTypeTask.String(),
@@ -455,6 +456,7 @@ func ValidGrantedPluralObjectType() schema.SchemaValidateDiagFunc {
 			sdk.PluralObjectTypeTags.String(),
 			sdk.PluralObjectTypeStages.String(),
 			sdk.PluralObjectTypeStreams.String(),
+			sdk.PluralObjectTypeStreamlits.String(),
 			sdk.PluralObjectTypeTables.String(),
 			sdk.PluralObjectTypeExternalTables.String(),
 			sdk.PluralObjectTypeTasks.String(),
```

**Comment by sfc-gh-jmichalak** [comment]
Hi @JohnCalhoun @danielhstahl @ric-sylvera 👋 Streamlits have been added in [v0.94](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.94.0) release. Please follow our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v0930--v0940).

**Comment by sfc-gh-asawicki** [comment]
Closing as completed.
