### ISSUE TITLE
Failed to `terraform plan` snowflake_file_format on 0.68.0

### ISSUE THREAD

**Issue by rjminchuk** [Snowflake-Labs/terraform-provider-snowflake#1934]
**Provider Version**

0.68.0

**Terraform Version**

1.5.2

**Describe the bug**

> Planning failed. Terraform encountered an error while generating this plan.
> 
> ╷
> │ Warning: Deprecated Resource
> │ 
> │   with module.snowflake.snowflake_schema_grant.grant,
> │   on .terraform/modules/snowflake/role.tf line 47, in resource "snowflake_schema_grant" "grant":
> │   47: resource "snowflake_schema_grant" "grant" {
> │ 
> │ This resource is deprecated and will be removed in a future major version
> │ release. Please use snowflake_grant_privileges_to_role instead.
> │ 
> │ (and 70 more similar warnings elsewhere)
> ╵
> ╷
> │ Error: cannot read file format: object does not exist or not authorized
> │ 
> │   with module.snowflake.snowflake_file_format.this,
> │   on .terraform/modules/snowflake/main.tf line 20, in resource "snowflake_file_format" "this":
> │   20: resource "snowflake_file_format" "this" {
> │ 
> ╵

**Expected behavior**

I expect TF not to fail to plan on a minor version change of the provider module. This error does not occur in v.0.67.0, and I have pinned my usage of the provider to that for now.

**Code samples and commands**

```
resource "snowflake_database" "this" {
  name                        = local.database_name
  comment                     = "Database for ${local.database_name}"
  data_retention_time_in_days = var.data_retention_time_in_days
}

resource "snowflake_schema" "this" {
  name     = local.schema_name
  database = snowflake_database.this.name
}

resource "snowflake_file_format" "this" {
  database                       = snowflake_database.this.name
  format_type                    = "CSV"
  name                           = local.format_name
  schema                         = snowflake_schema.this.name
  compression                    = "AUTO"
  null_if                        = ["\\N", "NUL", "NULL", "\u0000"]
  field_delimiter                = ".=@=|"
  record_delimiter               = "|=@=."
  time_format                    = "AUTO"
  timestamp_format               = "AUTO"
  binary_format                  = "UTF8"
  date_format                    = "AUTO"
  encoding                       = "UTF8"
  escape                         = "NONE"
  escape_unenclosed_field        = "NONE"
  field_optionally_enclosed_by   = "NONE"
  trim_space                     = false
  error_on_column_count_mismatch = true
  skip_byte_order_mark           = false
  replace_invalid_characters     = false
  empty_field_as_null            = true
  skip_blank_lines               = true
  skip_header                    = 0
  lifecycle {
    ignore_changes = [
      null_if,
    ]
  }
}
```

**Additional context**

I have a rather interesting setup using terragrunt that I'd rather not get into.. but it seems strange that a resource that existed before could not be referenced in the plan..

**Comment by sfc-gh-ngaberel** [comment]
Hi @rjminchuk can you share the sql query that was generated by the provider? You should be able to find in the activity tab in snowsight.

**Comment by sfc-gh-ngaberel** [comment]
I suspect this ID check does not match any of the result, it could be due to different capitalization.
https://github.com/Snowflake-Labs/terraform-provider-snowflake/commit/2596990808d97a7b98fa459a74eb7a77edf25cd5#diff-7e89fb0973fe2d7e7a859868ae043401a033d6e4af4a3b0a3d8edbce43c2af44R662-R664

**Comment by rjminchuk** [comment]
I see the following. prehaps it's missing the `in schema ...` part?

```
SHOW FILE FORMATS LIKE 'MY_FORMAT'
SHOW FILE FORMATS LIKE 'MY_FORMAT'
SHOW FILE FORMATS LIKE 'MY_FORMAT' IN SCHEMA "MY_DB"."MY_SCHEMA"
```

**Comment by rjminchuk** [comment]
The users I'm running these terraform plan commands with is a generic user for all my Snowflake DBs. IE: it doesn't have a default DB/schema. I would imagine those commands would return either: nothing, or fail. and these queries are all showing as EXECUTION_STATUS  SUCCESS,.. IE: returns nothing, and my plan fails

**Comment by mddataminr** [comment]
I have a similar issue that I closed when I saw this one. https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1935

I think its related to how the provider is reading the file formats. 

This is because it attempts to read it using SHOW FILE FORMATS LIKE 'JSON'.

Previous versions emit SHOW FILE FORMATS LIKE 'JSON' IN SCHEMA "DATABASE"."SCHEMA"

**Comment by sfc-gh-ngaberel** [comment]
Thanks for the feedback both, I think you're right, the `IN SCHEMA ...`part should be present. Can you both confirm that running the queries with `IN SCHEMA "MY_DB"."MY_SCHEMA"` returns expected results in the UI?
I'll prepare a fix now.

**Comment by mddataminr** [comment]
Yeah I verified the results for both with and without

**Comment by sfc-gh-ngaberel** [comment]
v0.68.1 is being released right now with the fix.

**Comment by rjminchuk** [comment]
that did the trick. Thanks @sfc-gh-ngaberel!
