### ISSUE TITLE
snowflake_stage_grant is deprecated, use snowflake_grant_privileges_to_role instead 

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1939]
**Provider Version**

```
$ terraform version
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.68.1
```

**Terraform Version**

```
$ terraform version
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.68.1
```

**Describe the bug**

If you use a ` snowflake_stage_grant` resource, you'll get `This resource is deprecated and will be removed in a future major version release. Please use snowflake_grant_privileges_to_role instead.`. 

But the docs for `snowflake_grant_privileges_to_role` don't mention anything about how to migrate a stage grant. In fact, the word `stage` isn't even preset at all in the docs for this resource. I would expect it to be listed as part of the docs for `on_account_object.object_type` and/or `on_schema_object.object_type`, both of which mention valid object types:

> Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP

**Expected behavior**

I expect migration from `snowflake_stage_grant` to `snowflake_grant_privileges_to_role` should be possible and the migration path should be documented with examples.

**Code samples and commands**

Resource:
```
resource "snowflake_stage_grant" "application_snowflake_import_export" {
  count         = var.use_snowflake ? 1 : 0
  database_name = snowflake_database.default[0].name
  schema_name   = snowflake_schema.application[0].name
  roles = [
    snowflake_role.role[0].name,
    snowflake_role.staff_read_write[0].name,
    snowflake_role.staff_read_only[0].name
  ]
  privilege  = "USAGE"
  stage_name = snowflake_stage.application_snowflake_import_export[0].name
}
```

Error:
```
This resource is deprecated and will be removed in a future major version release. Please use snowflake_grant_privileges_to_role instead.
```

**Additional context**

https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1929

This commented-out part caught my attention, though it ultimately may or may not be relevant, I'm not sure: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1929/files#diff-e46e7bc05f7265aedd2b7f67fb22068c4c3afda04d00f9f2c52762eb8375ba53R180-R182

**Comment by jakeberesford-palmetto** [comment]
I was about to report the same issue for `snowflake_pipe_grant`. Would the maintainers prefer to handle this in one issue, or should I create a separate issue for this?

**Comment by sfc-gh-swinkler** [comment]
This is a documentation issue, which was fixed in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1941, and will be corrected in the next release. The `snowflake_grant_privileges_to_role` resource does support pipes and stages, even now. I will go ahead and close this issue. If you would like to further the conversation, please comment in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1949, which will be used to consolidate these sorts of issues. Thank you!
