### ISSUE TITLE
Deprecated resource types should be documented

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1940]
**Provider Version**

```
$ terraform version
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.68.1
```

**Terraform Version**

```
$ terraform version
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.68.1
```

**Describe the bug**

The following resource types have been deprecated and will produce a deprecation warning if you try to use them:
- `snowflake_account_grant`
- `snowflake_function_grant`
- `snowflake_procedure_grant`
- `snowflake_schema_grant`
- `snowflake_stage_grant`
- `snowflake_table_grant`
- `snowflake_view_grant`
- `snowflake_warehouse_grant`
- (and maybe others too, these are just the ones which we are using)

If you try to use them, you'll get an error like this:

```
This resource is deprecated and will be removed in a future major version release. Please use snowflake_grant_privileges_to_role instead.
```

Deprecating resources is fair enough, but there is no deprecation warning on the docs page for those deprecated resources. This could cause a new user to stumble upon one of those resources as they browse the docs, then only after they do the work of adding one of those resources to their code and running `terraform plan` would they see that those resources are deprecated.

**Expected behavior**

Deprecated resources should have a note in the docs page for each resource which states that the resource is deprecated, preferably with a link to the new resource which should be used instead.

**Code samples and commands**

Try to use any of the above resources in any fashion, run `terraform plan` on v0.68.1 or higher, and notice the deprecation warning. 

**Additional context**

https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1929

**Comment by sfc-gh-swinkler** [comment]
@jrobison-sb Thank you for bringing this to our attention, and I agree -- we will upgrade the documentation alerting the user that the resources are deprecated. I have also upgraded the [terraforming snowflake](https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#0) documentation to use the new resource.

**Comment by milanrm** [comment]
Hi @sfc-gh-swinkler or anyone, I have some queries regarding the new resource `snowflake_grant_privileges_to_role` 

1.  how do we enable the  attribute `enable_multiple_grants` as true in the new resource? ( I was using this in many deprecated grant resources)
2. In the new resource, is there a way I can give multiple role names as list?

I would be really grateful, if you can point me to some documentation to migrate the exiting grants to the new resource smoothly.  You can see a sample  grant below with the deprecated resource

```

resource "snowflake_database_grant" "full_db_grant" {
  provider               = snowflake.security_admin
  **enable_multiple_grants = true**
  for_each               = local.db_privilege_map
  database_name          = split("|", snowflake_database.database[replace(each.value.database, "${local.env}_", "")].id)[0]
  privilege              = each.value.privilege
  **roles                  = [snowflake_role.de_role.name, "DBT_CONTROL_ROLE"]**
  depends_on             = [snowflake_database.database]
}
```

**Comment by sfc-gh-jcieslak** [comment]
Hey @jrobison-sb 👋 
In the latest versions, we added deprecated resources and their counterparts in our documentation ([here](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs#currently-deprecated-resources)). We also added deprecation messages to the resource's subpages ([example](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account_grant)). That being said I think we can close this one, right?

**Comment by jrobison-sb** [comment]
@sfc-gh-jcieslak yeah, LGTM. thanks for updating these docs.
