### ISSUE TITLE
Warehouse creation not working for 0.67.

### ISSUE THREAD

**Issue by BojanValcon** [Snowflake-Labs/terraform-provider-snowflake#1944]
**Provider Version**

0.6.7

**Describe the bug**

Hello,  I am trying to create a warehouse through terraform but i get the error message: 

Error: 001423 (22023): SQL compilation error:
│ invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled

This should not be the case at all since the enable_query_acceleration is set to false. 
I have tried multiple version of this, with both the enable_query_acceleration set to true and false, with and without the query_acceleration_max_scale_factor variable being set. Could you please check this? 

Regards,
Bojan

**Comment by forest** [comment]
Having the same issue. I did not change provider versions so wondering if something changed on the Snowflake API side.

If `enable_query_acceleration` is false then maybe `query_acceleration_max_scale_factor` should not be passed to Snowflake. I tried setting `query_acceleration_max_scale_factor = 0` and that didn't work either.

**Comment by forest** [comment]
Duplicate: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1474

**Comment by BojanValcon** [comment]
@forest what is the actual solution? I am struggling to see as it still requires me to provide both parameters when defining the warehouse. Thanks.

**Comment by fcarlislehg** [comment]
I upgrade the provider to `v0.68.1` and it worked for me. The provider now checks if this feature exists on your account, for Standard account it does not, and then doesn't send these params if they are not supported.

**Comment by forest** [comment]
I upgrade the provider to v0.68.1 and it worked for me. The provider now checks if this feature exists on your account, for Standard account it does not, and then doesn't send these params if they are not supported.

**Comment by BojanValcon** [comment]
Yes mate sorry i checked it later with the new versions, forgot to update it... It works now. Thanks a lot @forest !
