### ISSUE TITLE
snowflake_grant_privileges_to_role - Example Usage Conflicts With Documentation

### ISSUE THREAD

**Issue by sl-tarvin** [Snowflake-Labs/terraform-provider-snowflake#1949]
**Provider Version**
version = "0.68.1"

**Terraform Version**
Terraform v1.5.2 on windows_amd64

**Describe the bug**

Please update provider documentation for the `snowflake_grant_privileges_to_role`.  Running `terraform plan` throws: 

```
Warning: Deprecated Resource
with snowflake_table_grant.table_grants,
│   on main.tf line 190, in resource "snowflake_table_grant" "table_grants":
│  190: resource "snowflake_table_grant" "table_grants" {
│
│ This resource is deprecated and will be removed in a future major version release. Please use snowflake_grant_privileges_to_role instead.
```

There is conflicting information in the documentation for the Snowflake Provider Resource `snowflake_grant_privileges_to_role`. Example usage seems to support table privilege assignment to roles but it is unclear how to accomplish table level privilege assignment.

[Documentation Source](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#on_account_object)

Example Usage in Documentation
```
# all in schema
resource "snowflake_grant_privileges_to_role" "g12" {
  privileges = ["SELECT", "INSERT"]
  role_name  = snowflake_role.r.name
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_schema          = "\"my_db\".\"my_schema\"" # note this is a fully qualified name!
    }
  }
}

# future in database
resource "snowflake_grant_privileges_to_role" "g13" {
  privileges = ["SELECT", "INSERT"]
  role_name  = snowflake_role.r.name
  on_schema_object {
    future {
      object_type_plural = "TABLES"
      in_database        = snowflake_database.d.name
    }
  }
}
```

**Expected behavior**
Valid values indicated by documentation:

```
object_type (String) The object type of the schema object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP
```

**Code samples and commands**
The example usage code references `TABLES` which does not appear supported based on documentation.
```
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_schema          = "\"my_db\".\"my_schema\"" # note this is a fully qualified name!
    }
  }
```

**Comment by sfc-gh-ckite** [comment]
I've submitted PR #1941 to update the documentation

**Comment by sfc-gh-swinkler** [comment]
This resource does support table objects, the documentation is wrong.  @sfc-gh-ckite thank you for updating the documentation. I have merged your PR and it will be available in the next release. @sl-tarvin please let me know if there is anything else I can help with.
