### ISSUE TITLE
external_table_grant deprecated, but doesn't have support in snowflake_grant_privileges_to_role 

### ISSUE THREAD

**Issue by danu165** [Snowflake-Labs/terraform-provider-snowflake#1952]
**Provider Version**

0.68.1

**Terraform Version**

1.0.8

**Describe the bug**

This pull requested deprecated the ExternalTableGrant: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1929/files#diff-c7dc3edb296af39a8681c412f574df7fb6e74e357cfb135a27f23cc6096df462

However, based on the updated docs in this pull request, there is no support for External Tables with `snowflake_grant_privileges_to_role`: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1941

**Expected behavior**

External Tables should be supported in `snowflake_grant_privileges_to_role`

**Comment by jacobcbeaudin** [comment]
I would like to add that I am also experiencing this. I am getting the following error.
```
Error: expected on_schema_object.0.all.0.object_type_plural to be one of [ALERTS EVENT TABLES FILE FORMATS FUNCTIONS PROCEDURES SECRETS SEQUENCES PIPES MASKING POLICIES PASSWORD POLICIES ROW ACCESS POLICIES SESSION POLICIES TAGS STAGES STREAMS TABLES TASKS VIEWS MATERIALIZED VIEWS], got EXTERNAL TABLES
```

**Comment by sfc-gh-swinkler** [comment]
Thank you for reporting this error.  I looked into this, and it was a bug that resulted from `"EXTERNAL_TABLE" != "EXTERNAL TABLE"`.  I created a PR, which will be merged and available by the next release.  Thank you again for your patience.
