### ISSUE TITLE
snowflake_account resources can now be deleted

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1973]
**Provider Version**

```
$ terraform version
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.67.0
```

**Terraform Version**

```
$ terraform version
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.67.0
```

**Describe the bug**

At the time when the `snowflake_account` resource was first added to this provider, presumably [it wasn't possible to delete accounts](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/account.go#L372-L374) by way of the API. The only option was to delete accounts by way of a support ticket.

It has now become possible to `DROP ACCOUNT`, so the provider should support this.
https://docs.snowflake.com/en/release-notes/2023-07#deleting-an-account-self-service-preview
https://docs.snowflake.com/en/user-guide/organizations-manage-accounts-delete

**Expected behavior**

You should be able to delete an account using Terraform.

**Comment by sfc-gh-swinkler** [comment]
@jrobison-sb thank you for sharing this information. I have made a note of your feature request, and we will implement it when we have resources available.

**Comment by ben-wilson-peak** [comment]
> @jrobison-sb thank you for sharing this information. I have made a note of your feature request, and we will implement it when we have resources available.

Hey @sfc-gh-swinkler, is there any movement internally on this feature? We note that the deletion API requires a grace period, which would need to be either hard coded in the provider (not that desirable) or defaulted and overridable as a param in the resource itself.

**Comment by sfc-gh-asawicki** [comment]
Hey @ben-wilson-peak. Yes, there is an open PR #2065 that supports account dropping.

**Comment by ben-wilson-peak** [comment]
> Hey @ben-wilson-peak. Yes, there is an open PR #2065 that supports account dropping.

Amazing thank you for the heads up, totally missed that!

**Comment by jrobison-sb** [comment]
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2065
