### ISSUE TITLE
Can't bump provider version due to error: Incompatible provider version

### ISSUE THREAD

**Issue by myshon** [Snowflake-Labs/terraform-provider-snowflake#1976]
**Provider Version**

0.68.1

**Terraform Version**

1.5.3

**Describe the bug**

I had used snowflake terraform provider 0.56. Recently I bumped up provider to 0.68.1. Then, terraform init throws error: 

```
Initializing provider plugins...

- Finding snowflake-labs/snowflake versions matching "~> 0.68.1"...

- Finding hashicorp/aws versions matching "~> 5.0"...

- Installing hashicorp/aws v5.9.0...

- Installed hashicorp/aws v5.9.0 (signed by HashiCorp)

╷

│ Error: Incompatible provider version

│

│ Provider [registry.terraform.io/snowflake-labs/snowflake](https://registry.terraform.io/snowflake-labs/snowflake) v0.68.2 does not have a package available for your current platform, windows_386.

│

│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

╵
```

I tried terraform init -upgrade but it didn't help. 

**Expected behavior**

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

Machine: x64 / Windows 10 Enterprise.

**Comment by myshon** [comment]
Any update? 🤔

**Comment by sfc-gh-swinkler** [comment]
@myshon there is now a windows 386 build for the provider as of 0.70.1
