### ISSUE TITLE
snowflake v0.68.2 does not have a package available for your current platform, windows_386.

### ISSUE THREAD

**Issue by baabaakz** [Snowflake-Labs/terraform-provider-snowflake#1985]
**Provider Version**

snowflake v0.68.2

**Terraform Version**

Terraform v1.5.4
on windows_386

**Describe the bug**

When I run terraform init I get this error:
 Error: Incompatible provider version Provider registry.terraform.io/snowflake-labs/snowflake v0.68.2 does not have a package available for your current platform, windows_386.

Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

**Expected behavior**

To use the provider without issues

**Code samples and commands**

terraform {
  cloud {
    organization = "avalonhcs"
    hostname     = "app.terraform.io"
    workspaces {
      name = "uat-lvm-snowflake-dwh"
    }
  }
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.68"
    }
  }
}

**Comment by sfc-gh-asawicki** [comment]
Hey @baabaakz.

386 builds were added back in #2038 (released in [v0.70.1](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.70.1)). Please upgrade to this version.

**Comment by sfc-gh-asawicki** [comment]
@baabaakz can we close the issue?

**Comment by baabaakz** [comment]
Yes. Thank you
