### ISSUE TITLE
Insert Row data Using a Query in snowflake using terraform

### ISSUE THREAD

**Issue by kushal1313** [Snowflake-Labs/terraform-provider-snowflake#1987]
**Is your feature request related to a problem? Please describe.**
Yes, if we want to do automation of inserting data in a table, we can use this option.

There is a requirement to insert row data in a snowflake table, and i almost tried all the options available from the last 1 week, and need help in this scenario.
Example:
INSERT INTO mytable (id, name, age)
VALUES (1, 'John Doe', 30);
this is one of a similar example which i want to run using terraform.

**Describe the solution you'd like**
May be any resource module, where we can run sql or python scripts.

**Describe alternatives you've considered**
No alternatives found as for now.

**Comment by sfc-gh-asawicki** [comment]
Hey @kushal1313. Thanks for reporting the issue.

We have introduced [snowflake_unsafe_execute](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute) resource in [v0.77.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.77.0) release. Does it fit your needs?

**Comment by sfc-gh-asawicki** [comment]
Hey @kushal1313 , I will close this issue, because of the inactivity and because the unsafe resource is currently usable in such a scenario.
