### ISSUE TITLE
Documentation for snowflake_file_format_grant has wrong import

### ISSUE THREAD

**Issue by WojtekWaga** [Snowflake-Labs/terraform-provider-snowflake#1994]
**0.68.2**

The provider version you are using.

**1.3.7**

The version of Terraform you were using when the bug was encountered.

**Describe the bug**

Documentation for snowflake_file_format_grant specifies import clause as:

# format is database_name|schema_name|file_format_name|privilege|with_grant_option|on_future|roles
terraform import snowflake_file_format_grant.example "MY_DATABASE|MY_SCHEMA|MY_FILE_FORMAT|USAGE|false|false|role1,role2'

whereas the command requires one more attribute. I believe the documentation should read:

# format is database_name|schema_name|file_format_name|privilege|with_grant_option|on_future|on_all|roles
terraform import snowflake_file_format_grant.example "MY_DATABASE|MY_SCHEMA|MY_FILE_FORMAT|USAGE|false|false|false|role1,role2'

**Comment by chrisweis** [comment]
This issue seems to also apply to the import example in [grant_privileges_to_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#import).

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
Sorry, but closing, as the ticket is about the deprecated resource which we are not supporting. If you still need to upgrade to the latest provider versions, please refer to the [upgrading guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) and [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md).
