### ISSUE TITLE
Task cannot be updated to remove "when"

### ISSUE THREAD

**Issue by shellderp** [Snowflake-Labs/terraform-provider-snowflake#2036]
**Provider Version**

0.70.0

**Terraform Version**

v1.2.4

**Describe the bug**

```
│ Error: error updating when condition on task
````

**Expected behavior**

The task should be recreated with no `when` condition. In Terraform this could be implemented as "forces replacement"

**Code samples and commands**

For example, apply the following

```
resource "snowflake_task" "task" {
  name          = "sample"
  sql_statement = "..."
  when    = "system$stream_has_data('sample_stream')"
  enabled = true
}
```

Then change it to this and apply again

```
resource "snowflake_task" "task" {
  name          = "sample"
  sql_statement = "..."
  enabled = true
}
```

**Additional context**

Adding a `when` condition to a task without the `when` does already work.

**Comment by sfc-gh-asawicki** [comment]
Hey @shellderp. Thanks for creating the ticket.

The problem comes from a gap in the `ALTER TASK` statement (currently, there is no way to `UNSET` it - other than dropping and recreating). Setting `when` to `TRUE` should work as a workaround when clearing `when` like in the example.

**Comment by sfc-gh-asawicki** [comment]
@shellderp can you confirm it works?

**Comment by shellderp** [comment]
it works to drop and recreate, yes

**Comment by sfc-gh-asawicki** [comment]
Changed the behavior in #2479 (conditional forceNew).

**Comment by sfc-gh-asawicki** [comment]
Closing the issue because it was fixed. @shellderp please create a new one if you encounter the bad behavior in the newest provider version.
