### ISSUE TITLE
snowflake_grant_privileges_to_role listed example doesn't seem to work

### ISSUE THREAD

**Issue by Bryan-Meier** [Snowflake-Labs/terraform-provider-snowflake#2044]
**Provider Version**
0.69.0

**Terraform Version**
1.3.5

**Describe the bug**
The below example is listed on the documentation (https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role)

```
# all in database
resource "snowflake_grant_privileges_to_role" "g11" {
  privileges = ["SELECT", "INSERT"]
  role_name  = snowflake_role.r.name
  on_schema_object {
    all {
      in_database = snowflake_database.d.name
    }
  }
}
```

From everything I have tried, this doesn't seem to work. If this isn't how the resource works now, could we get the documentation updated?

**Expected behavior**

For the code to run without errors

**Code samples and commands**

**Additional context**

**Comment by Bryan-Meier** [comment]
@florencewambui, it doesn't seem to change anything. I tried it with and without the provider attribute and got the same results. I am guessing that it worked in 0.68 and the functionality was changed or removed in 0.69+ versions. I can't even do a "terraform validate" without getting syntax errors.
```
PS C:\terraform\> terraform validate
╷
│ Error: Missing required argument
│
│   on main.tf line 367, in resource "snowflake_grant_privileges_to_role" "g11":
│  367:     all {
│
│ The argument "object_type_plural" is required, but no definition was found.
```

**Comment by systematics78** [comment]
Also then granting ownership privilege there no option to provide COPY/REVOKE CURRENT GRANTS

**Comment by Bryan-Meier** [comment]
@systematics78 I agree. I haven't seen the implementation of the COPY/REVOKE CURRENT GRANTS in any resource that deals with the OWNERSHIP privilege. This is basically mandatory in order to change ownership on existing objects.

**Comment by jshields** [comment]
I get the same error. It seems the "all in database" functionality is what doesn't work. The documentation is wrong, or the code needs to support what the documentation says.
```
│ Error: Missing required argument
│ 
│   on redacted.tf line 326, in resource "snowflake_grant_privileges_to_role" "redacted":
│  326:     all {
│ 
│ The argument "object_type_plural" is required, but no definition was found.
```

I was able to get mine working by limiting the scope of the grants to one object type, in my case tables. Another resource block would be needed for another type like views.
```
...
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_database = "..."
    }
  }
...
```

**Comment by KarthikRajashekaran** [comment]
Can someone please provide example to replace `snowflake_table_grant` to  `snowflake_grant_privileges_to_role`  to grant table privileges SELECT to share 

```
   7: resource "snowflake_table_grant" "grant" {
│
│ This resource is deprecated and will be removed in a future major version release. Please use snowflake_grant_privileges_to_role instead.
│
```

**Comment by sfc-gh-jcieslak** [comment]
Hey, soon we should have a migration guide in our MIGRATION.md document on how to migrate old grant resources to new ones.

**Comment by sfc-gh-jcieslak** [comment]
Hey @Bryan-Meier, could you confirm the doc fix was provided and close the issue?

**Comment by Bryan-Meier** [comment]
The doc update looks good. Thank you for this!
