### ISSUE TITLE
Handle PARSE_HEADER option for file_format resource

### ISSUE THREAD

**Issue by adrian-damaschin** [Snowflake-Labs/terraform-provider-snowflake#2050]
**Is your feature request related to a problem? Please describe.**

We are trying to implement a new file format to be able to read CSV headers for stage objects in snowflake. For this we need a file format with PARSE_HEADER = true.

**Describe the solution you'd like**

Add support for PARSE_HEADER attribute on file_format  resource

**Describe alternatives you've considered**

The only alternative is to define this format manually which is not acceptable on our standards

**Additional context**

![Screenshot 2023-09-08 at 15 00 52](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/24243437/84954008-0b14-408a-ad87-60832929e147)

**Comment by sfc-gh-asawicki** [comment]
Added with #2132. Closing.
