### ISSUE TITLE
OWNERSHIP can only be transferred error on destruction of snowflake_grant_privileges_to_role resource

### ISSUE THREAD

**Issue by liamjamesfoley** [Snowflake-Labs/terraform-provider-snowflake#2084]
**Provider Version**
0.71

**Terraform Version**
1.5.2

**Describe the bug**
https://docs.snowflake.com/en/sql-reference/sql/grant-ownership
Destruction of `snowflake_grant_privileges_to_role` produces that a query that will always fail.

<img width="692" alt="image" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/4086743/2098de34-b902-4dfb-a095-7db85bdcfd2c">

**Expected behavior**
This is happening in a managed access schema module I'm working on, so TBH, I don't care as long as the resource destruction happens without using `terraform state rm` b/c I'm also destroying the schema, but ownership should probably go to `ACCOUNTADMIN`?

Since `snowflake_schema_grant` is being deprecated the new resource should have something similar to [revert_ownership_to_role_name](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/schema_grant#revert_ownership_to_role_name).
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/schema_grant.go#L106-L114

**Code samples and commands**

Resource:
```
resource "snowflake_grant_privileges_to_role" "owner_schema_grant" {
  # `GRANT OWNERSHIP ON SCHEMA ${schema_identifier} TO ROLE ${owner_role};`,
  role_name  = snowflake_role.owner_role.name
  privileges = ["OWNERSHIP"]
  on_schema {
    schema_name = "${var.db_name}.${snowflake_schema.schema.name}"
  }
  with_grant_option = true
}
```

**Comment by imre-kerr-sb1** [comment]
We also have issues with ownership grants. For now we are using the following workaround:

```terraform
data "snowflake_current_role" "current" {}

resource "snowsql_exec" "owner_schema_grant" {
  name = "owner_schema_grant"

  create {
    statements           = "GRANT OWNERSHIP ON SCHEMA ${schema_identifier} TO ROLE ${snowflake_role.owner_role.name};"
    number_of_statements = 1
  }

  read {
    statements           = "SHOW GRANTS ON SCHEMA ${schema_identifier};"
    number_of_statements = 1
  }

  delete {
    statements           = "GRANT OWNERSHIP ON SCHEMA ${schema_identifier} TO ROLE ${data.snowflake_current_role.current.name};"
    number_of_statements = 1
  }
}
```

**Comment by entechlog** [comment]
Having the same error. When we try to change the owner using snowflake_grant_privileges_to_role resource the plan runs fine but apply fails with below error.

Error: error revoking privileges from account role: exactly one of AllPrivileges, GlobalPrivileges, AccountObjectPrivileges, SchemaPrivileges, or SchemaObjectPrivileges must be set

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing, as the issue was about the deprecated/not allowed functionality. Recently, we released [a new grant resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership) which is capable of granting ownership. Please, give it a try. If there will be any issues with it, create another GitHub issue. Also, please check our [technical documentation section](https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/main/docs/technical-documentation) where you can find a migration guide that can help you with upgrading to the latest grant resources and our newly added design decision doc (regarding new grant resources).
