### ISSUE TITLE
Snowflake view with no reference table

### ISSUE THREAD

**Issue by snowflakecausr** [Snowflake-Labs/terraform-provider-snowflake#2085]
**Provider Version**

The provider version you are using.

**Terraform Version**

The version of Terraform you were using when the bug was encountered.

**Describe the bug**

Running Terraform fmt on snowflake_view with no table reference will crash and return code 3

**Expected behavior**

Creation of a view without table reference should be possible

**Code samples and commands**

  statement  = <<-SQL
    SELECT NULL AS TYPE;
SQL

**Additional context**

**Comment by sfc-gh-jcieslak** [comment]
Hey @snowflakecausr  👋
Yesterday, we released a new provider version ([v0.95.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.95.0)) that contains many upgrades to views. Please upgrade using the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) and let us know if you observe the same issues. If yes, please upload logs from the `terraform apply` with `TF_LOG=DEBUG` environment variable set.
