### ISSUE TITLE
Feature request: Enable multiple grant resources for the same privilege

### ISSUE THREAD

**Issue by dstuck** [Snowflake-Labs/terraform-provider-snowflake#210]
I wanted to create a ticket to discuss what it would take to enable granting privileges to the same snowflake object in multiple resources.

Currently this limitation is blocking the ability to use submodules since all roles need to have permissions granted in one place. It also limits the ability to write code in a logically separated way. For example we want to create a local sysadmin that will be used to create some schemas and then add roles for accessing those schemas, but we have to create all roles and grant db usage up front, then create the schemas and finally grant privileges on those schemas.

For now we're going to just avoid using any grants and manage privileges using local-exec rather than design a module that requires merging all privilege grants up front. Having that capability would be really valuable though and we're interested in discussing the feasibility and work involved in allowing overlapping grant resources.

This is related to but a bigger ask than https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/142 which is requesting raising when this issue is present rather than developing a fix.

**Comment by leftathome** [comment]
Corollary: Some of the grant resources say that they're exclusive grants, but others don't.  It appears they're all exclusive.

Even with the additional flexibility provided by Terraform 12, there are scenarios involving modules where "one grant resource to rule them all" is not proving to be enough.  I'm not sure how much work is required under the hood for this but I think it would be a big deal for users as their Snowflake account grows in complexity...

**Comment by robbruce** [comment]
Scenario described in https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/211#issuecomment-688496123

**Comment by ryanking** [comment]
In a post terraform 0.13 world (with for_each on modules) this seems like a more sustainable approach. It might take us a bit of time to plan on execute on though.

**Comment by funes79** [comment]
I also agree with @dstuck , in our case we would like to separate the terraform state and the whole module into multiple state files. Not sure if it is possible, but consider a scenario where you have 1 role (out of 20) which has access to DEV and PROD.
And DEV has tens or hundreds of grants and resources and PROD has tens or hundreds of grants and resources. If we would be able to split and separate, the CICD can then just run for dev only changes only on the DEV part.

**Comment by dstuck** [comment]
@ryanking I noticed that with the migration of docs to the terraform registry that there are no longer warnings about grants removing any other applied grants. Was this issue actually resolved or is it just less explicit?

**Comment by rasmusab** [comment]
Adding to the comment by @dstuck . I'm also not able to find any documentation on that it's not possible to have multiple grant resources of the same kind. Looking through the GitHub history I found this documentation in the README, but I can't fins it in the official documentation over at https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs . I think it's easy to get bitten by this and I think it would be great to include the old README info in the new documentation.

**Comment by ajwootto** [comment]
Echoing the concern about this warning being missing from the provider docs. I just got bitten by this yesterday and accidentally removed a bunch of pre-created grants from the database. It basically took doing that to discover that this is how those resources work.

I would also love the ability to separate grants as stated. It does make it hard to use these resources when all the roles need to be listed out in one place to create the grant.

**Comment by dstuck** [comment]
It looks like this is being addressed in part by https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/520. This looks like a smaller fix than I expected was necessary. Are there plans to standardize all grants in this way?

**Comment by louis-vines** [comment]
I like @robbruce's suggestion in https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/211#issuecomment-688496123. Is this something people think could be pursued?

**Comment by dstuck** [comment]
I believe this is addressed as of [v0.26.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.26.0)
I am overjoyed that this pretty fundamental limitation has been addressed!
