### ISSUE TITLE
Can't configure provider with `account`, `user` and `password` since v0.74.0

### ISSUE THREAD

**Issue by lra** [Snowflake-Labs/terraform-provider-snowflake#2131]
**Provider Version**

`+ provider registry.terraform.io/snowflake-labs/snowflake v0.74.0`

**Terraform Version**

```
Terraform v1.6.1
on darwin_arm64
```

**Describe the bug**

Configuring the provider with account, user and password does not work:
```
Error: account and User must be set in provider config, ~/.snowflake/config, or as an environment variable
```

**Expected behavior**

Per the doc and per previous versions, we should be able to configure the provider with `account`, `user` and `password`.

**Code samples and commands**

Save this as `test.tf`:
```
terraform {
  required_providers {
    snowflake = {
      source = "Snowflake-Labs/snowflake"
    }
  }
}

provider "snowflake" {
  account  = "whatever"
  role     = "SECURITYADMIN"
  user     = "whatever"
  password = "whatever"
}

data "snowflake_users" "current" {
  pattern = "user1"
}
```

Running `terraform plan` leads to:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: account and User must be set in provider config, ~/.snowflake/config, or as an environment variable
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on test.tf line 9, in provider "snowflake":
│    9: provider "snowflake" {
│ 
╵
```

**Additional context**

This broke since v0.74.0

The workaround is to downgrade to  v0.73.0 and rename `user` to `username` in the provider.

We can't use the env vars because we have lots of providers and they don't share the same user/password, so we have to feed those dynamically in the user/password properties with variables.

**Comment by scottruss-lacework** [comment]
Can we mark 0.74 as a bad release, revert to 0.73 as the latest, and either back out the change or make a new major version? I shouldn't be needing to make provider config changes on a minor version change.

**Comment by ianwesleyarmstrong** [comment]
are there any plans to be more careful about versions? i've ran into 2/3 breaking changes in the last couple months that have required urgent fixes

**Comment by elventear** [comment]
> We can't use the env vars because we have lots of providers and they don't share the same user/password, so we have to feed those dynamically in the user/password properties with variables.

I am curious if this a mistake or a design decision. If this is how the provider is planned to behave in the future, this feels like a huge step backward. For us it will be a giant blocker as the way we get authentication credentials is dynamic using terraform itself, and then have terraform leak the credentials outside of the execution by writing to the filesystem seems counterproductive, TBH.

cc: @sfc-gh-swinkler 
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blame/16012ae222c611080efc3ffe2b820961bff5fc90/pkg/provider/provider.go#L741

**Comment by Symbianx** [comment]
our credentials for the snowflake provider are not hardcoded but they are coming from a data resource that gets them from a secure location. 
This is a very common pattern that we use in many providers. I would be surprised if this is the intended design...

**Comment by lra** [comment]
Fixed by https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2136
