### ISSUE TITLE
Error: account and User must be set in provider config, ~/.snowflake/config, or as an environment variable

### ISSUE THREAD

**Issue by lzitka** [Snowflake-Labs/terraform-provider-snowflake#2137]
**Provider Version**
 Installed snowflake-labs/snowflake v0.74.0
id did not happened with - Installed snowflake-labs/snowflake v0.73.0
**Terraform Version**

1.5.7

**Describe the bug**

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/146438230/155d4a80-9f9b-40df-9919-80299c36f37c)

**Expected behavior**

It is not well documented how to configure the provider, on main page README.md file

**Code samples and commands**

This is current documentation:
![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/146438230/e32818d5-1e2d-4448-8954-f67aa455116a)

**Comment by smith-m** [comment]
Seeing the same issue following the Snowflake Terraform demo:
https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html#4

fixed by forcing version 0.73.0

**Comment by sfaller98** [comment]
> Latest release 0.74.0 screwed up things completely!
> 
> The examples in the readme are not working anymore when using a private key:
> 
> export SNOWFLAKE_USER="..." export SNOWFLAKE_PRIVATE_KEY_PATH="~/.ssh/snowflake_key.p8" export SNOWFLAKE_PRIVATE_KEY_PASSPHRASE="...
> 
> But it returns:
> 
> Γöé Error: 260002: password is emptys] Γöé Γöé with provider["registry.terraform.io/snowflake-labs/snowflake"].SYSADMIN, Γöé on main.tf line 24, in provider "snowflake": Γöé 24: provider "snowflake" {m 43s]
> 
> I really do not understand how touching the login methods in this way sounded like a good idea.

Did you find a way around this? we need the new release! I guess todays job will be looking for a way around this

**Comment by sfaller98** [comment]
> Nope, reverted to 0.73.0 - I see an hotfix is coming in 0.74.1; but I do not know if it is solving the private key issue or just the "account and User must be set" issue.

So the terraform variables don't work but if i set both the account and user as variables i got it to work. 
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2138
looks like they are aware of the issue!

**Comment by simonepm** [comment]
Yes, also SNOWFLAKE_USER and SNOWFLAKE_ACCOUNT were set, the error I receive is:

Error: 260002: password is empty

I guess the environment variables for the private key are not read in the correct way anymore in 0.74.0, leading the provider to try the password login anyway, that is in the end empty.

**Comment by matthiasng** [comment]
We have SNOWFLAKE_USER, SNOWFLAKE_ROLE, SNOWFLAKE_ACCOUNT and SNOWFLAKE_PRIVATE_KEY set as environment variable and we also receive the same error: "Error: 260002: password is empty"

**Comment by simonepm** [comment]
Error: 260002: password is empty issue still present in 0.75.0: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2133

**Comment by pauldraper** [comment]
I'm really, really curious how people are using 0.74.0 and 0.75.0.

Apparently it's not completely broken for someone right? I can't it to work.

**Comment by alexeiser** [comment]
I am using this to automate management of a set of snowflake accounts, using vault based dynamic credentials. 

With the issues form 0.74&0.75 I decided to move to generating a profile file, with each acocunt under management. That’s worked pretty well, and a little superior than the previous method which had some leaking in tf state.

**Comment by pauldraper** [comment]
@alexeiser what's the documentation on this "~/.snowflake/config" file.

Somehow I cannot find it.

**Comment by simonepm** [comment]
As far as I understood people that uses plain password should not have any problem. As soon as you make use of a different login method (private key) and/or a passing method (env variables) thing stop working since 0.74.0. The miscommunication happens between the provider config setup and the gosnowflake library under the hood.

**Comment by sfc-gh-swinkler** [comment]
As this specific problem has been fixed as of 0.75, I will close the issue. @simonepm has it correct that #2133 with private key is the current issue. I apologize for the issue, and we are working on a fix ASAP.

**Comment by attekei** [comment]
This helps: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169#issuecomment-1816167117

**Comment by sfc-gh-asawicki** [comment]
Hey @lzitka. The problem you initially mentioned should have been solved already in v0.76.0. Please confirm and close the issue if so.

@smith-m @simonepm @sfaller98 @matthiasng @pauldraper please consult the thread in #2169 like suggested above by @attekei (thanks).

**Comment by lzitka** [comment]
@sfc-gh-asawicki  - I will test during week or next and eventually close this topic. Thx everyone for feedback in this channel.

**Comment by sfc-gh-asawicki** [comment]
Closing as fixed.
