### ISSUE TITLE
snowflake_grant_privileges_to_role resource hangs with account grants within a module

### ISSUE THREAD

**Issue by danu165** [Snowflake-Labs/terraform-provider-snowflake#2151]
**Provider Version**

0.70.1

**Terraform Version**

0.14.11

**Describe the bug**

When we use snowflake_grant_privileges_to_role to apply account grants within a module, we see our Terraform Enterprise server hang. We cannot locate the root cause of this issue.

**Expected behavior**

Account grants should succeed

**Additional context**

Please refer to snowflake case 00625663 for more context, examples, and attachments

**Comment by sfc-gh-jcieslak** [comment]
Closing as afaik the issue has been resolved
