### ISSUE TITLE
SQL compilation error when using transformation in snowflake_pipe COPY INTO statement.

### ISSUE THREAD

**Issue by chriselion** [Snowflake-Labs/terraform-provider-snowflake#2165]
**Provider Version**

v0.75.0

**Terraform Version**

1.4.6

**Describe the bug**

When trying to use the `col_name` parameters in the `COPY INTO` statement in a `snowflake_pipe` resource, I get a "Error: 000904 (42000): SQL compilation error". A similar `snowflake_pipe` resource setup works without the destination columns, and a similar statement works when run in a worksheet.

**Expected behavior**

The provider should support the `table_name (column_name)` syntax.

**Code samples and commands**

Pipe definition:
```terraform
resource "snowflake_pipe" "pipe" {
  database    = var.database
  schema      = var.schema
  name        = var.pipe_name
  comment     = "Snowpipe. Managed by Terraform (${local.module_name})"
  auto_ingest = true

  copy_statement = <<-EOT
    COPY INTO ${snowflake_table.snowpipe_raw_results_table.qualified_name} (fileName, fileContent)
    FROM (
      SELECT metadata$filename, $1
      FROM @${local.snowpipe_stage_fqname} ( FILE_FORMAT => ${local.snowpipe_file_format_fqname} )
    )
  EOT
}
```
which results in the proposed action:
```terraform
  # module.terraform-aws-snowpipe["my-kinesis-firehose"].snowflake_pipe.pipe will be created
  + resource "snowflake_pipe" "pipe" {
      + auto_ingest          = true
      + comment              = "Snowpipe. Managed by Terraform (terraform-aws-snowpipe)"
      + copy_statement       = <<-EOT
            COPY INTO "MY_DATABASE"."PUBLIC"."my_pipe_raw_results_TF" (fileName, fileContent)
            FROM (
              SELECT metadata$filename, $1
              FROM @"MY_DATABASE"."PUBLIC"."my_pipe_stage_TF" ( FILE_FORMAT => "MY_DATABASE"."PUBLIC"."my_pipe_file_format_TF" )
            )
        EOT
      + database             = "MY_DATABASE"
      + id                   = (known after apply)
      + name                 = "my_pipe"
      + notification_channel = (known after apply)
      + owner                = (known after apply)
      + schema               = "PUBLIC"
    }
```
and then produces the error
```
│ Error: 000904 (42000): SQL compilation error: error line 1 at position 220
│ invalid identifier 'FILENAME'
│ 
│   with module.terraform-aws-snowpipe["my-kinesis-firehose"].snowflake_pipe.pipe,
│   on ../modules/terraform-aws-snowpipe/main.tf line 208, in resource "snowflake_pipe" "pipe":
│  208: resource "snowflake_pipe" "pipe" {
```

**Additional context**
If I use a simpler table, and don't use the "Data load with transformation" syntax, like
```terraform
  copy_statement = <<-EOT
    COPY INTO ${snowflake_table.snowpipe_raw_results_table.qualified_name}
    FROM @${local.snowpipe_stage_fqname}
    FILE_FORMAT = (TYPE = JSON)
EOT
```
then the pipe is created without any problems.

I was following [this guide](https://frost-stefan.medium.com/setting-up-some-what-streaming-with-aws-kinesis-firehose-s3-and-snowflake-de02f6685b52) for setting up the pipe, and was able to create the pipe using the columns in a worksheet.

I see that there are [two different syntaxes for COPY INTO](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table) - is it possible that only the "Standard data load" one is supported?

**Comment by sfc-gh-asawicki** [comment]
Hey, @chriselion. Thanks for creating the issue.

The provider itself does not interfere with the copy statement you are providing; it just passes it over to Snowflake. So, I would assume that this statement is not 100% correct.

**Comment by chriselion** [comment]
OK, I'll take another look at this today. Is there any way to enable output of the SQL that's being executed, so I can see whether it's getting altered somewhere along the way?

**Comment by sfc-gh-asawicki** [comment]
@chriselion you can run terraform commands with `TF_LOG=debug` to show (much) more output.

**Comment by leonard-henriquez** [comment]
I have the exact same problem.
Did you find a solution @chriselion ?

the error:
```
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 101 unexpected '@BUZ_S3_PIPE_2123'.
│
│   with snowflake_pipe.buz_s3_pipe,
│   on buz.tf line 41, in resource "snowflake_pipe" "buz_s3_pipe":
│   41: resource "snowflake_pipe" "buz_s3_pipe" {
│
```

my code:
```
resource "snowflake_pipe" "buz_s3_pipe" {
  depends_on  = [snowflake_table.buz_s3, snowflake_stage.buz_s3_stage]
  name        = local.buz_pipe_name
  schema      = local.buz_schema
  database    = local.buz_database
  auto_ingest = true

  copy_statement = "COPY INTO '${local.buz_table_name}' from @${local.buz_database}.${local.buz_schema}.${local.buz_pipe_name} file_format = (type = 'JSON')"
}
```

**Comment by chriselion** [comment]
In my case, it turned out that I needed to quote the column names, but you're not using that form of COPY INTO.

My guess is that you need quotes around the `from @${local.buz_database}.${local.buz_schema}.${local.buz_pipe_name}` part of your statement. You can see in the output, it's trying to execute
```
... from @bronze.snowplow_buz.BUZ_S3_PIPE ...
```
but that might need to be
```
... from @"bronze"."snowplow_buz"."BUZ_S3_PIPE" ...

**Comment by sfc-gh-asawicki** [comment]
@chriselion, can you close the issue then?

@leonard-henriquez, the suggestion above is a valid one. The provider itself does not interfere with the statements provided in places like the `copy_statement` like it does when constructing the usual SQL statements. It means the provider is not adjusting the provided identifiers in this case. The Snowflake identifiers are a tricky topic. Please read https://docs.snowflake.com/en/sql-reference/identifiers-syntax for the reference.

**Comment by chriselion** [comment]
Closed.

Just a thought: providing `qualified_name` (as requested in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2035) would make it easier for people to get the identifier right the first time.

**Comment by sfc-gh-asawicki** [comment]
@chriselion, that's right. We have it high on our list of improvements. Hopefully, we will visit this in the upcoming months.
