### ISSUE TITLE
PASSWORD_MIN_AGE_DAYS and PASSWORD_HISTORY parameters availability for snowflake_password_policy resource

### ISSUE THREAD

**Issue by GomathiMa** [Snowflake-Labs/terraform-provider-snowflake#2212]
### Terraform CLI and Provider Versions

Terraform Snowflake provider version: 68.2

### Use Cases or Problem Statement

We are not able to utilise the PASSWORD_MIN_AGE_DAYS and PASSWORD_HISTORY parameters  in snowflake_password_policy resource for password policy creation.

### Proposal

Please add the parameters PASSWORD_MIN_AGE_DAYS and PASSWORD_HISTORY parameters  in snowflake_password_policy resource

### How much impact is this issue causing?

Medium

### Additional Information

Password acceptable criteria not being met due to this.

**Comment by sfc-gh-asawicki** [comment]
Closing as done in #2231
