### ISSUE TITLE
data source snowflake_alerts: syntax error line 1 at position 17 unexpected 'IN'

### ISSUE THREAD

**Issue by hieu-cc** [Snowflake-Labs/terraform-provider-snowflake#2216]
### Terraform CLI and Provider Versions

```
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.76.0
```

### Terraform Configuration

```terraform
data "snowflake_alerts" "current" {
  database = "MYDB"
  schema   = "MYSCHEMA"
}
```

### Expected Behavior

No error, even if the database and schema don't exist.

### Actual Behavior

> terraform apply

returns:

```
data.snowflake_alerts.current: Reading...
╷
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 17 unexpected 'IN'.
│
│   with data.snowflake_alerts.current,
│   on main.tf line 1, in data "snowflake_alerts" "current":
│    1: data "snowflake_alerts" "current" {
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/hieu-cc/8e37ac3556b5b0f0d3589206aec501a5

**Comment by sfc-gh-asawicki** [comment]
Hey @hieu-cc. Thanks for reporting the issue.

You are right, there is a problem with SQL statement construction for this datasource. The fix is easy, so we will add it to one of the next releases.
