### ISSUE TITLE
Support ability to alter schema/database and rename

### ISSUE THREAD

**Issue by mwufigma** [Snowflake-Labs/terraform-provider-snowflake#2226]
### Terraform CLI and Provider Versions

Terraform CLI version: >= 1.5.0
Snowflake provider version: 0.68.0

### Use Cases or Problem Statement

When we try to update the name of a schema in Terraform, it attempts to drop and re-create it. We do not want this behavior and would need it to `ALTER SCHEMA RENAME ...`.

### Proposal

Implement something similar to the solution to this issue https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/891 but for schemas and databases

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @mwufigma. Thanks for creating the issue.

We are supporting renames for the schema. We changed the schema implementation lately (check https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.73.0). The rename happens here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/8fbc5cf3005f33c7cfb27815d6e4a1909ffbac80/pkg/resources/schema.go#L179. I have also confirmed that in this test: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/8fbc5cf3005f33c7cfb27815d6e4a1909ffbac80/pkg/resources/schema_acceptance_test.go#L35 rename is behaving correctly.

You may be changing another parameter that causes a recreation.

Can you upgrade to the newer provider version first? If this does not help, could you provide the configurations you are using that are causing the issue?

**Comment by sfc-gh-asawicki** [comment]
Hey @mwufigma, I will close this issue; please open a new one if you are experiencing problems with renaming in the more recent versions of the provider.
