### ISSUE TITLE
Random password generated did not work in Snowflake

### ISSUE THREAD

**Issue by natashamathur** [Snowflake-Labs/terraform-provider-snowflake#2240]
### Terraform CLI and Provider Versions

+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/snowflake-labs/snowflake v0.76.0

### Terraform Configuration

```terraform
output "password_url_ABCD" {
  value     = snowflake_managed_account.ABCD_account.admin_password
  sensitive = true
}

output "password_ABCD_account" {
  value     = snowflake_managed_account.ABCD_account.admin_password
  sensitive = true
}
```

### Expected Behavior

After I created a new snowflake share, I expected that the password output through the above code to give me the correct Admin account password. Both outputs were the same. 

### Actual Behavior

The passwords did not work and I could not log into the share. I ultimately reached out to Snowflake and they re-set the share. 

### Steps to Reproduce

terraform output --json

### How much impact is this issue causing?

Medium

### Additional Information

We have other shares that were created in the same way. For those the admin_password output worked.

**Comment by sfc-gh-jcieslak** [comment]
Hey @natashamathur 👋 
Not sure what is causing the issue here. Could you elaborate a bit and provide the configurations that you think are invalid?
