### ISSUE TITLE
Plugin did not respond error when deploying resources

### ISSUE THREAD

**Issue by thomasj20git** [Snowflake-Labs/terraform-provider-snowflake#2244]
### Terraform CLI and Provider Versions

Terraform v1.5.4

### Terraform Configuration

```terraform
resource "snowflake_role" "role" {
  name     = var.role
}

resource "snowflake_grant_privileges_to_role" "database_grant" {
  privileges = ["USAGE"]
  role_name  = var.role
  on_account_object {
    object_type = "DATABASE"
    object_name = var.db_name
  }
}
resource "snowflake_schema" "schema" {
  database   = var.db_name
  name       = var.schema_name
  is_managed = false
}

resource "snowflake_grant_privileges_to_role" "schema_grant" {
  # provider   = snowflake.security_admin
  privileges = ["USAGE"]
  role_name  = var.role
  on_schema {
    schema_name = var.schema_name
  }
}
```

### Expected Behavior

Expected this to create schema and grant permission to the schema to the role i created. The first two resources work correctly I create the role and grant the database privilege to the role. The second two resources plan correctly when i run terraform plan but then error out when i apply

### Actual Behavior

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 
Terraform will perform the following actions:
 
  # module.name_3.snowflake_grant_privileges_to_role.schema_grant will be created
  + resource "snowflake_grant_privileges_to_role" "schema_grant" {
      + all_privileges    = false
      + id                = (known after apply)
      + on_account        = false
      + privileges        = [
          + "USAGE",
        ]
      + role_name         = "TF_DEMO_SVC_ROLE"
      + with_grant_option = false
 
      + on_schema {
          + schema_name = "TF_DEMO"
        }
    }
 
  # module.name_3.snowflake_schema.schema will be created
  + resource "snowflake_schema" "schema" {
      + data_retention_days = 1
      + database            = "test_db_data_exchange_demo_1"
      + id                  = (known after apply)
      + is_managed          = false
      + is_transient        = false
      + name                = "TF_DEMO"
    }
 
  # module.name_4.snowflake_grant_privileges_to_role.schema_grant will be created
  + resource "snowflake_grant_privileges_to_role" "schema_grant" {
      + all_privileges    = false
      + id                = (known after apply)
      + on_account        = false
      + privileges        = [
          + "USAGE",
        ]
      + role_name         = "TF_DEMO_SVC_ROLE_2"
      + with_grant_option = false
 
      + on_schema {
          + schema_name = "TF_DEMO_2"
        }
    }
 
  # module.name_4.snowflake_schema.schema will be created
  + resource "snowflake_schema" "schema" {
      + data_retention_days = 1
      + database            = "test_db_data_exchange_demo_2"
      + id                  = (known after apply)
      + is_managed          = false
      + is_transient        = false
      + name                = "TF_DEMO_2"
    }
 
Plan: 4 to add, 0 to change, 0 to destroy.
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
module.name_3.snowflake_grant_privileges_to_role.schema_grant: Creating...
module.name_3.snowflake_schema.schema: Creating...
module.name_4.snowflake_grant_privileges_to_role.schema_grant: Creating...
module.name_4.snowflake_schema.schema: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
 
Stack trace from the terraform-provider-snowflake_v0.76.0 plugin:
 
panic: runtime error: index out of range [1] with length 1
 
goroutine 44 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewDatabaseObjectIdentifierFromFullyQualifiedName({0x140007a3f69?, 0x14000e96750?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:159 +0xb8
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0x14000f4bc60?, {0x14000f7d460, 0x1, 0x1}, 0x40?, 0x14000e3acb8)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:715 +0x730
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x102609740?, 0x14000e6aa90?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:456 +0x13c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x10264b080?, {0x10264b080?, 0x14000f6c210?}, 0xd?, {0x102609740?, 0x14000e6aa90?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000be8380, {0x10264b080, 0x14000f6c210}, 0x14000f781a0, 0x14000aa3680, {0x102609740, 0x14000e6aa90})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000b661b0, {0x10264b080?, 0x14000f6c030?}, 0x14000f665f0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x102667ba0?, 0x14000b661b0?}}, {0x10264b080, 0x14000f6c030}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x10264afd8?, {0x10264b080?, 0x14000f5bce0?}, 0x14000f665a0)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000bee140, {0x10264b080?, 0x14000f5b2f0?}, 0x14000bd4bd0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1025b66e0?, 0x14000bee140}, {0x10264b080, 0x14000f5b2f0}, 0x14000bd4b60, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001a12c0, {0x10265a900, 0x140001fb6c0}, 0x14000f627e0, 0x140007ca390, 0x1032771d8, 0x0)
        google.golang.org/grpc@v1.58.2/server.go:1376 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x140001a12c0, {0x10265a900, 0x140001fb6c0}, 0x14000f627e0, 0x0)
        google.golang.org/grpc@v1.58.2/server.go:1753 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.2/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.58.2/server.go:996 +0x16c
panic: runtime error: index out of range [1] with length 1
 
goroutine 67 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewDatabaseObjectIdentifierFromFullyQualifiedName({0x140007ebf10?, 0x14000f756e0?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:159 +0xb8
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0x14000f4d660?, {0x1400101e690, 0x1, 0x1}, 0x40?, 0x14000d58cb8)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:715 +0x730
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x102111740?, 0x1400057af70?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:456 +0x13c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x102153080?, {0x102153080?, 0x14000f611a0?}, 0xd?, {0x102111740?, 0x1400057af70?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400063d180, {0x102153080, 0x14000f611a0}, 0x14000f56d00, 0x14000f7a080, {0x102111740, 0x1400057af70})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400099a000, {0x102153080?, 0x14000f60fc0?}, 0x14000f0dc70)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x10216fba0?, 0x1400099a000?}}, {0x102153080, 0x14000f60fc0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x102152fd8?, {0x102153080?, 0x14000f60c90?}, 0x14000f0dc20)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140009aa140, {0x102153080?, 0x14000f60480?}, 0x14000f25340)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1020be6e0?, 0x140009aa140}, {0x102153080, 0x14000f60480}, 0x14000f252d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400067b2c0, {0x102162900, 0x14000103520}, 0x14000f5d9e0, 0x14000999ef0, 0x102d7f1d8, 0x0)
        google.golang.org/grpc@v1.58.2/server.go:1376 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x1400067b2c0, {0x102162900, 0x14000103520}, 0x14000f5d9e0, 0x0)
        google.golang.org/grpc@v1.58.2/server.go:1753 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.2/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.58.2/server.go:996 +0x16c
 
Error: The terraform-provider-snowflake_v0.76.0 plugin crashed!
 
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @thomasj20git 
You have to put the fully qualified name of the schema in the **"snowflake_grant_privileges_to_role"."schema_grant"** resource.
```terraform
resource "snowflake_grant_privileges_to_role" "schema_grant" {
  # provider   = snowflake.security_admin
  privileges = ["USAGE"]
  role_name  = var.role
  on_schema {
    schema_name = var.schema_name # <- here, instead of <schema_name> it expects <database_name>.<schema_name>
  }
}
```

**Comment by thomasj20git** [comment]
Hi @sfc-gh-jcieslak thank you so much that fixes the plugin error!

**Comment by thomasj20git** [comment]
Hi @sfc-gh-jcieslak have you encountered this issue before https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2264
