### ISSUE TITLE
getting  Error: 260002: password is empty when using Private key to connect

### ISSUE THREAD

**Issue by baabaakz** [Snowflake-Labs/terraform-provider-snowflake#2245]
### Terraform CLI and Provider Versions

0.78

### Terraform Configuration

```terraform
provider "snowflake" {
  account     = var.snowflake_account_locator
  username    = var.snowflake_svc
  #  private_key_path = var.private_key_path
  private_key = var.private_key
  role        = var.terraform_role
  warehouse   = var.terraform_warehouse
}
```

### Expected Behavior

Like in version 0.73 is authenticate using private key

### Actual Behavior

gives following error:
╷
│ Error: 260002: password is empty
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on main.tf line 21, in provider "snowflake":
│   21: provider "snowflake" {
│
╵
Operation failed: failed running terraform plan (exit 1)

and cannot authenticate.

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @baabaakz. Thanks for reaching out.

Versions in between introduced some changes to the configuration. You can read about them here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide and here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169#issuecomment-1816046269.

It seems that in your case, you have to:
- rename the `username` to `user`;
- add the `authenticator` parameter set to `JWT`.

**Comment by sfc-gh-asawicki** [comment]
@sdiazben, it's great to hear that it solved your problem.

We are working on clarity in the docs. As you suggested, we will update the migration guide and probably link it to the Terraform docs.

Could you please close the issue?

**Comment by baabaakz** [comment]
@sfc-gh-asawicki thanks for the solution. Yeah it worked. Thank you.
let’s close this issue
