### ISSUE TITLE
Support plural ICEBERG TABLES in snowflake_grant_privileges_to_role

### ISSUE THREAD

**Issue by danu165** [Snowflake-Labs/terraform-provider-snowflake#2248]
### Terraform CLI and Provider Versions

CLI: 1.0.11
Provider: 0.78.0

### Use Cases or Problem Statement

`snowflake_grant_privileges_to_role` is not able to grant privileges such as `SELECT` on all future iceberg tables. Code to reproduce:
```
resource "snowflake_role" "role" {
  name       = "DUMMY_ICEBERG_ROLE"
}

resource "snowflake_grant_privileges_to_role" "iceberg_privs" {
  depends_on = [snowflake_role.role]
  privileges = ["SELECT"]
  role_name  = snowflake_role.role.name

  on_schema_object {
    future {
      object_type_plural = "ICEBERG TABLES"
      in_schema          = "MY_DB.MY_SCHEMA"
    }
  }
}
```

Error:
```
╷
│ Error: expected on_schema_object.0.future.0.object_type_plural to be one of ["ALERTS" "DYNAMIC TABLES" "EVENT TABLES" "FILE FORMATS" "FUNCTIONS" "PROCEDURES" "SECRETS" "S
EQUENCES" "PIPES" "MASKING POLICIES" "PASSWORD POLICIES" "ROW ACCESS POLICIES" "SESSION POLICIES" "TAGS" "STAGES" "STREAMS" "TABLES" "EXTERNAL TABLES" "TASKS" "VIEWS" "MATE
RIALIZED VIEWS"], got ICEBERG TABLES
│
│   with snowflake_grant_privileges_to_role.ice_privs,
│   on main.tf line 50, in resource "snowflake_grant_privileges_to_role" "ice_privs":
│   50:       object_type_plural = "ICEBERG TABLES"
│

```

### Proposal

Either support `ICEBERG TABLES` in `object_type_plural` or possibly remove the validation in general so it's easier to use new Snowflake features without contributing to provider code.

### How much impact is this issue causing?

High

### Additional Information

We are working to deliver Iceberg Tables by December 13th to our company. We would need the ability to issue these grants for Iceberg Tables.

**Comment by danu165** [comment]
Note: we would also need support for grants on `EXTERNAL VOLUMES`. Additionally, `object_type` should support `ICEBERG TABLE` and  `EXTERNAL VOLUME`.

**Comment by bjornm82** [comment]
How to create the external volumes in terraform? This are also missing still right?

**Comment by danu165** [comment]
> How to create the external volumes in terraform? This is also not implemented right?

It’s not, but for our use case we mostly need the grants as the external volumes will be created outside of Terraform. Our thinking is that it shouldn’t be too complicated to modify this resource for grants related to external volumes and iceberg tables. We’re hoping that asking for just grants will be implemented more quickly than also requesting the resources.

**Comment by bjornm82** [comment]
Seems fair, I'll create another ticket for the implementation of `EXTERNAL VOLUME`, `CATALOG INTEGRATION` and `ICEBERG TABLE` support.

**Comment by sfc-gh-jcieslak** [comment]
Hey @danu165 @bjornm82 
I'll try to push a PR for this today and if it will be merged, then we'll release a bugfix version today or tomorrow.

**Comment by sfc-gh-jcieslak** [comment]
@danu165 @bjornm82 
We just released a bugfix version [0.79.1](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.79.1) that should be able to resolve the issue. 
It adds support for the `ICEBERG TABLES` and `EXTERNAL VOLUMES`.
For the `CATALOG INTEGRATION`, please try to use `INTEGRATION` type.

**Comment by bjornm82** [comment]
Sweet! Thanks very much! I'll check it right away.

**Comment by sfc-gh-jcieslak** [comment]
Hey @danu165 @bjornm82 
Are you able to use the missing parameters? Can we close the issue?

**Comment by danu165** [comment]
Hi @sfc-gh-jcieslak, I seem to be getting an error with the provider. Here is my setup:
```

terraform {
  required_providers {
    snowflake = {
      source  = "snowflake-labs/snowflake"
      version = "0.79.1"
    }
  }
}


provider "snowflake" {
  user          = var.snowflake_username
  token         = var.snowflake_oauth_token
  account       = var.snowflake_account
  role          = var.snowflake_terraform_role
  authenticator = "OAuth"
}


resource "snowflake_role" "role" {
  name       = "DUMMY_ICEBERG_ROLE"
}

resource "snowflake_grant_privileges_to_role" "ice_privs" {
  depends_on = [snowflake_role.role]
  privileges = ["SELECT", "INSERT", "UPDATE", "TRUNCATE", "DELETE", "REFERENCES"]
  role_name  = snowflake_role.role.name

  on_schema_object {
    future {
      object_type_plural = "ICEBERG TABLES"
      in_schema          = "MY_DB.MY_SCHEMA"
    }
  }
}
```

Returns the following error:
```
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/snowflake-labs/snowflake" planned an invalid value for snowflake_grant_privileges_to_role.ice_privs.with_grant_option:
│ planned value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/snowflake-labs/snowflake" planned an invalid value for snowflake_grant_privileges_to_role.ice_privs.all_privileges: planned
│ value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/snowflake-labs/snowflake" planned an invalid value for snowflake_grant_privileges_to_role.ice_privs.on_account: planned
│ value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
I get the same error if I only select one privilege like `SELECT` as well

**Comment by sfc-gh-jcieslak** [comment]
@danu165 
Hey, I suspect this is an issue caused by old Terraform CLI. Some of its internal behavior changed over time. The upgrade to at least 1.1.5 should do the job.

**Comment by danu165** [comment]
Ah, yes, I tried again with CLI 1.3.6 and this worked. Thank you very much!
