### ISSUE TITLE
error associating tag to object: snowflake_tag_association incorrectly wraps column name with quotes

### ISSUE THREAD

**Issue by hieu-cc** [Snowflake-Labs/terraform-provider-snowflake#2254]
### Terraform CLI and Provider Versions

Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.79.1

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.79.1"
    }
  }
}

resource "snowflake_tag" "tag" {
  name           = "MY_TAG"
  database       = "MY_DB"
  schema         = "MY_SCHEMA"
  allowed_values = ["VALUE1"]
}

resource "snowflake_tag_association" "db_association" {
  object_identifier {
    database = "MY_DB"
    name     = "MY_TABLE.full_name"
    schema   = "MY_SCHEMA"
  }
  object_type = "COLUMN"
  tag_id      = "MY_DB.MY_SCHEMA.MY_TAG"
  tag_value   = "VALUE1"
}
```

### Expected Behavior

The provider shouldn't wrap the column name with quotes in the SQL code.

Should be:
```
ALTER TABLE "MY_DB"."MY_SCHEMA"."MY_TABLE" MODIFY COLUMN full_name SET TAG "MY_DB"."MY_SCHEMA"."MY_TAG" = 'VALUE1';
```
instead of
```
ALTER TABLE "MY_DB"."MY_SCHEMA"."MY_TABLE" MODIFY COLUMN "full_name" SET TAG "MY_DB"."MY_SCHEMA"."MY_TAG" = 'VALUE1';
```

### Actual Behavior

```
│ Error: error associating tag to object: ["MY_DB"."MY_SCHEMA"."MY_TABLE.full_name"] with command: [ALTER TABLE "MY_DB"."MY_SCHEMA"."MY_TABLE" MODIFY COLUMN "full_name" SET TAG "MY_DB"."MY_SCHEMA"."MY_TAG" = 'VALUE1'], tag_id [MY_DB.MY_SCHEMA.MY_TAG]
│
│   with snowflake_tag_association.db_association,
│   on main.tf line 21, in resource "snowflake_tag_association" "db_association":
│   21: resource "snowflake_tag_association" "db_association" {
```

The provider seems to run the following SQL and wraps the column name with quotes:

```
ALTER TABLE "MY_DB"."MY_SCHEMA"."MY_TABLE" MODIFY COLUMN "full_name" SET TAG "MY_DB"."MY_SCHEMA"."MY_TAG" = 'VALUE1';
```
and when I try to run it in Snowflake, I get this error:
```
Error: invalid identifier '"full_name"' (line 28)
```
However, if we remove the quotes from the column, then the code runs successfully:
```
Statement executed successfully.
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @hieu-cc. Thanks for reporting the issue.

This is a part of the old implementation we gradually getting rid of. The fix seems to be easy, we will add it "in the meantime".

**Comment by sfc-gh-asawicki** [comment]
One more question: how are you creating the table?

**Comment by hieu-cc** [comment]
Hey @sfc-gh-asawicki, thanks for the message. The tables were already created in my Snowflake account, but you should be able to reproduce the issue by either creating db, schema, table manually or with those resource blocks:

1. snowflake_database
2. snowflake_schema
3. snowflake_table

**Comment by sfc-gh-asawicki** [comment]
This is precisely why I have asked this. Creating the table using the `snowflake_table` resource uses the exact old implementation. It means that table column names are also quoted. It works smoothly with the tags association resource, which you can check in the `TestAcc_TagAssociationColumn` test.

We will replace the old implementation, but we also have a bigger discussion around the identifiers topic incoming. That's why we will wait to change the old implementation.

What you can try now is to capitalize the column name in the `snowflake_tag_association` resource. If you created it by hand (it was unquoted), then it's capitalized on Snowflake side. Still, it should work with quotes if you provide the correct capitalization in the name.

Let me know if that helps.

**Comment by hieu-cc** [comment]
That makes sense now.

I have tested both cases:
1.  Capitalise all letters in the column name if it was created without quotes
2. Use exact column name if it was create with quotes. 

and I could associate the columns with tags.

Thanks for explaining and appreciate your amazing work!
