### ISSUE TITLE
Schema Create after import

### ISSUE THREAD

**Issue by NovaLogicDev** [Snowflake-Labs/terraform-provider-snowflake#2265]
### Terraform CLI and Provider Versions

Terraform v1.6.3
on windows_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.76.0

### Terraform Configuration

```terraform
provider "snowflake" {
  role                   = "<REDACTED>"
  account                = "<REDACTED>"
  authenticator          = "JWT"
  profile                = "default"
}
```

### Expected Behavior

Actions Taken:

Create a TF File with one Database and two schemas.
Run terraform import on Database, run plan, plan is to update existing database
Run terraform import on first Schema, run plan, plan is to update existing database and first existing schema
Run terraform import on second Schema, run plan, plan is to update existing database and first existing schema and second existing schema

### Actual Behavior

Actions Taken:

Create a TF File with one Database and two schemas.
Run terraform import on Database, run plan, plan is to update existing database
Run terraform import on first Schema, run plan, plan is to update existing database and first existing schema
Run terraform import on second Schema, run plan, plan is to update existing database and second existing schema, CREATE first existing schema

### Steps to Reproduce

1. `terraform import <database>`
2. `terraform import <schema1>`
3. `terraform import <schema2>`
4. `terraform plan`

### How much impact is this issue causing?

High

### Additional Information

This issue always seems to effect on of the two schemas, even tried dropping the schema it wanted to create and then running `terraform apply` and then `terraform plan` and the result was the same the plan wanted to create the schema still.

**Comment by sfc-gh-asawicki** [comment]
Hey @NovaLogicDev. Thanks for reporting the issue.

We recently had a similar problem which was addressed in #2238. Can you try upgrading to at least [v0.78.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.78.0) and confirm that the issue still exists?

**Comment by NovaLogicDev** [comment]
Logs were omitted due to security concerns. reading through them I'm noticing these lines

```2023-12-13T11:13:05.556-0700 [TRACE] Executing graph transform *terraform.pruneUnusedNodesTransformer
2023-12-13T11:13:05.556-0700 [DEBUG] pruneUnusedNodes: <REDACTED SCHEMA1> (expand) is no longer needed, removing
2023-12-13T11:13:05.556-0700 [TRACE] Completed graph transform *terraform.pruneUnusedNodesTransformer with new graph:
  provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
  <REDACTED DB> (expand) - *terraform.nodeExpandApplyableResource
    provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
  <REDACTED SCHEMA2> - *terraform.NodeApplyableResourceInstance
    provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
    <REDACTED DB> (expand) - *terraform.nodeExpandApplyableResource
    <REDACTED SCHEMA2> (expand) - *terraform.nodeExpandApplyableResource
  <REDACTED SCHEMA2> (expand) - *terraform.nodeExpandApplyableResource
    provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
    <REDACTED DB> (expand) - *terraform.nodeExpandApplyableResource
  ------ 
```

**Comment by NovaLogicDev** [comment]
That would do it, the problem appears to be gone on the latest release, thanks.
