### ISSUE TITLE
`Share` object error messages are too opaque.

### ISSUE THREAD

**Issue by originalrkk** [Snowflake-Labs/terraform-provider-snowflake#2271]
### Terraform CLI and Provider Versions

This applies to all versions.

### Use Cases or Problem Statement

We get opaque error messages like
```
Error: error reading share err = [errors.go:17] object does not exist or not authorized
```

It's not clear what share this refers to, so it's almost impossible to debug what's happening. This is currently blocking the Snowflake Terraform config for our entire organization.

### Proposal

This PR should solve the issue:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2270

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @originalrkk. I am closing due to #2270 being merged.
