### ISSUE TITLE
Create new warehouse is failing on v>77

### ISSUE THREAD

**Issue by baabaakz** [Snowflake-Labs/terraform-provider-snowflake#2272]
### Terraform CLI and Provider Versions

v78,  v79 and v80
Terraform CLI: 1.6.5

### Terraform Configuration

```terraform
resource "snowflake_warehouse" "WH_TABLEAU_DEVELOPMENT" {
  auto_resume                         = true
  auto_suspend                        = 120
  comment                             = null
  enable_query_acceleration           = true
  initially_suspended                 = true
  max_cluster_count                   = 8
  max_concurrency_level               = 8
  min_cluster_count                   = 1
  name                                = "WH_TABLEAU_DEVELOPMENT"
  query_acceleration_max_scale_factor = 8
  resource_monitor                    = "null"
  scaling_policy                      = "STANDARD"
  statement_queued_timeout_in_seconds = 0
  statement_timeout_in_seconds        = 172800
  warehouse_size                      = "XLARGE"
  warehouse_type                      = "STANDARD"
}
```

### Expected Behavior

Create a warehouse

### Actual Behavior

Error: [errors.go:17] object does not exist or not authorized
with module.snowflake_warehouses.snowflake_warehouse.WH_TABLEAU_DEVELOPMENT
on warehouses/warehouses.tf line 43, in resource "snowflake_warehouse" "WH_TABLEAU_DEVELOPMENT":
resource "snowflake_warehouse" "WH_TABLEAU_DEVELOPMENT" {

On Snowflake I see this error: 
SQL compilation error: Object 'null' does not exist or not authorized.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

**Comment by baabaakz** [comment]
When I switched to V0.77 it starter working

**Comment by sfc-gh-asawicki** [comment]
Hey @baabaakz. THanks for reporting the issue.

Can you share the debug logs?

**Comment by baabaakz** [comment]
[run-Gd1zJKo79cSCWSj9-plan-log.txt](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/13689967/run-Gd1zJKo79cSCWSj9-plan-log.txt)

**Comment by sfc-gh-asawicki** [comment]
Hey @baabaakz. Unfortunately, the logs you gave me do not have the described error.

Can you share the logs with the error?

**Comment by baabaakz** [comment]
That error is resolved.
I had to remove resource monitor = null to make it work

**Comment by sfc-gh-asawicki** [comment]
It's great to hear that! Can we close it then?

**Comment by baabaakz** [comment]
Yes please
