### ISSUE TITLE
Error 394300 (08004) when establishing connection with Snowflake using Terraform

### ISSUE THREAD

**Issue by jacobcbeaudin** [Snowflake-Labs/terraform-provider-snowflake#2280]
### Terraform CLI and Provider Versions

Terraform CLI: `1.6.1`
Snowflake-Labs/snowflake Version: `0.80.0`

### Terraform Configuration

```terraform
provider "snowflake" {
  account       = local.snowflake_account
  authenticator = "JWT"
}

provider "snowflake" {
  alias         = "account_admin"
  role          = "ACCOUNTADMIN"
  account       = local.snowflake_account
  authenticator = "JWT"
}

provider "snowflake" {
  alias         = "security_admin"
  role          = "SECURITYADMIN"
  account       = local.snowflake_account
  authenticator = "JWT"
}

provider "snowflake" {
  alias         = "sys_admin"
  role          = "SYSADMIN"
  account       = local.snowflake_account
  authenticator = "JWT"
}
```

### Expected Behavior

I expect to generate a terraform plan. The same code is able to run without issue in a separate development account

### Actual Behavior

```
$ terraform plan

➜ tfp
data.terraform_remote_state.snowflake_default_user_passwords: Reading...
data.terraform_remote_state.snowflake_default_user_passwords: Read complete after 2s

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: open snowflake connection: 394300 (08004): !394300!
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on versions.tf line 24, in provider "snowflake":
│   24: provider "snowflake" {
│
╵
╷
│ Error: open snowflake connection: 394300 (08004): !394300!
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].account_admin,
│   on versions.tf line 29, in provider "snowflake":
│   29: provider "snowflake" {
│
╵
╷
│ Error: open snowflake connection: 394300 (08004): !394300!
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].security_admin,
│   on versions.tf line 36, in provider "snowflake":
│   36: provider "snowflake" {
│
╵
╷
│ Error: open snowflake connection: 394300 (08004): !394300!
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].sys_admin,
│   on versions.tf line 43, in provider "snowflake":
│   43: provider "snowflake" {
│
╵
```
I am getting an `open snowflake connection` error every time I run terraform plan

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @jacobcbeaudin. Thanks for reporting the issue.

At first glance, it looks like a problem on your side. You mention that the code runs on the other environment. The error code 08004 indicates that the connection was rejected. The error 394300 is mentioned here: https://docs.snowflake.com/en/user-guide/key-pair-auth-troubleshooting#list-of-errors with possible troubleshooting:

394300 | JWT_TOKEN_INVALID_USER_IN_ISSUER | The user name specified in the issuer does not exist in the Snowflake account. For possible solutions, see [Common Errors and Solutions](https://docs.snowflake.com/en/user-guide/key-pair-auth-troubleshooting#label-key-pair-troubleshooting-common-errors).
-- | -- | --

**Comment by jacobcbeaudin** [comment]
This resolved my issue, thanks!
