### ISSUE TITLE
Add “CREATE STREAMLIT” privilege in grant_privileges_to_role resource

### ISSUE THREAD

**Issue by LukLight** [Snowflake-Labs/terraform-provider-snowflake#2290]
### Terraform CLI and Provider Versions

Terraform CLI: 1.0.9 
Snowflake-Labs/snowflake Version: 0.47.0 -> 0.80.0

### Use Cases or Problem Statement

In the “new” grant resource, it is currently not possible to use the “CREATE STREAMLIT” privilege.
This kind of prevents us in having a clean privilege assignment.

### Proposal

Include the privilege within the resource:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/grant_privileges_to_role.go
It has already been included into the “old” resource schema_grant
https://github.com/Snowflake-Labs/terraform-provider-snowflake/commit/7b112cc94822807d3c25c78ec812ec2c2c66ea16

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment]
@LukLight 
Hey 👋 
In https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2303 we added support for create streamlit privilege, so in the next release version (0.83.0) **snowflake_grant_privileges_to_role** should be working correctly.

**Comment by LukLight** [comment]
Thank you very much for the fast response (& fix)!
