### ISSUE TITLE
Remove deprecated configuration parameters from procedure resource

### ISSUE THREAD

**Issue by LukLight** [Snowflake-Labs/terraform-provider-snowflake#2291]
### Terraform CLI and Provider Versions

Terraform CLI: 1.0.9 
Snowflake-Labs/snowflake Version: 0.47.0 -> 0.80.0

### Use Cases or Problem Statement

According to the official Snowflake documentation using the optional parameter “VOLATILE/IMMUTABLE” is deprecated in all languages. 
https://docs.snowflake.com/en/sql-reference/sql/create-procedure#optional-parameters
Currently, this does not result in any major errors when creating/updating a stored procedure via terraform, but it might will in the future.

### Proposal

Get rid of optional parameter “return_behavior”:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/procedure.go 

### How much impact is this issue causing?

Low

**Comment by sfc-gh-asawicki** [comment]
Hey @LukLight. Thanks for creating the issue.

We did not include these deprecated parameters in the SDK. We will remove it during migrating the resource to use the SDK implementation instead of the old one.

**Comment by LukLight** [comment]
Sorry for the late answer @sfc-gh-asawicki !
I'll close the request as it is included in the Pull Request.
