### ISSUE TITLE
external_table column_type uses default even if other precision is specified

### ISSUE THREAD

**Issue by justin-ramirez-gametime** [Snowflake-Labs/terraform-provider-snowflake#2310]
### Terraform CLI and Provider Versions

Terraform v1.6.1
Provider version 0.82.0

### Terraform Configuration

```terraform
resource "snowflake_external_table" "external_table" {
  provider     = snowflake.sys_admin
  database     = var.target_database_name
  schema       = var.target_schema_name
  name         = var.external_table_name
  comment      = var.description
  file_format  = var.file_format
  location     = "@${var.source_database_name}.${var.source_schema_name}.${var.source_stage_name}/${var.file_path}"
  pattern      = var.pattern
  partition_by = var.partition_by

  dynamic "column" {
    for_each = var.columns
    content {
      name = column.value.name
      type = column.value.type
      as   = "(${column.value.as}::${column.value.type})"
    }
  }
  auto_refresh = var.auto_refresh
}
```

### Expected Behavior

Expected the external_table column to be cast as the type described in 'type'. 
{
  name = "RECAPTCHA_ASSESSMENT_SCORE"
  type = "NUMBER(2, 2)"
  as   = "GET($1, 'recaptcha_assessment_score')"
}

should become: RECAPTCHA_ASSESSMENT_SCORE NUMBER(2, 2) AS (TO_NUMBER(GET($1, 'recaptcha_assessment_score'), 2, 2))

### Actual Behavior

It seems as though the precision specification is being ignored or replaced with the type default for the column type casting but not for the read expression type:
RECAPTCHA_ASSESSMENT_SCORE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'recaptcha_assessment_score'), 2, 2))

We saw similar issues occur when type is:
VARCHAR(1000); It was changed to BOUNCE_REASON VARCHAR(16777216) AS (CAST(GET($1, 'bounce_reason') AS VARCHAR(1000)))

NUMBER(9,2); TRANSACTION_AMOUNT NUMBER(38,0) AS (TO_NUMBER(GET(VALUE, 'c10'), 9, 2))

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

The file_formats for each of these occurrences varied between CSV, Custom JSON_GZIP, AVRO
It only seems to be an issue when we are not using the default precision for the type cast.

**Comment by sfc-gh-jcieslak** [comment]
Hey @justin-ramirez-gametime 
I'll take a look at it as soon as possible (probably this or next week). 
Thank you for reporting an issue.

**Comment by sfc-gh-jcieslak** [comment]
Hey @justin-ramirez-gametime 
Could you check if the issue persists in the latest version of the provider?
