### ISSUE TITLE
LESS Resources for Granting Privileges Not More

### ISSUE THREAD

**Issue by NovaLogicDev** [Snowflake-Labs/terraform-provider-snowflake#2314]
### Terraform CLI and Provider Versions

Terraform v1.6.3
on windows_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.79.1

### Use Cases or Problem Statement

The basic use case is I want to create a "read" access role for my database, which loosly means I need to grant usage on the database, the schemas and future schemas, usage on stages, and file formats, as well as select on tables, future tables, views, and future views. using the deprecated snowflake_<object>_grant resources we get a configuration to satisfy this need as follows:

```terraform
resource "snowflake_database_grant" "mydatabasegrant" {
  database_name = "MYDB"
  privilege     = "USAGE"
  roles = [snowflake_role.myreadrole.name]
}

resource "snowflake_stage_grant" "mystagegrant" {
  database_name = "MYDB"
  privilege     = "USAGE"
  roles         = [snowflake_role.myreadrole.name]
  on_all        = true
  on_future     = true
}

resource "snowflake_file_format_grant" "myffgrant" {
  database_name = "MYDB"
  privilege     = "USAGE"
  roles         = [snowflake_role.myreadrole.name]
  on_all        = true
  on_future     = true
}

resource "snowflake_schema_grant" "myschemagrant" {
  database_name = "MYDB"
  privilege     = "USAGE"
  roles         = [snowflake_role.myreadrole.name]
  on_future     = true
  on_all        = true
}

resource "snowflake_table_grant" "mytablegrant" {
  database_name = "MYDB"
  privilege     = "SELECT"
  roles         = [snowflake_role.myreadrole.name]
  on_future     = true
  on_all        = true
}

resource "snowflake_view_grant" "myviewgrant" {
  database_name = "MYDB"
  privilege     = "SELECT"
  roles         = [snowflake_role.myreadrole.name]
  on_future     = true
  on_all        = true
}
```

which is relatively straightforward, additionally if I then go to make a write role, I can reuse some of my grants by simply adding the role to the list of roles I'm apply a given grant to, such as making the database usage grant resource common for the two needs.

Migrating to use `snowflake_grant_privileges_to_role` resources gives the following configuration
```terraform
resource "snowflake_grant_privileges_to_role" "grantdbusage" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["USAGE"]
  on_account_object {
    object_type = "DATABASE"
    object_name = "MYDB"
  }
}

resource "snowflake_grant_privileges_to_role" "grantschemausage" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["USAGE"]
  on_schema {
    all_schemas_in_database = "MYDB"
  }
}

resource "snowflake_grant_privileges_to_role" "grantfutureschemausage" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["USAGE"]
  on_schema {
    future_schemas_in_database = "MYDB"
  }
}

resource "snowflake_grant_privileges_to_role" "grantfileformat" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["USAGE"]
  on_schema_object {
    all {
      object_type_plural = "FILE FORMATS"
      in_database        = "MYDB"
    }
    future {
      object_type_plural = "FILE FORMATS"
      in_database        = "MYDB"
    }
  }
}

resource "snowflake_grant_privileges_to_role" "grantstage" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["USAGE"]
  on_schema_object {
    all {
      object_type_plural = "STAGES"
      in_database        = "MYDB"
    }
    future {
      object_type_plural = "STAGES"
      in_database        = "MYDB"
    }
  }
}

resource "snowflake_grant_privileges_to_role" "granttable" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["SELECT"]
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_database        = "MYDB"
    }
    future {
      object_type_plural = "TABLES"
      in_database        = "MYDB"
    }
  }
}

resource "snowflake_grant_privileges_to_role" "grantview" {
  role_name  = snowflake_role.myreadrole.name
  privileges = ["SELECT"]
  on_schema_object {
    all {
      object_type_plural = "VIEWS"
      in_database        = "MYDB"
    }
    future {
      object_type_plural = "VIEWS"
      in_database        = "MYDB"
    }
  }
}
```

not only is it harder to read thanks to the additional characters and syntax all over the place, we've bloated an additional unnecessary resource, because we can't define that our schema grant is for all current AND future schemas, because that has to be a separate resource. furthermore the need to separate everything into so many resources seems wholly unnecessary anyway.

### Proposal

I propose the following changes

- Support all of `on_account_object` `on_schema` and `on_schema_object` in a single `snowflake_grant_privileges_to_role` block
- move `privileges` into the nested schemas
- in `on_schema` support both `all_schemas_in_database` and `future_schemas_in_database` in the same block
- role_name should take a list of roles
- in the `on_schema_object.all` and `on_schema_object.future` `object_type_plural` should take a list

The result of these changes is two resources instead of the many before, which is more concise and clear as to what is being granted.

```terraform
resource "snowflake_grant_privileges_to_role" "grant_read" {
  role_name  = [snowflake_role.myreadrole.name]
  on_account_object {
    privileges = ["USAGE"]
    object_type = "DATABASE"
    object_name = "MYDB"
  }
  on_schema {
    privileges = ["USAGE"]
    all_schemas_in_database = "MYDB"
    future_schemas_in_database = "MYDB"
  }
  on_schema_object {
    all {
      privileges = ["SELECT"]
      object_type_plural = ["TABLES", "VIEWS"]
      in_database        = "MYDB"
    }
    future {
      privileges = ["SELECT"]
      object_type_plural = ["TABLES" "VIEWS"]
      in_database        = "MYDB"
    }
  }
}

resource "snowflake_grant_privileges_to_role" "grantstage_ff" {
  role_name  = [snowflake_role.myreadrole.name]
  on_schema_object {
    all {
      privileges = ["USAGE"]
      object_type_plural = ["STAGES", "FILE FORMATS"]
      in_database        = "MYDB"
    }
    future {
      privileges = ["USAGE"]
      object_type_plural = ["STAGES", "FILE FORMATS"]
      in_database        = "MYDB"
    }
  }
}
```

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment]
Hey @NovaLogicDev 👋 
Right now, we're finishing redesigns of grant resources and implementing missing ones. There are more reasons behind the current approach and why **snowflake_grant_privileges_to_role** works the way it does. Allowing for multiple grant branches at the same time would make the resource more complicated (because it would make multiple grant calls), which we would like to avoid as it is already fairly complex and still incomplete in some parts. After we'll make our provider more stable we'll be open to modifications like these, but for now please use them as one grant call = one resource. 

I would also advise using [for_each](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) which makes your configurations much shorter. For example (grant usage on every database):
```terraform
resource "snowflake_grant_privileges_to_role" "grant_for_each" {
  role_name  = snowflake_role.myreadrole.name
  for_each = toset(["one_db", "two_db"]) # could also be retrieved by data sources or predefined variables
  privileges = ["USAGE", "CREATE SCHEMA", "MONITOR"]
  on_account_object {
    object_type = "DATABASE"
    object_name = each.key
  }
}
```
As you can see you don't have to repeat the resource and even can specify more privileges ("USAGE", "CREATE SCHEMA", "MONITOR" in this case).

In addition, you can create custom modules that would reduce repetition even more. [Here](https://www.techtarget.com/searchitoperations/tutorial/Learn-how-to-use-Terraform-modules-with-examples) is a good example of how to create one.

**Comment by sfc-gh-jcieslak** [comment]
Closing it due to long inactivity. If the issue persists, please create another ticket.
