### ISSUE TITLE
Error Updating Resource Monitor to add/update triggers

### ISSUE THREAD

**Issue by praveenkumarramalingam** [Snowflake-Labs/terraform-provider-snowflake#2316]
### Terraform CLI and Provider Versions

0.82.0

### Terraform Configuration

```terraform
terraform {
  required_version = "~> 1.6.6"
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.82.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
```

### Expected Behavior

I'm trying to update the warehouse monitor's suspend trigger threshold from x to y number

### Actual Behavior

Terraform Plan is ok but Terraform apply fails. Reason being the SQL generated for altering is incorrect
**Generated SQL**
ALTER RESOURCE MONITOR "AR_DEV_FIN_BI_XS_RM" **SET** TRIGGERS ON 90 PERCENT DO NOTIFY ON 30 PERCENT DO NOTIFY ON 60 PERCENT DO NOTIFY

Rather it is supposed to generate like below one
ALTER RESOURCE MONITOR "AR_DEV_FIN_BI_XS_RM"  TRIGGERS ON 90 PERCENT DO NOTIFY ON 30 PERCENT DO NOTIFY ON 60 PERCENT DO NOTIFY

### Steps to Reproduce

1. Create a resource monitor
2. Try to add or remove new trigger or threshold

### How much impact is this issue causing?

High

### Additional Information

Terraform will perform the following actions:

  # module.warehouses.snowflake_resource_monitor.resource_monitors["AR_DEV_FIN_BI_XS_RM"] will be updated in-place        
  ~ resource "snowflake_resource_monitor" "resource_monitors" {
        id                        = "AR_DEV_FIN_BI_XS_RM"
        name                      = "AR_DEV_FIN_BI_XS_RM"
      ~ suspend_trigger           = 90 -> 95
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.warehouses.snowflake_resource_monitor.resource_monitors["AR_DEV_FIN_BI_XS_RM"]: Modifying... [id=AR_DEV_FIN_BI_XS_RM]
╷
│ Error: error updating resource monitor AR_DEV_FIN_BI_XS_RM
│ 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 58 unexpected 'ON'.
│ syntax error line 1 at position 72 unexpected 'DO'.
│ syntax error line 1 at position 83 unexpected 'ON'.
│ syntax error line 1 at position 97 unexpected 'DO'.
│ syntax error line 1 at position 107 unexpected 'ON'.
│ syntax error line 1 at position 121 unexpected 'DO'.
│ syntax error line 1 at position 131 unexpected 'ON'.
│ syntax error line 1 at position 145 unexpected 'DO'.
│ syntax error line 1 at position 154 unexpected '<EOF>'.
│
│   with module.warehouses.snowflake_resource_monitor.resource_monitors["AR_DEV_FIN_BI_XS_RM"],
│   on ..\modules\common\warehouse\resource_monitors.tf line 1, in resource "snowflake_resource_monitor" "resource_monitors":
│    1: resource "snowflake_resource_monitor" "resource_monitors" {
│

**Comment by sfc-gh-asawicki** [comment]
Hey @praveenkumarramalingam. Thanks for reporting the issue.

It looks like an easy-to-fix bug; we will handle it in the next few days.
