### ISSUE TITLE
snowflake_warehouse resource does not read warehouse parameters

### ISSUE THREAD

**Issue by joedenniss** [Snowflake-Labs/terraform-provider-snowflake#2318]
### Terraform CLI and Provider Versions

Terraform 1.6.6
Provider 0.65.0+

### Terraform Configuration

```terraform
resource "snowflake_warehouse" "warehouse" {
  name           = "TEST_WAREHOUSE"
  warehouse_size = "XSMALL"

  max_concurrency_level        = 2
  statement_timeout_in_seconds = 60
  statement_queued_timeout_in_seconds = 60
}
```

### Expected Behavior

Existing values of `max_concurrency_level`, `statement_timeout_in_seconds` and `statement_queued_timeout_in_seconds` should be read on plan

### Actual Behavior

Values are not read

### Steps to Reproduce

1. `terraform apply`
2. Change warehouse parameters
  i) `alter warehouse TEST_WAREHOUSE set MAX_CONCURRENCY_LEVEL=4;`
  ii) `alter warehouse TEST_WAREHOUSE set STATEMENT_TIMEOUT_IN_SECONDS=120;`
  iii) `alter warehouse TEST_WAREHOUSE set STATEMENT_QUEUED_TIMEOUT_IN_SECONDS=120;`
3. `terraform plan`

### How much impact is this issue causing?

High

### Additional Information

Regression of https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/745, introduced by https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1792

This is particularly dangerous when importing existing warehouses into Terraform, as the provider will obliterate the currently configured values.

**Comment by sfc-gh-asawicki** [comment]
Hey @joedenniss. Thanks for reporting the issue.

It seems that the warehouse read is omitting these parameters. It is either an easy-to-fix problem or a design decision. I will consult with the team and get back to you. If this is the first option, we will solve it in the next few days.
