### ISSUE TITLE
Snowflake_account import timeout

### ISSUE THREAD

**Issue by IRISDavidD** [Snowflake-Labs/terraform-provider-snowflake#2330]
### Terraform CLI and Provider Versions

Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.82.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76"
    }
  }
}
```

### Expected Behavior

terraform import snowflake_account.com_prod {locator}

locator format is ID.REGION.AWS or AZURE

### Actual Behavior

snowflake_account.commercial_prod_useast: Refreshing state... [id=zt70377.us-east-2.a]
╷
│ Error: giving up after 5 attempts
│ 
│ 

### Steps to Reproduce

1. terraform import snowflake_account.com_prod {locator}

### How much impact is this issue causing?

High

### Additional Information

The provider is currently stored in a .env file

SNOWFLAKE_USER="account"
SNOWFLAKE_AUTHENTICATOR=JWT
SNOWFLAKE_PRIVATE_KEY="cat '/Users/key.p8'"
SNOWFLAKE_ACCOUNT="XXXX.eu-west-1.aws"
SNOWFLAKE_ROLE = "ORGADMIN"

**Comment by sfc-gh-asawicki** [comment]
Hey @IRISDavidD. Thanks for reporting the issue.

Please provide the full error log.

**Comment by IRISDavidD** [comment]
We'eve actually
