### ISSUE TITLE
Error provisioning snowflake_dynamic_table 

### ISSUE THREAD

**Issue by ramprasads108** [Snowflake-Labs/terraform-provider-snowflake#2331]
### Terraform CLI and Provider Versions

Terraform v1.3.6  
Snowflake-Labs Terraform provider 0.82.0

### Terraform Configuration

```terraform
terraform {
  required_version = ">= 1.3.6"
  required_providers {
    snowflake = {
      source  = "snowflake-labs/snowflake"
      version = "=0.82.0"
    }
  }
}

provider "snowflake" {
  user    = "I570067"
  authenticator   = "ExternalBrowser"
  account = "hassium-ceshassium"
  role    = "ACCOUNTADMIN"
}



resource "snowflake_dynamic_table" "example" {
  database   = "DEV_90467_DB"
  schema     = "HASS_DEMO_TEST"
  name       = "RSSSSS_DYNAMIC_TABLE"

  target_lag {
    maximum_duration = "20 minutes"
  }
  warehouse = "COMPUTE_WH"
  query     = "SELECT * from HASS_DEMO_TABLE"
  comment   = "example dynamic table"
}
```

### Expected Behavior

create a dynamic table in our snowflake account

### Actual Behavior

 terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # snowflake_dynamic_table.example will be created
  + resource "snowflake_dynamic_table" "example" {
      + automatic_clustering = (known after apply)
      + bytes                = (known after apply)
      + cluster_by           = (known after apply)
      + comment              = "example dynamic table"
      + data_timestamp       = (known after apply)
      + database             = "DEV_90467_DB"
      + id                   = (known after apply)
      + is_clone             = (known after apply)
      + is_replica           = (known after apply)
      + last_suspended_on    = (known after apply)
      + name                 = "RSSSSS_DYNAMIC_TABLE"
      + or_replace           = false
      + owner                = (known after apply)
      + query                = "SELECT * from HASS_DEMO_TABLE"
      + refresh_mode         = (known after apply)
      + refresh_mode_reason  = (known after apply)
      + rows                 = (known after apply)
      + scheduling_state     = (known after apply)
      + schema               = "HASS_DEMO_TEST"
      + warehouse            = "COMPUTE_WH"

      + target_lag {
          + maximum_duration = "20 minutes"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
snowflake_dynamic_table.example: Creating...
╷
│ Error: [errors.go:17] object does not exist or not authorized
│
│   with snowflake_dynamic_table.example,
│   on main.tf line 21, in resource "snowflake_dynamic_table" "example":
│   21: resource "snowflake_dynamic_table" "example" {
│
╵

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @ramprasads108. Thanks for reporting the issue.

Can you try specifying the fully qualified name for the table in the `query`?

If it does not help, please provide the full debug log with the error.

**Comment by ramprasads108** [comment]
Hey @sfc-gh-asawicki tried with fully qualified name for the table
[Uploading dyn.log…]()
. attaching debug log

same  error 





terraform {
  required_version = ">= 1.3.6"
  required_providers {
    snowflake = {
      source  = "snowflake-labs/snowflake"
      version = ">=0.82.0"
    }
  }
}

provider "snowflake" {
  user    = "I570067"
  authenticator   = "ExternalBrowser"
  account = "hassium-ceshassium"
  role    = "ACCOUNTADMIN"
}





resource "snowflake_dynamic_table" "example" {
  database   = "DEV_90467_DB"
  schema     = "HASS_DEMO_TEST"
  name       = "RSSSSS_DYNAMIC_TABLE"

  target_lag {
    maximum_duration = "20 minutes"
  }
  warehouse = "COMPUTE_WH"
  query     = "SELECT * from HASS_DEMO_TEST.HASS_DEMO_TABLE"
  comment   = "example dynamic table"
}

[dyn.log](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/13892872/dyn.log)

**Comment by sfc-gh-asawicki** [comment]
Hey @ramprasads108.

The fully qualified name for tables consists of three parts: database, schema, and table. Please try again, to confirm that it does not help.

Additionally, do you have all the required grants to perform the `CREATE` (https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table#access-control-requirements)?

**Comment by ramprasads108** [comment]
fully qualified works. thanks

**Comment by ramprasads108** [comment]
fully qualified works. thanks
