### ISSUE TITLE
snowflake_tag_association syntax update causes the provider to crash

### ISSUE THREAD

**Issue by abdulkaderf** [Snowflake-Labs/terraform-provider-snowflake#2335]
### Terraform CLI and Provider Versions

Terraform v1.5.4
on darwin_arm64

provider v0.82.0

### Terraform Configuration

```terraform
resource "snowflake_database" "db" {
  name    = "db_name"
  comment = "comment here"

  lifecycle {
    prevent_destroy = true
  }
}

resource "snowflake_tag" "tag_name" {
  name           = "tag_name"
  database       = snowflake_database.db.name
  schema         = "schema_name"
  allowed_values = ["value1", "value2"]
}

resource "snowflake_tag_association" "tag_assoc" {
  object_identifier {
    name     = snowflake_database.db.name    
  }
  object_type     = "DATABASE"
  tag_id          = snowflake_tag.tag_name.id
  tag_value       = var.variable_with_value
  skip_validation = true
}
```

### Expected Behavior

updating the syntax of `snowflake_tag_association` to use the `object_identifier` instead of `object_name`, should result in a smooth run for the terraform plan.

### Actual Behavior

The plugin crashed

### Steps to Reproduce

1. Run a terraform code containing the `snowflake_tag_association` resource with its old syntax (using the `object_name` attribute) using an older provider version (0.47.0 in our case)
2. Upgrade the provider version to 0.82.0
3. Update the syntax of the `snowflake_tag_association` resource to use an `object_identifier` object
4. Run `terraform plan`

### How much impact is this issue causing?

Medium

### Logs

https://gist.github.com/abdulkaderf/dfc5a72b16b80f9cbdfb450c06250fe1

### Additional Information

It seems that the only workaround is to completely destroy the object and remove it from the state, then create it again. This is cumbersome for our setup as there are many state files in which this resource exists.

**Comment by sfc-gh-asawicki** [comment]
Hey @abdulkaderf. Thanks for reporting the issue.

You are updating from an ancient version. We are still in an experimental phase (0.x.x version), so the schema migration between the versions does not always go smoothly. In this case, I suggest destroying the object and recreating it.

**Comment by abdulkaderf** [comment]
Thanks @sfc-gh-asawicki. 
In the context of migration as well, we noticed that `enable_multiple_grants` is no longer an option in the new `snowflake_grant_privileges_to_role` resource. Is the default behavior equivalent to setting it to true on the deprecated resources? I couldn't find any documentation on that. Thanks in advance.

**Comment by sfc-gh-asawicki** [comment]
@sfc-gh-jcieslak can you help with this one?

**Comment by abdulkaderf** [comment]
Thanks @sfc-gh-jcieslak ! Looking forward :)
