### ISSUE TITLE
Error: The terraform-provider-snowflake_ [v0.75.0 - 0.83.1] plugin crashed! on adding New roles and associated grants

### ISSUE THREAD

**Issue by saurabh2208** [Snowflake-Labs/terraform-provider-snowflake#2358]
### Terraform CLI and Provider Versions

Provider version -> v0.75.0 - v.0.83.1

Terraform CLI version -> 1.2.9

### Terraform Configuration

```terraform
resource "snowflake_role" "warehouse_monitor_role" {
  count   = var.warehouse_config["create_access_roles"] ? 1 : 0
  name    = "${local.warehouse_name}_MONITOR_ONLY"
  comment = "${local.warehouse_name} database role for Monitor Privilege to enable query history"
}

resource "snowflake_grant_privileges_to_role" "warehouse_monitor_role_1" {
  count      = var.warehouse_config["create_access_roles"] ? 1 : 0
  role_name  = snowflake_role.warehouse_monitor_role[count.index].name
  privileges = ["MONITOR"]
  on_account_object {
    object_type = "WAREHOUSE"
    object_name = local.warehouse_name
  }

  depends_on = [
    snowflake_warehouse.warehouse
  ]
}

resource "snowflake_role_grants" "warehouse_monitor_role_2" {
  count     = var.warehouse_config["create_access_roles"] ? 1 : 0
  role_name = snowflake_role.warehouse_monitor_role[count.index].name

  roles = [
    "SYSADMIN"
  ]

  depends_on = [
    snowflake_warehouse.warehouse
  ]
}
```

### Expected Behavior

Update the changes along with add new roles with No error

### Actual Behavior

All plugin versions are generating similar error output:

`Error: -16T14:28:57.293Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.294Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.295Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.295Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.295Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.296Z [ERROR] vertex "module.warehouses[\"DBT_COMMON_WH\"].snowflake_role.warehouse_monitor_role[0]" error: Plugin did not respond
Error: -16T14:28:57.296Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.296Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.296Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.296Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.296Z [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
Error: -16T14:28:57.298Z [ERROR] vertex "module.warehouses[\"DBT_INVEST_WH\"].snowflake_role.warehouse_monitor_role[0]" error: Plugin did not respond
Error: -16T14:28:57.300Z [ERROR] vertex "snowflake_warehouse.warehouse[\"SCRATCH_WH\"]" error: Plugin did not respond
Error: -16T14:28:57.301Z [ERROR] vertex "snowflake_oauth_integration.dbt_cloud[0]" error: Plugin did not respond
Error: -16T14:28:57.303Z [ERROR] vertex "snowflake_user.user[\"DBT_INVEST\"]" error: Plugin did not respond
Error: -16T14:28:57.304Z [ERROR] vertex "snowflake_warehouse.warehouse[\"DBT_COMMON_WH\"]" error: Plugin did not respond
Error: -16T14:28:57.305Z [ERROR] vertex "snowflake_user.user[\"DBT_COMMON\"]" error: Plugin did not respond
Error: -16T14:28:57.307Z [ERROR] vertex "module.warehouses[\"DATA_INGESTION_WH\"].snowflake_role.warehouse_monitor_role[0]" error: Plugin did not respond
Error: -16T14:28:57.308Z [ERROR] vertex "module.warehouses[\"TS_BI_WH\"].snowflake_role.warehouse_monitor_role[0]" error: Plugin did not respond
Error: -16T14:28:57.309Z [ERROR] vertex "module.warehouses[\"SCRATCH_WH\"].snowflake_role.warehouse_monitor_role[0]" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-snowflake_v0.83.1 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 88 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateOAuthIntegration(0xc000a28c00, {0x1fc48c0?, 0xc000ade340})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/oauth_integration.go:313 +0xa74
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x234a7a8?, {0x234a7a8?, 0xc000f4bb30?}, 0xd?, {0x1fc48c0?, 0xc000ade340?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007bb7a0, {0x234a7a8, 0xc000f4bb30}, 0xc000f365b0, 0xc000a28a80, {0x1fc48c0, 0xc000ade340})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000a08558, {0x234a7a8?, 0xc000f4b980?}, 0xc000f41090)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x235fdc0?, 0xc000a08558?}}, {0x234a7a8, 0xc000f4b980}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x234a7e0?, {0x234a7a8?, 0xc000f4b680?}, 0xc000f41040)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x[193](https://github.com/cmctechnology/data-cdp-dw/actions/runs/7543033983/job/20533143587#step:30:194)
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000a023c0, {0x234a7a8?, 0xc000f4ae70?}, 0xc00099dce0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1f76820?, 0xc000a023c0}, {0x234a7a8, 0xc000f4ae70}, 0xc000a28600, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000dad20, {0x234a7a8, 0xc000f4ade0}, {0x235b0c0, 0xc00078e680}, 0xc000f527e0, 0xc00061d1d0, 0x330db58, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0000dad20, {0x235b0c0, 0xc00078e680}, 0xc000f527e0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 35
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.83.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Process completed with exit code 1.`

### Steps to Reproduce

terraform apply

### How much impact is this issue causing?

High

### Additional Information

I was initially authenticating user via private_key_path & private_key_passphrase. The last working version was 0.72.0.
Have recently figured out change in authentication, private key being deprecated so changed to password authentication. Below is what now provider looks like:

`provider "snowflake" {
  user    = var.snowflake_username
  account = local.snowflake_account
  # region                 = local.region
  role = var.snowflake_terraform_role
  # private_key_path       = var.SNOWFLAKE_PK_PATH
  # private_key_passphrase = var.SNOWFLAKE_PK_PASSPHRASE
  password = var.SNOWFLAKE_TERRAFORM_ACCESS_KEY
  # authenticator = "Snowflake"
}`

**Comment by sfc-gh-asawicki** [comment]
Hey @saurabh2208. Thanks for reporting the issue.

I think you should use `JWT` for the `authenticator`: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#behavior-change-authenticator-jwt.

**Comment by saurabh2208** [comment]
Hi @sfc-gh-asawicki 

Guess I didn't put commented statements properly under code snippet. Here is the current provider snippet:
`provider "snowflake" {
  user    = var.snowflake_username
  account = local.snowflake_account
  role = var.snowflake_terraform_role
  password = var.SNOWFLAKE_TERRAFORM_ACCESS_KEY
}`

**Comment by sfc-gh-asawicki** [comment]
@saurabh2208 I can't see that in the config you provided, but looking at the logs provided the issue appears to be in `blocked_roles_list` in `snowflake_oauth_integration` resource. Can you provide the config for this?

**Comment by saurabh2208** [comment]
@sfc-gh-asawicki Here is the oauth integration resource snippet.

`resource "snowflake_oauth_integration" "dbt_cloud" {
  count                        = local.dev-env ? 1 : 0
  name                         = "DBT_CLOUD"
  oauth_client                 = "CUSTOM"
  oauth_client_type            = "CONFIDENTIAL"
  oauth_redirect_uri           = "xxxxxx"
  enabled                      = true
  oauth_issue_refresh_tokens   = true
  oauth_refresh_token_validity = 7776000
  blocked_roles_list           = ["SYSADMIN", "DATA_CDP_CD_ROLE", "DATA_CDP_CD_ROLE_NONPROD", "DATA_CDP_CD_ROLE_PROD"]
}`

**Comment by sfc-gh-swinkler** [comment]
I agree with @sfc-gh-asawicki , the error has nothing to do with the resources you are adding to your configuration, but instead to the oauth resource. Looking at the line 313 of oauth_integration.go

`		stmt.SetStringList(`BLOCKED_ROLES_LIST`, expandStringList(d.Get("blocked_roles_list").([]interface{})))
`
Seems to match with the panic message you are seeing:

> panic: interface conversion: interface {} is *schema.Set, not []interface {}

I think we should be doing this instead:

```
stmt.SetStringList(`BLOCKED_ROLES_LIST`, expandStringList(d.Get("privileges").(*schema.Set).List())) 
```

**Comment by sfc-gh-asawicki** [comment]
@saurabh2208 thanks for the config; this confirmed my suspicions. It is easily solvable, as Scott described. We will apply the fix in the upcoming days.
