### ISSUE TITLE
Warning: Argument is deprecated for Snowflake provider

### ISSUE THREAD

**Issue by kanocarra** [Snowflake-Labs/terraform-provider-snowflake#2368]
### Terraform CLI and Provider Versions

Terraform version: 1.3.9
Provider version: 0.82.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.32.1"
    }
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~>0.82"
    }
  }
  backend "s3" {}
}

provider "aws" {
  region = var.region
}

provider "snowflake" {
  role          = "SYSADMIN"
  alias         = "sys_admin"
  authenticator = "JWT"
}

provider "snowflake" {
  role          = "ACCOUNTADMIN"
  alias         = "account_admin"
  authenticator = "JWT"
}

provider "snowflake" {
  role          = "SECURITYADMIN"
  alias         = "security_admin"
  authenticator = "JWT"
}
```

### Expected Behavior

When upgrading from 0.69 -> 0.82 terraform-provider-snowflake, I am seeing a warning message in regards to the `provider` but do not understand how to address it as it doesn't tell me _which_ argument is deprecated. 

I would expect it to tell me _which_ argument it is so I can resovle it?

### Actual Behavior

Getting the following warning:

```
│ Warning: Argument is deprecated
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].sys_admin,
│   on main.tf line 19, in provider "snowflake":
│   19: provider "snowflake" {
│ 
│ use the [file Function](https://developer.hashicorp.com/terraform/language/functions/file) instead
│ 
│ (and 7 more similar warnings elsewhere)
╵
```

Note that I use a private key to auth with Snowflake, not username/password

### Steps to Reproduce

1. Upgrade to 0.82 with the above `main.tf` settings
2. Run `terraform plan`

### How much impact is this issue causing?

Low

**Comment by sfc-gh-asawicki** [comment]
Hey @kanocarra. Thanks for reporting the issue.

The warning concerns `private_key_path`; please use `private_key` with the mentioned `file` function.

Remember, these are just deprecation warnings, not breaking the configuration.
