### ISSUE TITLE
Unable to assign database ownership and future schema ownership grants using snowflake_grant_privileges_to_role

### ISSUE THREAD

**Issue by gdelia-pm** [Snowflake-Labs/terraform-provider-snowflake#2383]
### Terraform CLI and Provider Versions

PS C:\proj\GitRepo\Snowflake_Terraform> .\terraform.exe version
Terraform v1.7.0
on windows_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.84.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_role" "DB_OWNERSHIP-SYSADMIN" {
  for_each = { for db in var.DB_SCHEMA_MAPPING : db.database => db... }

  privileges = ["OWNERSHIP"]
  role_name  = "SYSADMIN"

  on_account_object {
    object_type = "DATABASE"
    object_name = each.key
  }
}

resource "snowflake_grant_privileges_to_role" "SCHEMA_OWNERSHIP-SYSADMIN" {
  for_each = { for ds in var.DB_SCHEMA_MAPPING : "${ds.database}_${ds.schema}" => ds }

  privileges = ["OWNERSHIP"]
  role_name  = "SYSADMIN"

  on_schema {
    future_schemas_in_database = each.value.database
  }
}
```

### Expected Behavior

1. plan to evaluate successfully
2. apply to evaluate successfully
3. apply to complete and all my databases to be owned by sysadmin and new schemas to also be owned by sysadmin

### Actual Behavior

1. plan evaluates successfully
2. apply evaluates successfully
3. when applying the plan it fails and we see the below 

```
Error: error granting privileges to account role: 003504 (01000): A future grant with privilege OWNERSHIP on object type SCHEMA already exists in the schema.

   with snowflake_grant_privileges_to_role.SCHEMA_OWNERSHIP-SYSADMIN["STG_RAW_FIRM_MARKET_DATA"],
   on 1-db_creation.tf line 26, in resource "snowflake_grant_privileges_to_role" "SCHEMA_OWNERSHIP-SYSADMIN":
   26: resource "snowflake_grant_privileges_to_role" "SCHEMA_OWNERSHIP-SYSADMIN" {

Error: error granting privileges to account role: 003504 (01000): A future grant with privilege OWNERSHIP on object type SCHEMA already exists in the schema.

   with snowflake_grant_privileges_to_role.SCHEMA_OWNERSHIP-SYSADMIN["DEV_AY_RAW_SNAPSHOTS"],
   on 1-db_creation.tf line 26, in resource "snowflake_grant_privileges_to_role" "SCHEMA_OWNERSHIP-SYSADMIN":
   26: resource "snowflake_grant_privileges_to_role" "SCHEMA_OWNERSHIP-SYSADMIN" {

```

### Steps to Reproduce

1. Use snowflake_grant_privileges_to_role to set ownership on a database
2. Use snowflake_grant_privileges_to_role to set ownership on future schemas in the same database 
3. run terraform plan which shows the config as presumably valid
4. on application of the plan, it will fail wiht the error shown above

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment]
Hey @gdelia-pm 
I would say that's more Snowflake misuse than the TF Provider bug. That's a Snowflake error that says `grant x on future schemas in database y` have been called on this object (by Terraform or it was granted previously outside of the Terraform). Also, I would say `snowflake_grant_privileges_to_role` is not that well suited for granting ownership. You can use it for now, but soon, we should start the work on the grant ownership resource which should handle different cases. But I guess it makes sense in this case because Snowflake doesn't allow to transfer of ownership from role to role that already has it.

**Comment by gdelia-pm** [comment]
Thanks for responding here, I guess I thought (incorrectly) that we should have been using the snowflake_grant_privileges_to_role for ownership as using the snowflake_schema_grant option gives an deprecated resource warning on every run. 

I'll use that along with snowflake_database_grant to set these and wait for a newer resource to come along instead to manage this.  Any eta on what that would be availalbe?

**Comment by sfc-gh-jcieslak** [comment]
You can also use ** snowflake_role_ownership_grant** for managing ownership transfer. It's also deprecated and will be replaced by the newer resource, but it should be better at managing ownership. Cannot give you the exact eta, but it **may** be somewhere around next quarter. To be honest the error should also be visible when using **snowflake_database_grant**. The error comes from Snowflake, not the provider. If the error is not returned I would be suspicious of either deprecated resource not doing the call (or alternating it to something else) or the configuration is doing something else and thus not triggering the error.

**Comment by gdelia-pm** [comment]
Ah I see what you mean.  With the snowflake_database_grant  it's assigning a second ownership grant, and leaving the old grant in place despite having enable_multiple_grants set to false. 
Next quarter-ish is fine for us, as this is not really a blocker for us, just a non perfect setup.  Thanks for detailed info here Jan, was very helpful for me to trace what is happening here vs. on the snowflake side.
