### ISSUE TITLE
allow to specify noorder/order parameter for  sequence resource

### ISSUE THREAD

**Issue by bohuslav-broza** [Snowflake-Labs/terraform-provider-snowflake#2387]
### Terraform CLI and Provider Versions

TF 1.7.0
provider 0.84.0

### Use Cases or Problem Statement

With coming change in sequence behaviour https://docs.snowflake.com/en/release-notes/bcr-bundles/2024_01/bcr-1483 the support for ORDER and NOORDER parameters is missing in provider sequence resource. 

### Proposal

Add support to specify order and noorder parameters. Something like =>

resource snowflake_sequence sequence {
  database = "db"
  schema   = "test"
  name     = "seq1"
  order  = true
}

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-asawicki** [comment]
Hey @bohuslav-broza. Thanks for creating the issue.

We will be migrating sequence resource to the new SDK implementation; we may be able to address this change there.

**Comment by bohuslav-broza** [comment]
Hi, any time plan for this activity or any source to follow? thx

**Comment by bohuslav-broza** [comment]
handled in [PR #2351 ](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2351)
