### ISSUE TITLE
snowflake_grant_privileges_to_role TASK OWNERSHIP permadrift

### ISSUE THREAD

**Issue by liamjamesfoley** [Snowflake-Labs/terraform-provider-snowflake#2414]
### Terraform CLI and Provider Versions

terraform version = 1.5.2
provider version = 0.84.1

### Terraform Configuration

```
module "operation_db_tasks_schema" {
  source        = "./stack/snowflake/unmanaged-schema"
  database_name = module.operation_db_database.name
  name          = "TASKS"
  comment       = "MANAGED BY Terraform, FOR TASKS ONLY!"
  usage_roles = [
    snowflake_role.analyst.name,
  ]
}

module "analytics_prod_sam_fcr_task" {
  source          = "./stack/snowflake/task"
  task_name       = "SAM_FCR"
  schedule        = "USING CRON 30 * * * * America/Los_Angeles"
  sql_statement   = file("tasks_sql_scripts/sam_fcr.sql")
  warehouse_name  = module.analytics_wh_warehouse.warehouse_name
  task_owner_role = snowflake_role.analyst.name
}
```
...
Module Definition
....
```
resource "snowflake_task" "task" {
  comment = var.comment

  database  = "OPERATION_DB"
  schema    = "TASKS"
  warehouse = var.warehouse_name

  name          = var.task_name
  schedule      = var.schedule
  sql_statement = var.sql_statement

  session_parameters = var.session_parameters

  user_task_timeout_ms = var.task_timeout
  after                = var.after
  when                 = var.when
  enabled              = var.enabled

  lifecycle {
    ignore_changes = [enabled]
  }
}

resource "snowflake_grant_privileges_to_role" "task_owner_grant" {
  privileges = ["OWNERSHIP"]
  role_name  = var.task_owner_role
  on_schema_object {
    object_type = "TASK"
    object_name = "OPERATION_DB.TASKS.${snowflake_task.task.name}"
  }
}
```

### Expected Behavior

We should not see any changes detected when the Snowflake matches terraform.

```
SHOW TASKS IN OPERATION_DB.TASKS;
```
<img width="100" alt="image" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/4086743/7296b13c-576b-405b-86e2-4e3d769b9c1a">

### Actual Behavior

We see changes detected on this resource for every plan.

```
  # module.analytics_prod_sam_fcr_task.snowflake_grant_privileges_to_role.task_owner_grant will be updated in-place
  ~ resource "snowflake_grant_privileges_to_role" "task_owner_grant" {
        id                = "ANALYST|OWNERSHIP|false|false|false|false|false|true|false|false|TASK|OPERATION_DB.TASKS.SAM_FCR||false||false|"
      ~ privileges        = [
          + "OWNERSHIP",
        ]
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

Queue up a plan in TFE after no changes when the infra should match.

### How much impact is this issue causing?

High

**Comment by liamjamesfoley** [comment]
@sfc-gh-jcieslak Thanks! I'll close this issue once you've got that doc available. Thanks again!

**Comment by liamjamesfoley** [comment]
@sfc-gh-jcieslak Wait... How would `snowflake_role_ownership_grant` work? there's no option to use a task?

Do you mean `snowflake_task_grant`?

**Comment by sfc-gh-jcieslak** [comment]
Yeah, sorry. I meant `snowflake_task_grant`. It should work with ownership privilege. If not there's also an option to use [unsafe execute resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute) which is used to execute raw SQL (in case `snowflake_task_grant` would also fail)
