### ISSUE TITLE
Enable change_tracking on view

### ISSUE THREAD

**Issue by vthelu** [Snowflake-Labs/terraform-provider-snowflake#2430]
### Terraform CLI and Provider Versions

0.84.1

### Use Cases or Problem Statement

Enable change_tracking on view

### Proposal

Enable change_tracking on view

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @SteveGad12345 👋
Yesterday, we released a new provider version ([v0.95.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.95.0)) that allows to specify `change_tracking`. Please upgrade using the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md).

**Comment by sfc-gh-jmichalak** [comment]
Closing the issue due to inactivity.
