### ISSUE TITLE
Event Table resource missing?

### ISSUE THREAD

**Issue by juliankeppel** [Snowflake-Labs/terraform-provider-snowflake#2452]
### Terraform CLI and Provider Versions

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.84.1

### Use Cases or Problem Statement

Deploying and managing event tables with the Snowflake Terraform provider.

According to [this release note](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2230), it should already be there, but I can't find it in the docs and can't acutally use it in my code. I wonder if I'm missing something or if this is a bug.

### Proposal

Shouldn't the event table resource be there?

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-asawicki** [comment]
Hey @juliankeppel. Thanks for reaching out to us.

The message you are talking about was about adding the event table object SDK. The resource is still missing, but introducing it in the SDK allows us to implement it faster.

As for the event_table resource being missing, we have adding missing resources on our roadmap: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap. We'll be sure to add it then.

**Comment by juliankeppel** [comment]
Thank you @sfc-gh-asawicki for this answer.
