### ISSUE TITLE
Failed to instantiate provider "registry.terraform.io/snowflake-labs/snowflake" 

### ISSUE THREAD

**Issue by simplecoder** [Snowflake-Labs/terraform-provider-snowflake#2461]
### Terraform CLI and Provider Versions

TF: 0.13.5
Snowflake provider: 0.85.0

### Terraform Configuration

```terraform
Upgrading from snowflake provider 0.75.0 to 0.85.0 gives an error
```

### Expected Behavior

Provider runs fine with tf 0.13.5

### Actual Behavior

Error: Could not load plugin

Failed to instantiate provider
"registry.terraform.io/snowflake-labs/snowflake" to obtain schema:
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### How much impact is this issue causing?

Medium

**Comment by danu165** [comment]
I’m not sure if it’s spelled out somewhere but at some point it did become a requirement to use at least terraform version 1.1.5

**Comment by sfc-gh-asawicki** [comment]
Hey @simplecoder. Thanks for reaching out to us.

As @danu165 wrote, please bump your Terraform CLI to at least 1.1.5 and try the migration then.
