### ISSUE TITLE
Managed account broken after rename in 0.85

### ISSUE THREAD

**Issue by chrisluedtke** [Snowflake-Labs/terraform-provider-snowflake#2464]
### Terraform CLI and Provider Versions

```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/aidanmelen/snowsql v0.3.0
+ provider registry.terraform.io/hashicorp/azurerm v3.50.0
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
+ provider registry.terraform.io/snowflake-labs/snowflake v0.85.0
```

### Terraform Configuration

```terraform
resource "snowflake_managed_account" "reader_account" {
  count          = var.reader_account_enabled ? 1 : 0
  name           = "MASTERYINTERNAL_DEV"
  admin_name     = "admin"
  admin_password = random_password.reader_account_admin_password[0].result
  type           = "READER"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior

Terraform should be able to refresh the state of this resource.

### Actual Behavior

I changed the name of a managed account via
1. ```sql
   ALTER ACCOUNT MM100DEVREADER RENAME TO MASTERYINTERNAL_DEV SAVE_OLD_URL = TRUE;
    ```
2. ```
   terraform state rm 'snowflake_managed_account.reader_account[0]'
   terraform import 'snowflake_managed_account.reader_account[0]' MM100DEVREADER
    ```
    **Note:** even though we changed the name, we still had to re-use the old ID in the import statement.

After upgrading to 0.85, this resource now fails.

```
╷
│ Error: giving up after 5 attempts
│ 
│   with snowflake_managed_account.reader_account[0],
│   on reader_account.tf line 1, in resource "snowflake_managed_account" "reader_account":
│    1: resource "snowflake_managed_account" "reader_account" {
│ 
╵
```

In snowflake, I see the following behavior:

```sql
-- Using the old account name returns one row with account named MASTERYINTERNAL_DEV
SHOW MANAGED ACCOUNTS LIKE 'MM100DEVREADER';

-- Using the new account name returns nothing
SHOW MANAGED ACCOUNTS LIKE 'MASTERYINTERNAL_DEV';
```

If I revert to 84.1, the issue disappears.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @chrisluedtke. Thanks for reaching out to us.

In the terraform provider, we are limited to what Snowflake returns through the API. So basically, we are executing the same statement as you (`SHOW MANAGED ACCOUNTS LIKE ...`). Please reach out to Snowflake support or to your account manager, to verify if this is the correct behavior after the rename (i.e. SHOW returning row using old name in like and returning nothing using the new name).

**Comment by chrisluedtke** [comment]
Thanks, I opened this ticket because the behavior was not seen in 0.84.1, and I saw some recent code changes pertaining to managed accounts. I also opened a Snowflake support ticket, and was informed that `save_old_url = true` is not supported when renaming managed accounts.
