### ISSUE TITLE
snowflake_grant_privileges_to_role all_privileges=true not updating the DB state correctly

### ISSUE THREAD

**Issue by mohideenbilal** [Snowflake-Labs/terraform-provider-snowflake#2467]
### Terraform CLI and Provider Versions

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.70.1"
    }
  }
}

### Terraform Configuration

```terraform
terraform script #1:

resource "snowflake_grant_privileges_to_role" "warehouse_grant" {
  role_name = ROLE_1
  on_account_object {
    object_type = "WAREHOUSE"
    object_name = snowflake_warehouse.warehouse.name
  }
  all_privileges    = true
  with_grant_option = true
}

after apply successfully creating the warehouse all_privileges for the role.
now some other script removed ["USAGE", "MONITOR"] privileges  from the role in the DB

now when we again plan/apply above terraform script we expect again all_privileges  in this case missing ["USAGE", "MONITOR"] should be created.but its not creating these privilages db still missing ["USAGE", "MONITOR"]
```

### Expected Behavior

create all missing privileges in the DB after reapply the terraform script

### Actual Behavior

Not creating missing privileges in the DB after reapply the terraform script

### Steps to Reproduce

1. `terraform apply`
 
2.Remove/Revoke  any privilege's  e.g ["USAGE", "MONITOR"] from the DB directly by script or any ways.

3.Again plan and apply 
terraform plan
terraform apply

### How much impact is this issue causing?

Medium

### Additional Information

if we specify the privilages explicitly them its working fine instead of  all_privileges    

resource "snowflake_grant_privileges_to_role" "warehouse_grant" {
  role_name = local.role_name
  on_account_object {
    object_type = "WAREHOUSE"
    object_name = "DEV_TEST_WH"
  }
  privileges        = ["APPLYBUDGET", "MODIFY", "USAGE", "MONITOR", "OPERATE"]
  with_grant_option = true
}

**Comment by sfc-gh-jcieslak** [comment]
Hey @mohideenbilal 👋 
Is there a possibility to try the latest version of the provider (0.85.0 at that time) to see if the issue has been resolved or not? In the latest versions, there were a lot of refactors in grant resources, which could resolve the issue. Also, in the latest versions we provided a newer version of `snowflake_grant_privileges_to_role` named `snowflake_grant_privileges_to_account_role`. We prepared a guide that may help you with migration in case where `snowflake_grant_privileges_to_account_role` would work for you. [The migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md).

**Comment by ike-lacey** [comment]
We're having a similar issue that I think might be related. If its not I'd happily open another bug.
Following resource is unable to be. imported
```
resource "snowflake_grant_privileges_to_account_role" "XX_warehouses" {
  privileges = ["USAGE"]
  account_role_name = "AD_HOC_USR"
  always_apply      = false
  with_grant_option = false
  on_account_object {
    object_type = "WAREHOUSE"
    object_name = "XX_WH"
  }
}
```

`terraform import snowflake_grant_privileges_to_account_role.ad_hoc_warehouses "AD_HOC_USR|false|false|USAGE|OnAccountObject|WAREHOUSE|XX_WH"`

import command just returns "killed"
Turning the logs higher, seems to give no indicator as to whats going on.
The import will lock the workspace, but not unlock the workspace.
No SQL commands are run against the db by the user when checked.

**Comment by sfc-gh-jcieslak** [comment]
@mohideenbilal Hey again,
Sorry, but I didn't understand the issue at first. The `all_privileges` option is **not** tracking the privileges on the Snowflake side for a few reasons. In the future, we're planning to go through this issue and decide what the solution should be. For now, If you would like Terraform to be aware of privileges in Snowflake and re-apply privileges that could be removed by another config, you have to explicitly pass all of the privileges for that object type individually in the `privileges` field.

@ike-lacey "XX_warehouses" is the name of the resource and in the command, you refer to it as "ad_hoc_warehouses". Is that it or this was changed before putting it into a comment? (I think you can create a new issue for that if that's not the case and you are not able to import the resource)

**Comment by sfc-gh-jcieslak** [comment]
Hey @mohideenbilal 
In the latest version, we provided a flag in the newer resource `snowflake_grant_privileges_to_account_role` called `always_apply` which will apply all_privileges on every `terraform apply` and possibly `terraform plan` which could solve your issue for now. As I previously said the option for tracking privileges is not yet decided, but we'll have this conversation in the future and change the resource accordingly. If the provided workaround (`always_apply` flag) is working for you and you're fine with using it, please close this issue.

**Comment by bob-zarkoob** [comment]
@sfc-gh-jcieslak I am using the 0.87.2 version and using always_apply flag. according to the docuemtntaion this flag should cause a plan everytime terraform runs, but that is not doing that for me.
Here is an example of terraform config file I have:
```
resource "snowflake_grant_privileges_to_account_role" "db_full_arl_8" {
  count             = length(local.db_role_mapping_1)
  with_grant_option = false
  all_privileges    = true
  always_apply      = true

  account_role_name = local.db_role_mapping_1[count.index]["role"]
  on_schema_object {
    future {
      object_type_plural = "VIEWS"
      in_database        = local.db_role_mapping_1[count.index]["db"]
    }
  }
}
```

**Comment by sfc-gh-jcieslak** [comment]
@bob-zarkoob I'll take a look at it as soon as possible

**Comment by bob-zarkoob** [comment]
Thank you so much @sfc-gh-jcieslak.

**Comment by sfc-gh-jcieslak** [comment]
Hey as the issue got a little bit off topic, @bob-zarkoob could you open another issue describing your issue with `always_apply`? It would be much easier to manage on our end. I've checked this case and it looks like the `always_apply` is not read from the configuration during resource creation. That means you have to unset it and set it back to make it work (or create it with `always_apply` set to `false` and set it to `true` in the next `terraform apply`). Please use this workaround for now, and create another issue, so I'll put it into our backlog to work on it as soon as possible.
