### ISSUE TITLE
Possible wrong string escape method.

### ISSUE THREAD

**Issue by AntoniJakubiak** [Snowflake-Labs/terraform-provider-snowflake#2475]
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/018bb74429d95a2554b3418061fdf3eacb3c735a/pkg/snowflake/table.go#L10

This method will not support quotation marks inside the escaped string.

**Comment by sfc-gh-asawicki** [comment]
Hey @AntoniJakubiak. Thanks for creating the ticket.

This is a deprecated method used only for the column names. There shouldn't be any more quotation marks. It will be removed with the upcoming redesign of the existing resources (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap).
