### ISSUE TITLE
Deprecation error message after provider upgrade from 0.66.2 to 0.85.0

### ISSUE THREAD

**Issue by toni-moreno** [Snowflake-Labs/terraform-provider-snowflake#2476]
### Terraform CLI and Provider Versions

cli 1.5.0
provider  0.85.0 

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.85.0"
    }
    snowsql = {
      source  = "aidanmelen/snowsql"
      version = ">= 0.1.0"
    }
  }
}

provider "snowflake" {
  alias = "UA"
  role  = "USERADMIN"
}

provider "snowflake" {
  alias = "SECA"
  role  = "SECURITYADMIN"
}

provider "snowflake" {
  alias = "SA"
  role  = "SYSADMIN"
}

provider "snowflake" {
  alias = "AAD"
  role  = "AAD_PROVISIONER"
}


and environment var.

```bash
SNOWFLAKE_USER=MYADMIN_USER
SNOWFLAKE_PASSWORD=MY_PASSWORD
SNOWFLAKE_REGION=<some_azure_region>
SNOWFLAKE_ACCOUNT=xx0000
```

### Expected Behavior

Everything ok after provider upgrate. 

### Actual Behavior

this deprecation warning appeared. 

I can't find any related documentation about this deprecation on the [provider site  doc](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/databases)  and none in the CHANGELOG.md file.

```bash
╷
│ Warning: Argument is deprecated
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].SA,
│   on 000_main.tf line 24, in provider "snowflake":
│   24: provider "snowflake" {
│ 
│ Specify the region as part of the account parameter
│ 
│ (and 4 more similar warnings elsewhere)
╵
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

**Comment by sfc-gh-asawicki** [comment]
Hey @toni-moreno. Thanks for reaching out to us.

There are migration notes inside the repository. The one you linked is described here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#remove-redundant-information-region.

I will make sure to note down to add the link to the migration notes in the official docs you have linked.

**Comment by toni-moreno** [comment]
Ok, thank  you !!
