### ISSUE TITLE
Warning: Show with OnAll option is skipped.

### ISSUE THREAD

**Issue by nicolamarangoni** [Snowflake-Labs/terraform-provider-snowflake#2480]
### Terraform CLI and Provider Versions

Terraform version: **v1.7.3**
Provider version: **0.85.0**

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "datainterface_all_table_read" {
  depends_on = [snowflake_database.database, snowflake_role.datainterface_role]
  for_each = merge([for database_schema, roles in transpose(var.datainterfaces_read) : {
    for role in roles : format("%s:%s", database_schema, role) => { schema = database_schema, role = role }
  }]...)

  privileges = ["SELECT"]
  account_role_name  = upper(each.value.role)
  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_schema          = upper(each.value.schema)
    }
  }
}
```

### Expected Behavior

Deployment completed without errors and warnings.

### Actual Behavior

This warning appears:

```
│ Warning: Show with OnAll option is skipped.
│ 
│   with snowflake_grant_privileges_to_account_role.datainterface_all_table_read["prod.di_proprice:datainterface_di_proprice"],
│   on snowflake_datainterfaces.tf line 42, in resource "snowflake_grant_privileges_to_account_role" "datainterface_all_table_read":
│   42: resource "snowflake_grant_privileges_to_account_role" "datainterface_all_table_read" {
│ 
│ See our document on design decisions for grants: <LINK (coming soon)>
│ 
│ (and 158 more similar warnings elsewhere)
```

### Steps to Reproduce

1. `terragrunt apply`

### How much impact is this issue causing?

High

### Additional Information

I have 2 resources in the deployment:
- one that grant select to future tables in the schema
- one that grant select to all (existing) tables in the same schema

I'm testing it with an empty schema and the warning appears for the resource that grant select to all existing tables in schema
Is the warning caused by the fact that there are no tables to grant select to?

**Comment by sfc-gh-jcieslak** [comment]
Hey, so this warning will be transformed into a log in future versions as it was only to indicate the fact that the resource won't be checking the state in Snowflake when `on_all` is specified. There's most likely nothing wrong with the configuration. Additionally, soon we will prepare a document about grant design decisions that will be posted in our repository. Closing the issue as it doesn't seem like a bug.
