### ISSUE TITLE
Issue with privileges, all_privileges in snowflake_grant_privileges_to_database_role resource

### ISSUE THREAD

**Issue by ajaychaudhari110** [Snowflake-Labs/terraform-provider-snowflake#2494]
### Terraform CLI and Provider Versions

terraform {
  required_providers {
    snowflake = {
      source = "Snowflake-Labs/snowflake"
      version = "~> 0.85"
    }
  }
}

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_database_role" "grant1" {
    privileges = ["USAGE","MONITOR"]
    database_role_name = "\"${snowflake_database_role.db_role.database}\".\"${snowflake_database_role.db_role.name}\""
    on_database = snowflake_database_role.db_role.database
    with_grant_option = false
    always_apply = false
    all_privileges = false
}
```

### Expected Behavior

Usage, Monitor privileges on database should be applied to database role. 

### Actual Behavior

**1. Only privileges attribute should be allowed to specified but it gives below error if all_privileges is not specified**
_Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/snowflake-labs/snowflake" planned an invalid value for snowflake_grant_privileges_to_database_role.grant1.all_privileges: planned  
│ value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker._

**2. When both attributes privileges and all_privileges is provided it gives below error**
_│ Error: Invalid combination of arguments
│
│   with snowflake_grant_privileges_to_database_role.grant1,
│   on snowflake_grant_privileges_to_database_role.tf line 9, in resource "snowflake_grant_privileges_to_database_role" "grant1":
│    9:     privileges = ["USAGE","MONITOR"]
│
│ "privileges": only one of `all_privileges,privileges` can be specified, but `all_privileges,privileges` were specified.
╵
╷
│ Error: Invalid combination of arguments
│
│   with snowflake_grant_privileges_to_database_role.grant1,
│   on snowflake_grant_privileges_to_database_role.tf line 14, in resource "snowflake_grant_privileges_to_database_role" "grant1":
│   14:     all_privileges = false
│
│ "all_privileges": only one of `all_privileges,privileges` can be specified, but `all_privileges,privileges` were specified._

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-asawicki** [comment]
Hey @ajaychaudhari110. Thanks for reaching out to us.

Which version of Terraform do you use? I suppose it's lower than 1.1.5. Please bump the Terraform version to 1.1.5 (at least; preferrable is the newest version). It should solve the problem. Please let me know if that helps.

**Comment by sfc-gh-asawicki** [comment]
Great to hear that! I am closing the issue then.
