### ISSUE TITLE
Show with OnAllSchemasInDatabase option is skipped warning

### ISSUE THREAD

**Issue by freylafert** [Snowflake-Labs/terraform-provider-snowflake#2529]
### Terraform CLI and Provider Versions

terraform --version
Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.36.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/snowflake-labs/snowflake v0.86.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "ip_info_private_sharing_schemas_grant" {
  count             = local.is_dev_env ? 1 : 0
  provider          = snowflake.account_admin
  privileges        = ["USAGE"]
  account_role_name = snowflake_role.app_user_role.name
  on_schema {
    all_schemas_in_database = var.snowflake_ip_info_private_sharing_db_name
  }
  with_grant_option = false
}
```

### Expected Behavior

terraform applied with no warnings

### Actual Behavior

Getting following warning during terraform apply
╷
│ Warning: Show with OnAllSchemasInDatabase option is skipped.
│ 
│   with module.snowflake.snowflake_grant_privileges_to_account_role.ip_info_private_sharing_schemas_grant[0],
│   on ../reporting/snowflake/snowflake.tf line 197, in resource "snowflake_grant_privileges_to_account_role" "ip_info_private_sharing_schemas_grant":
│  197: resource "snowflake_grant_privileges_to_account_role" "ip_info_private_sharing_schemas_grant" {
│ 
│ See our document on design decisions for grants: <LINK (coming soon)>

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Unknown

### Additional Information

Not sure what is the actual impact of this warning.

**Comment by sfc-gh-asawicki** [comment]
Hey @freylafert. Thanks for reaching out to us.

It was already discussed in #2520 and it was already merged in #2521. It will be released with 0.87.0 version.

**Comment by freylafert** [comment]
Nice, just one more question, I see also warning "Show with OnAll option is skipped." Is it goes away in 0.87.0 version as well or I should open a separate issue?

**Comment by sfc-gh-asawicki** [comment]
Yes, they should be all gone (unless we missed something).

**Comment by freylafert** [comment]
Thank you

**Comment by sfc-gh-jcieslak** [comment]
@freylafert yes
