### ISSUE TITLE
Error on table creation with double quotes in the field name.

### ISSUE THREAD

**Issue by toni-moreno** [Snowflake-Labs/terraform-provider-snowflake#2557]
### Terraform CLI and Provider Versions

Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.86.0

### Terraform Configuration

```terraform
I've tested several convinations with escape characters but no way to create it.

simplifing after reasigning variables

1) one single escape


locals {
columns = [ { name = "\"FROM\"", type = "VARCHAR(16777216)" } ]
}

resource "snowflake_table" "table" {

  database = MY_DB
  schema   =  MY_SCHEMA
  name     = MY_TABLE
  comment  = "Auto generated by terraform"

  dynamic "column" {
    for_each = local.columns
    content {
      name     = column.value.name
      type     = column.value.type
      nullable = true
    }
  }

}

2) multiple escape.

```hcl
locals {
columns = [ { name = "\\\"FROM\\\"", type = "VARCHAR(16777216)" } ]
}

resource "snowflake_table" "table" {

  database = MY_DB
  schema   =  MY_SCHEMA
  name     = MY_TABLE
  comment  = "Auto generated by terraform"

  dynamic "column" {
    for_each = local.columns
    content {
      name     = column.value.name
      type     = column.value.type
      nullable = true
    }
  }

}
```

### Expected Behavior

Create the table as I did some weeks ago by hand

### Actual Behavior

I'm tryin to create with terraform  snowflake_table resource the same table we have created ( by hand) some monts ago.

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/5883405/53d7cc16-4183-497f-95fb-6d9289926451)

It has double quotes in the field name "FROM" .

1) firts way return with this error.
```
module.xxxx.snowflake_table.table["MY_DB.MY_SCHEMA.MY_TABLE"]: Modifying... [id=XXXXXXXXXXX]
╷
│ Error: error adding column: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 71 unexpected 'FROM'.
│ 
│   with module.sfbs.snowflake_table.table["MY_DB.MY_SCHEMA.MY_TABLE"],
│   on ../modules/snowflake_bs_v2/table.tf line 34, in resource "snowflake_table" "table":
│   34: resource "snowflake_table" "table" {
│ 
╵
```
2) second way return this error.
```
module.xxxx.snowflake_table.table[["MY_DB.MY_SCHEMA.MY_TABLE"]: Modifying... [id=XXXXXXXXXXXXXXXXXX]
╷
│ Error: error adding column: 001003 (42000): SQL compilation error:
│ parse error line 1 at position 77 near '34'.
│ parse error line 1 at position 97 near '<EOF>'.
│ syntax error line 1 at position 97 unexpected '<EOF>'.
│ 
│   with module.sfbs.snowflake_table.table[["MY_DB.MY_SCHEMA.MY_TABLE"],
│   on ../modules/snowflake_bs_v2/table.tf line 34, in resource "snowflake_table" "table":
│   34: resource "snowflake_table" "table" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @toni-moreno. Thanks for creating the issue.

The first question I would ask is: why are you trying to name the column `FROM`? There are multiple other names that can (and should) be used.

However, if you need such a name (or any other name for that matter), the current behavior of the `column` attribute in `snowflake_table` resource is adding quotes automatically. This means that the solution for your config is just putting no quoting there (remember that case matters - `from` versus `FROM`):
```
resource "snowflake_table" "test_table" {
	name                = "test"
	database            = "test"
	schema              = "test"
	column {
		name = "FROM"
		type = "VARCHAR(16777216)"
	}
}
```
The above results in `CREATE TABLE "test"."test"."test" ("FROM" VARCHAR(16777216) COLLATE '' COMMENT '')`.

**Comment by toni-moreno** [comment]
hello @sfc-gh-asawicki  and thank you for your fast answer.

You are rigth if removed double quotes in the locals definition as any other field name , the create statement adds itself the "double quote" in the creation definition, and he table creation doesn't fail.

this is how finally I have fixed the definition mistake.

```hcl
locals {
columns = [ { name = "FROM", type = "VARCHAR(16777216)" } ]
}

resource "snowflake_table" "table" {

  database = MY_DB
  schema   =  MY_SCHEMA
  name     = MY_TABLE
  comment  = "Auto generated by terraform"

  dynamic "column" {
    for_each = local.columns
    content {
      name     = column.value.name
      type     = column.value.type
      nullable = true
    }
  }

}

```
Thank you very much.
