### ISSUE TITLE
snowflake_oauth_integration does not expose network policy

### ISSUE THREAD

**Issue by josh-gree** [Snowflake-Labs/terraform-provider-snowflake#2568]
### Terraform CLI and Provider Versions

0.86.0

### Use Cases or Problem Statement

OAUTH SECURITY INTEGRATION allow for the setting of network policy this isn't exposed in the resource

### Proposal

Add network policy

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @josh-gree. Thanks for creating the issue.

We will redesign the existing resources on our road to V1 (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap). We will address it then.

**Comment by josh-gree** [comment]
@sfc-gh-asawicki Do you have any suggestions for workarounds in the meantime? Is there a way to run generic Alter statements perhaps?

**Comment by sfc-gh-asawicki** [comment]
There is a https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute resource. You can basically run any statement there. This is a dangerous resource, though. Please make sure you read its documentation before using it.

**Comment by josh-gree** [comment]
Thanks - implications understood!

**Comment by sfc-gh-jmichalak** [comment]
Hey @josh-gree    👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides a new resource for oauth: `oauth_integration_for_custom_clients`. This resource contains `network_policy`, so please migrate from`oauth_integration` to this new resource. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-snowflake_oauth_integration_for_custom_clients-and-snowflake_oauth_integration_for_partner_applications-resources).
