### ISSUE TITLE
snowflake_account_parameter import cause "key" diff

### ISSUE THREAD

**Issue by harukitake** [Snowflake-Labs/terraform-provider-snowflake#2573]
### Terraform CLI and Provider Versions
```
Terraform v1.7.3
on darwin_arm64

provider[registry.terraform.io/snowflake-labs/snowflake] 0.86.0
```
### Terraform Configuration

```terraform
resource "snowflake_account_parameter" "timezone" {
  key   = "TIMEZONE"
  value = "Etc/UTC"
}

import {
  to = snowflake_account_parameter.timezone
  id = "TIMEZONE"
}
```

### Expected Behavior

The result of plan should be import only.

### Actual Behavior

```
 # snowflake_account_parameter.timezone must be replaced
  # (imported from "TIMEZONE")
  # Warning: this will destroy the imported resource
-/+ resource "snowflake_account_parameter" "timezone" {
      ~ id    = "TIMEZONE" -> (known after apply)
      + key   = "TIMEZONE" # forces replacement
        value = "Etc/UTC"
    }
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-asawicki** [comment]
Hey @harukitake. Thanks for creating the issue.

I think that import is not handled correctly for this resource. I will do some testing and we should have a fix next week.

**Comment by sfc-gh-asawicki** [comment]
@harukitake hey, please verify if bumping to the newest version solves the issue for you.

**Comment by harukitake** [comment]
@sfc-gh-asawicki It works good. Thanks for the quick fix.
