### ISSUE TITLE
Cannot create a stream in Terraform

### ISSUE THREAD

**Issue by spachari** [Snowflake-Labs/terraform-provider-snowflake#2583]
### Terraform CLI and Provider Versions

"terraform_version": "1.7.3"

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76"
    }
  }
}


resource "snowflake_stream" "STREAM" {
  comment = var.comment

  database = var.stream_database
  schema   = var.stream_schema
  name     = var.stream_name

  on_table    = var.on_table_name
  append_only = false
  insert_only = false

#   owner = var.owner
}

resource "snowflake_stream_grant" "STREAM_GRANT" {
  database_name = snowflake_stream.STREAM.database
  schema_name   = snowflake_stream.STREAM.schema
  stream_name   = snowflake_stream.STREAM.name

  privilege = var.privilege
  roles     = var.roles

  on_future         = false
  with_grant_option = false
}
```

### Expected Behavior

To be able to create a stream

### Actual Behavior

│   with module.SALES_STREAM.snowflake_stream.STREAM,
│   on stream/main.tf line 22, in resource "snowflake_stream" "STREAM":
│   22:   owner = var.owner
│ 
│ Can't configure a value for "owner": its value will be decided automatically based on the result of applying this configuration.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @spachari it's not a bug. Owner is a computed field which means it should be populated by the Terraform plugin. It's mapping from Snowflake's `SHOW` command which indicates who created the resource. If an inability to set the 'owner` field is the only concern, please close the ticket.

**Comment by spachari** [comment]
Thanks @sfc-gh-jcieslak is there any documentation on how to set this owner field? Thanks

**Comment by sfc-gh-jcieslak** [comment]
The meaning of Computed is "a value will be assigned during Create" and it's not something you can set in Terraform. You can "set" the owner by using a certain role to create a resource. Example in SQL, so you'll know what the owner is:
```sql
use role accountadmin;
create database test_database;
show databases like 'test_database'; -- owner = accountadmin

create role test_role;
use role test_role;
create database another_test_database;
show databases like 'another_test_database; -- owner = test_role
```
As you can see owner is not something you can set, but rather a role that was used to create a resource.

**Comment by sfc-gh-jcieslak** [comment]
@spachari Can you confirm that's not a bug and close the ticket if that's the case? Computed fields cannot be set generally in Terraform.

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity
