### ISSUE TITLE
Error upgrading from snowflake_grant_privileges_to_role to snowflake_grant_privileges_to_account_role

### ISSUE THREAD

**Issue by nick-amplify** [Snowflake-Labs/terraform-provider-snowflake#2585]
### Terraform CLI and Provider Versions

1.6.5

### Terraform Configuration

```terraform
Going from: 

resource "snowflake_grant_privileges_to_account_role" "gcs_integration_grants" {
  for_each = toset(var.names)

  privileges        = ["USAGE"]
  account_role_name = snowflake_role.snowflake_tenant_roles[each.key].name

  on_account_object {
    object_type = "INTEGRATION"
    object_name = var.object_name
  }
}
```

to 

```
resource "snowflake_grant_privileges_to_account_role" "gcs_integration_grants" {
  privileges        = ["USAGE"]
  account_role_name = snowflake_role.snowflake_tenant_roles[each.key].name
  on_account_object {
    object_type = "INTEGRATION"
    object_name = var.object_name
  }
}
```

### Expected Behavior

To have the old resource deleted and the new one created

### Actual Behavior

This error:
```terraform 
Error: error revoking privileges from account role: 003935 (23001): Revoke partially executed: 0 grant(s) revoked, 1 grant(s) skipped due to dependent grants and no CASCADE is specified.
```

### Steps to Reproduce

Create a resource with the old, then migrate to the new. 

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment]
Hey @nick-amplify 👋 
The examples refer to `snowflake_grant_privileges_to_account_role`, but I assume the top one should be `snowflake_grant_privileges_to_role`. Now, assuming that we have to know what migration strategy you chose. I assume that you just modified exiting the `snowflake_grant_privileges_to_role` resource into the `snowflake_grant_privileges_to_account_role` one. This means that `snowflake_grant_privileges_to_role` will call Delete operation ([Revoke ... from role](https://docs.snowflake.com/en/sql-reference/sql/revoke-privilege)) and that leads to this error. The error is connected to the dependent granted roles, see the SQL example of this situation:
```sql
create database test_database;
create role test_role_a;
create role test_role_b;
grant usage on database test_database to role test_role_a with grant option; -- with grant option means that role can grant usage to that database to another role creating a dependency
grant role test_role_a to user <your_username>;
use role test_role_a;
grant usage on database test_database to role test_role_b; -- creates dependency role_a (usage) -> role_b (usage)
use role accountadmin;
show grants on database test_database;
revoke usage on database test_database from role test_role_a; -- error: can only remove with cascade (because test_role_b has usage granted)
```
There are a few ways to overcome this issue:
1. Follow our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) that describes "no downtime" migration (migration without revoking any grant, so no error will occur).
2. As `snowflake_grant_privileges_to_role` cannot revoke with CASCADE, you can do it by hand, then remove the `snowflake_grant_privileges_to_role` resource from the state ([also described in the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md#2-terraform-rm)) and at the end modify the resource as you did into `snowflake_grant_privileges_to_account_role` and apply which only will call Create operation which called underneath `grant .. to role` (it won't have any effect as we didn't revoke any grant and calling `grant .. to role` multiple times shouldn't cause any errors).

**Comment by nick-amplify** [comment]
Ah thanks. that is what I ended up doing to get it to work. Wish I had found the migration guide sooner. thank you!

**Comment by sfc-gh-jcieslak** [comment]
No problem 👍 
If that resolves your problem, please close the issue. Thanks :)
