### ISSUE TITLE
Network Policy SDK update

### ISSUE THREAD

**Issue by sfc-gh-jcieslak** [Snowflake-Labs/terraform-provider-snowflake#2593]
### Use Cases or Problem Statement

Follow up for https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2514. Because there were new fields added to the documentation, we have to adjust the current implementation in the SDK to support those new fields.

### How much impact is this issue causing?

Medium

### Additional Information

Resource implementation reference: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2482

**Comment by freakyfriday** [comment]
Hi team, any update on when this feature might be implemented? Thanks :-)

**Comment by Relativity74205** [comment]
@sfc-gh-jcieslak Like posted #2482 the headline for this issue is wrong. The network rules SDK was already created and it is fine. But the network policy SDK has to be updated in order to use the network rules.

**Comment by sfc-gh-jcieslak** [comment]
@Relativity74205 True, thanks :)
Sorry, It looks like we have no team capacity for it right now, but let me consult with the team if we could somehow squeeze this in.

**Comment by Relativity74205** [comment]
@sfc-gh-jcieslak That would be great. As soon as the SDK update is finished, it would start implement the network rule feature

**Comment by Relativity74205** [comment]
@sfc-gh-jcieslak I see, that a PR was created two weeks ago, however, it ran into some issues. Can I support here somehow?

**Comment by sfc-gh-asawicki** [comment]
Hey @Relativity74205. @sfc-gh-swinkler was working on it but is only partially involved in the project. Today, we'll discuss whether we can speed it up because this PR is nearly merged.
