### ISSUE TITLE
[Docs]: New deprecated message may be wrong.

### ISSUE THREAD

**Issue by harukitake** [Snowflake-Labs/terraform-provider-snowflake#2599]
### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs#currently-deprecated-resources

### Description

> * [snowflake_role_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/resources/role_grants) - use [snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/resources/grant_privileges_to_account_role) instead

I think `snwoflake_grant_account_role` is correct.
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role

Deprecated message in plan results have same issue.

### Would you like to implement a fix?

None

**Comment by sfc-gh-asawicki** [comment]
Hey @harukitake. Thanks for reaching out to us.

This is a good catch; it should be fixed as you suggested.

I've seen your PR, thanks for that! Unfortunately, the docs are being generated automatically based on the schema. Your changes will be overwritten next time we generate the docs. We do not have a good set of instructions for making the contributions yet but you can check my PR #2602 for future reference (you just change the `DeprecationMessage` inside the resource schema and run `make docs`)

**Comment by harukitake** [comment]
OK! I understood how to fix docs.
Thanks.

**Comment by sfc-gh-asawicki** [comment]
@harukitake, we have released the new 0.87.2 version with the updated documentation. Please check. :)

**Comment by harukitake** [comment]
It looks good.
