### ISSUE TITLE
grant_privileges_to_account_role Unsupported privilege 'OWNERSHIP'

### ISSUE THREAD

**Issue by lukeyz1** [Snowflake-Labs/terraform-provider-snowflake#2610]
### Terraform CLI and Provider Versions

Terraform v1.7.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.39.1
+ provider registry.terraform.io/snowflake-labs/snowflake v0.87.2

### Terraform Configuration

```terraform
# OLD
resource "snowflake_stream_grant" "grant" {
  for_each                  =  local.bucket_targets
  
  database_name = local.schema_map[each.value.schema].database
  schema_name   = local.schema_map[each.value.schema].name
  stream_name   = snowflake_stream.stream[each.key].name

  privilege           = "OWNERSHIP"
  roles               = [each.value.role]

}

# NEW
resource "snowflake_grant_privileges_to_account_role" "grant" {
  for_each              = local.bucket_targets

  account_role_name     = each.value.role
  privileges            = ["OWNERSHIP"]
  with_grant_option     = false
  on_schema_object {
    all {
      object_type_plural = "STREAMS"
      in_schema          = "\"${local.schema_map[each.value.schema].database}\".\"${local.schema_map[each.value.schema].name}\""
    }
  }
}
```

### Expected Behavior

snowflake_stream_grant has a deprecation notice. The documentation says to use the snowflake_grant_privileges_to_account_role. However snowflake_grant_privileges_to_account_role does not support "OWNERSHIP" as a privilege option. The expected behaviour is to at least replicate the previous resource block

### Actual Behavior

An error of

Error: Unsupported privilege 'OWNERSHIP'
Granting ownership is only allowed in dedicated resources (snowflake_user_ownership_grant, snowflake_role_ownership_grant)

Perhaps the documentation needs to be updated to reflect this.

### Steps to Reproduce

1. Create a grant using snowflake_stream_grant, set the privilege to "OWNERSHIP"
2. Attempt to migrate that grant using snowflake_grant_privileges_to_account_role.
3. Run terraform plan/apply

### How much impact is this issue causing?

Medium

**Comment by pauldraper** [comment]
snowflake_database_grant says it's deprecated and to use snowflake_grant_privledges_to_account_role

snowflake_grant_privledges_to_account_role says to use a dedicated ownership resource type.

And round and round it goes.

**Comment by sfc-gh-jcieslak** [comment]
Hey @lukeyz1 @pauldraper 
The ownership resource is in progress (there is one out of two pr's ready for review right now). The `snowflake_grant_privledges_to_account_role` resource is not a 1:1 replacement for the `snowflake_database_grant`, but most of the time you could replace it with the newer `snowflake_grant_privledges_to_account_role`. Unfortunately, Terraform documentation doesn't allow conditional deprecation messages where it would be based on your configuration (e.g. we can't remove the deprecation message when privilege = OWNERSHIP). What we can do right now is to extend deprecation messages to include this case is not supported yet. We already have a ticket to update existing examples, so I'll add it there.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing, as the issue was about the deprecated/not allowed functionality. Recently, we released [a new grant resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership) which is capable of granting ownership. Please, give it a try. If there will be any issues with it, create another GitHub issue. Also, please check our [technical documentation section](https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/main/docs/technical-documentation) where you can find a migration guide that can help you with upgrading to the latest grant resources and our newly added design decision doc (regarding new grant resources).
