### ISSUE TITLE
`snowflake_grant_privileges_to_share` revokes grants without reason

### ISSUE THREAD

**Issue by mlavaert** [Snowflake-Labs/terraform-provider-snowflake#2619]
### Terraform CLI and Provider Versions

Terraform 1.7.5
Snowflake Provider 0.87.2

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_share" "allow_share_to_use_production" {
  provider    = snowflake.securityadmin
  to_share    = snowflake_share.shares["<redacted>"].name
  privileges  = ["USAGE"]
  on_database = snowflake_database.databases["PRODUCTION"].name
}
```

### Expected Behavior

Once the grant is applied, it stays there. Do not revoke the grant in the next apply.

### Actual Behavior

Grant gets revoked again

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @mlavaert 
I couldn't reproduce your issue with the following config
```terraform
# Account 1
resource "snowflake_share" "test" {
  provider = snowflake.sharing # provider configuration that connects to secondary account
  name = "sharing_test_share"
  accounts = [ "<org-name>.<acc-name>" ]
}

resource "snowflake_database" "test" {
  provider = snowflake.sharing
  name = "sharing_test_database"
}

resource "snowflake_grant_privileges_to_share" "test" {
  provider = snowflake.sharing
  privileges = [ "USAGE" ]
  on_database = snowflake_database.test.name
  to_share = snowflake_share.test.name 
}
```
Calling `shows grats to share "sharing_test_share"` returns USAGE granted by `snowflake_grant_privileges_to_share`. Please provide full steps to reproduce this issue as it seems to work properly.
