### ISSUE TITLE
Terraform state file error - Error: error retrieving grants for account role: [errors.go:17] object does not exist or not authorized

### ISSUE THREAD

**Issue by vthelu** [Snowflake-Labs/terraform-provider-snowflake#2621]
### Terraform CLI and Provider Versions

terraform version 1.7.0 
hashicorp/aws v3.75.2
snowflake-labs/snowflake v0.86.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_role" "ac-fn-at-get_aclstartdate_fn-grantrole-taskowner" {
  privileges = ["USAGE"]
  role_name  = local.taskowner_role
  on_schema_object {
    object_type = "FUNCTION"
    object_name = "${database}.${schema}.${fn.name}(TIMESTAMP_NZ)"
  }
  with_grant_option = false
}
```

### Expected Behavior

This function is dropped explicit by user. The deployment fails since then with error on granting access
Error: error retrieving grants for account role: [errors.go:17] object does not exist or not authorized

### Actual Behavior

Function grants shall be executed if object exits or update state file to remove the object 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment]
Hey @vthelu 
Thanks for reporting the issue. I'll try to provide a fix for it as soon as possible. For now as a workaround, please just remove an unwanted resource from the state with the `terraform state rm` and remove the resource configuration.

**Comment by sfc-gh-jcieslak** [comment]
Hey,
Closing the issue as the `snowflake_grant_privileges_to_role` is deprecated and the workaround was provided (and it worked). Also in the latest provider version, this shouldn't be a problem in the `snowflake_grant_privileges_to_account_role`. If this issue is happening in the latest provider version with the new grant resources, please create another gh issue.
