### ISSUE TITLE
Guidance for migrating grants to snowflake_grant_privileges_to_account_role that have multiple roles?

### ISSUE THREAD

**Issue by lukeyz1** [Snowflake-Labs/terraform-provider-snowflake#2622]
A lot of the deprecated grant resources have been replaced with `snowflake_grant_privileges_to_account_role`.
I am looking for some guidance on how to replace the deprecated resource if we have multiple roles, example below.

 **Current state**
```terraform
locals {
    data_sources = {
        data_source1 = {
            name = "data_source_example"
            database = "database_example"
            schema = "schema_example"
            tag = "tag_example"
            roles = ["role1", "role2"]
        }
        ... # Could have multiple sources
    }
}

resource "snowflake_tag_grant" "tag_grant_example" {
  for_each      = local.data_sources
  database_name = each.database
  schema_name   = each.schema
  tag_name      = each.tag
  roles         = [for role in each.value.roles: role]
  privilege     = "APPLY"
}
```

In the above example using the deprecated `snowflkae_tag_grant` I am able to create a grant `for_each` data source in locals. This is possible as this resource block allows **multiple** roles.

However, if I was to use the `snowflake_grant_privileges_to_account_role` this only allows **one** role. I would not be able to loop the data_sources in locals.

Would the recommendation be to create a `snowflake_grant_privileges_to_account_role` for each data_source in locals?

i.e.

```terraform
resource "snowflake_grant_privileges_to_account_role" "table_grant_readonly_select" {
  for_each   = toset([local.data_sources.data_source1.roles])

  account_role_name     = each.value
  privileges            = ["APPLY"]
  on_schema_object {
    all {
      object_type_plural = "TAGS"
      in_schema          = "\"${local.data_sources.data_source1.database}\".\"${local.data_sources.data_source1.schema}\""
    }
  }
}
```

Ideally I would like to keep one resource block doing a for_each and then somehow looping the roles in the data_sources. Please give some guidance. Thanks!

**Comment by sfc-gh-asawicki** [comment]
Hey @lukeyz1. Thanks for reaching out to us.

Did you check the [resource migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md)?

**Comment by lukeyz1** [comment]
Hi @sfc-gh-asawicki, yes I found that migration guide. It uses the for_each to go through a list of roles. However, previously I was using the for_each to get the list of roles. I don't think terraform supports a nested for_each to create resources.

Something like this is what I'm trying to achieve. In my locals I have a lot of data sources with different list of roles that require role grants.
```terraform
resource "snowflake_grant_privileges_to_account_role" "table_grant_readonly_select" {
  for_each = local.data_sources
  for_each = toset(each.roles) # Cannot have multiple for_each

  account_role_name     = each.value
  privileges            = ["APPLY"]
  on_schema_object {
    all {
      object_type_plural = "TAGS"
      in_schema          = "\"${local.data_sources.data_source1.database}\".\"${local.data_sources.data_source1.schema}\""
    }
  }
}
```

What would you recommend? Cheers

**Comment by sfc-gh-jcieslak** [comment]
Hey @lukeyz1 
Can't you just create another local field which would map `data_sources` to `roles` and flatten the result? I guess it would be something similar to:
```terraform
locals {
  # flatten ensures that this local value is a flat list of objects, rather
  # than a list of lists of objects.
  network_subnets = flatten([
    for network_key, network in var.networks : [
      for subnet_key, subnet in network.subnets : {
        network_key = network_key
        subnet_key  = subnet_key
        network_id  = aws_vpc.example[network_key].id
        cidr_block  = subnet.cidr_block
      }
    ]
  ])
}
```
Full examples, here: https://developer.hashicorp.com/terraform/language/functions/flatten

**Comment by lukeyz1** [comment]
Hey @sfc-gh-jcieslak, thank you! 
Flattening it into a combination of `data_sources` and `roles` worked like a charm.
 
Inside the resource block I then created a for_each based on the name and role.

```terraform
resource "snowflake_grant_privileges_to_account_role" "example" {
  for_each = {
    for pair in local.data_source_role_combinations : "${pair.name}-${pair.role_name}" => pair
  }
  account_role_name  = each.value.role_name
  ...
```
