### ISSUE TITLE
Crash on version v0.87.2 during plan generation

### ISSUE THREAD

**Issue by mostafasadeghi97** [Snowflake-Labs/terraform-provider-snowflake#2645]
### Terraform CLI and Provider Versions

Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.87.2

### Terraform Configuration

```terraform
terraform {

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }

    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      
    }

  }

}
```

### Expected Behavior

The functionality was operational with the previous version but ceased to function correctly upon updating to the latest version.

### Actual Behavior

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ConfigureProvider request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ConfigureProvider request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.87.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10150a768]

goroutine 38 [running]:
crypto/rsa.(*PrivateKey).Public(...)
        crypto/rsa/rsa.go:122
github.com/snowflakedb/gosnowflake.prepareJWTToken(0x140009c7400)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:462 +0x28
github.com/snowflakedb/gosnowflake.createRequestBody(0x14000b6e240, 0x1020e8ac0?, {{0x14000232112, 0x1c}, {0x101c23414, 0x6}, {0x140006250d0, 0x8}, {0x101c327b5, 0x9}}, ...)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:425 +0x370
github.com/snowflakedb/gosnowflake.authenticate.func1()
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:336 +0x60
github.com/snowflakedb/gosnowflake.(*retryHTTP).execute(0x14000b6bd50)
        github.com/snowflakedb/gosnowflake@v1.7.1/retry.go:313 +0x1b0
github.com/snowflakedb/gosnowflake.postAuthRestful({0x10244bf30?, 0x103348f00?}, 0x19?, 0x14000160500?, 0x1020c33c0?, 0x0?, 0x14000b6be38?, 0x1007e3d84?)
        github.com/snowflakedb/gosnowflake@v1.7.1/restful.go:198 +0xd8
github.com/snowflakedb/gosnowflake.postAuth({0x10244bf30, 0x103348f00}, 0x14000abd5f0, 0x8?, 0x14000590ec8, 0x15?, 0x14000b6bfe8?, 0x2?)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:229 +0x2e8
github.com/snowflakedb/gosnowflake.authenticate({0x10244bf30, 0x103348f00}, 0x14000b6e240, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:356 +0xdec
github.com/snowflakedb/gosnowflake.authenticateWithConfig(0x14000b6e240)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:547 +0x404
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0x140002320d9, 0x7}, {0x140002320d0, 0x7}, {0x140002320d0, 0x0}, {0x0, ...}, ...})
        github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:43 +0x114
github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open({}, {0x140002320d0, 0xcf})
        github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:26 +0x108
github.com/luna-duclos/instrumentedsql.dsnConnector.Connect(...)
        github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:53
github.com/luna-duclos/instrumentedsql.wrappedConnector.Connect({{{0x102433b60, 0x102426840}, {0x1024362c0, 0x103348f00}, 0x0, 0x0}, {0x10243b978, 0x14000ac4c40}, 0x14000b52a40}, {0x10244bf30?, ...})
        github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:33 +0x188
database/sql.(*DB).conn(0x14000abd520, {0x10244bf30, 0x103348f00}, 0x1)
        database/sql/sql.go:1387 +0x824
database/sql.(*DB).PingContext.func1(0xd0?)
        database/sql/sql.go:850 +0x40
database/sql.(*DB).retry(0x14000c77dd0?, 0x14000b6ccd8)
        database/sql/sql.go:1538 +0x4c
database/sql.(*DB).PingContext(0x14000abd520, {0x10244bf30?, 0x103348f00})
        database/sql/sql.go:849 +0x70
database/sql.(*DB).Ping(...)
        database/sql/sql.go:867
github.com/jmoiron/sqlx.Connect({0x101c6153c?, 0x16?}, {0x140002320d0?, 0x14000b52a00?})
        github.com/jmoiron/sqlx@v1.3.5/sqlx.go:642 +0x48
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x0?)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:151 +0xfc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider(0x101c233f0?)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:785 +0x1770
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0x14000ab6120, {0x10244bf68, 0x14000c76f90}, 0x14000a125f0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/provider.go:296 +0x180
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0x1400089eaf8, {0x10244bf68?, 0x14000d93530?}, 0x14000b44930)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:607 +0x340
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x102461538?, 0x1400089eaf8?}}, {0x10244bf68?, 0x14000d93530?}, 0x14000b448d0?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:80 +0x154
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0x14000a1f490, {0x10244bf68?, 0x14000d93230?}, 0x5?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x110
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0x140009e68c0, {0x10244bf68?, 0x14000d929f0?}, 0x14000b52080)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:568 +0x22c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x1023b5240?, 0x140009e68c0}, {0x10244bf68, 0x14000d929f0}, 0x14000b7c300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:449 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000cad20, {0x10244bf68, 0x14000d92960}, {0x10245cb20, 0x14000603380}, 0x14000c5f440, 0x14000b54060, 0x1032ffc70, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140000cad20, {0x10245cb20, 0x14000603380}, 0x14000c5f440)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 30
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x138
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105032768]

goroutine 65 [running]:
crypto/rsa.(*PrivateKey).Public(...)
        crypto/rsa/rsa.go:122
github.com/snowflakedb/gosnowflake.prepareJWTToken(0x140009e7600)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:462 +0x28
github.com/snowflakedb/gosnowflake.createRequestBody(0x14000e107e0, 0x105c10ac0?, {{0x1400067e112, 0x1c}, {0x10574b414, 0x6}, {0x1400000f290, 0x8}, {0x10575a7b5, 0x9}}, ...)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:425 +0x370
github.com/snowflakedb/gosnowflake.authenticate.func1()
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:336 +0x60
github.com/snowflakedb/gosnowflake.(*retryHTTP).execute(0x14000c4dd50)
        github.com/snowflakedb/gosnowflake@v1.7.1/retry.go:313 +0x1b0
github.com/snowflakedb/gosnowflake.postAuthRestful({0x105f73f30?, 0x106e70f00?}, 0x19?, 0x140006e2800?, 0x105beb3c0?, 0x0?, 0x14000c4de38?, 0x10430bd84?)
        github.com/snowflakedb/gosnowflake@v1.7.1/restful.go:198 +0xd8
github.com/snowflakedb/gosnowflake.postAuth({0x105f73f30, 0x106e70f00}, 0x14000ac1a00, 0x8?, 0x1400010f910, 0x15?, 0x14000c4dfe8?, 0x2?)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:229 +0x2e8
github.com/snowflakedb/gosnowflake.authenticate({0x105f73f30, 0x106e70f00}, 0x14000e107e0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:356 +0xdec
github.com/snowflakedb/gosnowflake.authenticateWithConfig(0x14000e107e0)
        github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:547 +0x404
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0x1400067e0d9, 0x7}, {0x1400067e0d0, 0x7}, {0x1400067e0d0, 0x0}, {0x0, ...}, ...})
        github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:43 +0x114
github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open({}, {0x1400067e0d0, 0xcb})
        github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:26 +0x108
github.com/luna-duclos/instrumentedsql.dsnConnector.Connect(...)
        github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:53
github.com/luna-duclos/instrumentedsql.wrappedConnector.Connect({{{0x105f5bb60, 0x105f4e840}, {0x105f5e2c0, 0x106e70f00}, 0x0, 0x0}, {0x105f63978, 0x14000ad1840}, 0x14000b7f940}, {0x105f73f30?, ...})
        github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:33 +0x188
database/sql.(*DB).conn(0x14000ac1930, {0x105f73f30, 0x106e70f00}, 0x1)
        database/sql/sql.go:1387 +0x824
database/sql.(*DB).PingContext.func1(0x90?)
        database/sql/sql.go:850 +0x40
database/sql.(*DB).retry(0x14000b9af90?, 0x14000c4ecd8)
        database/sql/sql.go:1538 +0x4c
database/sql.(*DB).PingContext(0x14000ac1930, {0x105f73f30?, 0x106e70f00})
        database/sql/sql.go:849 +0x70
database/sql.(*DB).Ping(...)
        database/sql/sql.go:867
github.com/jmoiron/sqlx.Connect({0x10578953c?, 0x16?}, {0x1400067e0d0?, 0x14000b7f900?})
        github.com/jmoiron/sqlx@v1.3.5/sqlx.go:642 +0x48
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x0?)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:151 +0xfc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider(0x10574b3f0?)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:785 +0x1770
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0x14000ac8240, {0x105f73f68, 0x14000b9a150}, 0x14000a2ccd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/provider.go:296 +0x180
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0x140006fab70, {0x105f73f68?, 0x14000ac4f30?}, 0x14000e08768)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:607 +0x340
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x105f89538?, 0x140006fab70?}}, {0x105f73f68?, 0x14000ac4f30?}, 0x14000e08708?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:80 +0x154
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0x14000a3d500, {0x105f73f68?, 0x14000ac4c30?}, 0x5?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x110
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0x1400093c960, {0x105f73f68?, 0x14000aaaae0?}, 0x14000b7f400)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:568 +0x22c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x105edd240?, 0x1400093c960}, {0x105f73f68, 0x14000aaaae0}, 0x14000c04980, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:449 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000cad20, {0x105f73f68, 0x14000aaa870}, {0x105f84b20, 0x140005824e0}, 0x14000b926c0, 0x14000b802a0, 0x106e27c70, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140000cad20, {0x105f84b20, 0x140005824e0}, 0x14000b926c0)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 38
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x138

Error: The terraform-provider-snowflake_v0.87.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @mostafasadeghi97. Thanks for reaching out to us.

Your configuration seems incorrect (it's probably the private_key/private_key_path setting).

Bear in mind the changes introduced between 0.86.0 and 0.87.0: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#provider-configuration-changes.

**Comment by mostafasadeghi97** [comment]
Thank you @sfc-gh-asawicki . I applied the changes related to the private key, and it resolved the issue.
