### ISSUE TITLE
Infinite Plan Loop on SNOWFLAKE.ML Privilege Grants

### ISSUE THREAD

**Issue by coleheflin-gt** [Snowflake-Labs/terraform-provider-snowflake#2651]
### Terraform CLI and Provider Versions

Terraform v1.7.0
provider registry.terraform.io/snowflake-labs/snowflake v0.87.2

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "schema_object" {
  privileges        = ["CREATE SNOWFLAKE.ML.ANOMALY_DETECTION","CREATE SNOWFLAKE.ML.FORECAST"]
  account_role_name = "TEST"

  on_schema_object {
    object_type = "SCHEMA"
    object_name = "DATABASE.SCHEMA"
  }
}
```

### Expected Behavior

This should apply the "CREATE SNOWFLAKE.ML.ANOMALY_DETECTION","CREATE SNOWFLAKE.ML.FORECAST" to the "TEST" role one time and no longer appear in the plan.

### Actual Behavior

This applies the "CREATE SNOWFLAKE.ML.ANOMALY_DETECTION","CREATE SNOWFLAKE.ML.FORECAST" to the "TEST" role one time and continually appears in the plan (infinite plan loop).

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

**Comment by sfc-gh-asawicki** [comment]
Hey @coleheflin-gt. Thanks for reaching out to us.

Could you please share the result of SHOW GRANTS ON ...? My guess is that Snowflake is not returning them. In such a case, there's not much we can do on the provider side, until the results appear there.

**Comment by coleheflin-gt** [comment]
Hi @sfc-gh-asawicki, thanks for the quick response! It does appear the grants are returned, see screenshot below.

![Screenshot 2024-03-26 at 7 31 54 AM](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/121121705/86693020-4442-4896-8cde-8be948f83248)

**Comment by sfc-gh-asawicki** [comment]
Thanks for checking it @coleheflin-gt. I will try to reproduce this error inside the provider tomorrow.

**Comment by coleheflin-gt** [comment]
@sfc-gh-asawicki Thanks for looking into this. I have created an internal ticket with snowflake and requested they cc you.

**Comment by sfc-gh-asawicki** [comment]
Hey @coleheflin-gt. It seems that Snowflake behavior was fixed (proved in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2806). Could you please try to check if you are still experiencing the infinite plan loop? (version bump is not needed because it was fixed on SF side, not the provider)

**Comment by coleheflin-gt** [comment]
Thanks for following up, it has been resolved!
