### ISSUE TITLE
Allow granting USAGE access to all current and future STREAMLIT apps in a schema to account roles.

### ISSUE THREAD

**Issue by anita0918** [Snowflake-Labs/terraform-provider-snowflake#2656]
### Terraform CLI and Provider Versions

TERRAFORM_VERSION: 1.3.6
Provider version: 0.82.0

### Use Cases or Problem Statement

All the schemas in the firm are managed schemas and are controlled by a terraform role. To share the Streamlit Apps with underlying managed schema, user needs to apply GRANT USAGE on the underlying streamlit app which is not possible using current versions of terraform modules as streamlit isn't included in the list of [allowed plural object types](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/v0.86.0/pkg/resources/grant_helpers.go#L439-L467).

Until this functionality is available, users with not be able to share the Streamlit apps and it will impact the usability of Streamlit feature overall.

### Proposal

Add "STREAMLIT" object to the list of allowed plural object types for all and future lists.

The current list has other schema object but not the "STREAMLIT" as shown below:
Once the "STREAMLIT" object is available, we can create resource to GRANT USAGE on STREAMLIT app to allow sharing on STREAMLIT applications.
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role

[Nested Schema for on_schema_object.all](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#nested-schema-for-on_schema_objectall)
Required:

[object_type_plural](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#object_type_plural) (String) The plural object type of the schema object on which privileges will be granted. Valid values are: ALERTS | DYNAMIC TABLES | EVENT TABLES | FILE FORMATS | FUNCTIONS | ICEBERG TABLES | PROCEDURES | SECRETS | SEQUENCES | PIPES | MASKING POLICIES | PASSWORD POLICIES | ROW ACCESS POLICIES | SESSION POLICIES | TAGS | STAGES | STREAMS | TABLES | EXTERNAL TABLES | TASKS | VIEWS | MATERIALIZED VIEWS
Optional:

[in_database](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#in_database) (String) The fully qualified name of the database.
[in_schema](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#in_schema) (String) The fully qualified name of the schema.

[Nested Schema for on_schema_object.future](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#nested-schema-for-on_schema_objectfuture)
Required:

[object_type_plural](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#object_type_plural) (String) The plural object type of the schema object on which privileges will be granted. Valid values are: ALERTS | DYNAMIC TABLES | EVENT TABLES | FILE FORMATS | FUNCTIONS | ICEBERG TABLES | PROCEDURES | SECRETS | SEQUENCES | PIPES | MASKING POLICIES | PASSWORD POLICIES | ROW ACCESS POLICIES | SESSION POLICIES | TAGS | STAGES | STREAMS | TABLES | EXTERNAL TABLES | TASKS | VIEWS | MATERIALIZED VIEWS
Optional:

[in_database](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#in_database) (String) The fully qualified name of the database.
[in_schema](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role#in_schema) (String) The fully qualified name of the schema.

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @anita0918. Thanks for reaching out to us.

I will take a look on it today.

**Comment by anita0918** [comment]
Thanks Artur.

**Comment by sfc-gh-asawicki** [comment]
Hey @anita0918. I am able to grant USAGE privilege to a single Streamlit and to ALL STREAMLITS in DATABASE. I have trouble setting it on ALL FUTURE STREAMLITS in DATABASE, though - it results in an error: `Unsupported feature 'STREAMLIT'`. Can you verify if this is possible on your side?

**Comment by anita0918** [comment]
Hi Artur, what version and resource are you using? I don't see it in the documentation here - https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role

I will test it out on my end for the current version that I am using - 0.82.0

**Comment by sfc-gh-asawicki** [comment]
Okay, I wasn't clear. I checked it from the SQL side inside a worksheet before adding it to the provider. So it is not available in any version of the provider yet.

Because it does not work for me for FUTURE streamlits I have prepared a PR adding it to the specific streamlit and ON ALL, but not ON FUTURE. You can track #2659 .

Also, we did a bigger rework of grants resources, you can read more in https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#vxxxx---v0850. We encourage you to migrate to the newest version because multiple problems with grants were fixed.

**Comment by anita0918** [comment]
Thanks Artur, we are in the process of upgrading to 0.85.0 version. What are the timelines for availability for grating USAGE on STREAMLIT?

**Comment by sfc-gh-asawicki** [comment]
Next release (this or next week).

**Comment by anita0918** [comment]
Hi Artur, Checking on the release and what version of snowflake provider should be used? Thanks

**Comment by sfc-gh-asawicki** [comment]
No release yet, the next one is 0.88.0.

**Comment by anita0918** [comment]
Thanks Artur.

**Comment by anita0918** [comment]
Thanks for the quick solution.
