### ISSUE TITLE
Changing warehouse size and name requires applying twice

### ISSUE THREAD

**Issue by gavh3** [Snowflake-Labs/terraform-provider-snowflake#2673]
### Terraform CLI and Provider Versions

Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.43.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.87.2

### Terraform Configuration

```terraform
# initial warehouse configuration (first apply)
resource "snowflake_warehouse" "this" {
  name           = "WH_TEST_XS"
  warehouse_size = "X-Small"
}

# revised warehouse configuration (second apply)
resource "snowflake_warehouse" "this" {
  name           = "WH_TEST_S"
  warehouse_size = "Small"
}
```

### Expected Behavior

Changing the `name` and `warehouse_size` of an existing warehouse applies successfully on first run of `terraform apply`

### Actual Behavior

Applying simultaneous `name` and `warehouse_size` change results in error, requiring a second `terraform apply`

│ Error: [errors.go:17] object does not exist or not authorized
│ 
│   with snowflake_warehouse.this,
│   on warehouse_module_testing.tf line 14, in resource "snowflake_warehouse" "this":
│   14: resource "snowflake_warehouse" "this" {

### Steps to Reproduce

1. Create initial warehouse configuration
2. `terraform apply`
3. Modify `name` and `warehouse_size` values
4. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

Snowflake query history shows that the rename happens first, and then the statement to alter the warehouse size tries to reference the old warehouse name resulting in `SQL compilation error: Warehouse 'TEST_WAREHOUSE_XS' does not exist or not authorized.`

![Screenshot 2024-04-03 at 8 55 02 AM](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/81283016/0534f2f8-bfe1-4f37-8c2e-b02aa57fb28f)

**Comment by sfc-gh-jcieslak** [comment]
Hey @gavh3 
This seems like a small bug. It seems we're not setting id properly in the update function when the name changes. Thanks for reporting this issue, we'll try to fix it as soon as possible.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
In the v0.89.0, we provided a fix for this. Please test and confirm you're not having the same/similar issues.

**Comment by gavh3** [comment]
> Hey 👋 In the v0.89.0, we provided a fix for this. Please test and confirm you're not having the same/similar issues.

Thanks, after upgrading the issue no longer persists.
