### ISSUE TITLE
always_apply flag won't generate a terraform plan

### ISSUE THREAD

**Issue by bob-zarkoob** [Snowflake-Labs/terraform-provider-snowflake#2689]
### Terraform CLI and Provider Versions

Provider version: 0.87.2 
CLI: 1.7.5

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "db_full_arl_8" {
  count             = length(local.db_role_mapping_1)
  with_grant_option = false
  all_privileges    = true
  always_apply      = true

  account_role_name = local.db_role_mapping_1[count.index]["role"]
  on_schema_object {
    future {
      object_type_plural = "VIEWS"
      in_database        = local.db_role_mapping_1[count.index]["db"]
    }
  }
}
```

### Expected Behavior

To generate a terraform plan every time it runs

### Actual Behavior

it is not generating plan when the flag is set to true

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

### Additional Information

Issue was first discussed here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2467

**Comment by sfc-gh-jcieslak** [comment]
@bob-zarkoob FYI, I'll fix it and it'll be available in the next released version.

**Comment by bob-zarkoob** [comment]
Thank you so much

**Comment by sfc-gh-jcieslak** [comment]
Hey, we released a new provider version: https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.89.0. Please bump and confirm that it works.

**Comment by sfc-gh-jcieslak** [comment]
Hmm, I think that this may still not work for the resources created before v0.89.0, so for the old ones created with `always_apply = true` you still have to unset/set it, but now the flag should work for newly created resources.

**Comment by bob-zarkoob** [comment]
OK, let me try it in the next few days and will let you know. thank you so much

**Comment by sfc-gh-jcieslak** [comment]
Hey @bob-zarkoob 
Any news on the flag?

**Comment by bob-zarkoob** [comment]
Hi @sfc-gh-jcieslak ,
Yes, I have unset and set the flag and it is now working :)
thank you.
