### ISSUE TITLE
Terraform Create Tag fails if the object already exists in Snowflake

### ISSUE THREAD

**Issue by supreetkumarcorvus** [Snowflake-Labs/terraform-provider-snowflake#2695]
### Terraform CLI and Provider Versions

Terrafor 1.7.5

### Terraform Configuration

```terraform
resource "snowflake_tag" "tag" {
  name           = "cost_center"
  database       = snowflake_database.database.name
  schema         = snowflake_schema.schema.name
  allowed_values = ["finance", "engineering"]
}
```

### Expected Behavior

- Should create a tag if it doesnt exist already
- if the tag already exists in database and was created via some other process, terraform apply should ignore tag creation and shouldnt fail

### Actual Behavior

- Works fine in case of new tag to be created
- Fails when the tag already exists (created earlier from either Snowflake UI or using tools like dbt)

### Steps to Reproduce

1. Create a tag in Snowflake UI
2. Add the same tag resource in .tf file
3. Run terraform apply. 

### How much impact is this issue causing?

Medium

### Additional Information

The problem could be solved with either of the multiple solutions:
- if terraform refresh can somehow get the state of tags, this resource create_tag wont fail
- Other option is allowing data resource to fetch the current state of tags. If this works, we can define the creation resource to conditionally create tags. There's already a feature request for data resource(https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1372)

**Comment by sfc-gh-jcieslak** [comment]
Hey @supreetkumarcorvus 
Closing as the solution for now it to use the standard way of importing existing objects to Terraform.
