### ISSUE TITLE
[Docs]: snowflake_grant_ownership example gives an incorrect key word - "plural_object_type" instead of "object_type_plural"

### ISSUE THREAD

**Issue by cpmub1** [Snowflake-Labs/terraform-provider-snowflake#2696]
### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership

### Description

snowflake_grant_ownership example gives an incorrect key word - "plural_object_type" instead of "object_type_plural"

### Would you like to implement a fix?

None

**Comment by sfc-gh-jcieslak** [comment]
Hey @cpmub1 
Thanks for pointing this out. We'll try to address this as soon as possible.

**Comment by sfc-gh-jcieslak** [comment]
Hey, we released a new provider version: https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.89.0. The docs should be fixed now.

**Comment by sfc-gh-jcieslak** [comment]
Hey @cpmub1 
Did you have a chance to take a look at the fixed documentation? We would like you to confirm the change and close the ticket if that's what you wanted to see.

**Comment by cpmub1** [comment]
this is looking good now. thanks for fixing it
