### ISSUE TITLE
tags_validations.go incorrectly restricting AllowedValues field: between 1 and 50

### ISSUE THREAD

**Issue by ajain-coveo** [Snowflake-Labs/terraform-provider-snowflake#2721]
### Terraform CLI and Provider Versions

Terraform v1.7.4
Snowflake Provider version = "0.88.0"

### Terraform Configuration

```terraform
N/A
```

### Expected Behavior

allowed_values in snowflake_tag resource should not be restricted to 50. Snowflake has that tag restriction of 50 only at the object level ==> Snowflake allows a maximum number of 50 unique tags that can be set on a single object.
But this restriction does not apply to the number of allowed values on a tag. 

resource "snowflake_tag" "tag" {
  name           = "cost_center"
  database       = snowflake_database.database.name
  schema         = snowflake_schema.schema.name
  allowed_values = ["finance", "engineering",........] `==> This should not have restriction of 50`
}

### Actual Behavior

When allowed_values list has more than 50 items getting following error while creating snowwflake_tag resource:

`Error: [tags_validations.go:39] AllowedValues field: Values must be between 1 and 50`

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

Error: [tags_validations.go:39] AllowedValues field: Values must be between 1 and 50

**Comment by sfc-gh-asawicki** [comment]
Hey @ajain-coveo. Thanks for reaching out to us.

As I can see, it was updated in Snowflake Nov. 27, 2023. We plan to work on such differences with upcoming resources redesign https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#supporting-all-snowflake-ga-features. This is a really small change, though, I will try to include it in tomorrow's release.

**Comment by sfc-gh-asawicki** [comment]
Hey @ajain-coveo. We have released new version with the requested changes: https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.89.0. Please bump and confirm that it works.

**Comment by sfc-gh-asawicki** [comment]
Closing as fixed. Please open a new issue if the problem persists in the newest provider version.
