### ISSUE TITLE
Task fail to properly pull Parent's name

### ISSUE THREAD

**Issue by bob-zarkoob** [Snowflake-Labs/terraform-provider-snowflake#2751]
### Terraform CLI and Provider Versions

CLI: 1.8.2
Provider: 0.89

### Terraform Configuration

```terraform
resource "snowflake_task" "task_load_dim_p" {

  database  = "${var.environment}_SILVER_DB"
  schema    = "TEST"
  name      = "TASK_LOAD_DIM_P"
  enabled   = true
  warehouse = local.etl_warehouse
  after     = [
    snowflake_task.task_load_line.name
  ]

  sql_statement = "call ${var.environment}_SILVER_DB.TEST.SP_LOAD_DIM_P()"
  depends_on    = [
    snowflake_task.task_load_line

  ]
}

I have also tried 


resource "snowflake_task" "task_load_dim_p" {

  database  = "${var.environment}_SILVER_DB"
  schema    = "TEST"
  name      = "TASK_LOAD_DIM_P"
  enabled   = true
  warehouse = local.etl_warehouse
  after     = [    "${snowflake_task.task_load_line.database}.${snowflake_task.task_load_line.schema}.${snowflake_task.task_load_line.name}"
  ]

  sql_statement = "call ${var.environment}_SILVER_DB.TEST.SP_LOAD_DIM_P()"
  depends_on    = [
    snowflake_task.task_load_line

  ]
}
```

### Expected Behavior

To create the task with the correct parent 

### Actual Behavior

Fails because it cannot find the parent when using the first config, and the second config, creates a messed up SQL behind the scene like this: 
```sql
DESCRIBE TASK "UAT_SILVER_DB"."TEST"."UAT_BRONZE_DB.TEST.TASK_LOAD_LINE"
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by bob-zarkoob** [comment]
I even tried to hard code the parent task fully qualified and get error and seeing this error on the snowflake side:
Config:

```
resource "snowflake_task" "task_load_dim_p" {

  database  = "${var.environment}_SILVER_DB"
  schema    = "TEST"
  name      = "TASK_LOAD_DIM_P"
  enabled   = true
  warehouse = local.etl_warehouse
  after     = [
    "UAT_BRONZE_DB.TEST.TASK_LOAD_HEADER"
  ]

  sql_statement = "call ${var.environment}_SILVER_DB.TEST.SP_LOAD_DIM_P()"
  depends_on    = [
    snowflake_task.task_load_line

  ]
}
```
and the SQL created is like this which errors out:
```sql
DESCRIBE TASK "UAT_SILVER_DB"."TEST"."UAT_BRONZE_DB.TEST.TASK_LOAD_HEADER", 
```
because it is placing the fully qualified name in the name section when it tries to desc.
I cannot use the 
  after     = [
    snowflake_task.task_load_line.name
  ]
because the parent task is in another schema and this will not work when want to actually create this task.

**Comment by sfc-gh-asawicki** [comment]
Hey @bob-zarkoob. Thanks for reaching out to us.

From Snowflake docs (scroll down to `AFTER` section https://docs.snowflake.com/en/sql-reference/sql/create-task#optional-parameters):
```
All tasks in a task graph must exist in the same schema.
```
