### ISSUE TITLE
[Bug]: During import of snowflake_warehouse, terraform plan output indicates, that property `query_acceleration_max_scale_factor` will be setted (updated)

### ISSUE THREAD

**Issue by Hunter-99** [Snowflake-Labs/terraform-provider-snowflake#2763]
### Terraform CLI Version

1.8.2

### Terraform Provider Version

0.89

### Terraform Configuration

```terraform
resource "snowflake_warehouse" "warehouse" {

  name                                = "TEST_WAREHOUSE"
  warehouse_size                      = "SMALL"
  comment                             = ""
  auto_resume                         = true
  min_cluster_count                   = 1
  max_cluster_count                   = 1
  max_concurrency_level               = 8
  query_acceleration_max_scale_factor = 8
  statement_queued_timeout_in_seconds = 0
  statement_timeout_in_seconds        = 172800
  scaling_policy                      = "STANDARD"
  enable_query_acceleration           = false
}
```

### Category

category:resource

### Object type(s)

resource:warehouse

### Expected Behavior

```terraform
...
  # snowflake_warehouse.warehouse["TEST_WAREHOUSE"] will be imported
    resource "snowflake_warehouse" "warehouse" {
        auto_resume = true
        comment = ""
        enable_query_acceleration = false
        id = "TEST_WAREHOUSE"
        max_cluster_count = 1
        max_concurrency_level = 8
        min_cluster_count = 1
        name = "TEST_WAREHOUSE"
        query_acceleration_max_scale_factor = 8
        resource_monitor = "null"
        scaling_policy = "STANDARD"
        statement_queued_timeout_in_seconds = 0
        statement_timeout_in_seconds = 172800
        warehouse_size = "SMALL"
        warehouse_type = "STANDARD"
    }
...
```

### Actual Behavior

```terraform
... 

 # snowflake_warehouse.warehouse["TEST_WAREHOUSE"] will be updated in-place
  # (imported from "TEST_WAREHOUSE")
  ~ resource "snowflake_warehouse" "warehouse" {
        auto_resume = true
        comment = ""
        enable_query_acceleration = false
        id = "TEST_WAREHOUSE"
        max_cluster_count = 1
        max_concurrency_level = 8
        min_cluster_count = 1
        name = "TEST_WAREHOUSE"
      + query_acceleration_max_scale_factor = 8
        resource_monitor = "null"
        scaling_policy = "STANDARD"
        statement_queued_timeout_in_seconds = 0
        statement_timeout_in_seconds = 172800
        warehouse_size = "SMALL"
        warehouse_type = "STANDARD"
    }

...
```

### Steps to Reproduce

1. Create resourse `snowflake_warehouse`:

```terraform
resource "snowflake_warehouse" "warehouse" {
        auto_resume = true
        comment = ""
        enable_query_acceleration = false
        id = "TEST_WAREHOUSE"
        max_cluster_count = 1
        max_concurrency_level = 8
        min_cluster_count = 1
        name = "TEST_WAREHOUSE"
        query_acceleration_max_scale_factor = 8
        resource_monitor = "null"
        scaling_policy = "STANDARD"
        statement_queued_timeout_in_seconds = 0
        statement_timeout_in_seconds = 172800
        warehouse_size = "SMALL"
        warehouse_type = "STANDARD"
    }
```
2. Run `terraform plan`

### How much impact is this issue causing?

Medium

### Additional Information

This issue (bug) happend, only when `enable_query_acceleration` param for warehouse is `false` (but `query_acceleration_max_scale_factor` equals, for example 8).

See the following part of `ReadWarehouse` func:

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/d0d504868b0dda15e3a779e94969d7742253160c/pkg/resources/warehouse.go#L273-L279

In this code, when terraform checks warehouse, and see, that `enable_query_acceleration` = false, then terraform will think, that `query_acceleration_max_scale_factor` is null.

But, in `UpdateWarehouse` function it will be set `query_acceleration_max_scale_factor` (8 by default), even though `enable_query_acceleration` = false

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/d0d504868b0dda15e3a779e94969d7742253160c/pkg/resources/warehouse.go#L424-L427

Thus, I think, we need to read `query_acceleration_max_scale_factor` property in `ReadWarehouse`, regardless of the `enable_query_acceleration` value 

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @Hunter-99. Thanks for reaching out to us.

I will try to reproduce this today. I will also find out why the attached logic was written this way.

**Comment by Hunter-99** [comment]
@sfc-gh-jcieslak, @sfc-gh-asawicki thanks! Now it works as I expected.

**Comment by sfc-gh-asawicki** [comment]
Hey @Hunter-99. Just letting you know that warehouse resource was redesigned and the behavior for `enable_query_acceleration` will change starting from v0.93.0. You can check the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v0920--v0930). The release should happen this week.
