### ISSUE TITLE
Snowflake Parameters Getting Failed | Terraform | Error [Bug]: 

### ISSUE THREAD

**Issue by ravisingh27** [Snowflake-Labs/terraform-provider-snowflake#2767]
### Terraform CLI Version

1.7.5

### Terraform Provider Version

0.89.0

### Terraform Configuration

```terraform
We presently use terraform automation to apply snowflake parameters, and we do so for 13 parameters total. These parameters are passed in as Terraform variables (map). We tried adding the two arguments below to our code recently, however we were receiving the error below. A remedy for this would be beneficial.

TERRAFORM_VERSION "1.7.5"

Error:
╷
│ Error: Invalid object parameter: ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY
│ 
│   with module.pre_snowflake_account_parameters["Account_Parameters-1"].snowflake_account_parameter.child_account_parameter,
│   on .terraform/modules/pre_snowflake_account_parameters/main.tf line 1, in resource "snowflake_account_parameter" "child_account_parameter":
│    1: resource "snowflake_account_parameter" "child_account_parameter" {
│ 
╵
╷
│ Error: Invalid object parameter: ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_SPCS_BLOCK_STORAGE
│ 
│   with module.pre_snowflake_account_parameters["Account_Parameters-2"].snowflake_account_parameter.child_account_parameter,
│   on .terraform/modules/pre_snowflake_account_parameters/main.tf line 1, in resource "snowflake_account_parameter" "child_account_parameter":
│    1: resource "snowflake_account_parameter" "child_account_parameter" {
│ 
╵
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1

/** Variable Section **/
Account_Parameters-1 = {
key  = "ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY",
    value = true,
    },
Account_Parameters-2 = {
    key  = "ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_SPCS_BLOCK_STORAGE",
    value = true,
    },
Account_Parameters-14 = {
      key  = "PERIODIC_DATA_REKEYING",
      value = true,
    },
```

### Category

category:resource

### Expected Behavior

ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY = true
ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_SPCS_BLOCK_STORAGE = true

### Actual Behavior

Error:
╷
│ Error: Invalid object parameter: ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY
│ 
│   with module.pre_snowflake_account_parameters["Account_Parameters-1"].snowflake_account_parameter.child_account_parameter,
│   on .terraform/modules/pre_snowflake_account_parameters/main.tf line 1, in resource "snowflake_account_parameter" "child_account_parameter":
│    1: resource "snowflake_account_parameter" "child_account_parameter" {
│ 
╵
╷
│ Error: Invalid object parameter: ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_SPCS_BLOCK_STORAGE
│ 
│   with module.pre_snowflake_account_parameters["Account_Parameters-2"].snowflake_account_parameter.child_account_parameter,
│   on .terraform/modules/pre_snowflake_account_parameters/main.tf line 1, in resource "snowflake_account_parameter" "child_account_parameter":
│    1: resource "snowflake_account_parameter" "child_account_parameter" {
│ 
╵
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1

![Account_Parameter_Error](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/156783233/2d3398a4-a110-4c05-919a-bb523e58b718)

### Steps to Reproduce

sourcing the snowflake_account_parameters as a module.
mapping the key : value - as a terraform variable.
for_each = var.snowflake_account_parameters
  key = each.value.key
  value = each.value.value

terraform apply 

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @ravisingh27 👋
Today, we released a new version [v0.90.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.90.0) that contained a fix for your issue. Please, let us know if you're still experiencing this issue in the latest version.

**Comment by ravisingh27** [comment]
Thanks, I'll check and close.

**Comment by sfc-gh-asawicki** [comment]
Hey @ravisingh27. Were you able to test the new version?

**Comment by ravisingh27** [comment]
Hey @sfc-gh-asawicki , Not yet but we'll be including this in next quarter.

**Comment by sfc-gh-asawicki** [comment]
I will close the issue then. Please create a new one if the added parameters won't work.
