### ISSUE TITLE
[Docs]:  Provider missing in Documentation

### ISSUE THREAD

**Issue by natashamathur** [Snowflake-Labs/terraform-provider-snowflake#2775]
### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/

### Description

When following the instructions at the documentation above I got this error:

```
Error: Invalid provider configuration
Provider "registry.terraform.io/snowflake-labs/snowflake" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
```

In order to fix it I had to include provider, like this:

```
resource "snowflake_grant_privileges_to_account_role" "example" {

  provider = <provider_role>
  account_role_name = snowflake_role.db_role.name
  on_account        = true
  all_privileges    = true
  with_grant_option = true
}
```

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @natashamathur. Thanks for reaching out to us.

This is the terraform behavior (in general) when you specify aliases. You can check more in https://developer.hashicorp.com/terraform/language/providers/configuration#default-provider-configurations.
