### ISSUE TITLE
[Bug]: For loop for stream and/or stage causes plugin to crash

### ISSUE THREAD

**Issue by barabasakos** [Snowflake-Labs/terraform-provider-snowflake#2792]
### Terraform CLI Version

1.3.6

### Terraform Provider Version

0.89.0

### Terraform Configuration

```terraform
variable "iceberg_resources" {
  type = list(object({
    table_name         = string
    base_location      = string
    metadata_file_path = string
    stage_name         = string
    stream_name        = string
  }))
  description = "Iceberg table name, base location on the bucket, metadata file path on the bucket"
  default     = null
}

locals {
iceberg_resources = [
    {
      table_name         = "test"
      base_location      = "test/"
      metadata_file_path = "metadata/test.metadata.json"
      stage_name         = "test"
      stream_name        = "test"
      cron_schedule      = "0 */12 * * *"
    }]
}
resource "snowflake_stage" "main" {
  for_each            = { for i in local.iceberg_resources : i.base_location => i }
  name                = each.value.stage_name
  url                 = "s3://${local.external_volume_base_url}/${each.value.base_location}"
  database            = local.database_name
  schema              = local.schema_name
  storage_integration = local.storage_integration
  comment             = "Stage created for landing ${local.project_name} data from S3"
  directory           = "ENABLE = true AUTO_REFRESH = true"
}

resource "snowflake_stream" "stream" {
  for_each = { for i in local.iceberg_resources : i.stream_name => i }
  comment  = "Snowflake streams are objects that track all DML operations against the source table, this is used for ${local.project_name}"

  database = local.database_name
  schema   = local.schema_name
  name     = each.value.stream_name

  on_stage    = true
  append_only = false
  insert_only = false
}
```

### Category

category:provider_config

### Expected Behavior

Create new resources (stream,stage and some others).

### Actual Behavior

module.snowflake-objects.snowflake_stream.stream["test"]: Creating...
module.snowflake-objects.snowflake_storage_integration.s3: Creating...
module.snowflake-objects.snowflake_stage.main["test/"]: Creating...
module.snowflake-objects.snowflake_stream.stream["test"]: Creating...
module.snowflake-objects.snowflake_stage.main["test/"]: Creating...
module.snowflake-objects.snowflake_stream.stream["test"]: Creating...
module.snowflake-objects.snowflake_stage.main["test/"]: Creating...
module.snowflake-objects.snowflake_stream.stream["test"]: Creating...
module.snowflake-objects.snowflake_stage.main["test/"]: Creating...
╷
│ Warning: Argument is deprecated
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on providers.tf line 50, in provider "snowflake":
│   50:   username  = local.snowflake_username
│
│ Use `user` instead of `username`
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.89.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 105 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateStream(0x0?, {0x103f0cac0?, 0x14000110778?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/stream.go:195 +0x11bc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1042f5008?, {0x1042f5008?, 0x14000c548d0?}, 0xd?, {0x103f0cac0?, 0x14000110778?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000626ee0, {0x1042f5008, 0x14000c548d0}, 0x14001102410, 0x140010d5300, {0x103f0cac0, 0x14000110778})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000d08528, {0x1042f5008?, 0x14000c54720?}, 0x14001190fa0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xb08
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x10430a718?, 0x14000d08528?}}, {0x1042f5008, 0x14000c54720}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x1042f5040?, {0x1042f5008?, 0x14000c54270?}, 0x14001190f50)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000a1c8c0, {0x1042f5008?, 0x14000c409c0?}, 0x14001138070)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x10425dda0?, 0x14000a1c8c0}, {0x1042f5008, 0x14000c409c0}, 0x140010d4b00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000ead20, {0x1042f5008, 0x14000c40930}, {0x104305ca0, 0x14000102ea0}, 0x14000a846c0, 0x14000827b00, 0x1051bbeb8, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140000ead20, {0x104305ca0, 0x14000102ea0}, 0x14000a846c0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 45
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x138

Error: The terraform-provider-snowflake_v0.89.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

Same as above, i'm thinking the for_each statement causes the provider to fail/error out.

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @barabasakos 👋 
It seems like your config for stream is incorrect, you have to put a fully qualified name to the `on_stage` field, so you have to go from this
```terraform
resource "snowflake_stream" "stream" {
  for_each = { for i in local.iceberg_resources : i.stream_name => i }
  comment  = "Snowflake streams are objects that track all DML operations against the source table, this is used for ${local.project_name}"

  database = local.database_name
  schema   = local.schema_name
  name     = each.value.stream_name

  on_stage    = true
  append_only = false
  insert_only = false
}
```
to this
```terraform
resource "snowflake_stream" "stream" {
  for_each = { for i in local.iceberg_resources : i.stream_name => i }
  comment  = "Snowflake streams are objects that track all DML operations against the source table, this is used for ${local.project_name}"

  database = local.database_name
  schema   = local.schema_name
  name     = each.value.stream_name

  # replace database_name, schema_name, and stage_name with real values
  on_stage    = "\"${database_name}\".\"${schema_name}\".\"${stage_name}\""
  append_only = false
  insert_only = false
}
```

**Comment by barabasakos** [comment]
@sfc-gh-jcieslak Ah, thanks.. that did the trick. :)
