### ISSUE TITLE
[Bug]: Issue with grant_privileges_to_share - help us understand this error message

### ISSUE THREAD

**Issue by natashamathur** [Snowflake-Labs/terraform-provider-snowflake#2793]
### Terraform CLI Version

0.88.0

### Terraform Provider Version

0.88.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_share" "raw_db_reference_usage_grant" {
  provider = snowflake.account_admin
  for_each = toset([
    snowflake_share.ext_a_share.name,
    snowflake_share.ext_b_share.name,
    snowflake_share.ext_c_share.name,
  ])
  privileges  = ["REFERENCE USAGE"]
  to_share    = each.key
  on_database = snowflake_database.raw.name

}

resource "snowflake_grant_account_role" "reporter_grant_to_roles" {
  provider = snowflake.security_admin
  for_each = toset([for u in [snowflake_role.data_engineer_role.name,
    snowflake_role.dev_team_role.name,
    "ACCOUNTADMIN",
  "SYSADMIN"] : nonsensitive(u)])
  role_name = snowflake_role.reporter_role.name
  user_name = each.value
}
```

### Category

category:grants

### Expected Behavior

- Grant REFERENCE USAGE on the database RAW to the shares indicated
- Grant `reporter_role` to the roles listed

### Actual Behavior

Got the following errors:
<img width="881" alt="Screenshot 2024-05-10 at 2 23 46 PM" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/35498283/11fe3874-6c40-44e8-84eb-06ffbada6df7">

### Steps to Reproduce

Did not error in terraform plan but did error when applied. 

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @natashamathur 
I'm guessing this line is causing the error `privileges  = ["REFERENCE USAGE"]`, as you can see in the [documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege-share#syntax), the privilege name is `REFERENCE_USAGE` (with the underscore, not space). Please, try to use the correct privilege name and let me know if that works.
