### ISSUE TITLE
[Bug]: Unable to use `sdk.Client.Users.Show` with insufficient priveleges

### ISSUE THREAD

**Issue by candiduslynx** [Snowflake-Labs/terraform-provider-snowflake#2817]
### Terraform CLI Version

N/A

### Terraform Provider Version

0.90.0

### Terraform Configuration

```terraform
N/A
```

### Category

category:sdk

### Object type(s)

resource:user, data_source:users

### Expected Behavior

The missing fields should just be left empty

### Actual Behavior

The [`sdk.Users`](https://pkg.go.dev/github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk#Users) `Show` method (`sdk.Client.Users.Show`) fails when using credentials that don't have both `OWNERSHIP` & `MANAGE GRANTS` privileges (as required for full output in [docs](https://docs.snowflake.com/en/sql-reference/sql/show-users#usage-notes).

```
2024/05/15 15:27:31 [DEBUG] err: sql: Scan error on column index 10, name "disabled": sql/driver: couldn't convert "null" into type bool
```

### Steps to Reproduce

1. Create a user `A`
2. Create a user `B` without `OWNERSHIP` & `MANAGE GRANTS` privileges on `A`
3. Execute `sdk.Client.Users.Show`

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by candiduslynx** [comment]
The issue is caused by several columns being returned as `"null"` string instead of an actual `null` sql value (that is received in Go as untyped `nil`).

**Comment by sfc-gh-asawicki** [comment]
Hey @candiduslynx. I will link it to the user resource redesign as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1.

**Comment by sfc-gh-asawicki** [comment]
Hey @candiduslynx, the fix was included in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3013 and will be released in v0.95.0 today or tomorrow (we have to wrap up a few other PRs before making a release). Please check the migration guide and report any problems.

**Comment by candiduslynx** [comment]
cc: @erezrokah

**Comment by sfc-gh-asawicki** [comment]
Hey @arkadiyt.
We have just released v0.95.0 of the provider. It contains a reworked `snowflake_user` resource. Please consult the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v094x--v0950).

**Comment by candiduslynx** [comment]
cc @erezrokah once more

**Comment by sfc-gh-asawicki** [comment]
Closing the issue due to inactivity. Please create a new one if the issue persists in the newest version of the provider.
