### ISSUE TITLE
[Bug]: snowflake_grant_privileges_to_account_role is not working iceberg tables

### ISSUE THREAD

**Issue by adwaitdes** [Snowflake-Labs/terraform-provider-snowflake#2825]
### Terraform CLI Version

1.3.6

### Terraform Provider Version

0.88.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "iceberg_table"{
privileges = ["SELECT"]
account_role_name = "ACCOUNT_ROLE"
on_schema_object {
   object_type = "ICEBERG TABLE"
   object_name = "database_name.schema_name.iceberg_table_name"
}
} 

Error:
An error occured while granting privileges to account role
Id: "ACCOUNT_ROLE"|false|false|SELECT|OnSchemaObject|OnObject|ICEBERG TABLE|"database_name"."schema_name"."iceberg_table_name"
Account Role Name: {ACCOUNT_ROLE}
Error: object does not exist or not authorized
```

### Category

category:resource

### Expected Behavior

Select grant on iceberg table must be given to account role

### Actual Behavior

Error: object does not exist or not authorized

### Steps to Reproduce

Used following resource:
resource "snowflake_grant_privileges_to_account_role" "iceberg_table"{
privileges = ["SELECT"]
account_role_name = "ACCOUNT_ROLE"
on_schema_object {
   object_type = "ICEBERG TABLE"
   object_name = "database_name.schema_name.iceberg_table_name"
}
} 

Ensured that Iceberg table is present in given database and schema.
Ensured that user running terraform script has grants with appropriate grant options.

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
What's worth mentioning is that object_name is also case-sensitive, so passed database.schema.table will have the same casing. Please check if they are lower-cased in Snowflake. Other than that I cannot really help without logs. Please attach the logs with the `TF_LOG=DEBUG` environment variable enabled.

**Comment by adwaitdes** [comment]
Thanks. after matching case Terraform apply went through. However, destroy is failing.
Error:
error revoking privileges from account role exactly one of AccountRoleGrantPrivileges fields[AllPrivileges GlobalPrivileges AccountObjectPrivileges SchemaPrivileges SchemaObjectPrivileges] must be set.

**Comment by sfc-gh-jcieslak** [comment]
Hmm, that's a familiar error (I'm guessing after you create the grant, there's an infinite plan on `privileges` saying it will "add" the privileges you specified, because right now they're empty). My best guess is that when you call `show grants on iceberg table <iceberg_table_identifier>` then the `granted_on` column returns something different than `ICEBERG TABLE` (could be returning e.g. `TABLE`). It would be great if you could confirm that. Until we will fix it, you can create the resource and "turn off" the plan for privileges with [ignore changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) meta argument, but you won't be able to remove (revoke) the grant resource. I'm not able to say when the fix would be applied, but as I said additional info on SHOW GRANTS command would help.

**Comment by adwaitdes** [comment]
> Hmm, that's a familiar error (I'm guessing after you create the grant, there's an infinite plan on `privileges` saying it will "add" the privileges you specified, because right now they're empty). My best guess is that when you call `show grants on iceberg table <iceberg_table_identifier>` then the `granted_on` column returns something different than `ICEBERG TABLE` (could be returning e.g. `TABLE`). It would be great if you could confirm that. Until we will fix it, you can create the resource and "turn off" the plan for privileges with [ignore changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) meta argument, but you won't be able to remove (revoke) the grant resource. I'm not able to say when the fix would be applied, but as I said additional info on SHOW GRANTS command would help.

"SHOW GRANTS ON ICEBERG TABLE <iceberg_table_name>"
 shows granted_on column as "TABLE" and not "ICEBERG TABLE"

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity. Please try the provided solution.
