### ISSUE TITLE
[Bug]: The provider reports Error: 260002: password is empty

### ISSUE THREAD

**Issue by sgandhi1011** [Snowflake-Labs/terraform-provider-snowflake#2883]
### Terraform CLI Version

Terraform v1.5.7 on darwin_arm64

### Terraform Provider Version

0.88.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.88.0"
    }
  }
  backend "s3" {
    encrypt = true
  }
}

variable "snowflake_role" {
  type    = string
  default = ""
}

provider "snowflake" {
  role = var.snowflake_role != "" ? var.snowflake_role : "SECURITYADMIN"
}

resource "snowflake_grant_ownership" "owner" {
  account_role_name = "USERADMIN"
  on {
    object_type = "USER"
    object_name = "SOMEONE"
  }
}
```

### Category

category:resource

### Expected Behavior

No errors

### Actual Behavior

│ Error: 260002: password is empty
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on config.tf line 21, in provider "snowflake":
│   21: provider "snowflake" {

### Steps to Reproduce

1. Set the env variables the provider need
export SNOWFLAKE_ACCOUNT=sfaccount
export SNOWFLAKE_USER=user-id
export SNOWFLAKE_PRIVATE_KEY="" OR export SNOWFLAKE_PRIVATE_KEY_PATH=~/rsa_key.p8
export SNOWFLAKE_REGION=eu-west-2

2. terraform init and terraform apply

### How much impact is this issue causing?

High

### Additional Information

We are currently using providers less than 0.71.0 and when using anything like 0.88.0 or latest we are facing password missing error. Not sure if it only supports password authentication, but we need key pair auth to work.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @sgandhi1011. Thanks for reaching out to us.

Please read https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#behavior-change-authenticator-jwt and try setting out the authenticator explicitely.

**Comment by sgandhi1011** [comment]
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.92.0"
    }
  }
  backend "s3" {
    encrypt = true
  }
}

provider "snowflake" {
  role = var.snowflake_role != "" ? var.snowflake_role : "SECURITYADMIN"
  authenticator = "JWT"
}

That worked. Thanks.
