### ISSUE TITLE
[Bug]: snowflake_share cannot add accounts due to incorrect quoting

### ISSUE THREAD

**Issue by dmfay** [Snowflake-Labs/terraform-provider-snowflake#2889]
### Terraform CLI Version

1.8.0

### Terraform Provider Version

0.90.0

### Terraform Configuration

```terraform
resource "snowflake_share" "share" {
  name     = var.name
  comment  = var.comment
  accounts = ["abcdefg.${var.target}"]
}
```

### Category

category:identifiers

### Object type(s)

resource:share

### Expected Behavior

Share should be created and my target account added.

### Actual Behavior

Application yields an error:

```
│ Error: 003516 (0A000): SQL compilation error:
│ Following accounts cannot be added to this share: "abcdefg".TARGET.
```

### Steps to Reproduce

apply

### How much impact is this issue causing?

High

### Additional Information

I am able to reproduce the exact error in snowsql if I quote the organization name part (I can quote the target account, but that seems to be parsed correctly as an identifier):

```
dfay#WAREHOUSE@DB.SCHEMA>alter share dmfshare add accounts="abcdefg".target;
003516 (0A000): SQL compilation error:
Following accounts cannot be added to this share: "abcdefg".target.
dfay#WAREHOUSE@DB.SCHEMA>alter share dmfshare add accounts="abcdefg"."target";
003516 (0A000): SQL compilation error:
Following accounts cannot be added to this share: "abcdefg".target.
dfay#WAREHOUSE@DB.SCHEMA>alter share dmfshare add accounts=abcdefg.target;
+----------------------------------+
| status                           |
|----------------------------------|
| Statement executed successfully. |
+----------------------------------+
```

I'd use the locator, but:

```
│ Error: account locators are not allowed - please use 'organization_name.account_name
│ 
│   with module.my_stuff.snowflake_share.share,
│   on ../../../modules/snowflake/share_source/main.tf line 37, in resource "snowflake_share" "share":
│   37:   accounts = var.target_accounts
```

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @dmfay. Thanks for reaching out to us.

Remember that the casing matters with fully qualified names (the quoted ones). In your example, "target" is written in different ways (lowercase vs. uppercase). I have just reproduced the same behavior while using the wrong casing on our test account. Please try UPPERCASING.

**Comment by dmfay** [comment]
ah, I'd tried uppercasing the `target` account name earlier, but it needs the organization name uppercased too. The printed error has the account already uppercased (and unquoted) but it looks like the provider parses the string and adds quotes to the organization -- is that behavior documented anywhere? Thanks!

**Comment by sfc-gh-asawicki** [comment]
Hey @dmfay. Do I understand correctly that uppercasing both solved your problem?

It may not be documented in one place, but we will work on the documentation clarity before reaching a stable V1. For now, you can assume that casing always matters when using the TF provider.

**Comment by dmfay** [comment]
yes, that's correct.
