### ISSUE TITLE
[Bug]: Unable to import file format

### ISSUE THREAD

**Issue by kharigardner** [Snowflake-Labs/terraform-provider-snowflake#2897]
### Terraform CLI Version

1.9.0

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
resource "snowflake_file_format" "parquet" {
    for_each =  toset(local.environments)

    name        = "S3_PARQUET"
    database    = "${each.key}_DATA_ADMINISTRATION"
    schema      = "INTEGRATIONS"
    format_type = "PARQUET"
}
```

### Category

category:import

### Expected Behavior

Import succeeds

### Actual Behavior

![bug](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/75547721/ff2ef0c7-5a35-40f0-a73d-d82bac18c091)

### Steps to Reproduce

terraform import 'snowflake_file_format.parquet["SBX"]' SBX_DATA_ADMINISTRATION.INTEGRATIONS.S3_PARQUET

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @kharigardner. I think that the resource ID is incorrect. Please follow https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/file_format#import, the pipe (`|`) is the correct separator for importing file formats.
