### ISSUE TITLE
[Feature]: Unable to use snowflake_grant_privileges_to_account_role for STAGE grant

### ISSUE THREAD

**Issue by hiromu166** [Snowflake-Labs/terraform-provider-snowflake#2903]
### Use Cases or Problem Statement

According to the documentation, it is recommended to use `snowflake_grant_privileges_to_account_role` instead of `snowflake_stage_grant`.
However, the `object_type` in the `on_account_object` argument of `snowflake_grant_privileges_to_account_role` does not include STAGE as an option, so it seems that it does not provide the same functionality as `snowflake_stage_grant`.
Is there a way to achieve the same functionality as `snowflake_stage_grant` using `snowflake_grant_privileges_to_account_role`? Or is it currently under development and will be added in the future?

### Category

category:grants

### Object type(s)

resource:grant_privileges_to_account_role

### Proposal

I want to use `snowflake_grant_privileges_to_account_role` instead of `snowflake_stage_grant`.

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @hiromu166. Thanks for reaching out to us.

Stage is not an account-level object. It is listed in the schema objects section: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role#nested-schema-for-on_schema_object.

**Comment by hiromu166** [comment]
Thank you for your response.
As you mentioned, using `on_schema_object` solved the issue!
