### ISSUE TITLE
[General Usage]: 

### ISSUE THREAD

**Issue by tabu69** [Snowflake-Labs/terraform-provider-snowflake#2911]
### Terraform CLI Version

1.1.5

### Terraform Provider Version

0.91.0

### Terraform Configuration

```terraform
Hi Community,

I am putting this query under general category as I'm not sure if it's a bug or something I am doing incorrect with use of the snowflake_grant_account_role resource.

Specifically, grants related to stages; my use case is implementing  usage, read and write grants. However on Apply this occurs:

-------------------------------

Error: An error occurred when granting privileges to account role

  with snowflake_grant_privileges_to_account_role.TEST_DB_TEST_SCHEMA_STAGES_WRITE_future["TEST_ROLE"],
  on schema_objects_grants.gen.tf line 1420, in resource "snowflake_grant_privileges_to_account_role" "TEST_DB_TEST_SCHEMA_STAGES_WRITE_future":
1420: resource "snowflake_grant_privileges_to_account_role" "TEST_DB_TEST_SCHEMA_STAGES_WRITE_future" {

Id:
"KDR_INFRA_DEV"|false|false|WRITE|OnSchemaObject|OnFuture|STAGES|InSchema|"TEST_DB"."TEST_SCHEMA"
Account role name: {TEST_ROLE}
Error: 003511 (23001): SQL compilation error: Privilege order violation for
the future grants on stage. READ should be granted before/simultaneously with
WRITE.

-------------------------------

Re-running the plan outputs grants write will be created and running Apply, the write grants apply successfully

  # snowflake_grant_privileges_to_account_role.TEST_DB_TEST_SCHEMA_STAGES_WRITE_future["TEST_ROLE"] will be created
  + resource "snowflake_grant_privileges_to_account_role" "TEST_DB_TEST_SCHEMA_STAGES_WRITE_future" {
      + account_role_name = "TEST_ROLE"
      + all_privileges    = false
      + always_apply      = false
      + id                = (known after apply)
      + on_account        = false
      + privileges        = [
          + "WRITE",
        ]
      + with_grant_option = false

      + on_schema_object {

          + future {
              + in_schema          = "\"TEST_DB\".\"TEST_SCHEMA\""
              + object_type_plural = "STAGES"
            }
        }
    }
-------------------------------

The questions: 

1. For stage objects, where grants of usage, read and write are attempted to be applied at the same time does the provider have inbuilt logic to determine that read should be applied before write?

2. In absence of the above, is there a known approach/workaround to ensure read gets applied before write?

Thanks in advance!

Tanya
```

### Category

category:resource

### Expected Behavior

Provider has logic to know that read grants is a dependency for write grant

### Actual Behavior

Initial Apply of grants fails due to error with write grant being applied before read.

### Steps to Reproduce

N/A

### How much impact is this issue causing?

Low

**Comment by sfc-gh-jmichalak** [comment]
Hi @tabu69. Can you provide exact resource configuration? On my side, I tested with
```resource "snowflake_grant_privileges_to_account_role" "TEST_DB_TEST_SCHEMA_STAGES_WRITE_future" {
  account_role_name = "TEST_ROLE"
  always_apply = false
  privileges = [
    "WRITE", "READ", "USAGE",
  ]
  with_grant_option = false

  on_schema_object {

    future {
      in_schema          = "\"JMICHALAK\".\"PUBLIC\""
      object_type_plural = "STAGES"
    }
  }
}
```
and it works fine. Note that you need to explicitly configure "READ" privilege here. In provider, this is applied at the same time, because Snowflake allows it with query like this: `GRANT WRITE, READ, USAGE ON FUTURE STAGES IN SCHEMA "JMICHALAK"."PUBLIC" TO ROLE "TEST_ROLE"`

**Comment by tabu69** [comment]
Hi @sfc-gh-jmichalak - Sorry for the delayed response. much more testing has been undertaken.  Just a question on this - if write access is is required, is it necessary to also specify read? i.e. is write privilege, implicit. Thanks!

**Comment by tabu69** [comment]
Hi @sfc-gh-jmichalak  - Thanks a lot for sharing the info, sorry I missed this in the documentation.

I believe the issue is with my code then, essentially the grants for write and read are duplicate in my code and executing twice, which leads to write being applied before read, which is also a product of migrating to the new resource type snowflake_grant_privileges_to_account_role. I need to remove some reference to old logic that creates resource per grant for read, write and usage and as you've pointed out in original response declare the read, write, usage in a single resource.

Thanks very much for your guidance. I will go ahead and close this one.
