### ISSUE TITLE
[Bug]: error creating object parameter for ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY, CLIENT_ENCRYPTION_KEY_SIZE, and PERIODIC_DATA_REKEYING

### ISSUE THREAD

**Issue by raegreen** [Snowflake-Labs/terraform-provider-snowflake#2915]
### Terraform CLI Version

1.4.6

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
resource "snowflake_object_parameter" "rekey_opt_out" {
  provider   = snowflake.accountadmin
  key        = "ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY"
  value      = "true"
  on_account = true
}

resource "snowflake_object_parameter" "encryption_key_size" {
  provider   = snowflake.accountadmin
  key        = "CLIENT_ENCRYPTION_KEY_SIZE"
  value      = "256"
  on_account = true
}

resource "snowflake_object_parameter" "periodic_data_rekeying" {
  provider   = snowflake.accountadmin
  key        = "PERIODIC_DATA_REKEYING"
  value      = "true"
  on_account = true

  depends_on = [snowflake_object_parameter.rekey_opt_out]
}
```

### Category

category:sdk

### Object type(s)

resource:object_parameter

### Expected Behavior

parameters would be updated as a part of the apply

### Actual Behavior

I get the same error for all three: 

Error: error creating object parameter err = Invalid object parameter: <parameter name>

### Steps to Reproduce

1. add a parameter:

resource "snowflake_object_parameter" "sample" {
  provider   = snowflake.accountadmin
  key        = "ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY"
  value      = "true"
  on_account = true
}

2. apply update

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @raegreen. Thanks for reaching out to us.

[ENABLE_TRI_SECRET_AND_REKEY_OPT_OUT_FOR_IMAGE_REPOSITORY](https://docs.snowflake.com/en/sql-reference/parameters#enable-tri-secret-and-rekey-opt-out-for-image-repository) is the account level parameter. Please use [snowflake_account_parameter](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/account_parameter) to set it. The same applies to [CLIENT_ENCRYPTION_KEY_SIZE](https://docs.snowflake.com/en/sql-reference/parameters#client-encryption-key-size) and [PERIODIC_DATA_REKEYING](https://docs.snowflake.com/en/sql-reference/parameters#periodic-data-rekeying).

We will revisit `snowflake_account_parameter` and `snowflake_object_parameter` as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-the-rest-of-the-fundamental-ga-objects-for-the-provider-v1 (this includes fixing the docs too).
