### ISSUE TITLE
[Bug]: Import resource procedure trying to rebuild resource

### ISSUE THREAD

**Issue by olevenkov** [Snowflake-Labs/terraform-provider-snowflake#2918]
### Terraform CLI Version

1.8.5

### Terraform Provider Version

0.92

### Terraform Configuration

```terraform
While importing procedures, terraform tries to add 
null_imput_behavior 
return _behavior 
and trying to recreate importing resources 
I tried to add the missing parameters and remove them..., but it is trying to recreate it...
```

### Category

category:resource

### Expected Behavior

Import without recreating resources

### Actual Behavior

tries to recreate resources 

### Steps to Reproduce

Try to  use the import block. 

import {
              ID = "dbName.schemaName.procedureName(varchar, varchar, varchar)"
              to snowflake_procedure.example
}

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @olevenkov. Thanks for reaching out to us.

Both these parameters are marked as ForceNew, so any change to them will require resource recreation. Currently, both have the defaults set in the config. For now, you can explicitly set them to their default values in the config (`CALLED ON NULL INPUT` and `VOLATILE`). This should prevent the recreation.

Keep in mind that this resource is subject to redesign, and we will visit it shortly as part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1.
