### ISSUE TITLE
[Docs]: snowflake_user_password_policy_attachment invalid args

### ISSUE THREAD

**Issue by georgeb-accelins** [Snowflake-Labs/terraform-provider-snowflake#2920]
### Object type(s)

resource:user_password_policy_attachment

### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/user_password_policy_attachment

### Description

Using the latest provider version, 0.92.0, I get the following errors if I try to include `password_policy_database` or `password_policy_schema` args to resource `snowflake_user_password_policy_attachment`

Unexpected attribute: An attribute named "password_policy_database" is not expected here
Unexpected attribute: An attribute named "password_policy_schema" is not expected here

I also do not see these fields defined in the resource [schema](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/ed237c36e82291d75d38e2741bdcfd53e598a447/pkg/resources/user_password_policy_attachment.go#L15).

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @georgeb-accelins. THanks for reaching out to us.

You are right, the example is incorrect. We will fix it before today's release.

**Comment by sfc-gh-asawicki** [comment]
Hey @georgeb-accelins, we updated the example in v0.93.0: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/user_password_policy_attachment

**Comment by sfc-gh-asawicki** [comment]
Closing as completed.
