### ISSUE TITLE
[Bug]: Database clone not possible anymore in v0.93

### ISSUE THREAD

**Issue by nicolamarangoni** [Snowflake-Labs/terraform-provider-snowflake#2926]
### Terraform CLI Version

1.9.2

### Terraform Provider Version

0.93

### Terraform Configuration

```terraform
Upgrade from provider version 0.92 to 0.93
```

### Category

category:resource

### Expected Behavior

The resource snowflake_database has a property to allow cloning of existing databases.

### Actual Behavior

In version 0.93, I don't find a property to clone a database.

### Steps to Reproduce

Try cloning a database using v0.93

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @nicolamarangoni. Thanks for reaching out to us.

We dropped the possibility of cloning the databases in v0.93.0 and won't support object cloning for any object for V1. We mentioned it in https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#behavior-change-resource-renamed-snowflake_database---snowflake_database_old, and we will include a bigger motivation soon (we missed that before the release).

Currently, you can either use https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute or clone manually and import with terraform.

**Comment by nicolamarangoni** [comment]
Ok thanks for the information!

**Comment by sfc-gh-asawicki** [comment]
I will keep this issue open until we add a proper motivation in https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/CHANGES_BEFORE_V1.md#design-decisions-before-v1

**Comment by sfc-gh-asawicki** [comment]
Motivation added here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/CHANGES_BEFORE_V1.md#object-cloning. Closing.
