### ISSUE TITLE
[Docs]: Faulty advice in resource_migration.md

### ISSUE THREAD

**Issue by jamiekt** [Snowflake-Labs/terraform-provider-snowflake#2928]
### Documentation Link

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md

### Description

The document states:
> Unfortunately, for_each cannot be used when generating with import blocks

That isn't true. for_each for import blocks has been available since terraform 2.7 which has been available since 2024-01-17 (https://www.hashicorp.com/blog/terraform-1-7-adds-test-mocking-and-config-driven-remove)

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by jamiekt** [comment]
Fix here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2929

**Comment by sfc-gh-asawicki** [comment]
Hey @jamiekt. Thanks for the contribution. Merged :)
