### ISSUE TITLE
[Feature]: SECRET and EXTERNAL ACCESS INTEGRATION

### ISSUE THREAD

**Issue by nicolamarangoni** [Snowflake-Labs/terraform-provider-snowflake#2932]
### Use Cases or Problem Statement

We need to create a secret, a network rule and an external access integration.
I see that there is a resource snowflake_network_rule but I miss snowflake_secret and snowflake_external_access_integration.

### Category

category:resource

### Proposal

Provide the resources snowflake_secret and snowflake_external_access_integration.

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @nicolamarangoni. Thanks for creating the issue.

THere are already open issues: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2545 and https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2546 with the answers.

**Comment by nicolamarangoni** [comment]
Hi @sfc-gh-asawicki , sorry, I didn't find the previous issues with the search.

**Comment by sfc-gh-asawicki** [comment]
Closing as duplicate.
