### ISSUE TITLE
snowflake_user_parameter resource is missing

### ISSUE THREAD

**Issue by simonepm** [Snowflake-Labs/terraform-provider-snowflake#2938]
### Use Cases or Problem Statement

Hello,

we have snowflake_account_parameter and snowflake_object_parameter.

I see we do not have a way to set parameters at user level e.g. CLIENT_SESSION_KEEP_ALIVE true for Kafka connector users.

I was not able to find it in the roadmap as well, feel free to close this issue if is going to be implemented.

Many thanks!

### Category

category:resource

### Object type(s)

resource:account_parameter, resource:object_parameter, resource:user

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @simonepm 👋 We're adding missing session parameters to our in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2936. We're currently redesigning user resource, so this should be implemented in the next release. cc @sfc-gh-asawicki

**Comment by simonepm** [comment]
Unfortunately session_parameter does not cover this use case in particular, but glad to hear that user resource is getting a redesign, thank you!

**Comment by sfc-gh-asawicki** [comment]
Hey @simonepm. I am currently redesigning the user resource. It will support ~60 user parameters (including the requested `CLIENT_SESSION_KEEP_ALIVE`). We will publish the full list in our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide) when it's ready.

**Comment by sfc-gh-asawicki** [comment]
Done in #2968 (not released yet).

**Comment by sfc-gh-asawicki** [comment]
Hey @simonepm.
We have just released v0.95.0 of the provider. It contains a reworked `snowflake_user` resource. Please consult the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v094x--v0950).

**Comment by sfc-gh-asawicki** [comment]
Closing the issue due to inactivity. Please create a new one if the issue persists in the newest version of the provider.
