### ISSUE TITLE
[Bug]: Snowflake_Warehouse Resource Limits Max Cluster Count

### ISSUE THREAD

**Issue by bdumford-OM1** [Snowflake-Labs/terraform-provider-snowflake#2948]
### Terraform CLI Version

1.5.3

### Terraform Provider Version

0.93.0

### Terraform Configuration

```terraform
resource "snowflake_warehouse" "warehouse" {
  ...
  max_concurrency_level               = var.warehouse_max_concurrency_level
}
```

### Category

category:resource

### Object type(s)

resource:warehouse

### Expected Behavior

The documentation for the `snowflake_warehouse` does say that the `max_cluster_count` parameter is ranged from 1-10.  However, not every Snowflake account is limited to only 10 clusters on a given warehouse.  We have a warehouse that has a max cluster count value of 20.  I would expect the proper behavior to be that terraform would throw an apply error if the max cluster count exceeded what is allowed on the Snowflake account.  I would not expect a plan error, but that's exactly what I'm getting.  We did not have this problem in the provider version `0.92.0`.
![warehouse](https://github.com/user-attachments/assets/5276eb41-e69a-4536-9cd6-e6470a1f9ce0)

### Actual Behavior

The following plan error is thrown:
```
│ Error: expected max_cluster_count to be in the range (1 - 10), got 20
│ 
│   with snowflake_warehouse.warehouse,
│   on warehouses.tf line 65, in resource "snowflake_warehouse" "warehouse":
│   65:   max_cluster_count                   = var.warehouse_max_cluster_count
```

### Steps to Reproduce

Create a warehouse using the `snowflake_warehouse` resource using provider version 0.93.0.  Set `max_cluster_count` to a value >10.

### How much impact is this issue causing?

Medium

### Additional Information

Our Snowflake account allows >10 max clusters per warehouse.  This differs from the Snowflake documentation, but I'm sure there are other users out there that are allowed >10 clusters on their warehouse that will be affected by this.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @bdumford-OM1. Thanks for reaching out to us.

You are right; it was once fixed (in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1919), but v0.93.0 introduced the same validation again. We will roll it back in v0.94.0 (expected next week on Wednesday/Thursday).

**Comment by bdumford-OM1** [comment]
Thanks @sfc-gh-asawicki!  I was going to post that I'm not even able to work around this by adding `max_cluster_count` to a `lifecycle -> ignore_changes` block.  But if it's going to be rolled back next week, I will just wait for that version.

**Comment by sfc-gh-asawicki** [comment]
Hey @bdumford-OM1, I have relaxed the validations in #2959. It will be part of the v0.94 release (tomorrow morning CEST).

**Comment by bdumford-OM1** [comment]
> Hey @bdumford-OM1, I have relaxed the validations in #2959. It will be part of the v0.94 release (tomorrow morning CEST).

Thanks for taking care of this!
