### ISSUE TITLE
snowflake_pipe fails to create with sqlx error "notification_channel": converting NULL to string is unsupported

### ISSUE THREAD

**Issue by tjtaill** [Snowflake-Labs/terraform-provider-snowflake#296]
**Provider Version**

0.18.0

**Terraform Version**

0.13.4

**Describe the bug**

Trying to create a snowflake pipe with this resource declaration

```hcl
resource "snowflake_pipe" "this" {
  comment        = var.comment
  copy_statement = var.copy_statement
  database       = var.database
  name           = var.name
  schema         = var.schema
}
```

but I get this error

Error: sql: Scan error on column index 6, name "notification_channel": converting NULL to string is unsupported

**Expected behavior**

I expect the resource to be created or a more useful error message I have tried to set notification_channle myself but it
says I shouldn't set that field

**Code samples and commands**

terragrunt plan works
terragrunt apply fails with error

Error: sql: Scan error on column index 6, name "notification_channel": converting NULL to string is unsupported

**Additional context**

I am using terragrunt

**Comment by tjtaill** [comment]
Maybe at https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/snowflake/pipe.go#L135 maybe NotificationChannel member should be a string pointer instead if snowflake can return a null value for notification_channel ?

here is the pipe struct def with the suggested change

```go
type pipe struct {
	Createdon           string `db:"created_on"`
	Name                string `db:"name"`
	DatabaseName        string `db:"database_name"`
	SchemaName          string `db:"schema_name"`
	Definition          string `db:"definition"`
	Owner               string `db:"owner"`
	NotificationChannel *string `db:"notification_channel"`
	Comment             string `db:"comment"`
}
```

**Comment by tjtaill** [comment]
sorry it did create the pipe so the bug is purely in the ScanPipe my fix is probably good

```tsv
created_on	name	database_name	schema_name	definition	owner	notification_channel	comment	integration	pattern
2020-11-02 17:24:29.830 -0800	S3PIPE	RAW	EVENTS	copy into RAW.EVENTS.EVENTS    from @RAW.EVENTS.S3LAKE    file_format = (type = 'JSON' compression = 'GZIP')	ACCOUNTADMIN		A pipe for s3 datalake events		
```

**Comment by dtger** [comment]
We should close this issue, confirmed working in `provider registry.terraform.io/chanzuckerberg/snowflake v0.25.3`

**Comment by sfc-gh-asawicki** [comment]
Pipes have been drastically reworked in the newer provider versions, closing as outdated.
