### ISSUE TITLE
[Bug]: Can not deploy/modify snowflake_network_policy.

### ISSUE THREAD

**Issue by DmytroMorhulDevPro** [Snowflake-Labs/terraform-provider-snowflake#2964]
### Terraform CLI Version

v1.7.4

### Terraform Provider Version

0.94.0/0.93.0

### Terraform Configuration

```terraform
# This part of code generates rules but fails in policy
resource "snowflake_network_rule" "rule" {
  for_each   = var.schemas
  name       = "Access to ${each.value.db_name}.${each.value.schema_name} "
  database   = each.value.db_name
  schema     = each.value.schema_name
  comment    = "Access from managed environmant"
  type       = "IPV4"
  mode       = "INGRESS"
  value_list = local.ip_set
}

resource "snowflake_network_policy" "policy" {
  name                      = "SCHEMA_ACCESS"
  allowed_network_rule_list = [for rule in snowflake_network_rule.rule : rule.qualified_name]
  blocked_network_rule_list = []
  comment                   = "allowed IP sets"
}
# I can create policy without setting allowed_network_rule_list, below part is working but after creation I'm still not able to add allowed_network_rule_list
resource "snowflake_network_policy" "policy" {
  name                      = "SCHEMA_ACCESS"
  allowed_network_rule_list = []
  blocked_network_rule_list = []
  comment                   = "allowed IP sets"
}
```

### Category

category:resource

### Object type(s)

resource:network_policy

### Expected Behavior

Network policy created and allowed rules attached

### Actual Behavior

Network policy with allowed_network_rule_list failed to create
Network policy with empty allowed_network_rule_list created but can not update itself after creation.

### Steps to Reproduce

# This part of code generates rules but fails in policy
resource "snowflake_network_rule" "rule" {
  for_each   = var.schemas
  name       = "Access to ${each.value.db_name}.${each.value.schema_name} "
  database   = each.value.db_name
  schema     = each.value.schema_name
  comment    = "Access from managed environmant"
  type       = "IPV4"
  mode       = "INGRESS"
  value_list = local.ip_set
}

resource "snowflake_network_policy" "policy" {
  name                      = "SCHEMA_ACCESS"
  allowed_network_rule_list = [for rule in snowflake_network_rule.rule : rule.qualified_name]
  blocked_network_rule_list = []
  comment                   = "allowed IP sets"
}

### How much impact is this issue causing?

High

### Additional Information

Error messages:
snowflake_network_policy.policy: Creating...
╷
│ Error: Error creating network policy
│ 
│   with snowflake_network_policy.policy,
│   on main.tf line 33, in resource "snowflake_network_policy" "policy":
│   33: resource "snowflake_network_policy" "policy" {
│ 
│ error creating network policy ACCESS err = [errors.go:22] object does not exist or not authorized

snowflake_network_policy.policy: Modifying... [id=ACCESS]
╷
│ Error: [errors.go:22] object does not exist or not authorized
│ 
│   with snowflake_network_policy.policy,
│   on main.tf line 33, in resource "snowflake_network_policy" "policy":
│   33: resource "snowflake_network_policy" "policy" {

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @DmytroMorhulDevPro. Thanks for reaching out to us.

We will verify it and get back to you.

**Comment by sfc-gh-jcieslak** [comment]
Hey @DmytroMorhulDevPro 👋 
Could you provide logs from the `terraform apply` command, ideally with the `TF_LOG=DEBUG` environment enabled? Let me know, and in the meantime, I'll try to reproduce this issue.

**Comment by sfc-gh-jcieslak** [comment]
The following configuration was applied successfully
```terraform
resource "snowflake_network_rule" "test" {
  database = "TEST_DATABASE"
  schema = "TEST_SCHEMA"
  name = "TEST_NETWORK_RULE"
  type = "IPV4"
  mode = "INGRESS"
  value_list = ["111.111.111.111"]
}

resource "snowflake_network_policy" "test" {
  name = "test_network_policy"
  allowed_network_rule_list = [ snowflake_network_rule.test.qualified_name ]
}
```
I'm guessing this may be one of the network rule identifiers (it's possible to have a valid identifier for network rule, but may appear invalid in the allowed_network_rule_list). I think this may be an issue on your end with the identifier structure of certain network rule, but I would need the logs I mentioned above.

**Comment by DmytroMorhulDevPro** [comment]
Hey @sfc-gh-jcieslak 
Here the debug log - [tf_debug_log.txt](https://github.com/user-attachments/files/16426396/tf_debug_log.txt)
I found the SQL query that must be executed and it's not working on worksheet as well.
The list of rules created by terraform by the same code.

**Comment by DmytroMorhulDevPro** [comment]
I was managed to fix this by transforming netwrok rule names.

old name: "TEAM access to DB.SCHEMA"
new name: "TEAM_ACCESS_DB_SCHEMA"

Might be the issue was on synax of rule name that is a part of rule fully qualyfied rule name.
The issue resolved
