### ISSUE TITLE
[Bug]: "Root object was present, but now absent" when creating a Stream

### ISSUE THREAD

**Issue by teresatj-gh** [Snowflake-Labs/terraform-provider-snowflake#2967]
### Terraform CLI Version

1.9.3

### Terraform Provider Version

0.94.0

### Terraform Configuration

```terraform
resource "snowflake_stream" "fhir_update_stream" {
  name          = "fhir_update_stream"
  database      = "cdp_sandbox"
  schema        = "cdp_firehose_export"
  on_table      = "cdp_sandbox.cdp_firehose_export.fhir_update_raw"
  append_only   = true
}
```

### Category

category:resource

### Object type(s)

resource:stream

### Expected Behavior

The Snowflake Stream is created without any error.

### Actual Behavior

The Snowflake Stream was created, but the overall Terraform command failed with "Error: Provider produced inconsistent result after apply," and the Stream wasn't added to the tfstate file. When `terraform apply` command was rerun, it couldn't see the Stream. (It should be able to, because the role used to run the command was the owner of the Stream, based on info from `show streams like 'fhir_update_stream';`.)

### Steps to Reproduce

Run terraform apply with the provided `snowflake_stream` config.

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/teresatj-gh/8444b2a7901ae95e9715d58c70178531

### Additional Information

Not sure if this is relevant, but our tfstate is stored in S3. (We use Terraform for provisioning infra in AWS and Snowflake.)

I tried some workaround mentioned in similar issues, like upgrading to the latest versions of Terraform CLI and the Snowflake provider, as well as running `terraform import`. Upgrading didn't work - the issue persisted. And I couldn't run `terraform import` because the command requires the resource ID, which I couldn't get since the Stream wasn't added to the tfstate file.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey, glad to hear it worked. We will update our docs and FAQ with the usage notes on `QUOTED_IDENTIFIERS_IGNORE_CASE`.

Closing the ticket.
