### ISSUE TITLE
[Bug]: Cannot migrate deprecated snowflake_role_grants to snowflake_grant_account_role

### ISSUE THREAD

**Issue by vivi0209** [Snowflake-Labs/terraform-provider-snowflake#2974]
### Terraform CLI Version

1.7.4

### Terraform Provider Version

0.93.0

### Terraform Configuration

```terraform
Previously, I have a resource like below,
resource "snowflake_role_grants" "role_grant_user" {
  provider  = snowflake.useradmin_role
  role_name = snowflake_role.role.name
  users     = [snowflake_user.user.name]
}
To upgrade to 0.93.0, I changed to below(I do not want to use terraform state rm so using the removed block instead),
removed {
  from = snowflake_role_grants.role_grant_user
  lifecycle {
    destroy = false
  }
}
resource "snowflake_grant_account_role" "role_grant_user_new" {
  provider  = snowflake.useradmin_role
  role_name = snowflake_role.role.name
  user_name = snowflake_user.user.name
}
import {
  to = snowflake_grant_account_role.role_grant_user_new
  id = "<role_name>|USER|<user_name>"
}

But got the error and warning,

│ Error: no schema available for snowflake_role_grants.role_grant_user while reading state; this is a bug in Terraform and should be reported

 │ Warning: Missing resource schema from provider
    │ 
    │ No resource schema found for snowflake_role_grants when decoding prior
    │ state

Even, if I completely removed the old resource without any removed or import block, I got the same error.

I did the same for snowflake_oauth_integration -> snowflake_oauth_integration_for_partner_applications and it works.
```

### Category

category:resource

### Expected Behavior

The old resource should not be destroyed and should be able to be imported to the new one. The plan should be no changes for this.

### Actual Behavior

Error about no schema available even remove the resource block, thus cannot upgrade to the version 0.93.0

### Steps to Reproduce

1. create the resource snowflake_role_grants listed above with snowflake provider version 0.92 
2. update the version to 0.93 and delete the resource.
3. update the version to 0.93 and using the removed, import block plus the new resource mentioned above.

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @vivi0209. Thanks for reaching out to us.

In 0.93.0 there is no `snowflake_role_grants`, so it's a correct error that `no schema available for snowflake_role_grants.role_grant_user while reading state`.

If you want to run the migration your way, I believe you have to do it being on 0.92.0 version.

**Comment by vivi0209** [comment]
> Hey @vivi0209. Thanks for reaching out to us.
> 
> In 0.93.0 there is no `snowflake_role_grants`, so it's a correct error that `no schema available for snowflake_role_grants.role_grant_user while reading state`.
> 
> If you want to run the migration your way, I believe you have to do it being on 0.92.0 version.

Hi! Thanks for your quick reply! Does it mean that I need to split it into 2 pull requests for upgrading to version 0.93.0? First, do the migrations on 0.92.0 and then upgrade the version to 0.93.0?

**Comment by sfc-gh-asawicki** [comment]
If you don't want to touch the state, then yes. You can't have the state with objects that are already gone.

**Comment by vivi0209** [comment]
> If you don't want to touch the state, then yes. You can't have the state with objects that are already gone.

Thanks! I just come into another issue for the import block, I can see in the statefile that the id for snowflake_role_grants is  "id": "FLYWAY_FR||FLYWAY_AU", but when I copy it to the import block, I got the error, "invalid object type specified: , expected ROLE or USER│ ", I tried to add ROLE or USER to the middle but got another error about "│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to
│ "snowflake_grant_account_role.flyway_role_grant", the provider detected
│ that no object exists with the given id. Only pre-existing objects can be
│ imported; check that the id is correct and that it is associated with the
│ provider's configured region or endpoint, or use "terraform apply" to
│ create a new remote object for this resource."

Why is that and how to fix it?

**Comment by sfc-gh-asawicki** [comment]
The old id in `snowflake_role_grants` according to https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/role_grants#import was:
```
role_name|role1,role2|user1,user2
```
so based on your example I guess that:
- `FLYWAY_FR` is the name of the role
- `FLYWAY_AU` is the name of the user

According to the docs of `snowflake_grant_account_role `: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role#import, the new id should be:
```
"FLYWAY_FR"|USER|"FLYWAY_AU"
```

If this is the one you check, please run the code with `TF_LOG=DEBUG` and share the SQL statements being run.

> which means I need to destroy the old deprecated ones and create the new resources?
No, we do not require destroying and recreating.

**Comment by vivi0209** [comment]
> The old id in `snowflake_role_grants` according to https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/role_grants#import was:
> 
> ```
> role_name|role1,role2|user1,user2
> ```
> 
> so based on your example I guess that:
> 
> * `FLYWAY_FR` is the name of the role
> * `FLYWAY_AU` is the name of the user
> 
> According to the docs of `snowflake_grant_account_role `: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role#import, the new id should be:
> 
> ```
> "FLYWAY_FR"|USER|"FLYWAY_AU"
> ```
> 
> If this is the one you check, please run the code with `TF_LOG=DEBUG` and share the SQL statements being run.
> 
> > which means I need to destroy the old deprecated ones and create the new resources?
> 
> No, we do not require destroying and recreating.

Thanks for your help! I found the issue, I wrote id = "FLYWAY_FR|USER|FLYWAY_AU" in the import block but it should be id = "\"FLYWAY_FR\"|USER|\"FLYWAY_AU\"".

Thanks again for your help!

**Comment by sfc-gh-asawicki** [comment]
Great to hear that @vivi0209. I am closing the issue then :)
