### ISSUE TITLE
[Bug]: snowflake_database with the from_database won't migrate automatically for 0.93

### ISSUE THREAD

**Issue by kamilamarcinekpgs** [Snowflake-Labs/terraform-provider-snowflake#2978]
### Terraform CLI Version

1.2.6

### Terraform Provider Version

0.93

### Terraform Configuration

```terraform
resource "snowflake_database" "test" {
  name = "VERY_IMPORTANT_DB"
  data_retention_time_in_days = 7
  from_database = "THE_MODEL_DB"
}
```

### Category

category:resource

### Object type(s)

resource:database

### Expected Behavior

I'm trying to upgrade from 0.92 to 0.93.

I have the old `snowflake_database resource`, with the from_database parameter set.

The migration guide says: 

> If you had from_database set, it should migrate automatically.

### Actual Behavior

I'm not sure what it means, that it should migrate automatically. 
If I just change the version, it says "**Unsupported argument**". 
If I change the version and remove the `from_database param`, it says "**failed to upgrade the state with database created from database**".

What should I do to achieve the "automatic upgrade" mentioned in the migration guide?

### Steps to Reproduce

.

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @kamilamarcinekpgs 
That's a documentation error; I'll fix it. As `from_database` is database cloning, which is not currently supported, the only way is to remove the database from the state `terraform state rm` -> upgrade to the newer version -> import the database.

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity.
