### ISSUE TITLE
[Bug]: Getting an error which seems circular

### ISSUE THREAD

**Issue by nadirdbit** [Snowflake-Labs/terraform-provider-snowflake#2984]
### Terraform CLI Version

>= 1.5.1

### Terraform Provider Version

0.93.0

### Terraform Configuration

```terraform
resource "snowflake_oauth_integration_for_custom_clients" "alation_compose_prod_hulux" {
  provider                         = snowflake.<reference>
  name                             = "<integration_name>"
  oauth_client_type                = "CONFIDENTIAL"
  oauth_redirect_uri               = "<url>"
  enabled                          = "true"
  oauth_allow_non_tls_redirect_uri = "false"
  oauth_enforce_pkce               = "false"
  oauth_use_secondary_roles        = "NONE"
  pre_authorized_roles_list        = []
  blocked_roles_list               = ["ACCOUNTADMIN", "ORGADMIN", "SECURITYADMIN"]
  oauth_issue_refresh_tokens       = "true"
  comment                          = "<comment>"
}
```

### Category

category:resource

### Object type(s)

resource:oauth_integration

### Expected Behavior

No error should have been obtained as prior resources were created fine via SQL with having OAUTH_ALLOW_NON_TLS_REDIRECT_URI set to False.

Issue noted for the first time when using the Terraform-Snowflake-Provider to create these new resources for Dev and Prod.

### Actual Behavior

Error: 390316 (22023): The redirect URI must use TLS unless OAUTH_ALLOW_NON_TLS_REDIRECT_URI is set to False.
with snowflake_oauth_integration_for_custom_clients.

### Steps to Reproduce

N/A

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @nadirdbit 👋 I think this may be a bug on the snowflake side. When I try to create a similar integration in Snowsight, I'm also getting this error. However, when I set `OAUTH_ALLOW_NON_TLS_REDIRECT_URI = true`, then it works. Semantically, this is expected behavior (to use `http://`, we want to **allow** non-TLS URI), so that's why I think the error message is incorrect. Could you please verify this on your side?

**Comment by nadirdbit** [comment]
Hi Jakub,

This is ok to close - working fine.

User had a typo in request which was implemented and that seems to have caused this. 

Thank you.

**Comment by nadirdbit** [comment]
Hi Jakub,

This refers to your comment 3 weeks back.

We weren't able to validate with http - only **https** and thus reopening this issue.

Thank you.

**Comment by sfc-gh-jmichalak** [comment]
Hi, could you provide the following:
- configuration of the resource (you should have  `oauth_allow_non_tls_redirect_uri = "true"`)
- SQL for CREATE SECURITY INTEGRATION which works for you in Snowsight

I can't reproduce this: I configured a resource with `oauth_allow_non_tls_redirect_uri = "true"` and `oauth_redirect_uri = "http://example.com"` and it works fine.

**Comment by nadirdbit** [comment]
Hi Jakub,

This was done via Terraform using the Snowflake provider -

#snippet from our providers.tf file
 required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.93.0"
    }
  }

#Oauth snippet
resource "snowflake_oauth_integration_for_custom_clients" "<name1>" {
  provider                         = snowflake.<name2>
  name                             = "<name3>"
  oauth_client_type                = "CONFIDENTIAL"
  oauth_redirect_uri               = "https://<url>"
  enabled                          = "true"
  oauth_allow_non_tls_redirect_uri = "false"
  oauth_enforce_pkce               = "false"
  oauth_use_secondary_roles        = "NONE"
  pre_authorized_roles_list        = []
  blocked_roles_list               = local.si_common_blocked_roles
  oauth_issue_refresh_tokens       = "true"
  comment                          = "<comment>"
}

Thank you.

**Comment by sfc-gh-jmichalak** [comment]
Just to confirm, the config you provided is working fine, and we can close this issue?

**Comment by nadirdbit** [comment]
Hi Jakub,

Yes!

Thanks again.
