### ISSUE TITLE
[Bug]:  Certain database role grants not persisting in state file

### ISSUE THREAD

**Issue by norbert-fivestars** [Snowflake-Labs/terraform-provider-snowflake#2992]
### Terraform CLI Version

1.9.3

### Terraform Provider Version

0.94.1

### Terraform Configuration

```terraform
My TF plan/apply shows the following around additional grants to be extended to database roles.
 # module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["STAGING"] will be updated in-place
  ~ resource "snowflake_grant_privileges_to_database_role" "schema_write_create" {
        id                 = "\"DATA_PLATFORM_PROD\".\"DATA_PLATFORM_PROD_STAGING_WRITE\"|false|false|CREATE TABLE,CREATE VIEW,CREATE MATERIALIZED VIEW, CREATE FUNCTION|OnSchema|OnSchema|\"DATA_PLATFORM_PROD\".\"STAGING\""
      ~ privileges         = [
          + "CREATE MATERIALIZED VIEW, CREATE FUNCTION",
            # (2 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["TABLEAU_REPOSITORY"] will be updated in-place
  ~ resource "snowflake_grant_privileges_to_database_role" "schema_write_create" {
        id                 = "\"DATA_PLATFORM_PROD\".\"DATA_PLATFORM_PROD_TABLEAU_REPOSITORY_WRITE\"|false|false|CREATE TABLE,CREATE VIEW,CREATE MATERIALIZED VIEW, CREATE FUNCTION|OnSchema|OnSchema|\"DATA_PLATFORM_PROD\".\"TABLEAU_REPOSITORY\""
      ~ privileges         = [
          + "CREATE MATERIALIZED VIEW, CREATE FUNCTION",
            # (2 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Once I apply these, I see a successful message of all the changes being applied. However, if I go run plan again, the same exact additional resources are shown as needed to be created. 
The grants were given to the role though, just that the TF state file doesn't capture/persist this.
```

### Category

category:resource

### Object type(s)

resource:grant_privileges_to_database_role

### Expected Behavior

Once changes have been applied, the should have persisted in the TF state file as reflective of Snowflake (the grants were successfully extended in Snowflake by Terraform).

### Actual Behavior

The Terraform state file does not reflect the change as it was applied by Terraform.  No matter how many times tf apply is executed successfully and these changes are marked as updated by the command, the next time tf plan is run, the same changes are shown to see be missing and hence are to be created

### Steps to Reproduce

terraform apply
yes
terraform plan

### How much impact is this issue causing?

Medium

### Logs

2024-08-12T13:53:38.806-0400 [WARN]  Provider "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new value for module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["SANDBOX"] during refresh.
      - .privileges: planned set element cty.StringVal("CREATE MATERIALIZED VIEW, CREATE FUNCTION") does not correlate with any element in actual
2024-08-12T13:53:38.809-0400 [WARN]  Provider "registry.terraform.io/snowflake-labs/snowflake" produced an invalid plan for module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["SANDBOX"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .with_grant_option: planned value cty.False for a non-computed attribute
      - .all_privileges: planned value cty.False for a non-computed attribute
      - .always_apply: planned value cty.False for a non-computed attribute
      - .on_schema[0].all_schemas_in_database: planned value cty.StringVal("") for a non-computed attribute
      - .on_schema[0].future_schemas_in_database: planned value cty.StringVal("") for a non-computed attribute
2024-08-12T13:53:39.525-0400 [WARN]  Provider "registry.terraform.io/snowflake-labs/snowflake" produced an unexpected new value for module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["TABLEAU_REPOSITORY"] during refresh.
      - .privileges: planned set element cty.StringVal("CREATE MATERIALIZED VIEW, CREATE FUNCTION") does not correlate with any element in actual
2024-08-12T13:53:39.530-0400 [WARN]  Provider "registry.terraform.io/snowflake-labs/snowflake" produced an invalid plan for module.DATA_PLATFORM_PROD.snowflake_grant_privileges_to_database_role.schema_write_create["TABLEAU_REPOSITORY"], but we are tolerating it because it is using the legacy plugin SDK.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @norbert-fivestars 👋 Could you share your terraform config? You provided a terraform plan, so I don't know which fields are set. However, line `+ "CREATE MATERIALIZED VIEW, CREATE FUNCTION",` suggests that you configured privileges incorrectly - try passing privileges as separate list items like this `"CREATE MATERIALIZED VIEW", "CREATE FUNCTION"`

**Comment by norbert-fivestars** [comment]
Hello @sfc-gh-jmichalak  - You're 100% correct. Closing this as a PEBCAK
