### ISSUE TITLE
[Feature]: Add comments on columns defined in views

### ISSUE THREAD

**Issue by SteveGad12345** [Snowflake-Labs/terraform-provider-snowflake#3000]
### Use Cases or Problem Statement

Hi,

       We would like to add comments on columns defined in views. However, snowflake_view does not support it. Is it possible to add it ?

### Category

category:resource

### Object type(s)

resource:view

### Proposal

Add a collection of column definitions which contain the name and the comment (similar to table definition).

### How much impact is this issue causing?

High

### Additional Information

If you have a viable workaround to suggest, it would be great.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi, this resource is being reworked right now. We'll add this field 👍

**Comment by sfc-gh-jcieslak** [comment]
Hey @SteveGad12345 👋
Yesterday, we released a new provider version ([v0.95.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.95.0)) that allows to specify comments on columns. Please upgrade using the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) and let us know if that's what you requested. Thank You :)

**Comment by sfc-gh-jmichalak** [comment]
Closing the issue due to inactivity.
