### ISSUE TITLE
Create Snowflake Masking Policies in Terraform also set table column masking policies

### ISSUE THREAD

**Issue by tjtaill** [Snowflake-Labs/terraform-provider-snowflake#303]
**Is your feature request related to a problem? Please describe.**

would like to be able to create and apply masking policies this would probably involve two resources

snowflake_masking_policy based of https://docs.snowflake.com/en/user-guide/security-column-ddm-intro.html#dynamic-data-masking-ddl

we would another resource type to do the command

```sql
alter table empl_info modify column empl_id set masking policy mask_empl_id;
```

as shown here https://docs.snowflake.com/en/sql-reference/sql/alter-table-column.html#examples 

**Describe the solution you'd like**

I would like to be able create masking policies in terraform them and set the table columns which the masking policy should apply

**Describe alternatives you've considered**

I am also looking to see if I can get dbt (data build tool) to create and apply masking these policies
currently I am using dbt jinja2 macro to create  views that either return masked PII data or the real data based on roles

**Additional context**

none

**Comment by tjtaill** [comment]
Looks like a PR has been merged for this https://github.com/chanzuckerberg/terraform-provider-snowflake/commit/20e62ab7f18299e9aecfd1fcdc5e49a8852435ae but not yet released will close this when it gets into a release

**Comment by yohei1126** [comment]
@ryanking @alldoami Should `snowflake_masking_policy` resource generate this sql? Or should be separate resource?

```
alter table empl_info modify column empl_id set masking policy mask_empl_id;
```

**Comment by yohei1126** [comment]
Masking policy can be applied to multiple table columns so it should be separate resource.

**Comment by tjtaill** [comment]
So far you can create the masking policy and grant the privilege to apply it but you can actually apply it on table columns yet that is the missing link might be nice if there was a table data source and you use it in in an alter table resource to apply the masking.

**Comment by LouisAmon** [comment]
Looks like #387 has been merged

**Comment by prae04** [comment]
Valid issue by @tjtaill, the disconnect between the masking policy and *using* the masking policy to table columns is missing.  Currently solution is outside of Terraform to run the sample query provided above by @yohei1126

**Comment by brewerdaniel-IW** [comment]
I've made a PR to tackle this issue: https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/796

**Comment by reallocf** [comment]
+1 on this issue - we will definitely use this once it's available! Thanks @brewerdaniel-IW for taking it on 👍

**Comment by Yogesh-BK** [comment]
I believe this resource helps us to attach masking policies on tables, Is there any resource to attach masking policies on views?
