### ISSUE TITLE
[Bug]: snowflake_storage_integration produced an unexpected new value: .comment: was null, but now cty.StringVal("")

### ISSUE THREAD

**Issue by benlamonica** [Snowflake-Labs/terraform-provider-snowflake#3056]
### Terraform CLI Version

1.0.11

### Terraform Provider Version

0.95.0

### Terraform Configuration

```terraform
resource "snowflake_storage_integration" "integration" {
  name    = "mi_${var.env}_snowflake_external_stage"
  type    = "EXTERNAL_STAGE"

  enabled = true

  storage_allowed_locations = ["s3://${aws_s3_bucket.snowflake_external_stage.id}/data"]
  storage_aws_object_acl    = "bucket-owner-full-control"

  storage_provider         = "S3"
  storage_aws_role_arn     = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.snowflake_role_name}"
}
```

### Category

category:resource

### Object type(s)

resource:storage_integration

### Expected Behavior

I expect the storage integration to be created without being immediately tainted.

### Actual Behavior

If the storage integration is missing a comment, then the storage integration is successfully created, but terraform provider receives an unexpected response, and taints the resource, destroying and recreating it next time.

Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.deployment.snowflake_storage_integration.integration, provider "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]" produced an unexpected new value: .comment: was null, but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

If I specify a comment in the terraform resource block, then everything is created successfully. Comment should either be made mandatory, or the provider should be able to handle when the comment is null.

### Steps to Reproduce

1. Copy the config
2. run terraform apply
3. see error about inconsistent state
4. run terraform apply again, the integration will be destroyed and recreated

### How much impact is this issue causing?

Low

### Additional Information

Adding a comment allows it to be created successfully.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @benlamonica. Thanks for reaching out to us.

Please bump your terraform cli to at least 1.1.5. It seems that it is an error similar to the one described here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CREATING_ISSUES.md#old-terraform-cli-version.

**Comment by benlamonica** [comment]
Yes, you are right. I upgraded to 1.8.5 and problem no longer exists. Apologies for not seeing the documentation.
