### ISSUE TITLE
[Bug]: Unexpected grant in state file

### ISSUE THREAD

**Issue by dlouseiro** [Snowflake-Labs/terraform-provider-snowflake#3059]
### Terraform CLI Version

1.5.7

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
resource "snowflake_grant_privileges_to_account_role" "snowflake_imported_privileges_to_snowflake_monitoring" {
  account_role_name = snowflake_role.snowflake_monitoring.name
  privileges        = ["IMPORTED PRIVILEGES"]
  on_account_object {
    object_type = "DATABASE"
    object_name = "SNOWFLAKE"
  }
}
```

### Category

category:grants

### Object type(s)

resource:grant_privileges_to_account_role

### Expected Behavior

For the resource to be registered in the state file as something like this:

```
    {
      "mode": "managed",
      "type": "snowflake_grant_privileges_to_account_role",
      "name": "snowflake_imported_privileges_to_snowflake_monitoring",
      "provider": "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_role_name": "SNOWFLAKE_MONITORING",
            "all_privileges": false,
            "always_apply": false,
            "always_apply_trigger": null,
            "id": "\"SNOWFLAKE_MONITORING\"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|\"SNOWFLAKE\"",
            "on_account": false,
            "on_account_object": [
              {
                "object_name": "SNOWFLAKE",
                "object_type": "DATABASE"
              }
            ],
            "on_schema": [],
            "on_schema_object": [],
            "privileges": [
              "IMPORTED PRIVILEGES"
            ],
            "with_grant_option": false
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "snowflake_role.snowflake_monitoring"
          ]
        }
      ]
    }
```

### Actual Behavior

Resource is stored in the state file as:

```
    {
      "mode": "managed",
      "type": "snowflake_grant_privileges_to_account_role",
      "name": "snowflake_imported_privileges_to_snowflake_monitoring",
      "provider": "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_role_name": "SNOWFLAKE_MONITORING",
            "all_privileges": false,
            "always_apply": false,
            "always_apply_trigger": null,
            "id": "\"SNOWFLAKE_MONITORING\"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|\"SNOWFLAKE\"",
            "on_account": false,
            "on_account_object": [
              {
                "object_name": "SNOWFLAKE",
                "object_type": "DATABASE"
              }
            ],
            "on_schema": [],
            "on_schema_object": [],
            "privileges": [
              "IMPORTED PRIVILEGES",
              "USAGE"
            ],
            "with_grant_option": false
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "snowflake_role.snowflake_monitoring"
          ]
        }
      ]
    }
```

### Steps to Reproduce

1. Remove resource from the state with `terraform state rm 'snowflake_grant_privileges_to_account_role.snowflake_imported_privileges_to_snowflake_monitoring'`
2. Run `terraform apply` (grant is reapplied)
3. Run `terraform apply` again

Result received is:

```
  # snowflake_grant_privileges_to_account_role.snowflake_imported_privileges_to_snowflake_monitoring will be updated in-place
  ~ resource "snowflake_grant_privileges_to_account_role" "snowflake_imported_privileges_to_snowflake_monitoring" {
        id                = "\"SNOWFLAKE_MONITORING\"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|\"SNOWFLAKE\""
      ~ privileges        = [
          - "USAGE",
            # (1 unchanged element hidden)
        ]
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Terraform considers that the `USAGE` grant should be removed, which makes sense as it was never declared in the first place, but somehow terraform stored it in the state.

4. Reply `yes` to the `terraform apply`. Result: command fails as it's not possible to revoke `USAGE` privilege on the `SNOWFLAKE` database.

### How much impact is this issue causing?

Medium

### Additional Information

Fun fact here is that this only happens in our production account. If I run the exact same steps mentioned above in one of our test accounts, everything goes well and the second `terraform apply` (point 3) does not detect any changes in the state.

Workaround applied: 

Added a lifecyle in the resource to ignore changes in privileges:

```
  lifecycle {
    ignore_changes = [
      privileges
    ]
  }
```

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @dlouseiro. Thanks for reaching out to us.

Could you please describe how did you migrate the production accounts (was it just v0.91.0 -> v0.92.0 or a bigger version bump? which option did you pick to migrate the old grant resources or did you not have to migrate them? etc. every detail that you can share will be potentially helpful here because we also cannot reproduce such a situation on our test accounts, so probably we need a better setup - the one closer to what you did on your prod account).

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
I tried to reproduce the original issue but couldn't (it worked every time). The behavior in different environments also seems strange. Maybe you have different Terraform versions or different Snowflake versions/settings? 

Regarding the second comment, I'm not really sure what you mean. I also tried to reproduce this behavior, but couldn't. Calling revoke twice when after the first one you have 2 grants, and after the second one none seems like a Snowflake error (stacking grants?).

Please try to create clearer steps to reproduce. The first step already removes the resource from the state, which is confusing. Create a step-by-step guide from no configuration on Snowflake and Terraform to the occurring issue.

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity. Please create another ticket if the issue still persists.

**Comment by denizsurmeli** [comment]
Hi, this happens I believe due to the following [behaviour](https://arc.net/l/quote/kyjlspyy). Looks like only way to workaround at the moment using lifecycle statements.

**Comment by sfc-gh-jcieslak** [comment]
We cannot reproduce this on our side; please provide reproducible steps so that we can diagnose this on our end.
