### ISSUE TITLE
Allow configuration of the PUBLIC schema

### ISSUE THREAD

**Issue by wesleyhillyext** [Snowflake-Labs/terraform-provider-snowflake#306]
It currently does not appear possible to define a "snowflake_schema" resource for a database's PUBLIC schema, which meaning that schema cannot be configured in Terraform.

A "snowflake_database" resource creates a database, complete with a PUBLIC schema. So an attempt to add a "snowflake_schema" resource for the PUBLIC schema results in an error like `'MY_DATABASE.PUBLIC' already exists` on apply.

It may be possible to do a `terraform import` on a PUBLIC schema and then configure it, but even if that works it still leads to a manual process of initially applying without the "snowflake_schema", then importing state, then adding the "snowflake_schema" back in and applying again. That workaround gets even worse if you have multiple databases configured with a helper module and want to add one more database.

If there's not already a solution to this problem, I'm not sure what the best approach would be. Maybe the "snowflake_schema" resource could special-case the PUBLIC schema so that it checks if it already exists, and performs ALTER SCHEMA operations instead of CREATE SCHEMA, even if the schema is not in the Terraform state yet.

**Comment by ryanking** [comment]
I think the two options for supporting this are–

1. rely on import - will not be great for some workflows, but has the advantage of keeping the provider code simple

2. special-case PUBLIC and make it part of the `snowflake_database` resource. I think this only makes sense if there is always a PUBLIC schema. Can you delete it? Can you create a database without it? I honestly don't know. This approach would make our implementation somewhat more complicated but would make workflows like you describe simpler.

**Comment by wesleyhillyext** [comment]
From the documentation on [CREATE DATABASE](https://docs.snowflake.com/en/sql-reference/sql/create-database.html#general-usage-notes), it says it will always create the PUBLIC schema, so it doesn't look like the database could be created without it.

**Comment by wmorin** [comment]
From the documentation, you can note also that this PUBLIC schema can be deleted.

**Comment by mackro-rocky** [comment]
Any plans to have this implemented? Importing the public schema manually doesn't seem like a great solution.
