### ISSUE TITLE
[Bug]: Issue with Terraform Import: "Plugin did not respond" Error When Importing Tables and Procedures

### ISSUE THREAD

**Issue by BLUENO01** [Snowflake-Labs/terraform-provider-snowflake#3072]
### Terraform CLI Version

1.9.5

### Terraform Provider Version

0.95.0

### Terraform Configuration

```terraform
main.tf
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.95"
    }
  }
}

provider "snowflake" {
  account  = var.snowflake_account
  user = var.snowflake_user
  password = var.snowflake_password
  role     = var.snowflake_role
  warehouse = var.snowflake_warehouse
}

# 変数の宣言
variable "snowflake_account" {
  type = string
}

variable "snowflake_user" {
  type = string
}

variable "snowflake_password" {
  type = string
  sensitive = true
}

variable "snowflake_role" {
  type = string
}

variable "snowflake_warehouse" {
  type = string
}
```

### Category

category:import

### Object type(s)

resource:table

### Expected Behavior

I wanted to use terraform import to manage existing tables, procedures, views, and other objects in the already established Snowflake environment with Terraform.

### Actual Behavior

I executed terraform import to manage existing tables, procedures, and other objects in the Snowflake environment using Terraform. However, the import process shows inconsistent results depending on the object type: some imports succeed, while others fail due to plugin errors, as shown in the error message below. (For example, importing databases, schemas, and views works, but importing tables and procedures fails.)

I have considered the possibility that this issue might be related to the version, and I tested the following environments:

Snowflake versions: 8.34.0 and 8.33.1 (I tested both environments, and similar issues occurred in both.)
Terraform Snowflake Provider versions: 0.83.1 to 0.95.0 (I tested all versions up to the latest one.)
`╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
`

### Steps to Reproduce

The folder structure used for execution was as follows:
<img width="471" alt="スクリーンショット 2024-09-13 12 01 02" src="https://github.com/user-attachments/assets/73d797d1-1f93-4a65-8122-bfe1b4a24130">

1. I ran terraform init in the above directory.
2. In the same directory, I executed the following import commands. Importing tables and procedures resulted in errors:

`terraform import -var-file=prod.tfvars snowflake_table.XXTABLE XXDB.XXSCHEMA.XXTABLE`

`terraform import -var-file=prod.tfvars snowflake_view.XXVIEW XXDB.XXSCHEMA.XXVIEW`

`terraform import -var-file=prod.tfvars snowflake_procedure.procXX XXDB.XXSCHEMA.procXX`

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @BLUENO01. Thanks for reaching out to us.

Please check the import commands:
- for table: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table#import (the id is `|` - separated).
- for procedure: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/procedure#import (you need to import with arguments)

After fixing the import commands according to the referenced docs, you should complete import successfully.

One note: we are currently reworking the objects on our road to V1. Because of that, import commands differ between the resources. We will eventually have them unified, please follow our release notes and migration guide (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide).

**Comment by sfc-gh-asawicki** [comment]
Closing the issue due to inactivity. Please create a new one if the issue persists in the newest version of the provider.
