### ISSUE TITLE
[Docs]: Bad arg included in snowflake_shared_database example usage

### ISSUE THREAD

**Issue by deanmorin** [Snowflake-Labs/terraform-provider-snowflake#3075]
### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.95.0/docs/resources/shared_database

### Description

In the docs for `snowflake_shared_database` (v.0.93.0 onward), `data_retention_time_in_days` appears as an optional arg in the example usage, but doesn't appear in the schema section (and isn't actually supported by the resource).

Also, `shared_database` wasn't an option for "Object type(s)" when creating this issue.
![image](https://github.com/user-attachments/assets/4cbe70d8-23c9-42d7-870c-9f1a152a3128)

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @deanmorin 👋 
Thanks for reporting this and creating the PR. We already reviewed it, and after resolving the comments, we can merge it 🙂

**Comment by sfc-gh-jcieslak** [comment]
The issue closed automatically (because of the `fixes` comment in your pr's description), but let me know If we should reopen it or it can stay as closed.
