### ISSUE TITLE
Support for external table resources

### ISSUE THREAD

**Issue by serge-bouschet-cko** [Snowflake-Labs/terraform-provider-snowflake#308]
**Is your feature request related to a problem? Please describe.**

No, this is a new feature to support resources such as external tables:
https://docs.snowflake.com/en/user-guide/tables-external.html

**Describe the solution you'd like**

Enhance the current table resource to support external tables:
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/docs/resources/table.md

**Describe alternatives you've considered**

We manage them via dbt using operations. A dbt package is available and creates external tables based on source definition: https://github.com/fishtown-analytics/dbt-external-tables
However our wish is now to de-couple these resources from the dbt analytics project and managed them via infrastructure as code.

**Additional context**

**Comment by lgwacker** [comment]
Was added in this PR https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/315/
