### ISSUE TITLE
[Bug]: Can't add expression column to table

### ISSUE THREAD

**Issue by lorenzo-romanelli** [Snowflake-Labs/terraform-provider-snowflake#3095]
### Terraform CLI Version

opentofu 1.7.2

### Terraform Provider Version

0.96.0

### Terraform Configuration

```terraform
column {
    name     = "_TS_CREATED"
    nullable = false
    type     = "TIMESTAMP_TZ"
    comment  = "The timestamp when the record was created."
    default {
      expression = "CURRENT_TIMESTAMP()"
    }
  }
```

### Category

category:resource

### Object type(s)

resource:table

### Expected Behavior

A column `_TS_CREATED` is created, and its default value should be the output of the `CURRENT_TIMESTAMP()` expression.

### Actual Behavior

apply fails with the following error:
```
╷
│ Error: failed to add column _TS_CREATED => Only adding a column as a constant is supported by Snowflake
│ 
│   with snowflake_table.user_tenants,
│   on settings_data.tf line 154, in resource "snowflake_table" "user_tenants":
│  154: resource "snowflake_table" "user_tenants" {
│ 
╵
```

### Steps to Reproduce

1. Create a `snowflake_table` resource which includes a column with a `default` block with an `expression` inside
2. Run apply

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @lorenzo-romanelli 👋 

Snowflake does not support adding new columns with default expressions (see [docs](https://docs.snowflake.com/en/sql-reference/sql/alter-table#table-column-actions-tablecolumnaction)).

**Comment by lorenzo-romanelli** [comment]
Hi @sfc-gh-jmichalak thank for the quick feedback!

To clarify, we are not trying to add a column to an existing table, but to create a new table which includes the column with a default expression. Looking at the doc it should be possible?
https://docs.snowflake.com/en/sql-reference/sql/create-table

**Comment by sfc-gh-jmichalak** [comment]
Yes, it should be possible, and we even have a test case for this :)
Please provider the whole table configuration, and logs with `TF_LOG=DEBUG`.

**Comment by lorenzo-romanelli** [comment]
My bad, we overlooked something in the process 😅 Destroying the table and recreating it works as expected
