### ISSUE TITLE
[Feature]: Add support for optional/default arguments for snowflake_function resources

### ISSUE THREAD

**Issue by deanmorin** [Snowflake-Labs/terraform-provider-snowflake#3097]
### Use Cases or Problem Statement

I want to create a function that has an optional/default argument, as specified in the [Snowflake Documentation](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-arguments#designating-an-argument-as-optional).

### Category

category:resource

### Object type(s)

resource:function

### Proposal

Add a `default` argument to the `arguments` block in the `snowflake_function` resource. This is identical to the [same proposal for procedures](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2623).

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @deanmorin 👋 
Functions and procedures are currently being reworked, and this will be supported in one of the next releases. cc @sfc-gh-asawicki

**Comment by sfc-gh-asawicki** [comment]
Hey @deanmorin.

In v0.100.0, we have introduced new function resources. Default values for arguments are now supported (with some Snowflake limitations). Please check it out and let us know if this solves your need.

**Comment by deanmorin** [comment]
@sfc-gh-asawicki I don't have anymore functions with default args, but I tried it out for procedures in v1.0.0 and so far so good!

BTW I did run into an issue when switching to the new resource type https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3297

**Comment by sfc-gh-asawicki** [comment]
Hey @deanmorin.

I will close this issue then as it was added to functions.

About the #3297 - let's continue there.
