### ISSUE TITLE
[General Usage]: Unable to fetch data source through snowflake_system_get_privatelink_config.

### ISSUE THREAD

**Issue by ravisingh27** [Snowflake-Labs/terraform-provider-snowflake#3099]
### Terraform CLI Version

1.7.5

### Terraform Provider Version

0.89.0

### Terraform Configuration

```terraform
we are unable to fetch the data through terraform data source, for this account - NV34080.

data.snowflake_system_get_privatelink_config.snowflake_private_link.aws_vpce_id
```

### Category

category:data_source

### Expected Behavior

We should be getting the service_name through this data source.

### Actual Behavior

it gives us service name is empty 

### Steps to Reproduce

create a endpoint 
attach the service_name through - terraform data source
data.snowflake_system_get_privatelink_config.snowflake_private_link.aws_vpce_id

### How much impact is this issue causing?

Low

**Comment by sfc-gh-jmichalak** [comment]
Hi @ravisingh27 👋 
This is probably a duplicate of https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1630. As a workaround, please set `QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE`, as mentioned in the comments.

The answer by @sfc-gh-asawicki is still valid:

> Reworking the SYSTEM$ function datasources was not our priority for V1, but we were thinking about introducing the generic datasource as a replacement. In the meantime, we will accept contributions following [our guidelines](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md).

**Comment by ravisingh27** [comment]
@sfc-gh-jmichalak Thanks. It worked
