### ISSUE TITLE
Replace `SHOW USERS LIKE x` command with `DESC USER x`

### ISSUE THREAD

**Issue by mhaley-miovision** [Snowflake-Labs/terraform-provider-snowflake#317]
**Is your feature request related to a problem? Please describe.**

Our snowflake account has many different roles and we strive to never use ACCOUNTADMIN unless we absolutely require it in an exceptional circumstance. This also means that we will never rely on that role for a daily task such as managing users in the database.  Currently the snowflake provider uses the `SHOW USERS` command to get information about a user which according to the [snowflake documents](https://docs.snowflake.com/en/sql-reference/sql/show-users.html) (and tested by me) requires the `MANAGE GRANTS` global privilege, which is essentially super user privileges, something we also want to avoid.

**Describe the solution you'd like**

The exact same information can be retrieved using the `DESC USER` command, and does not require that the executing role have global `MANAGE GRANTS` privileges.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanking** [comment]
@mhaley-miovision the docs do not specify, but it seems like unlike `show user`, `describe user` requires a using a warehouse. We have so far avoided that to keep the provider configuration simpler, but open to making that change if needed.

Also, it is not clear to me what permissions are needed to run `describe user` on a user other than the caller. Do you have docs on that?

**Comment by mhaley-miovision** [comment]
@ryanking You are right, the docs are not very clear on this.  The [Access Control Privileges](https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#user-and-role-privileges) make it seem like you can issue that command on your own user or any user that you own. From my testing, I grants all privileges on the account to a role, and it was not able to describe a user. So it seems like accountadmin is treated a bit special in this regard.

**Comment by zoharsan** [comment]
Documentation for Snowflake on this topic: https://docs.snowflake.com/en/sql-reference/ddl-user-security.html

`Snowflake provides a full set of SQL commands for managing users and security. These commands can only be executed by users who are granted roles that have the OWNERSHIP privilege on the managed object. This is usually restricted to the ACCOUNTADMIN and SECURITYADMIN roles.

However, individual users are able to perform the following tasks for themselves:

Change their password (only through the web interface).

View their user information (via DESCRIBE USER).

Change their default role, virtual warehouse, or namespace (via ALTER USER).

Change their session parameters (via ALTER SESSION).`

To answer the question, you can issue DESCRIBE user command as the user itself, as the role who has OWNERSHIP on the user, as ACCOUNTADMIN and/or SECURITYADMIN. The only caveat I found is that users who are owned by ACCOUNTADMIN won't be accessible through SECURITYADMIN.

After internal discussion, we will be clarifying our documentation in this area following this feedback.

**Comment by funes79** [comment]
@zoharsan I had a similar issue when I did a setup first time. As we started with just `SYSADMIN` role it was not enough and I had to create an alias for using the same snowflake connection but with the `SECURITYADMIN` role. So I ended up using two roles.  Or,.. is it possible to run all these user, grant, database and roles changes without those high roles?

**Comment by mhaley-miovision** [comment]
> @mhaley-miovision the docs do not specify, but it seems like unlike `show user`, `describe user` requires a using a warehouse.

@ryanking ran into this problem again today. Did a quick look and it looks like describe user does not require a warehouse either.

**Comment by alexrosenfeld10** [comment]
@ryanking I'm running into this problem as well. Why not just query the information schema for this as `show users like` will limit after 10k rows too? https://docs.snowflake.com/en/sql-reference/sql/show-users.html

> The command returns a maximum of 10K records for the specified object type, as dictated by the access privileges for the role used to execute the command; any records above the 10K limit are not returned, even with a filter applied.
> To view results for which more than 10K records exist, query the corresponding view (if one exists) in the Information Schema.

**Comment by ryanking** [comment]
@alexrosenfeld10 originally I avoided querying the information schema because (I think) it requires a warehouse, which complicates our configuration

I don't think we have time to fix this right now, but if someone wanted to take a stab at it, I would be happy to accept a PR that used describe.

**Comment by alexrosenfeld10** [comment]
I see. Alright, thanks. As I developed further it turned out that I can't use terraform for my use case as I have too many moving parts triggered by business logic in my middle tier. Thanks anyway, this is a cool provider!
