### ISSUE TITLE
[Docs]: snowflake_tag uses warehouse from v0.99.0

### ISSUE THREAD

**Issue by harukitake** [Snowflake-Labs/terraform-provider-snowflake#3251]
### Object type(s)

resource:tag

### Documentation Link

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/tag

### Description

Up to v0.98.0, `snowflake_tag` resource uses SHOW to get tag information, but in v0.99.0 `snowflake_tag` resource  has changed to querying information_schema.
Provider users need to configure warehouse to use `snowflake_tag` resource.
Most resources don't require warehouse configuration, so I request to update migration guide.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @harukitake. Thanks for bringing it to our attention.

We will update the migration guide.

**Comment by harukitake** [comment]
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#breaking-change-required-warehouse

I confirmed that the migration guide has updated.
It looks good.
