### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bmhah** [Snowflake-Labs/terraform-provider-snowflake#3259]
### Terraform CLI Version

1.57.0

### Terraform Provider Version

0.98.0

### Description 
The main issue is we are importing objects (procedures, views, tables, schemas) from one state into another state. Upon completing the import and running a plan we are seeing that all the objects are being destroyed and recreated. This is happening for 130 objects we are migrating and is considered a very high priority.

### Category

category:import

### Object type(s)

resource:procedure, resource:schema, resource:table, resource:view

### Expected Behavior

Upon importing objects into a new state, we want `terraform plan` to have no destroy and re-creations. Everything should be 0.

### Actual Behavior

Everything that was imported is being destroyed and recreated.

### Steps to Reproduce

1. Import an object to another state
2. run a plan
3. See the results that terraform outputs.

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @bmhah 
We cannot help without any examples. Please, provide at least one.
