### ISSUE TITLE
[Bug]: Failed to describe stage on terraform plan

### ISSUE THREAD

**Issue by AJuanJim** [Snowflake-Labs/terraform-provider-snowflake#3265]
### Terraform CLI Version

1.5.0

### Terraform Provider Version

0.85.0

### Terraform Configuration

```terraform
Hello, 

We tried to execute a terraform plan without making any changes on our configuration files and we found the following error on our stages:

Error: Failed to describe stage
with module.sfbs.snowflake_stage.stage["DB.PUBLIC.STAGE"], on ../modules/snowflake_bs/db-objects.tf line 174, in resource "snowflake_stage" "stage": 174: resource "snowflake_stage" "stage" {
Id: , Err: [errors.go:17] object does not exist or not authorized

Our stages are being created with an AccountAdmin privilege following the next configuration:

resource "snowflake_stage" "stage" {
  for_each = local.stage_map
 
  database            = snowflake_database.db[each.value.db].name
  schema              = each.value.schema == "PUBLIC" ? "PUBLIC" : snowflake_schema.schema[each.value.schema_id].name
  name                = each.value.stage
  url                 = each.value.url
  storage_integration = each.value.storage_integration

  lifecycle {
    ignore_changes = [directory]
  }
}

Also we found out that our last successful was executed on 04/12/2024(dd/mm/yyyy) having snowflake on version 8.44.2 and today when we are having above mentioned errors, we have the version 8.45.1, could this version upgrade cause problems with our terraform config?
```

### Category

category:resource

### Expected Behavior

0 changes on terraform plan

### Actual Behavior

Error: Failed to describe stage
with module.sfbs.snowflake_stage.stage["DB.PUBLIC.STAGE"], on ../modules/snowflake_bs/db-objects.tf line 174, in resource "snowflake_stage" "stage": 174: resource "snowflake_stage" "stage" {
Id: , Err: [errors.go:17] object does not exist or not authorized

### Steps to Reproduce

Run terraform plan

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by AJuanJim** [comment]
Hi,

After further investigation of the issue, we found the following error on all our stages:

"DB"."PUBLIC"."STAGE" err 002003 (02000): SQL compilation error:
2024-12-11T08:07:26.148+0100 [DEBUG] provider.terraform-provider-snowflake_v0.85.0: 2024/12/11 08:07:26 [DEBUG] sql-conn-query: [query DESCRIBE STAGE 

But when we are looking on the query history of the user with which these queries are being executed we found the following error:

![image](https://github.com/user-attachments/assets/f183ebc9-20cc-4540-b9aa-905502947285)

![image](https://github.com/user-attachments/assets/a1c59312-c328-4f29-b802-b99b36a3c175)

But when we run this same describes or queries from the Snowflake UI, we can run it without finding any errors.

**Comment by AJuanJim** [comment]
Hi,

We executed again a terraform plan isolating one of the stages, finding this errors after debugging:

2024-12-11T10:30:57.033+0100 [DEBUG] provider.terraform-provider-snowflake_v0.85.0: time="2024-12-11T10:30:57+01:00" level=error msg="error: 002003 (02000): SQL compilation error:\nDatabase 'DB' does not exist or not authorized." func="gosnowflake.(*snowflakeConn).queryContextInternal" file="connection.go:396"

2024-12-11T10:30:57.033+0100 [DEBUG] provider.terraform-provider-snowflake_v0.85.0: 2024/12/11 10:30:57 [DEBUG] sql-conn-query: [query DESCRIBE STAGE "DB"."PUBLIC"."STAGE" err 002003 (02000): SQL compilation error:

**Comment by AJuanJim** [comment]
Hi,

Finally with the help of Snowflake Support we could fix the issue, which was provoked due to a change on the default role of the user who was running the queries on terraform, after modifying that everything works properly.

Thank you for your help and sorry for the inconvenience.

**Comment by sfc-gh-jcieslak** [comment]
Hey @AJuanJim
Sorry for the late response. I'm happy that you managed to quickly fix your issue.
