### ISSUE TITLE
[Bug]: schema DATA_RETENTION_TIME_IN_DAYS from previous default -1

### ISSUE THREAD

**Issue by jsantora-uom** [Snowflake-Labs/terraform-provider-snowflake#3290]
### Terraform CLI Version

>=1.0

### Terraform Provider Version

>=1.0

### Terraform Configuration

```terraform
When migrating to version 1.0.0 (issue present in 0.99.0 as well) old parameter data_retention_time_in_days = -1 (default) to 1 (or to any number), terraform errors with: 
Error: 001008 (22023): SQL compilation error:
│ invalid value [-1] for parameter 'DATA_RETENTION_TIME_IN_DAYS'
│ 
│   with snowflake_schema.all_schemas["RAW"],
│   on db_schema.tf line 12, in resource "snowflake_schema" "all_schemas":
│   12: resource "snowflake_schema" "all_schemas" {
```

### Category

category:resource

### Object type(s)

resource:schema

### Expected Behavior

Schema data_retention_time_in_days changed from default (-1) to 1. 

### Actual Behavior

Error: 001008 (22023): SQL compilation error:
│ invalid value [-1] for parameter 'DATA_RETENTION_TIME_IN_DAYS'

### Steps to Reproduce

1. terraform-snowflake-provider 0.89.0
2. build schema with DATA_RETENTION_TIME_IN_DAYS = -1 (default)
3. migrate to 0.99.0 or 1.0.0
4. change schemas DATA_RETENTION_TIME_IN_DAYS to any value 

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by jsantora-uom** [comment]
Closing issue as found the resolution. 
Had to initially set it to 0, then form 0 to any number.

**Comment by sfc-gh-jmichalak** [comment]
Hi, 

Could you provide configs for v0.89.0 and v0.99.0? The older version uses `data_retention_days`, and the newer one uses `data_retention_time_in_days`, and this should not be set to `-1`.

It's cool that you found the solution, but I'm wondering if we can improve the migration for the `schema` resource.

**Comment by jsantora-uom** [comment]
hi @sfc-gh-jmichalak, 
No worries find config for 0.89 here:

```
resource "snowflake_schema" "all_schemas" {
  provider            = snowflake.EDW_SYSADMIN
  database            = snowflake_database.edw_database.name
  for_each            = toset(local.edw_schemas)
  data_retention_days = local.edw_schemas_retention[each.key]  # this in our config file was set to -1 (default)
  name                = each.key
  comment             = "${each.key} schema"
  lifecycle {
    prevent_destroy = true
  }
}
```
and 0.99.0 here:
```
resource "snowflake_schema" "all_schemas" {
  provider                    = snowflake.ACCOUNTADMIN
  database                    = snowflake_database.edw_database.name
  for_each                    = toset(local.edw_schemas)
  data_retention_time_in_days = local.edw_schemas_retention[each.key]  # this in our config file is set to 1 
  name                        = each.key
  is_transient                = false
  with_managed_access         = false
  comment                     = "${each.key} schema"
  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by sfc-gh-jmichalak** [comment]
I couldn't reproduce this, but because you have a workaround, let's leave this closed.
