### ISSUE TITLE
[Bug]: no schema available for snowflake_role while reading state

### ISSUE THREAD

**Issue by jsantora-uom** [Snowflake-Labs/terraform-provider-snowflake#3291]
### Terraform CLI Version

latest

### Terraform Provider Version

=1.0.0

### Terraform Configuration
```
resource "snowflake_role" "example" {
  provider = snowflake.USERADMIN
  name     = "example
  comment  = "example"
}
```

### Category

category:resource

### Object type(s)

resource:role

### Expected Behavior

Plan does not fail as no parameters have change, only snowflake terraform resource name. 

### Actual Behavior
```terraform
Migrating snowflake provider from 0.99 to 1.0.0. Terraform plan fails when changing from snowflake_role to snowflake_account_role resource.
```
Terraform plan fails with error below: 
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/8060fae3-2810-408b-9ce3-772da1928f1d" />

### Steps to Reproduce

1. create snowflake role with v 0.99.0
2. migrate to v 1.0.0
3. update resource name to snowflake_account_role (from snowflake_role in 0.99.0)
4. run terraform plan

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @jsantora-uom 👋 

`snowflake_role` has been removed in v1.0.0. Please first change `snowflake_role` to `snowflake_account_role` in v0.99, and then upgrade to v1.0.0 (see [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-new-snowflake_account_role-resource)).

**Comment by jsantora-uom** [comment]
Thanks @sfc-gh-jmichalak , that has been easier than initially thought.
