### ISSUE TITLE
Schema creation SQL error

### ISSUE THREAD

**Issue by drn** [Snowflake-Labs/terraform-provider-snowflake#384]
**Provider Version**

v0.20.0

**Terraform Version**

v0.13.4

**Describe the bug**

In the `terraform apply` when creating a `snowflake_schema` and subsequent runs of `terraform plan`, the following error is being thrown:
```
Error: sql: Scan error on column index 8, name "retention_time": converting driver.Value type string ("") to a int64: invalid syntax
```

**Code samples and commands**

This is the resource definition that is causing the issue:

```
resource snowflake_schema analytics_scratch {
  database = snowflake_database.analytics.name
  name     = "SCRATCH"
  comment  = "Scratch schema in Analytics DB for BI usage."

  is_transient        = false
  is_managed          = false
  data_retention_days = 0
}
```

The schema was created after the initial `terraform apply` and is displaying:

<img width="1155" alt="Screen Shot 2020-12-24 at 5 59 12 PM" src="https://user-images.githubusercontent.com/885841/103113971-c517ed00-4611-11eb-8e44-c757c63ca290.png">

**Additional context**

This appears to be the same error as issue https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/166

I suspect this may be due to `null` being returned when `data_retention_time_in_days` is being set to `0`.

* `alter schema analytics.scratch set data_retention_time_in_days=0;`
* `retention_time` is a null value
* `alter schema analytics.scratch set data_retention_time_in_days=1;`
* `retention_time` is an integer `1`

Seems like this may be solved by handling the null value when scanning the SQL results.

**Temporary Workaround**

To get around the continuous `terraform plan` failure, I gave up and set retention to 1 day directly and updated TF accordingly.

**Comment by robbruce** [comment]
Issue still exists in version 0.22.0 too
