### ISSUE TITLE
snowflake_database_grant should accept "ALL" as a privilege

### ISSUE THREAD

**Issue by igorchernysh** [Snowflake-Labs/terraform-provider-snowflake#386]
Hi,

Getting error:

`Error: expected privilege to be one of [REFERENCE_USAGE USAGE CREATE SCHEMA IMPORTED PRIVILEGES MODIFY MONITOR OWNERSHIP], got ALL`

, while trying to use "ALL" as a privilege value in "snowflake_database_grant"

Snowflake accepts it without problems, like:

`GRANT ALL ON DATABASE "TF_TEST_DB" TO TF_ROLE;`

Thanks!

**Comment by milldr** [comment]
+1 for this. I just updated from v0.15 where we were able to set that option, but now using v0.20 it's not allowed anymore.

**Comment by kanata2** [comment]
It seems that this provider implementation decides not to accept `ALL`.
more details: https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318
