### ISSUE TITLE
snowflake_table: table column actions  will force-destroy the table and recreate it

### ISSUE THREAD

**Issue by chenlu-wang** [Snowflake-Labs/terraform-provider-snowflake#446]
**Provider Version**

0.22.0

**Terraform Version**

0.14.5

**Describe the bug**

Add, alter, drop columns actions on table are attribute changes, but it will cause that the table is destroyed and recreated. 
For example, to add a column on table using `snowflake_table` resource, the table will be dropped and recreated. 
It makes unexpected data lost in whole table by column operations.

**Expected behavior**
When columns are updated, the table resource should be updated rather than destroyed. 
For example, to add a new column on table, the table should just update the column with empty data. 
In snowflake, it is the equivalent action of `alter table table_name add column column_1 data type;`
[snowflake documentation ](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html#table-column-actions-tablecolumnaction)

**Code samples and commands**
If I add a column {name="SOURCE", type="VARCHAR"} on mytable, terraform will destroy the table and add it again: 
```
-/+ resource "snowflake_table" "mytable" {
      ~ id       = "mydb|myschena|mytable" -> (known after apply)
        name     = "mytable"
      ~ owner    = "SYSADMIN" -> (known after apply)
        # (3 unchanged attributes hidden)

      + column { # forces replacement
          + name = "SOURCE"
          + type = "VARCHAR"
        }
    }
Plan: 1 to add, 0 to change, 1 to destroy.
```
The expected resource should be a resource change.

**Comment by nikolayskovpin** [comment]
Also version 0.23.2:
even changes were applied to snowflake table, every time I run `terraform plan` it shows previous state and plans to apply the same change

**Comment by hragarwal** [comment]
I see a merged PR, when this change would be available ?
