### ISSUE TITLE
Role Grants update in place due to comma.

### ISSUE THREAD

**Issue by weiminmei** [Snowflake-Labs/terraform-provider-snowflake#498]
**Provider Version**
0.23.0

**Terraform Version**
0.14.8

**Describe the bug**
The snowflake_role_grants keeps updating in place with subsequent terraform plans.

**Expected behavior**

With no change, the terraform plan should not show this action. I have added the comma to the resource declaration but each subsequent run still shows that it is adding it. Observing the state file, the comma is not added to the resource after the apply.

**Code samples and commands**
```
resource "snowflake_role_grants" "IT_grant" {
  role_name = "ITROLE"
  
  roles = [
    "ITROLE", #BUG
  ]
  depends_on = [
    snowflake_role.IT
  ]
}

  # snowflake_role_grants.IT_grant will be updated in-place
  ~ resource "snowflake_role_grants" "IT_grant" {
        id        = "ITROLE"
      ~ roles     = [
          + "ITROLE",
        ]
        # (2 unchanged attributes hidden)
    }
```
**Additional context**

Here is the tfstate entry:
```
  "schema_version": 0,
          "attributes": {
            "id": "ITROLE",
            "role_name": "ITROLE",
            "roles": [
              "ITROLE"
            ],
            "users": null
          },
```

**Comment by kevinkle** [comment]
Was wondering if this was just us, am getting the same issue on 0.25.4

**Comment by ybressler** [comment]
Looks like this might be a solution: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/211#issuecomment-681012530
