### ISSUE TITLE
Deleting role grant with securityadmin and accountadmin returns SQL error

### ISSUE THREAD

**Issue by kuannie1** [Snowflake-Labs/terraform-provider-snowflake#512]
**Provider Version**

0.23.2

**Terraform Version**

0.13.5

**Describe the bug**

Deleting role grants that involve SECURITYADMIN and ACCOUNTADMIN should be valid actions in this provider. 

**Expected behavior**

I expected deleting this resource would not return errors:
```
  - resource "snowflake_role_grants" “grant_name” {
      - id        = "SECURITYADMIN" -> null
      - role_name = "SECURITYADMIN" -> null
      - roles     = [
          - "ACCOUNTADMIN",
        ] -> null
      - users     = [
          - “oldUser”,
        ] -> null
    }
```
I got this error:
```
Error: 003042 (42501): SQL compilation error:
Role 'SECURITYADMIN' is a system object. REVOKE cannot be performed.
```

**Comment by sfc-gh-asawicki** [comment]
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.
