### ISSUE TITLE
`snowflake_pipe` error creating.  This session does not have a current database.

### ISSUE THREAD

**Issue by bubalush** [Snowflake-Labs/terraform-provider-snowflake#533]
**Provider Version**

0.25.0

**Terraform Version**

0.14.10

**Describe the bug**

`snowflake_pipe` resource can not be created. The following error received:
```
Error: error creating pipe xxxx_PIPE: 090105 (22000): Cannot perform operation. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.

  on input_health_snowpipe.tf line 50, in resource "snowflake_pipe" "xxxxx":
  50: resource "snowflake_pipe" "xxxxxx" {
  ```

**Expected behavior**

Snowpipe should be created

**Code samples and commands**

```
resource "snowflake_pipe" "xxx" {
  name              = "xxxx"
  database          = "testo"
  schema            = "testo_dev"
  comment           = "Ingestion pipe events."
  copy_statement    = "copy into testo.testo_dev.xxxx from @xstage"
  auto_ingest       = true
  aws_sns_topic_arn = "arn::"
}
```
**Additional context**

The SQL query created by snowflake TF provider works if use the worksheet in Snowflake console.

**Comment by vsayer** [comment]
> resource "snowflake_pipe" "xxx" {
  name              = "xxxx"
  database          = "testo"
  schema            = "testo_dev"
  comment           = "Ingestion pipe events."
  copy_statement    = "copy into testo.testo_dev.xxxx from @xstage"
  auto_ingest       = true
  aws_sns_topic_arn = "arn::"
}

If you need a workaround in the meantime, just fully-qualify the stage, i.e., `@DATABASE.SCHEMA.xstage`. That got it working for me.

Original: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/135#issuecomment-667178472

**Comment by rubemz** [comment]
still seeing this bug, fully qualifying the stage name works... but it would be nice to not need to do that.

**Comment by russell** [comment]
It also causes another bug when you have a file format that didn't use the fully qualified name, because then you'll get the error.

So you have to fully qualify all things that stage depends on because otherwise they might not work.

```
SQL compilation error: File format 'MY_JSON' does not exist or not authorized.
```

**Comment by sfc-gh-asawicki** [comment]
Closing as deprecated. Please use newer versions of the provider and create a new issue if the error persist there.
