### ISSUE TITLE
support for table constraints

### ISSUE THREAD

**Issue by rahulrraj** [Snowflake-Labs/terraform-provider-snowflake#538]
**Provider Version** v0.23.2
**Terraform Version** Terraform v0.13.1

As per the [documentation](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/table) ,Table column objects only allow name and type property as below
column {
    name = "id"
    type = "int"
  }

It would be nice if it can support CONSTRAINT like PRIMARY, not null etc as documented here.
https://docs.snowflake.com/en/sql-reference/sql/create-table-constraint.html

Is there any workaround to add those constraints with the current version of the provider?

**Comment by fonsecalink** [comment]
This is the work around that I am using at the moment:

```
resource "snowflake_table" "weew" {
  database = "weer"
  schema   = "weeb"
  name     = "weet"
  comment  = "."

  lifecycle {
    ignore_changes = [
        column[0]
    ]
  }

  column {
    name = "id"
    type = "NUMBER(38,0) NOT NULL AUTOINCREMENT CONSTRAINT WE_PK PRIMARY KEY"
  }
}
```
