### ISSUE TITLE
Network Policy attachment - terraform state show - no users

### ISSUE THREAD

**Issue by kumarjoshi** [Snowflake-Labs/terraform-provider-snowflake#569]
Provider version 0.25.5

Terraform v0.15.5

**Describe the bug**

After importing existing network policy attachments, when I run terrafom state show, it doesn't list the users attached to the network policy. 

**Expected behavior**

Like other resources, the expected behaviour is to be able to import existing resources to terraform state

**Code samples and commands**
```
terraform import snowflake_network_policy_attachment.wne_vpn WNE_VPN
terraform state show snowflake_network_policy_attachment.wne_vpn

# snowflake_network_policy_attachment.wne_vpn:
resource "snowflake_network_policy_attachment" "wne_vpn" {
    id = "WNE_VPN"
}
```

**Comment by alldoami** [comment]
Can you give more details on what you're expecting? Do you get errors from importing?

**Comment by kumarjoshi** [comment]
I doesn't give error. But it doesn't import users attached to the network policy. Isn't that the expected behavior of network_policy_attachment?

**Comment by alldoami** [comment]
Ah look like at the time there was no way to describe the network policy. Now there is, so moving this to a feature request. https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/network_policy_attachment.go#L78-L79

**Comment by sfc-gh-asawicki** [comment]
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.
