### ISSUE TITLE
Every new environment remove the previous global privileges

### ISSUE THREAD

**Issue by thomasschaller1** [Snowflake-Labs/terraform-provider-snowflake#587]
Hello,

I am trying to add the account privilege `EXECUTE TASK` to a specific role for each environment using this following code:

```
resource "snowflake_account_grant" "execute_task" {
  roles             = [snowflake_role.main["CREATOR"].name]
  privilege         = "EXECUTE TASK"
  with_grant_option = false
}
```
`snowflake_role.main["CREATOR"].name` being something like `PROD_CREATOR`. The problem with that is that it will remove the role when applying to a new workspace. For example, if I am applying to `DEV`, it will remove `PROD_CREATOR` and add `DEV_CREATOR` because it is a global resource between workspaces. How can I do it to not remove previous roles?

Thanks in advance

**Comment by alldoami** [comment]
Can you elaborate when saying `applying to DEV` and your definition of `workspaces`?
