### ISSUE TITLE
IDENTIFIER is safer / less pointy than double quotes alone

### ISSUE THREAD

**Issue by mike-weinberg** [Snowflake-Labs/terraform-provider-snowflake#592]
this is an example of a general suggestion (calling this a suggestion, not an issue, since really nothing is broken)

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/3d29ed6dbca4f2c6d147fd260300c0bada96fedb/pkg/snowflake/future_grant.go#L40

https://docs.snowflake.com/en/sql-reference/identifier-literal.html

This is an opinion, but forced use of double quotes is a little pointy because it forces case sensitivity even in cases where it might not be desired, which is counter to the default behavior in snowflake. 

Of course, if this was a major issue there would be more reports, so the primary benefit of using IDENTIFIER (which can also tolerate use of double quotes) would be increased difficulty of sql injection, _particularly_ if you use double-dollar-sign enquoted string literals like `fmt.Sprintf(IDENTIFIER($$"%v"."%v"$$), db, schema)` 

personally i think it would be nice if there was a switch indicating if identifiers are to be quoted, with the default being unquoted, throwing a parse error if unquoted identifier validation rules are violated.

**Comment by sfc-gh-asawicki** [comment]
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.
