### ISSUE TITLE
Support for `SECURITY INTEGRATION`

### ISSUE THREAD

**Issue by LouisAmon** [Snowflake-Labs/terraform-provider-snowflake#616]
**Describe the solution you'd like**

Support for for the `SECURITY INTEGRATION` resource

**Additional context**

https://docs.snowflake.com/en/sql-reference/sql/create-security-integration.html

There's only one per account, so we should specify that in the docs I think (same as the `network_policy_attachment`)

**Comment by ChrisIsidora** [comment]
@LouisAmon There are different types of Security Integration. The SCIM type is already implemented. Is there a particular one that you require?

**Comment by LouisAmon** [comment]
@ChrisIsidora I meant the SAML2 integration : it typically involves a lot of back and forth between two different services so it's a great use-case for IaC ;)

**Comment by kmertz-rga** [comment]
Agreed, SSO/SAML2 needs to be available in the terraform provider.

**Comment by intinfinite** [comment]
I think this issue can be closed with recent pull request

**Comment by sfc-gh-asawicki** [comment]
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.
