### ISSUE TITLE
grant on future functions in database requires schema name

### ISSUE THREAD

**Issue by BoAustin** [Snowflake-Labs/terraform-provider-snowflake#658]
**Provider Version**

v0.25.12

**Terraform Version**

Terraform v0.15.2

**Describe the bug**

When a snowflake_function_grant resource with on_future = true and a database with no schema specified is applied it returns the error: The argument "schema_name" is required, but no definition was found.

**Expected behavior**

A grant on future functions in the database should be issued

**Code samples and commands**

Sample resource definition (assuming database and role exist and provider can issue future grants):
```
resource "snowflake_function_grant" "future_function_usage" {
  database_name = "DB"
  privilege     = "USAGE"
  roles         = "SOME_ROLE"
  on_future     = true
}
```

**Additional context**

This works correctly for tables and views.
The snowflake provider documentation indicates this is supported.
This is the DDL that should be issued:
`grant USAGE on future functions in database DB to role SOME_ROLE;`

**Comment by wyattshapiro** [comment]
@BoAustin It appears there is a workaround: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/682#issuecomment-919647123
