### ISSUE TITLE
Docs for snowflake_task_grant show example with sequence_name 

### ISSUE THREAD

**Issue by jifeous** [Snowflake-Labs/terraform-provider-snowflake#691]
In the documentation the example for a task grant is a copy and paste from the sequences grant and the sequence name is there
https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/task_grant

resource snowflake_task_grant grant {
  database_name = "db"
  schema_name   = "schema"
  **sequence_name = "sequence"**

  privilege = "operate"
  roles = [
    "role1",
    "role2",
  ]

  on_future         = false
  with_grant_option = false
}

**Comment by yohei1126** [comment]
@jifeous This issues has already been fixed https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/task_grant
