### ISSUE TITLE
Unable to plan after storage integration from state was destroyed in environment

### ISSUE THREAD

**Issue by bneijt** [Snowflake-Labs/terraform-provider-snowflake#696]
**Provider Version**
0.25.19

**Terraform Version**

1.0.7

**Describe the bug**

Can't plan after a storage integration in the state has been removed from the environment.

To reproduce:
- Create a `snowflake_storage_integration` using the provider
- Delete the resulting integration
- Either:
  - Execute `terraform refresh` to update the state
  - Execute a plan to change other resources
  - Try to plan for destruction (`terraform plan -destroy`)

**Expected behavior**

A frefresh should allow the provider to notice the removal of the storage integration and update the state

**Code samples and commands**

```
resource "snowflake_storage_integration" "abc" {
  name    = "ABC"
  comment = "Storage integration for the alphabet"
  type    = "EXTERNAL_STAGE"

  enabled = true

  storage_allowed_locations = [
  ]

  storage_provider     = "S3"
  storage_aws_role_arn = data.aws_iam_role.snowflake.id
}
```

```
show integrations;
drop integration abc;
```

**Additional context**

I'm raising an issue because I thought I could work around this by creating a PR ( #692 ) and then just going for a destroy of my environment in the meantime, but a destroy does not work either. So I'm now going try to recreate the storage intregration by hand to allow the provider to delete it again, or if that fails, delete my state and manually remove all resources mentioned there (not something I really want to have to do).

**Comment by bneijt** [comment]
I feel stupid, but there is a simple workaround:
```
terraform state list
terraform state rm snowflake_storage_integration.integration
```

**Comment by edulop91** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/692 is a great fix to avoid the workaround though! Thank you for the contribution :smile:
