### ISSUE TITLE
snowflake_procedure_grant needs schema_name when on_future is set

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Snowflake-Labs/terraform-provider-snowflake#766]
Hi Team,

As seen here:

![image](https://user-images.githubusercontent.com/72515998/143295943-31eafc24-d34a-4281-a1f8-add7b8a4a7bc.png)

The documentation describes:

> **on_future (Boolean)** When this is set to true and a schema_name is provided, apply this grant on all future procedures in the given schema. When this is true and no schema_name is provided apply this grant on all future procedures in the given database. The procedure_name and shares fields must be unset in order to use on_future.

However, `schema_name` is set up as a required argument. This results in `snowflake_procedure_grant` requiring `schema_name` when `on_future` is set. This behavior seems inconsistent with view_grant and table_grant when used future grants (`on_future`).

Let me know if this is intentional or a bug?

**Comment by wyattshapiro** [comment]
@sfc-gh-pkommini I am running into the same issue. It appears that the on_future behavior for`snowflake_external_table_grant`, `snowflake_file_format_grant`, `snowflake_stage_grant` act in a similar way.

**Comment by wyattshapiro** [comment]
It appears there is a workaround: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/682#issuecomment-919647123
