### ISSUE TITLE
Grants fail on stages when they are mixed as internal and external

### ISSUE THREAD

**Issue by Bryan-Meier** [Snowflake-Labs/terraform-provider-snowflake#772]
**Provider Version**

v0.25.25

**Terraform Version**

1.0.10

**Describe the bug**

I would like to use snowflake_stages as a data source and (for_each) loop over the stages and set the privileges. The problem is that external and internal stages are returned and the same privileges cannot be applied to both types of stages. For example external stages can only have USAGE granted on them and internal stages can only have READ or WRITE granted. In this scenario it's impossible to apply the grant because there is no way of knowing what type of stage it is.

To be honest, I'm not sure why internal and external stages are not their own separate resource. Internal and external stages are fundamentally very different from each other. Just my 2 cents....

**Comment by alldoami** [comment]
Could you combine this with the feature request you just opened? It is repetitive.

**Comment by Bryan-Meier** [comment]
Hi @alldoami, I closed the feature request. I couldn't decide if this would be considered a bug or a feature request.
