### ISSUE TITLE
Allow default_secondary_roles to be set on a user

### ISSUE THREAD

**Issue by tekumara** [Snowflake-Labs/terraform-provider-snowflake#773]
**Is your feature request related to a problem? Please describe.**

For creating users that default to using all secondary roles.

**Describe the solution you'd like**

default_secondary_roles as an optional user object property

**Describe alternatives you've considered**

Using snowsql to set this.

**Comment by mwiewior** [comment]
Fixed by #1030

**Comment by tekumara** [comment]
Looks to be working thankyou!
