### ISSUE TITLE
Support for allowed_values in snowflake_tag resource

### ISSUE THREAD

**Issue by medwig** [Snowflake-Labs/terraform-provider-snowflake#815]
**Is your feature request related to a problem? Please describe.**

[snowflake_tag](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/tag) does not support the [allowed_values](https://docs.snowflake.com/en/user-guide/object-tagging.html#specifying-tag-values) argument. This would be very helpful in defining an explicit tag library.

**Describe the solution you'd like**

```
resource "snowflake_tag" "classification" {
  name     = "CLASSIFICATION"
  schema   = "SOME_SCHEMA"
  database = "SOME_DB"
  allowed_values = ["FOO", "BAR"]  # new field
}
```

**Comment by amit0904** [comment]
Should this be closed now as I can see it exists.

**Comment by medwig** [comment]
closing as feature is added by PR #1006

**Comment by medwig** [comment]
closing as feature is added by PR #1006
