### ISSUE TITLE
Schema Tag Failure Not Handled

### ISSUE THREAD

**Issue by swallace-rgare** [Snowflake-Labs/terraform-provider-snowflake#875]
**Provider Version**

0.25.36

**Terraform Version**

v1.0.7

**Describe the bug**

tag block in snowflake_schema resource generates invalid ALTER SCHEMA statement AND seems to have incorrectly updated Terraform state on execution failure.

**Expected behavior**

Passing an invalid tag name to in a tag block should cause an error.

**Code samples and commands**

The first attempt we improperly supplied the tag name, but the apply didn't fail.
tag {
  name = "is_adhoc"
  value = "True"
}
It resulted in this statement, which obviously failed because "".""."is_adhoc" isn't a real tag:
ALTER SCHEMA "{db_name}"."{schema_name" SET TAG "".""."is_adhoc" = "True"

Next we tried fixing that:
tag {
  name = "${db_name}.${schema_name}.IS_ADHOC" # This renders to the correct value - a valid tag
  value = "True"
}
And the statement generated was:
ALTER SCHEMA "{db_name}"."{schema_name" UNSET TAG "".""."is_adhoc"
which again failed obviously, and the new tag wasn't set. This suggests that the state was updated after the initial failure.

Furthermore, the docs only list "name" and "value" as keys for the tag block, but it seems to want "database" and "schema" as well based on how the ALTER SCHEMA statement renders.

**Additional context**

We're using a dynamic block to set the tags like:
  dynamic tag {
    for_each = var.tag

    content {
      name    = "${var.database_name}.${schema_name}.${tag.value.name}" 
      value    = tag.value.value 
    }
  } 

The tag variable is defined as:
variable "tag"{
  type        = list(object({
       name  = string
       value = string
  }))
} 

If you think this is just user error, let me know. Thanks for your help with this.

**Comment by sfc-gh-swinkler** [comment]
Hello @swallace-rgare  Tags are now associated using the purpose built "snowflake_tag_association" resource, and the old method has been deprecated. An example of how to use tag association resource would be:

```
resource "snowflake_warehouse" "test_wh" {
  name           = "TEST_WH"
  warehouse_size = "XSMALL"
}

resource "snowflake_tag" "t" {
  name = "tag1"
  //value = "value1"
  database = snowflake_database.db.name
  schema = snowflake_schema.s.name
}

resource "snowflake_tag_association" "ta" {
  tag_id = snowflake_tag.t.id
  tag_value ="value1"
  object_type = "WAREHOUSE"
  object_identifier {
    name = snowflake_warehouse.test_wh.name
  }
}
```
Please open a new ticket if you have any issues. Thanks!
