### ISSUE TITLE
Alter resource monitor is actually destroy plus create

### ISSUE THREAD

**Issue by kumarjoshi** [Snowflake-Labs/terraform-provider-snowflake#876]
**Provider Version**

0.25.36

**Terraform Version**
v1.1.6

The version of Terraform you were using when the bug was encountered.
v1.1.6

**Describe the bug**
I create a resource monitor `EVENTS_DEVELOPER_MONITOR` using ACCOUNTADMIN role and then granted all privileges on this monitor to the role DATA_ADMIN, which is used to run terraform.  That means the role DATA_ADMIN should have MODIFY and MONITOR privileges according to :
https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#resource-monitor-privileges
GRANT CREATE MONITOR is currently not supported by Snowflake.

When I try to alter one of the properties of this resource monitor using Terraform, it gives me an error:
```
│ Error: error deleting resource monitor EVENTS_DEVELOPER_MONITOR: 003001 (42501): SQL access control error:
│ Insufficient privileges to operate on resource_monitor 'EVENTS_DEVELOPER_MONITOR'
```
That means, `terraform apply` is not modifying the resource monitor but instead deleting and re-creating it. 

**Expected behavior**
With role `DATA_ADMIN` I should be able to modify existing resource monitors since I granted ALL privileges on this monitor to role DATA_ADMIN

**Code samples and commands**
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # snowflake_resource_monitor.events_developer_monitor must be replaced
-/+ resource "snowflake_resource_monitor" "events_developer_monitor" {
      ~ credit_quota               = 10000 -> 8000 # forces replacement
      ~ id                         = "EVENTS_DEVELOPER_MONITOR" -> (known after apply)
        name                       = "EVENTS_DEVELOPER_MONITOR"
      - suspend_immediate_triggers = [] -> null
      - suspend_triggers           = [] -> null
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
snowflake_resource_monitor.events_developer_monitor: Destroying... [id=EVENTS_DEVELOPER_MONITOR]
╷
│ Error: error deleting resource monitor EVENTS_DEVELOPER_MONITOR: 003001 (42501): SQL access control error:
│ Insufficient privileges to operate on resource_monitor 'EVENTS_DEVELOPER_MONITOR'
```

**Comment by thenaturalist** [comment]
Updates are not implemented yet for resource_monitors, see https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/83997a742332f1376adfd31cf7e79c36c03760ff/pkg/resources/resource_monitor.go#L94

**Comment by samsunde** [comment]
+1 on this issue. Even as ACCOUNTADMIIN changes to resource monitor credit quota require a destroy + create. This in turn erases the month to date (or other period) usage. 

For example, say my initial credit limit was 2k credits/mo and I wanted to bump it up to 3k b/c I had used 1.8k credits MTD. I would modify my terraform credit quota, this would delete my our resource monitor and I would be back at 0/3000 instead of 1800/3000.

@thenaturalist is there any plan to implement this? or can you point me to the implementation of this update vs destory/create for another resource?

Thanks!

**Comment by thenaturalist** [comment]
@samsunde I'm not one of the maintainers and unfortunately don't have time atm to go into this myself. 
If you're proficient at go, `pkg/snowflake/resource_monitor.go` & `pkg/resources/resource_monitor.go` are the places to implement the update behavior. It is atm not implemented. 

I guess it wouldn't necessarily be cumbersome. Modifying resource monitors can be complex [as per the Snowflake docs](https://docs.snowflake.com/en/user-guide/resource-monitors.html#modifying-a-resource-monitor), but just altering the quota or name should be 80% of the use cases with 20% of total complexity.
