### ISSUE TITLE
Granting SCIM AAD provisioned roles to Snowflake standard roles

### ISSUE THREAD

**Issue by z4f1r0v** [Snowflake-Labs/terraform-provider-snowflake#883]
**Provider Version**

0.25.36

**Terraform Version**

Terraform v1.1.7

**Describe the bug**

I am provisioning users and security groups from Azure Active Directory (AAD) via SCIM into Snowflake. Those become users and roles in Snowflake respectively. I am trying to create a setup like [this](https://trevorscode.com/toward-a-standard-model-for-snowflake-roles-and-privileges/) where I grant custom roles (managed by AAD) to standard Snowflake roles i.e. `SYSADMIN` and `ACCOUNTADMIN`. 

Even though the execution of the Terraform script is successful, the role grants are not applied. Furthermore, next time I repeat the same action, Terraform thinks that the same code can be applied again and happily accepts the same script, marking all files as changes.

**Expected behavior**

When I run a Terraform script for assigning any kind of grant should be reflected in Snowflake. For example, a role grant like the following should be able to grant the `schema_owner` role defined to the `SYSADMIN` Snowflake role:
```
resource "snowflake_role_grants" "db_owner_grant" {
  role_name = var.schema_owner

  roles = [local.role.sysadmin]
}
```

**Comment by ChrisIsidora** [comment]
@z4f1r0v I have been using this resource for a long time without any issues. I think you are misinterpeting what this resource does. It grants a role with the name role_name to Roles and Users specified. So in your case you did the reverse the correct code to achieve your desired situation based on your excerpt should be:
```
resource "snowflake_role_grants" "db_owner_grant" {
  role_name = local.role.sysadmin

  roles = [var.schema_owner]
}
```

Further more make sure the terraform snowflake user you are using has the correct role to assign roles e.g Account admin or Security Admin. This not a bug as far as I could've tested (until 0.25.36)
