### ISSUE TITLE
Error: strip_outer_array is an invalid format type option for format type json

### ISSUE THREAD

**Issue by brunocastroibarburu94** [Snowflake-Labs/terraform-provider-snowflake#935]
I believe the is an issue with the resource **snowflake_file_format**

During **terraform plan** I had no issues however after **terraform apply** I receive the following message

```
Error: strip_outer_array is an invalid format type option for format type json
```

I am positive that strip_outer_array is an acceptable option for JSON file formats, so my guess is some error.

```
terraform {
  backend "http" {
  }
  required_version = "= 1.1.3"
}

terraform {
  required_providers {
    snowflake = {
      source = "chanzuckerberg/snowflake"
      version = "0.25.36"
    }
  }
}

terraform
resource "snowflake_file_format" "large_json_array" {
  name        = upper("strip_outer_array_json_format")
  database    = var.database
  schema      = var.schema
  format_type = "json"
  strip_outer_array = true
  lifecycle {
    ignore_changes = [
      binary_format,
      compression,
      date_format,
      skip_byte_order_mark,
      time_format,
      timestamp_format,
    ]
  }
}
```

**Comment by thenaturalist** [comment]
Hi @brunocastroibarburu94 you need to uppercase the format_type is my guess. 'json' isn't understood by Snowflake. 
I can confirm that I have a working resource with the same specs, simply uppercase format_type value.
