### ISSUE TITLE
The terraform-provider-snowflake_v0.28.8 plugin crashed!

### ISSUE THREAD

**Issue by arunpgmi** [Snowflake-Labs/terraform-provider-snowflake#945]
**Provider Version**
terraform-provider-snowflake_v0.28.8
The provider version you are using.

**Terraform Version**
Terraform v1.0.3
The version of Terraform you were using when the bug was encountered.

**Describe the bug**
The terraform-provider-snowflake_v0.28.8 plugin crashed!

**Expected behavior**

**Code samples and commands**
================
Terraform apply crashes above version 0.28
================
Please add code examples and commands that were run to cause the problem.

**Additional context**

=========================
Stack trace from the terraform-provider-snowflake_v0.28.8 plugin:

panic: time: missing Location in call to Time.In

goroutine 21 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc00063a6e0, {{0xc000319cf0, 0xa}, 0x0, 0x0, {0xc000319d00, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc000908900, {0xc00063a6e0, 0xa, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139c180, 0xc0003e2f50}, {0x139c1e0, 0x1bb6578}, 0x0, 0x0}, {0x13bf7f0, 0xc00013c020}, {0x13abeb8, 0xc000908900}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc00017ac80)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13aa858, 0xc00017acb0}, 0xc000965588)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc00017ac80)
	database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.(*Row).Scan(0xc00062fa10, {0xc00063a5a0, 0xc00062fa40, 0xa})
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:201 +0xb4
github.com/jmoiron/sqlx.(*Row).scanAny(0xc00062fa10, {0xfd0080, 0xc00062fa40}, 0x1)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:789 +0x605
github.com/jmoiron/sqlx.(*Row).StructScan(...)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:794
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ScanRole(0xc00047bee0)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/role.go:23 +0x45
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadRole(0xc000586800, {0x1197f20, 0xc00047bee0})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/role.go:49 +0x11e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11ad12f, {0x13bf7b8, 0xc0003907c0}, 0x24, {0x1197f20, 0xc00047bee0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002af7a0, {0x13bf7b8, 0xc0003907c0}, 0xc000666a90, {0x1197f20, 0xc00047bee0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003ce0a8, {0x13bf7b8, 0xc0003907c0}, 0xc000390840)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00043a320, {0x13bf860, 0xc000756d80}, 0xc0003c4d20)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:746 +0x537
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x11679e0, 0xc00043a320}, {0x13bf860, 0xc000756d80}, 0xc0003c4cc0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004baa80, {0x13d2788, 0xc000464000}, 0xc0004ea000, 0xc0002d6390, 0x1b74e90, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0004baa80, {0x13d2788, 0xc000464000}, 0xc0004ea000, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-snowflake_v0.28.8 plugin crashed!
=========================

**Comment by KrunalGMI** [comment]
I am facing similar error for my project too

**Comment by jmrobles** [comment]
Same here! 

I don't know if its related with gosnowflake@1.6.5 driver. 
The problem appears during the refreshing stage.

**Comment by jmrobles** [comment]
Ok, some light.

- v0.28.8 uses Go Snowflake v1.6.7
- v0.25.36 uses Go Snowflake v1.6.2

checking the changes of `converter.go` from v1.6.2 to v.1.6.7, now it uses a location

![image](https://user-images.githubusercontent.com/1277154/159667135-ab8c80c8-d786-4093-ab9d-90845834e4c2.png)

' localLocation` is loaded after connection is done and Snowflake parameters are parsed:

![image](https://user-images.githubusercontent.com/1277154/159668008-5921f4ac-9354-4bf5-9b2d-b84322e2d295.png)

The point is that this function can return an error if the locales can't be access or not exists (in case of execution under a container without locales).

After change the `TIMEZONE` session parameter from `Europe/London` to `UTC`, the provider works well.

I've reported the issue for `gosnowflake` driver too => https://github.com/snowflakedb/gosnowflake/issues/565

**Comment by tkrussy** [comment]
@jmrobles - when you mention setting TIMEZONE to UTC, how are you accomplishing this within a terraform worker-image? 

I'm struggling to find a workaround in our situation because I'm unable to get a change passed in the worker-image or in the terraform environment variables.

**Comment by jmrobles** [comment]
@tkrussy I'm refering to the Snowflake's parameter. The workaround is to execute in Snowflake something like `alter user <user> set timezone = 'UTC'`. 

The best option is to modify the container image and include the locales files. (I.e an Alpine docker based => `run apk add --no-cache tzdata`)

More related info => https://ddcode.net/2019/06/30/panic-time-missing-location-in-call-to-time-in/

**Comment by Bryan-Meier** [comment]
@jmrobles is the man!! Ran the alter user on the Terraform service account and that fixed the issue we were facing with imports. Way to go!

**Comment by jmrobles** [comment]
Thanks mate!

**Comment by tkrussy** [comment]
@jmrobles thanks again for your help and added insight here, I was able to workaround being unable to get the container modification in, but we've noted it for future build time as well.

I did figure out how to change it in our worker-image, but the workaround satisfies what we need until the driver can resolve the locale error without manipulation.

**Comment by Spince** [comment]
I had this same issue but only when doing the apply within Atlantis. Locally I can plan + apply just fine. The suggestion https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/945#issuecomment-1077815229 resolved the issue within Atlantis for me.

**Comment by philippeboyd** [comment]
This issue just occurred to be with
```
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.33.1
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

**Comment by sfc-gh-swinkler** [comment]
since a workaround was found, and since this seems to be a problem with the go connector, i am going to close this. please open a new issue if this happens again in newer versions.
