### ISSUE TITLE
Task session parameters doesn't work

### ISSUE THREAD

**Issue by JinaMizrahi** [Snowflake-Labs/terraform-provider-snowflake#953]
**Provider Version**

0.25.28

**Terraform Version**

UNKNOWN

**Describe the bug**
When using the session_parameters option in task I got an error and couldn't change the parameter
SQL compilation error:
│ invalid value ["false"] for parameter 'ERROR_ON_NONDETERMINISTIC_MERGE'

**Expected behavior**

set the task session parameter ERROR_ON_NONDETERMINISTIC_MERGE to false

**Code samples and commands**

resource snowflake_task "blabla_task" {
  database  = snowflake_schema.base_view.database
  schema    = snowflake_schema.base_view.name
  warehouse = snowflake_warehouse.warehouse.name

  name          = "BLA_BLA"
  schedule      = "1 MINUTE"
  sql_statement = file("blabla.sql")

  session_parameters = {
    "ERROR_ON_NONDETERMINISTIC_MERGE" : false,
  }

  user_task_timeout_ms = 10000
  when                 = "system$stream_has_data('blabla')"
  enabled              = true
}

**Additional context**

**Comment by timfrazier1** [comment]
I am encountering the same issue.  I cannot supply any session_parameters when creating a task.

**Comment by MLdavion** [comment]
am facing the same issue, likely it is because the value(s) are converted to string based on [this line](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/snowflake/task.go#L165)
```...(fmt.Sprintf(`%v = "%v"`, k, tb.sessionParameters[k])))```

**Comment by sfc-gh-asawicki** [comment]
Hey @JinaMizrahi. Thanks for creating the issue.

The task resource has been greatly reworked since v.0.25.28. Can you confirm if the problem persists after upgrading to the newest provider version?
