### ISSUE TITLE
Support for grant ownership on user

### ISSUE THREAD

**Issue by advaitvdeo** [Snowflake-Labs/terraform-provider-snowflake#956]
**Is your feature request related to a problem? Please describe.**

I have users in snowflake who wants to set key/pair authentication for themselves along with OAuth authentication that we already have for them. In case of key/pair auth, users are going to generate their respective key/pair and they want to run "ALTER USER" command on their respective users to set rsa_public_key.
We want to enable this for individual user by changing the owner of user ID to that user itself.
Currently when we run terraform pipeline, owner of the user if the BOT user that creates that user in snowflake.
[snowflake_user](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/user) resource does not have any field to setup owner of that user.

**Describe the solution you'd like**

Similar to [snowflake_role_ownership_grant](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/role_ownership_grant), we should have snowflake_user_ownership_grant, where we should be able to assign ownership on a user to any row that we want.
This way, we can create a OWNER_ROLE and grant OWNERSHIP privilege on user to this OWNER_ROLE and then grant this OWNER_ROLE to the user or to the default role of user.

**Additional context**

NA

**Comment by aidanmelen** [comment]
I wrote the `snowflake_role_ownership_grant` resource. I have been putting off writing the `snowflake_user_ownership_grant` resource. Busy work week so I will try to make another contribution this weekend!

**Comment by aidanmelen** [comment]
My shameless plug... you can use the [terraform-provider-snowsql](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) to manage arbitrary snowflake objects with SnowSQL statements. This is useful for when resources are not yet implemented by this provider.

**Comment by aidanmelen** [comment]
@advaitvdeo I think you can close this out now

https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/user_ownership_grant
