### ISSUE TITLE
Support for CREATE / ALTER FAILOVER GROUP

### ISSUE THREAD

**Issue by tuhren** [Snowflake-Labs/terraform-provider-snowflake#964]
We would like to manage Failover Groups with the Snowflake Terraform Provider to avoid manual ressource management.

Despite the fact that this feature is currently in private preview we want to create this feature request.

Here are the docs:

https://docs.snowflake.com/en/LIMITEDACCESS/account-replication.html#create-failover-group
https://docs.snowflake.com/en/LIMITEDACCESS/account-replication.html#alter-failover-group
https://docs.snowflake.com/en/LIMITEDACCESS/account-replication.html#executed-on-source-account

**Comment by sfc-gh-swinkler** [comment]
already completed
