### ISSUE TITLE
snowflake_procedure_grant documentation is wrong

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#982]
**Provider Version**

```
$ terraform version
Terraform v0.14.11
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.36
```

**Describe the bug**

The docs for `snowflake_procedure_grant` are wrong:
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/examples/resources/snowflake_procedure_grant/resource.tf#L6-L15

```
  arguments   = [
    {
      "name": "a",
      "type": "array"
    },
    {
      "name": "b",
      "type": "string"
    }
  ]
```

This results in an error:

```
Error: Unsupported argument

  on ../../modules/aws/application/snowflake.tf line 1147, in resource "snowflake_procedure_grant" "foo":
1147:   arguments = [

An argument named "arguments" is not expected here. Did you mean to define a
block of type "arguments"?
```

**Expected behavior**

It should instead show the correct data type, which is a block, not a list:
```
  arguments {
    name = "a"
    type = "array"
  }

  arguments {
    name = "b"
    type = "string"
  }

```

**Comment by coryveilleux** [comment]
This applies to `snowflake_function_grant` as well:

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/examples/resources/snowflake_function_grant/resource.tf#L6-L15

**Comment by sfc-gh-jalin** [comment]
Issue has been resolved by above PR, closing issue
